### ISSUE TITLE
[Close This] Console Error on Spigot 1.13.2 "Could not hide vanished players..."

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [EssentialsX/Essentials#2381] opened 2019-01-14 17:03 UTC
### Information

**Full output of `/ess version`**:
https://gyazo.com/f34129f0d160bc1d4806a76700d14efa

**Server log**:  https://gist.github.com/pinkpig3777/bc9678640fd80e0290a1b4ed7a05f85c

**EssentialsX config**: https://gist.github.com/pinkpig3777/badd73bc99e174afa2976cde9ebe37bc

### Details

**Description**  
It's showing a console error.
https://gist.github.com/pinkpig3777/0bb1859dda009ba7ee7d74a579c7ae33

**Steps to reproduce**  
I started my server with EssentialsX, EssentialsXChat, and EssentialsXSpawn downloaded.

**Expected behavior**  
No Console error.

**Comment by kennyrkun** [comment] 2019-01-14 22:28
@pinkpig3777 [this is fixed,](https://github.com/EssentialsX/Essentials/issues/2327#issuecomment-453771316) update to the [latest build](https://ci.ender.zone/job/EssentialsX)

**Comment by PiggiesGoSqueal** [comment] 2019-01-15 07:07
Okay thanks @kennyrkun

**Comment by mdcfe** [comment] 2019-01-15 09:50
Closing as this was already fixed (duplicate of #2327, thanks @kennyrkun).

**Closed as completed by mdcfe** 2019-01-15 09:50 UTC

**Comment by JustZerooo** [comment] 2024-01-29 17:49
Having the same error on Mohist 1.20.2

```log
> about essentials
[18:45:41 INFO]: Essentials version 2.21.0-dev+25-fbfd7e9
[18:45:41 INFO]: Provides an essential, core set of commands for Bukkit.
[18:45:41 INFO]: Website: https://essentialsx.net/
[18:45:41 INFO]: Authors: Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally, drtshock, vemacs, SupaHam, mdcfe, JRoy and pop4959
[18:45:41 INFO]: EssentialsChat version 2.21.0-dev+25-fbfd7e9
[18:45:41 INFO]: Provides chat control features for Essentials.  Requires Permissions.
[18:45:41 INFO]: Website: https://essentialsx.net/
[18:45:41 INFO]: Authors: Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Okamosy, Iaccidentally, mdcfe, JRoy and triagonal
[18:45:41 INFO]: EssentialsSpawn version 2.21.0-dev+25-fbfd7e9
[18:45:41 INFO]: Provides spawn control commands, utilizing Essentials.
[18:45:41 INFO]: Website: https://essentialsx.net/
[18:45:41 INFO]: Authors: Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, SupaHam, mdcfe, DoNotSpamPls and JRoy
```
Server Version String

```
[18:46:42 INFO]: This server is running Mohist version 1.20.2-134 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT, Forge version 48.1.0)
```

Error in Console

```
[18:38:04 WARN]: Could not hide vanished players while handling org.bukkit.event.server.ServerListPingEvent
java.lang.UnsupportedOperationException: null
        at org.bukkit.event.server.ServerListPingEvent.iterator(ServerListPingEvent.java:186) ~[forge-1.20.2-48.1.0-universal.jar%23159!/:?]
        at com.earth2me.essentials.EssentialsServerListener.onServerListPing(EssentialsServerListener.java:74) [EssentialsX-2.21.0-dev+25-fbfd7e9.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) [forge-1.20.2-48.1.0-universal.jar%23159!/:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) [forge-1.20.2-48.1.0-universal.jar%23159!/:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:601) [forge-1.20.2-48.1.0-universal.jar%23159!/:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:585) [forge-1.20.2-48.1.0-universal.jar%23159!/:?]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callServerListPingEvent(CraftEventFactory.java:916) [forge-1.20.2-48.1.0-universal.jar%23159!/:?]
        at net.minecraft.server.network.LegacyQueryHandler.channelRead(LegacyQueryHandler.java:31) [server-1.20.2-20230921.100330-srg.jar%23154!/:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.97.Final.jar%23142!/:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.97.Final.jar%23142!/:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.97.Final.jar%23142!/:4.1.97.Final]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.97.Final.jar%23140!/:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [netty-transport-4.1.97.Final.jar%23142!/:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.97.Final.jar%23142!/:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.97.Final.jar%23142!/:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.97.Final.jar%23142!/:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [netty-transport-4.1.97.Final.jar%23142!/:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.97.Final.jar%23142!/:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.97.Final.jar%23142!/:4.1.97.Final]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) [netty-transport-classes-epoll-4.1.97.Final.j
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) [netty-transport-classes-epoll-4.1.97.Final.jar%23143!/:4.1.97.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) [netty-transport-classes-epoll-4.1.97.Final.jar%23143!/:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.97.Final.jar%23139!/:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.97.Final.jar%23139!/:4.1.97.Final]
        at java.lang.Thread.run(Thread.java:840) [?:?]
```

**Comment by Evidentsinger14** [comment] 2024-01-29 18:42
Please do not necro issues from 5 years ago. Mohist is also unsupported.

**Comment by JustZerooo** [comment] 2024-01-29 19:58
Why should it be unsupported if just 1 issue is there and 99% of the other thinks works as best as possible? Makes absoluteley no sense

**Comment by mbax** [comment] 2024-01-29 20:00
Mohist is not supported, and 99% of people definitely do not think Mohist is the best option for a server. Hybrid servers rarely work well, and Mohist is no exception. If you can reproduce this exact issue the ticket is about on a supported server software, please provide that here. Otherwise, open a new ticket if experiencing similar but different issues on *supported* server software. Personally, I recommend using Paper on the latest release of Minecraft.

**Comment by JustZerooo** [comment] 2024-01-29 20:09
I will think about that any will thank you for the time to answere this :)
