### ISSUE TITLE
console error (2.16.1.180-mc114-b95) on 03bd4b0-17da342 (MC: 1.14.1)

### ISSUE THREAD

**Issue by comonier** [EssentialsX/Essentials#2563] opened 2019-05-26 02:03 UTC
https://paste.ofcode.org/AN27c6EBjZCp32Hs9bHE2q
[Sat, 25. May 2019 22:04:19 EDT INFO] CONSOLE issued server command: /ess version
[Sat, 25. May 2019 22:04:19 EDT INFO] Server version: 1.14.1-R0.1-SNAPSHOT git-Spigot-03bd4b0-17da342 (MC: 1.14.1)
[Sat, 25. May 2019 22:04:19 EDT INFO] EssentialsX version: 2.16.1.180-mc114-b95
[Sat, 25. May 2019 22:04:19 EDT INFO] PermissionsEx version: 1.23.4
[Sat, 25. May 2019 22:04:19 EDT INFO] Vault version: 1.7.2-b107
[Sat, 25. May 2019 22:04:19 EDT INFO] EssentialsXChat version: 2.16.1.180-mc114-b95
[Sat, 25. May 2019 22:04:19 EDT INFO] EssentialsXGeoIP version: 2.16.1.180-mc114-b95
[Sat, 25. May 2019 22:04:19 EDT INFO] EssentialsXSpawn version: 2.16.1.180-mc114-b95

**Comment by mdcfe** [comment] 2019-05-26 08:22
You didn't fill out the template fully, nor did you include the full error.

This appears to be a duplicate of a known issue. Please search for existing issues before opening new ones.

**Closed as completed by mdcfe** 2019-05-26 08:22 UTC
