### ISSUE TITLE
Unknown Item [383(Spawn Eggs)] at protect list

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#562] opened 2016-04-10 08:46 UTC
```
[16:25:19] [Server thread/ERROR]: §4Unknown item 383 at protect.alert.on-placement list
[16:25:19] [Server thread/ERROR]: §4Unknown item 383 at protect.alert.on-use list
[16:25:19] [Server thread/ERROR]: §4Unknown item 383 at protect.alert.on-break list
[16:25:19] [Server thread/ERROR]: §4Unknown item 383 at protect.blacklist.placement list
[16:25:19] [Server thread/ERROR]: §4Unknown item 383 at protect.blacklist.usage list
[16:25:19] [Server thread/ERROR]: §4Unknown item 383 at protect.blacklist.break list
[16:25:19] [Server thread/ERROR]: §4Unknown item 383 at protect.blacklist.piston list
[16:25:19] [Server thread/ERROR]: §4Unknown item 383 at protect.blacklist.dispenser list
```

Can not disabling spawn eggs?

**Comment by ghost** [comment] 2016-04-10 08:47
#559 
#561 
Same bug.

**Comment by mdcfe** [comment] 2017-12-16 17:16
Duplicate of #559.

**Closed as completed by mdcfe** 2017-12-16 17:16 UTC
