### ISSUE TITLE
Chat Signing 1.19.2

### ISSUE THREAD

**Issue by Blzd87** [EssentialsX/Essentials#5042] opened 2022-08-09 02:24 UTC
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=76acfae9883740658bc58e23b3e381fc

### Bug description

chat is not working only sending the message without the players name or prefix etc when disabling ess chat it works like normal.

below is with ess chat disabled.
https://img.justblzd.com/f4ca3a.png

### Steps to reproduce

fresh install of 1.19.2 with latest dev essx and you will see it doesnt work.

### Expected behaviour

that the vault prefix and player name comes before the message.

### Actual behaviour

just shows plain message without players name or vault prefix.

**Comment by pop4959** [comment] 2022-08-09 02:46
From your dump, it doesn't appear that you have any plugins installed which provide prefixes. Would you be able to clarify what you are expecting with EssentialsChat installed?

**Comment by Blzd87** [comment] 2022-08-09 03:56
That it displays my actual name Infront of the message?

Without essentialsx chat installed. My chat messages show my name and the message. 

When essentialsx chat installed. It only shows the message with a ? Mark stating it's not the original message. But how are people supposed to know who's talking if there are no names.

**Comment by pop4959** [comment] 2022-08-09 04:20
I was asking because you didn't provide a screenshot with EssentialsChat enabled, and it wasn't clear to me that you meant the entire name was missing. I understand now.

That said, I'm not able to reproduce this issue with Paper-118 and Essentials 2.19.5-dev+41-ee7c1b1.

![image](https://user-images.githubusercontent.com/17698576/183563367-7ef4cf19-b7df-47a6-baff-71a6c7e2154c.png)

**Comment by Blzd87** [comment] 2022-08-09 04:24
Does chat preview have to be enabled for essentialsx chat to work?

If so it's the first I've heard of that. 

I'll test again on latest paper with chat preview enabled. When K get home.

**Comment by pop4959** [comment] 2022-08-09 05:15
It's not required for it to work, but if you want signed chat, it must be enabled, because players "approve" the preview before sending it as signed. Otherwise it will show up as the modified (?) indicator.

**Comment by Blzd87** [comment] 2022-08-09 06:18
Ok i can confirm fresh paper install 1.19.2-118 with chat preview enabled. my name is before my message...

but now that ive loaded my SMP live server as a clone on my local server with same paper version its now going back to just message with ? near it.

https://essentialsx.net/dump.html?id=5cf5f73f66474317a53810926d526a35

https://img.justblzd.com/36b7cd.png

https://img.justblzd.com/6175a6.png

I assume your going to tell me to disable all plugins and only load essentials and go from there to find whats causing the issue?

**Comment by pop4959** [comment] 2022-08-09 07:18
Yeah I mean that would be a good idea. By default EssentialsChat format uses the display name, which can be set by other plugins. So if a fresh server works it's most likely something else.

**Comment by Blzd87** [comment] 2022-08-09 07:37
sorry if im bothering you but... why would it be not working now if it is working perfectly fine in 1.19?? its only since the chat signing been added its now an issue.

**Comment by Blzd87** [comment] 2022-08-09 07:48
ok when removing essentialsxchat my chat works with player name and message.... its something to do with {displayname} as i enabled chat format with Chat Manager plugin then the same issue happened.... no name just message... its some issue with {displayname}....

**Comment by pop4959** [comment] 2022-08-09 07:53
Does your chat manager plugin support the new chat features?

**Comment by Blzd87** [comment] 2022-08-09 07:55
no so ive disabled chat format from that one.. i only use it for other chat features like filters and bot etc... i like to use essentialschat for formating. just trying to isolate what plugin is interferring with ess

**Comment by pop4959** [comment] 2022-08-09 08:00
Okay, well either way it seems evident that this is an issue with an incompatibility with other plugins. Chat signing itself, as well as displaying display name, works properly in EssentialsChat, so I will close this now.

For further help with this, please join the #essx-support channel on our [Discord server](https://discord.gg/ZwVJukcNQG).

**Closed as completed by pop4959** 2022-08-09 08:00 UTC
Labels: type: question

**Comment by Blzd87** [comment] 2022-10-11 07:56
That it displays my actual name Infront of the message?

I swear I keep repeating myself.

Without essentialsx chat installed. My chat messages show my name and the message.

When essentialsx chat installed. It only shows the message with a ? Mark stating it's not the original message. But how are people supposed to know who's talking if there are no names.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by pop4959** [comment] 2022-10-11 08:10
Please join the [Discord server](https://discord.gg/ZwVJukcNQG) for further help configuring and troubleshooting with your Essentials Chat setup, since we have already determined that this is not a bug.
