### ISSUE TITLE
burn command has no effect

### ISSUE THREAD

**Issue by seema84** [EssentialsX/Essentials#2200] opened 2018-10-06 21:19 UTC
### Information

[23:14:05 INFO]: Server version: 1.13.1-R0.1-SNAPSHOT git-Spigot-f6a273b-1cf8b5d (MC: 1.13.1)
[23:14:05 INFO]: EssentialsX version: dev-24.75
[23:14:05 INFO]: EssentialsXChat version: dev-24.75

### Details

the command /burn <player> <time> has no effect on player in survival mode
player in creative mode burn always only 1s

**Comment by mdcfe** [comment] 2018-12-22 17:14
CLosing as I can't reproduce this on the latest EssentialsX and Paper versions.

**Closed as completed by mdcfe** 2018-12-22 17:14 UTC
Labels: help wanted, bug: unconfirmed
