### ISSUE TITLE
Conflict with Chat Manager plugin 

### ISSUE THREAD

**Issue by zonprox** [EssentialsX/Essentials#2565] opened 2019-05-26 04:45 UTC
Spigot 1.14; 
EssentialsX-2.16.1.156
Chat Manager 3.4.7

[11:36:16] [Server thread/INFO]: admin issued server command: /afk
[11:36:17] [Async Chat Thread - #5/ERROR]: Could not pass event AsyncPlayerChatEvent to Essentials v2.16.1.156
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-03bd4b0-8378335]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-03bd4b0-8378335]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at net.minecraft.server.v1_14_R1.PlayerConnection.chat(PlayerConnection.java:1588) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1526) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_212]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_212]
Caused by: java.lang.IllegalStateException: AfkStatusChangeEvent cannot be triggered asynchronously from another thread.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[spigot.jar:git-Spigot-03bd4b0-8378335]
	at com.earth2me.essentials.User.setAfk(User.java:463) ~[?:?]
	at com.earth2me.essentials.User.updateActivity(User.java:560) ~[?:?]
	at com.earth2me.essentials.User.updateActivityOnInteract(User.java:580) ~[?:?]
	at com.earth2me.essentials.EssentialsPlayerListener.onPlayerChat(EssentialsPlayerListener.java:101) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-03bd4b0-8378335]
	... 11 more
[11:36:17] [Async Chat Thread - #5/INFO]: [0;30;1m[[0;37;22mDefault[0;30;1m] [0;37;22madmin [0;34;1m> [0;37;22masd[m
[11:36:52] [Async Chat Thread - #5/ERROR]: Could not pass event AsyncPlayerChatEvent to Essentials v2.16.1.156
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-03bd4b0-8378335]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-03bd4b0-8378335]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at net.minecraft.server.v1_14_R1.PlayerConnection.chat(PlayerConnection.java:1588) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1526) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_212]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_212]
Caused by: java.lang.IllegalStateException: AfkStatusChangeEvent cannot be triggered asynchronously from another thread.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[spigot.jar:git-Spigot-03bd4b0-8378335]
	at com.earth2me.essentials.User.setAfk(User.java:463) ~[?:?]
	at com.earth2me.essentials.User.updateActivity(User.java:560) ~[?:?]
	at com.earth2me.essentials.User.updateActivityOnInteract(User.java:580) ~[?:?]
	at com.earth2me.essentials.EssentialsPlayerListener.onPlayerChat(EssentialsPlayerListener.java:101) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-03bd4b0-8378335]
	... 11 more
[11:36:52] [Async Chat Thread - #5/INFO]: [0;30;1m[[0;37;22mDefault[0;30;1m] [0;37;22madmin [0;34;1m> [0;37;22msad[m
[11:37:38] [Async Chat Thread - #5/ERROR]: Could not pass event AsyncPlayerChatEvent to Essentials v2.16.1.156
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-03bd4b0-8378335]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-03bd4b0-8378335]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at net.minecraft.server.v1_14_R1.PlayerConnection.chat(PlayerConnection.java:1588) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1526) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_212]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_212]
Caused by: java.lang.IllegalStateException: AfkStatusChangeEvent cannot be triggered asynchronously from another thread.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[spigot.jar:git-Spigot-03bd4b0-8378335]
	at com.earth2me.essentials.User.setAfk(User.java:463) ~[?:?]
	at com.earth2me.essentials.User.updateActivity(User.java:560) ~[?:?]
	at com.earth2me.essentials.User.updateActivityOnInteract(User.java:580) ~[?:?]
	at com.earth2me.essentials.EssentialsPlayerListener.onPlayerChat(EssentialsPlayerListener.java:101) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-03bd4b0-8378335]
	... 11 more
[11:37:38] [Async Chat Thread - #5/INFO]: [0;30;1m[[0;37;22mDefault[0;30;1m] [0;37;22madmin [0;34;1m> [0;37;22mchao[m
[11:38:41] [Async Chat Thread - #6/ERROR]: Could not pass event AsyncPlayerChatEvent to Essentials v2.16.1.156
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-03bd4b0-8378335]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-03bd4b0-8378335]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at net.minecraft.server.v1_14_R1.PlayerConnection.chat(PlayerConnection.java:1588) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1526) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_212]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_212]
Caused by: java.lang.IllegalStateException: AfkStatusChangeEvent cannot be triggered asynchronously from another thread.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[spigot.jar:git-Spigot-03bd4b0-8378335]
	at com.earth2me.essentials.User.setAfk(User.java:463) ~[?:?]
	at com.earth2me.essentials.User.updateActivity(User.java:560) ~[?:?]
	at com.earth2me.essentials.User.updateActivityOnInteract(User.java:580) ~[?:?]
	at com.earth2me.essentials.EssentialsPlayerListener.onPlayerChat(EssentialsPlayerListener.java:101) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-03bd4b0-8378335]
	... 11 more
[11:38:41] [Async Chat Thread - #6/INFO]: [0;30;1m[[0;37;22mDefault[0;30;1m] [0;37;22madmin [0;34;1m> [0;37;22mpussy[m
[11:40:57] [Server thread/INFO]: [0;36;1m[[0;33;22mChat-Manager[0;36;1m][m [0;32;1mConfig has been reloaded.[m
[11:41:01] [Async Chat Thread - #7/ERROR]: Could not pass event AsyncPlayerChatEvent to Essentials v2.16.1.156
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-03bd4b0-8378335]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-03bd4b0-8378335]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at net.minecraft.server.v1_14_R1.PlayerConnection.chat(PlayerConnection.java:1588) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1526) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_212]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_212]
Caused by: java.lang.IllegalStateException: AfkStatusChangeEvent cannot be triggered asynchronously from another thread.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[spigot.jar:git-Spigot-03bd4b0-8378335]
	at com.earth2me.essentials.User.setAfk(User.java:463) ~[?:?]
	at com.earth2me.essentials.User.updateActivity(User.java:560) ~[?:?]
	at com.earth2me.essentials.User.updateActivityOnInteract(User.java:580) ~[?:?]
	at com.earth2me.essentials.EssentialsPlayerListener.onPlayerChat(EssentialsPlayerListener.java:101) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-03bd4b0-8378335]
	... 11 more
[11:41:01] [Async Chat Thread - #7/INFO]: [m<[0;33;1m[21m[Coal] [m[0;31;22madmin[0;33;1m[m> chao[m
[11:41:31] [Async Chat Thread - #7/ERROR]: Could not pass event AsyncPlayerChatEvent to Essentials v2.16.1.156
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-03bd4b0-8378335]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-03bd4b0-8378335]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at net.minecraft.server.v1_14_R1.PlayerConnection.chat(PlayerConnection.java:1588) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1526) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_212]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_212]
Caused by: java.lang.IllegalStateException: AfkStatusChangeEvent cannot be triggered asynchronously from another thread.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[spigot.jar:git-Spigot-03bd4b0-8378335]
	at com.earth2me.essentials.User.setAfk(User.java:463) ~[?:?]
	at com.earth2me.essentials.User.updateActivity(User.java:560) ~[?:?]
	at com.earth2me.essentials.User.updateActivityOnInteract(User.java:580) ~[?:?]
	at com.earth2me.essentials.EssentialsPlayerListener.onPlayerChat(EssentialsPlayerListener.java:101) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-03bd4b0-8378335]
	... 11 more
[11:41:31] [Async Chat Thread - #7/INFO]: [m<[0;33;1m[21m[Coal] [m[0;31;22madmin[0;33;1m[m> pussy[m
[11:41:33] [Async Chat Thread - #7/ERROR]: Could not pass event AsyncPlayerChatEvent to Essentials v2.16.1.156
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-03bd4b0-8378335]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-03bd4b0-8378335]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at net.minecraft.server.v1_14_R1.PlayerConnection.chat(PlayerConnection.java:1588) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1526) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_212]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_212]
Caused by: java.lang.IllegalStateException: AfkStatusChangeEvent cannot be triggered asynchronously from another thread.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[spigot.jar:git-Spigot-03bd4b0-8378335]
	at com.earth2me.essentials.User.setAfk(User.java:463) ~[?:?]
	at com.earth2me.essentials.User.updateActivity(User.java:560) ~[?:?]
	at com.earth2me.essentials.User.updateActivityOnInteract(User.java:580) ~[?:?]
	at com.earth2me.essentials.EssentialsPlayerListener.onPlayerChat(EssentialsPlayerListener.java:101) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-03bd4b0-8378335]
	... 11 more
[11:41:33] [Async Chat Thread - #7/INFO]: [m<[0;33;1m[21m[Coal] [m[0;31;22madmin[0;33;1m[m> pussy[m
[11:41:37] [Async Chat Thread - #7/ERROR]: Could not pass event AsyncPlayerChatEvent to Essentials v2.16.1.156
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-03bd4b0-8378335]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-03bd4b0-8378335]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at net.minecraft.server.v1_14_R1.PlayerConnection.chat(PlayerConnection.java:1588) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1526) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) [spigot.jar:git-Spigot-03bd4b0-8378335]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_212]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_212]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_212]
Caused by: java.lang.IllegalStateException: AfkStatusChangeEvent cannot be triggered asynchronously from another thread.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[spigot.jar:git-Spigot-03bd4b0-8378335]
	at com.earth2me.essentials.User.setAfk(User.java:463) ~[?:?]
	at com.earth2me.essentials.User.updateActivity(User.java:560) ~[?:?]
	at com.earth2me.essentials.User.updateActivityOnInteract(User.java:580) ~[?:?]
	at com.earth2me.essentials.EssentialsPlayerListener.onPlayerChat(EssentialsPlayerListener.java:101) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-03bd4b0-8378335]
	... 11 more
[11:41:37] [Async Chat Thread - #7/INFO]: [m<[0;33;1m[21m[Coal] [m[0;31;22madmin[0;33;1m[m> fuck[m
[11:42:29] [Server thread/INFO]: [0;36;1m[[0;33;22mChat-Manager[0;36;1m][m [0;32;1mConfig has been reloaded.[m

**Comment by mdcfe** [comment] 2019-05-26 08:25
Duplicate of #2545/#2556.

This issue has nothing to do with other plugins - you're running a non-experimental build on 1.14. Download an experimental build from the [build server](https://ci.ender.zone/job/EssentialsX-Experimental).

**Closed as completed by mdcfe** 2019-05-26 08:25 UTC
