### ISSUE TITLE
[1.15.2] /ess version says that Vault isn’t installed, even though it is

### ISSUE THREAD

**Issue by Nevrai** [EssentialsX/Essentials#2998] opened 2020-02-07 20:54 UTC
### Information

**Full output of `/ess version`**:

```
Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-93 (MC: 1.15.2)
EssentialsX version: 2.17.1.56
LuckPerms version: 5.0.72
Vault is not installed. Chat and permissions may not work.
```

**Server log**: https://gist.github.com/DeleteMetaInf/fcb9cc1f1d6f1ad61db815a48123f705

**EssentialsX config**: https://gist.github.com/DeleteMetaInf/4608f31db5e0f88a5db1697267fc5f80

#### Description
When running `/ess version`, it says that Vault isn’t installed, despite the fact that it _is_ installed. This occurs both when running the command from the console and running it in-game. This did not occur prior to updating EssentialsX to, I believe, version 2.17.1.54. I am currently using version 2.17.1.56, which is, as of writing this, the latest version of the plugin.

#### Steps to reproduce
1. Use `/ess version`.

#### Expected behavior
`/ess version` should not say that Vault is not installed. It should show the version of Vault that is installed.

#### Screenshots
![“Vault is not installed”](https://user-images.githubusercontent.com/59761487/74064913-f71d6200-49f3-11ea-93d3-99bf5fbc571b.png)

#### Versions
* **[Minecraft](https://minecraft.net/):** 1.15.2
* **[PaperMC](https://papermc.io/):** 93
* **[EssentialsX](https://ci.ender.zone/job/EssentialsX/):** 2.17.1.56
* **[Vault](https://dev.bukkit.org/projects/vault):** 1.7.2-b107

**Comment by pop4959** [comment] 2020-02-07 22:25
Duplicate of #2988. Please search existing issues before creating another one.

**Closed as completed by pop4959** 2020-02-07 22:25 UTC
Labels: status: duplicate

**Comment by Nevrai** [comment] 2020-02-09 05:14
Apologies. I forgot to do so.
