### ISSUE TITLE
Option to spawn new players at a random location

### ISSUE THREAD

**Issue by Jack1424** [EssentialsX/Essentials#3620] opened 2020-08-24 01:03 UTC
### Feature request

**Feature description**
In Essentials Spawn, there should be an option in the config that spawns new players at a random point in the world. (EX: Being able to set the "spawnpoint" option in the configuration file to "random")

**How the feature is useful**
This feature would be useful for server owners and players. I know that there are already plugins that do this, but they might not work with other plugins on a server and it's just easier to have one plugin that does everything (what Essentials is made for). I am currently making a survival server and I'd like players to spawn at random points on the world. This would help players spread out and have easier access to resources. If I were to make an Anarchy server, it would be nice not to have a central spawn, where players could be trapped or easily killed. I saw that this feature has been requested in the past, but it didn't get that much attention. There are many situations where this feature could be useful. Why not add it in? I think that this feature could be a small, but useful addition to Essentials.

**Comment by triagonal** [comment] 2020-08-24 04:15
(near) Duplicate of #1893.

Thanks for the suggestion. Now that EssentialsX has a random teleport implementation, this feature is likely to be added in the near future (hopefully as part of the 2.19 update).

**Closed as completed by triagonal** 2020-08-24 04:15 UTC
Labels: status: duplicate
