### ISSUE TITLE
Teleport Requests do not expire after they are accepted

### ISSUE THREAD

**Issue by satadrive420** [EssentialsX/Essentials#3576] opened 2020-08-07 01:43 UTC
### Information

**Full output of `/ess version`**:

07.08 01:34:48 [Server] INFO Server version: 1.16.1-R0.1-SNAPSHOT git-Tuinity-"650532a" (MC: 1.16.1)
07.08 01:34:48 [Server] INFO EssentialsX version: 2.18.0.7.9aec89f
07.08 01:34:48 [Server] INFO LuckPerms version: 5.1.75
07.08 01:34:48 [Server] INFO PlaceholderAPI version: 2.10.8
07.08 01:34:48 [Server] INFO Vault version: 1.7.3-b131
07.08 01:34:48 [Server] INFO EssentialsXSpawn version: 2.18.0.7.9aec89f

**Server log**: 

**EssentialsX config**:  https://gist.github.com/satadrive420/f1597cbd09034ec66f165e80201badaf

### Details

**Description**  
When a teleport request is accepted and the player accepts the request, the request does not expire. This allows the player to "reuse" a teleport request, even after a successful teleport.

**Steps to reproduce**  
The replication of this bug is in this video.
https://www.youtube.com/watch?v=y2KZZ5U7LLc

**Expected behavior**  
When a player accepts a teleport request, the request should expire.

**Comment by triagonal** [comment] 2020-08-07 01:46
Duplicate of #3563 - please update to the latest build [here](https://essentialsx.net/downloads.html) which includes a fix for this bug.

**Closed as completed by triagonal** 2020-08-07 01:46 UTC
Labels: status: duplicate
