### ISSUE TITLE
"Player has not set a home" when data file has homes

### ISSUE THREAD

**Issue by freddyheppell** [EssentialsX/Essentials#4387] opened 2021-07-21 21:06 UTC
### Type of bug

Other unexpected behaviour

### `/ess version` output

[20:52:08 INFO]: Server version: 1.17.1-R0.1-SNAPSHOT git-Paper-119 (MC: 1.17.1)
[20:52:08 INFO]: Brand version: Paper
[20:52:08 INFO]: EssentialsX version: 2.19.0-dev+221-1556b91
[20:52:08 INFO]: PlaceholderAPI version: 2.10.10
[20:52:08 INFO]: LuckPerms version: 5.3.47
[20:52:08 INFO]: Vault version: 1.7.3-b131
[20:52:08 INFO]: DiscordSRV version: 1.23.0
[20:52:08 INFO]: EssentialsXChat version: 2.19.0-dev+221-1556b91
[20:52:08 INFO]: EssentialsXSpawn version: 2.19.0-dev+221-1556b91
[20:52:08 INFO]: Economy Layer: None
[20:52:08 INFO]: Fetching version information...
[20:52:09 INFO]: You're running the latest EssentialsX dev build!

### Server startup log

https://gist.github.com/freddyheppell/db35090c7b461843d0a01b4b352872f0

### EssentialsX config files

https://gist.github.com/freddyheppell/db35090c7b461843d0a01b4b352872f0

### Bug description

For some players, running `/home` says they have no homes, despite them having homes in their data file. But, their homes are autocompleted when typing the `/home` command.

### Steps to reproduce

1. A player runs `/home` to view their existing homes
2. The player runs `/sethome test` to create a new home
3. The player runs `/home` again

### Expected behaviour

Running `/home` should show the homes that exist in their data file. Running `/home` again after `/sethome` should include the new home too.

### Actual behaviour

Both times they are told `Error: Player has not set a home`. However, both pre-existing home and the newly set home are shown in the autocomplete menu. Several players have this issue.

Another player ([whose datafile is here](https://gist.github.com/freddyheppell/7c31a3a373386a31d4f181c27c9701c6)), does not experience any of these issues.

**Comment by freddyheppell** [comment] 2021-07-21 21:16
After I posted this someone came forward with working homes, I've put their data file here: https://gist.github.com/freddyheppell/431e80a14c33c127e6c6bb0849966d52

**Comment by Antal1609** [comment] 2021-07-25 21:26
This happens when the player has one or more homes in a dimension that has been reset.

**Comment by TNTUP** [comment] 2021-08-01 19:39
Can confirm. A player is having this issue and its pretty annoying. 

Can't say if its due to a world reset, I haven't done any world resets since Jul 1, and not created any other worlds then delete after.

**Comment by JRoy** [comment] 2021-08-02 01:20
Confirmed by https://github.com/EssentialsX/Essentials/pull/4240#discussion_r680512079

**Comment by TNTUP** [comment] 2021-08-02 03:37
Found out some of the worlds looks like "176a8ad6-aa96-4459-83e7-0be437ec3049" which causes the issue "player has not set a home" but I never created such world. How EssX determines the correct world? That UUID named world should bring to the "world" which is somewhat confusing as hell :thokingintensifies:

EDIT: Noticed I posted my message in the PR which I marked as off-topic

**Closed as completed** 2021-08-02 15:23 UTC
Labels: bug: confirmed
