### ISSUE TITLE
whois xxxx is not working complete - throws PLAY_ONE_TICK exceptoni

### ISSUE THREAD

**Issue by smmmadden** [EssentialsX/Essentials#2163] opened 2018-09-06 04:05 UTC
### Information
Full output of `/ess version`:
[23:55:16 INFO]: Server version: 1.13.1-R0.1-SNAPSHOT git-Paper-221 (MC: 1.13.1)
[23:55:16 INFO]: EssentialsX version: 2.15.0.45
[23:55:16 INFO]: LuckPerms version: 4.2.88
[23:55:16 INFO]: Vault version: 1.6.7-b${env.TRAVIS_BUILD_NUMBER}
[23:55:16 INFO]: EssentialsXChat version: 2.15.0.45
[23:55:16 INFO]: EssentialsXExtras version: 2.15.0.1
[23:55:16 INFO]: EssentialsXProtect version: 2.15.0.45
[23:55:16 INFO]: EssentialsXGeoIP version: 2.15.0.45
[23:55:16 INFO]: EssentialsXAntiBuild version: 2.15.0.45
[23:55:16 INFO]: EssentialsXSpawn version: 2.15.0.45

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):
From server console:
> whois smmmadden
[23:53:56 INFO]: CONSOLE issued server command: /whois smmmadden
[23:53:56 INFO]:  ====== WhoIs: smmmadden ======
[23:53:56 INFO]:  - Nick: smmmadden
[23:53:56 INFO]:  - UUID: f098c794-f41a-4edd-a536-b638b26b748e
[23:53:56 INFO]:  - Health: 10/20
[23:53:56 INFO]:  - Hunger: 16/20 (+0 saturation)
[23:53:56 INFO]:  - Exp: 3,237 (Level 41)
[23:53:56 INFO]:  - Location: (world, 144, 78, -33)
**[23:53:56 ERROR]: [Essentials] Command whois failed:
java.lang.NoSuchFieldError: PLAY_ONE_TICK**
        at com.earth2me.essentials.commands.Commandwhois.run(Commandwhois.java:39) ~[?:?]
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:167) ~[?:?]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:520) ~[?:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:435) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.1.jar:git-Paper-221]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.13.1.jar:git-Paper-221]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:725) ~[patched_1.13.1.jar:git-Paper-221]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:687) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.DedicatedServer.aU(DedicatedServer.java:472) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:429) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:936) ~[patched_1.13.1.jar:git-Paper-221]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:834) ~[patched_1.13.1.jar:git-Paper-221]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 

### Details
I expected the content to be shown above, but was also looking to get the GEOIP details for City and Country.  Instead that data not provided and it thru an exception.  I thought that the /whois <player> would provide the GeoIP details too?  Perhaps it works differently on a PaperSpigot Server?
Thanks!

**Comment by mdcfe** [comment] 2018-09-07 06:42
Duplicate of #2115.

The GeoIP information is not shown because the command fails before reaching the point where it would show the information.

**Closed as completed by mdcfe** 2018-09-07 06:42 UTC

**Comment by smmmadden** [comment] 2018-09-07 10:36
Thanks @md678685 - if this was fixed 24 days ago, wouldn't it have already been included in Essentials 2.15.0.45 which was 11 days ago or did it somehow get reverted?

**Comment by mdcfe** [comment] 2018-09-09 15:02
@smmmadden It's fixed in experimental builds (with the version `dev-xx.yy`). We don't currently support running any regular builds on 1.13.x, and the issue was closed as the fix has already been made to the `1.13` branch.

**Comment by smmmadden** [comment] 2018-09-09 17:42
ok - was unware there were other builds with dev-xx.yy versions as I've always used the latest available builds.  How will we know when it has been rolled up to the builds generally available for download so I can retest it then?

**Comment by mdcfe** [comment] 2018-09-10 09:56
The fix will be included when 1.13 support is included in the main branch, which we'll announce.
