### ISSUE TITLE
Flight is maintained after switching world via end portal; even if essentials.fly was denied for that end world.

### ISSUE THREAD

**Issue by ultraic-space** [EssentialsX/Essentials#5040] opened 2022-08-08 08:38 UTC
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=ab1b82ddcc92426cb6f17a010c4d0870

### Bug description

We have a player on another world (in my case, world_spawn) who has the `essentials.fly` permission enabled in that world via contexts.
If the player has `essentials.fly` denied via contexts to the end world, and they enter an end portal in world_spawn while flying; they will keep their flight. This is unlike if they enter the end world via commands like ./warp, in which case their flight is removed.

https://user-images.githubusercontent.com/108235651/183375292-7b8c1874-ea94-4a64-b5dd-5473189bcac6.mp4

I'm not exactly sure if this is a bug with Essentials or Luckperms, so please let me know if I'm in the wrong place.

### Steps to reproduce

1. Give the player `essentials.fly in context world=world`, and deny `essentials.fly in context world=world_the_end`.
2. Go to an end portal, do ./fly and fly into the portal.
3. The player will have flight after entering the portal.

### Expected behaviour

The player will no longer have flight if they enter an end portal to a world where they do not have permissions to use essentials.fly.

### Actual behaviour

If entering a portal, the player maintains flight even if the entered end world has the appropriate permission `essentials.fly` denied for that end world.

**Comment by JRoy** [comment] 2022-08-18 17:13
Duplicate of #4325

**Closed as not planned by JRoy** 2022-08-18 17:13 UTC
Labels: status: duplicate
