### ISSUE TITLE
/exp set does not work

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#1313] opened 2017-06-20 14:57 UTC
If I use command /exp set <nickname> <amout>, I will receive help message only.

**Comment by SupaHam** [comment] 2017-06-20 18:29
duplicate of #1285.

**Comment by ghost** [comment] 2017-06-20 19:47
This is not same #1285, it is not working in older versions too.

**Comment by SupaHam** [comment] 2017-06-20 22:58
Older version of Essentials? If so, that's because this is a CraftBukkit/Spigot bug.

**Comment by ghost** [comment] 2017-06-21 18:32
I'm using 1.11.2 spigot and latest version of essentials. I tried version 484 and still same problem.

**Comment by SupaHam** [comment] 2017-06-21 18:39
@tomasmessing What happens when you type `/exp`?

If it doesn't say `<player> has <exp> exp (level <level>)...` then there is another plugin overriding Essentials.

**Comment by smmmadden** [comment] 2017-06-21 19:50
Could it be @tomasmessing that you're using /exp to set the experience and not using /xp command?
Not sure why it takes two different commands but /exp smmmadden will show what SupaHam stated:
![image](https://user-images.githubusercontent.com/10309346/27403700-61432d82-5699-11e7-8ebb-5fdf166a0f31.png)
But if you follow up with the /xp amount player it will give that player experience points.
![image](https://user-images.githubusercontent.com/10309346/27403638-220c36f4-5699-11e7-9887-a83d364a5eb5.png)

**Comment by mdcfe** [comment] 2017-08-12 17:45
`exp` and `xp` appear to be different commands, although the Essentials wiki says that `xp` is an alias of `exp`.

**Comment by mdcfe** [comment] 2017-09-20 15:49
Closing due to inactivity. If you need further assistance, feel free to respond to this issue and we'll reopen it.

**Closed as completed by mdcfe** 2017-09-20 15:49 UTC
