### ISSUE TITLE
Cannot Create Signs since 1.10

### ISSUE THREAD

**Issue by LogieOneCanobie** [EssentialsX/Essentials#789] opened 2016-08-02 00:37 UTC
Hi there! I've been recently working on my server, and I haven't been able to create any signs with commands (such as warp signs, disposal signs, etc.) Whenever I place the sign, nothing happens, and the sign shows up blank. This is ONLY since the 1.10 release (I created my server in 1.9 and was able to make these signs perfectly fine,) and I do indeed have the latest version of EssentialsX installed. Hopefully this gets fixed!
Logan

**Comment by SupaHam** [comment] 2016-08-04 15:50
Duplicate of #687. Update your server software (Spigot/CraftBukkit).

**Closed as completed by SupaHam** 2016-08-04 15:50 UTC
Labels: status: duplicate
