### ISSUE TITLE
Issues loading essentials spawn on latest build

### ISSUE THREAD

**Issue by BluePlastics** [EssentialsX/Essentials#2226] opened 2018-10-27 09:54 UTC
### Information

Full output of `/ess version`:
Running the latest dev build (#28) would post ess version but I get this when trying to run it:
https://pastebin.com/9nirxqgG

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):
https://gist.github.com/BluePlastics/b3abe8233e9969ceda746e904919de08

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 
https://gist.github.com/BluePlastics/666b657693cc9a2ca2e31069b27b28c9

### Details

Essentials spawn fails to load with the following trace:
https://gist.github.com/BluePlastics/6985cbc868349e486b60f66f55fc0f96

**Comment by BluePlastics** [comment] 2018-10-27 09:59
Server log running just essentials for reference, looks like all essentials plugins fail to load:
https://gist.github.com/BluePlastics/5f0732721be3a0954ff3ece1f531d1df

**Comment by mdcfe** [comment] 2018-10-27 14:09
This has the same root cause as #2224 - the `items.json` checksum is mistakenly passed to Gson and it throws an error, meaning EssentialsX doesn't enable. This was previously fixed in #2153 then reintroduced during refactoring for #2204.

This should be fixed in a7fcafb245b96a6f496c15f5a4fe39c425d56c55.

**Closed as completed by mdcfe** 2018-10-27 14:09 UTC
