### ISSUE TITLE
suggestion Light

### ISSUE THREAD

**Issue by SrMonsterYT** [EssentialsX/Essentials#5392] opened 2023-06-12 17:23 UTC
### Feature description

a command called /light when using it you would get infinite night vision to turn it on and off would be the same command

### How the feature is useful

players keep filling the map with torches when they go mining or exploring we would like a way to solve this just by using /light so they can turn the light on and off

**Comment by Chew** [comment] 2023-06-12 18:09
Duplicate of #3825.

See this comment for more info: https://github.com/EssentialsX/Essentials/issues/3825#issuecomment-873461319

Essentially, a command already exists, you can use aliases to give them the effect. No reason for us to alias existing functionality for you.

**Closed as not planned by Chew** 2023-06-12 18:09 UTC
Labels: status: duplicate

**Comment by SrMonsterYT** [comment] 2023-06-12 21:09
this just adds effect to the player the /light would be a light to the player to get rid of the torches in caves
