### ISSUE TITLE
Cannot Sleep

### ISSUE THREAD

**Issue by thebananaconsumer** [EssentialsX/Essentials#4435] opened 2021-08-03 14:11 UTC
### Type of bug

Other unexpected behaviour

### `/ess version` output

unable to fetch version, possibly due to it being on minehut?
"unable to check your version! self-built? build information: id:'invalid' branch:'invalid' isDev:false

### Server startup log

unknown how to do

### EssentialsX config files

unknown how to do

### Bug description

The OP on server cannot sleep to skip the night. All players on server are OP currently, but a non-op visited and was able to sleep. This has not been able to be recreated by command "deop" and then trying to sleep. Sleeping does let you lie in bed, and reset the phantom timer, but nothing else.

### Steps to reproduce

1. Be OP on server
2. Wait for night
3. Try to sleep

### Expected behaviour

Sleeping should skip the night.

### Actual behaviour

When an OP tries to sleep, the player lies in bed, but the night does not pass.

**Comment by thebananaconsumer** [comment] 2021-08-26 13:10
what the heck, you didn't fix anything, you can't just close it man. The issue is ongoing.

**Comment by CreeperFace00** [comment] 2021-08-29 20:55
Disabling the EssentialsXSpawn plugin fixed this, I am not sure why @JRoy is closing these issues.

**Comment by JRoy** [comment] 2021-08-29 20:58
Didn't mean to close this, my bad

**Comment by CreeperFace00** [comment] 2021-08-30 01:51
Actually, my bad as well, this issue is also unrelated to the one I was having, #4474 is the one I was thinking of.

**Comment by thebananaconsumer** [comment] 2021-08-30 12:03
Is there anything I can do to help the bug get fixed, like any more info that's needed? Or is there any way I can get help if it's just my server doing it? But I've seen a few other people online complain about the same issue, so although it's not rampant, I don't think it's isolated. It's been going on since I updated to 1.17

**Comment by SieghartCL** [comment] 2021-08-31 14:09
@thebananaconsumer @JRoy We're also having this problem on our server. I just tried updating Essentials to latest stable version on our 1.17 server, and says it's an unsupported version. Is it because we're using an old version? If I get the latest stable 1.17, it may be supported? Here's /ess version from the console:

31.08 14:00:43 [Server] Server thread/INFO CONSOLE issued server command: /ess version
31.08 14:00:43 [Server] Server thread/INFO Server version: 1.17-R0.1-SNAPSHOT 3136-Spigot-66f9d3c-ea1a843 (MC: 1.17)
31.08 14:00:43 [Server] Server thread/INFO EssentialsX version: 2.18.2.0
31.08 14:00:43 [Server] Server thread/INFO Vault version: 1.7.3-b131
31.08 14:00:43 [Server] Server thread/INFO EssentialsXChat version: 2.18.2.0
31.08 14:00:43 [Server] Server thread/INFO You are running an unsupported server version!

**Comment by JRoy** [comment] 2021-09-13 01:48
I cannot reproduce this on `2.19.0` with OP. This could possible be caused by another plugin or by granting yourself the `*` permission.

**Closed as completed by JRoy** 2021-09-13 01:48 UTC
Labels: bug: unconfirmed

**Comment by thebananaconsumer** [comment] 2021-09-13 03:26
I have removed all other plugins from my server. It has been seen on other servers before, see this post's comments. See also this Reddit post with identical issue: https://www.reddit.com/r/Minecraft/comments/nydk74/cant_sleep_in_117/ which includes multiple comments of users with the same issue. It may not be on every server, but it's not just mine. 

What is the * permission, and what do I need to do to fix that if that is indeed the problem?
