### ISSUE TITLE
Issue: Download Links On Jenkins Are Down

### ISSUE THREAD

**Issue by dvdcd** [EssentialsX/Essentials#1591] opened 2017-10-16 04:04 UTC
the page http://ci.drtshock.net/job/essentialsx/ will not load for me. i don't know if its just me but it might be nice to have the download links back up. 

thanks
Dvdcd

**Comment by mdcfe** [comment] 2017-10-16 15:21
Duplicate of #1587.

**Closed as completed by mdcfe** 2017-10-16 15:21 UTC
