### ISSUE TITLE
Custom join/leave messages delay and silentjoin/quit

### ISSUE THREAD

**Issue by AnonymousX86** [EssentialsX/Essentials#2687] opened 2019-07-24 22:12 UTC
### Information

Full output of `/ess version`:
[23:49:08 INFO]: Server wersja: 1.14.4-R0.1-SNAPSHOT git-Paper-135 (MC: 1.14.4)
[23:49:08 INFO]: EssentialsX wersja: 2.17.0.3
[23:49:08 INFO]: PermissionsEx wersja: 1.23.4
[23:49:08 INFO]: Vault wersja: 1.7.2-b107
[23:49:08 INFO]: EssentialsXSpawn wersja: 2.17.0.3
[23:49:08 INFO]: Używasz niekontaktybilnych wtyczek!
[23:49:08 INFO]: Używasz nieobsługiwanej wersji serwera!

**Server log:** https://gist.github.com/AnonymousX86/35ed44e185ec1f821722869000406326 

**EssentialsX config** https://gist.github.com/AnonymousX86/61df7304be7c70a8f55c50faa7e53075 

### Help request

**Problem**
1. Custom join/quit message works fine on restart, but on /ess reload only after 15-20 minutes.
2. Silent join/quit message doesn't work. Permissions are okay https://gist.github.com/AnonymousX86/6d2bb9f4295701e9e316d5ae8ec3d0d3

**What I have tried**
Reloading EssX and restarting whole server.

**Screenshots**
https://cdn.discordapp.com/attachments/583178280979529758/603710855393312768/unknown.png

**Comment by pop4959** [comment] 2019-10-27 03:16
Can you provide the full server log (at least up until the server is fully loaded). Output of the `/bukkit:plugins` command may also be useful. Also I see this issue has not been looked at for some time, so please update any other information as well.

If I understand this correctly, you have custom join and quit messages configured, however they do not work for 15-20 minutes after using `/ess reload`? Please describe the problem in more details, and if possible, exact steps to reproduce it.

**Comment by pop4959** [comment] 2020-02-06 11:15
Closing due to not enough information provided.

**Closed as completed by pop4959** 2020-02-06 11:15 UTC
Labels: status: not enough info, bug: unconfirmed
