### ISSUE TITLE
Tab completion - Kit item tags

### ISSUE THREAD

**Issue by d3ath2005** [EssentialsX/Essentials#1290] opened 2017-06-09 01:48 UTC
Issue 1: Tab Completion
I've used for example /tp d3 then press tab and It didn't complete my player name [username: d3ath2005].

Issue 2: Kit item tags
Is it possible to add an item to a kit containing tags such as Unbreakable, Hidden Flags(Hide item enchantments, Hide unbreakable, etc.)

Any help would be appreciated.

**Comment by SupaHam** [comment] 2017-06-09 01:51
Issue 1: Duplicate of #1287.

Issue 2: I believe you can use NBT for that: `{Unbreakable:1}` (Make sure to put it at the end of the item definition)

**Closed as completed** 2017-06-09 01:54 UTC
Labels: type: question

**Comment by d3ath2005** [comment] 2017-06-09 01:57
@SupaHam 
Issue 1: Feature hasn't been implemented yet.

Issue 2: How could I add this tag in the configuration file?
```
kits:
  Starter:
    delay: 86400
    items:
    - DIAMOND_PICKAXE 1 name:&eStarter_Pickaxe dig_speed:15
    - IRON_HELMET 1 name:&eStarter_Helmet
    - IRON_CHESTPLATE 1 name:&eStarter_Chestplate
    - IRON_LEGGINGS 1 name:&eStarter_Leggings
    - IRON_BOOTS 1 name:&eStarter_Boots
```

**Comment by mdcfe** [comment] 2017-06-10 14:25
> Make sure to put it at the end of the item definition

**Comment by d3ath2005** [comment] 2017-06-10 17:25
@md678685 - Like that?
````
kits:
  Starter:
    delay: 86400
    items:
    - DIAMOND_PICKAXE 1 name:&eStarter_Pickaxe dig_speed:15 {Unbreakable:1}
    - IRON_HELMET 1 name:&eStarter_Helmet
    - IRON_CHESTPLATE 1 name:&eStarter_Chestplate
    - IRON_LEGGINGS 1 name:&eStarter_Leggings
    - IRON_BOOTS 1 name:&eStarter_Boots
```

**Comment by mdcfe** [comment] 2017-06-10 20:17
@d3ath2005 I was quoting SupaHam. Have you tried it? Does it work?
