### ISSUE TITLE
org.bukkit.event.server.ServerListPingEvent java.lang.UnsupportedOperationException: null

### ISSUE THREAD

**Issue by Boastful1353** [EssentialsX/Essentials#2375] opened 2019-01-10 19:31 UTC
### Information

**Full output of `/ess version`**:
[Thu, 10. Jan 2019 19:28:54 UTC INFO] CONSOLE issued server command: /ess version
[Thu, 10. Jan 2019 19:28:54 UTC INFO] Server version: 1.13.2-R0.1-SNAPSHOT git-Spigot-f56e2e7-4385562 (MC: 1.13.2)
[Thu, 10. Jan 2019 19:28:54 UTC INFO] EssentialsX version: 2.16.0.26
[Thu, 10. Jan 2019 19:28:54 UTC INFO] LuckPerms version: 4.3.17
[Thu, 10. Jan 2019 19:28:54 UTC INFO] Vault version: 1.7.1-b91
[Thu, 10. Jan 2019 19:28:54 UTC INFO] EssentialsXGeoIP version: 2.16.0.26
[Thu, 10. Jan 2019 19:28:54 UTC INFO] EssentialsXChat version: 2.16.0.26
[Thu, 10. Jan 2019 19:28:54 UTC INFO] EssentialsXSpawn version: 2.16.0.26
```
n/a
```

**Server log**: https://gist.github.com/marvinej/0532c898d3eaab8004352d9248025a8e

**EssentialsX config**: n/a

### Details

**Description**  
Latest essentials build running on the latest 1.13.2 build of spigot causes an issue with vanish

**Steps to reproduce**  
Use Latest essentials with latest spigot

This server is running CraftBukkit version git-Spigot-f56e2e7-4385562 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Expected behavior**  
no console errors i guess..

**Screenshots**

**Comment by mdcfe** [comment] 2019-01-10 19:37
Duplicate of #2327. CraftBukkit and Spigot don't seem to support modifying the player list on the Multiplayer screen in Minecraft any more. You can ignore this particular error for now.

**Closed as completed by mdcfe** 2019-01-10 19:37 UTC
Labels: bug: confirmed, status: duplicate
