### ISSUE TITLE
Issue with GeoIP?

### ISSUE THREAD

**Issue by takatalvi** [EssentialsX/Essentials#1787] opened 2018-01-22 10:30 UTC
EssentialsX version (run `/essentials`): **2.0.1-b581**

Server software (run `/version`): **latest - git-Spigot-4bd94dc-bdcc7c7 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)**

Details:
Just updated Spigot and EssX (Using base, GeoIP, Spawn and Chat). GeoIP gives an error, but otherwise works normal:

[11:16:24 INFO]: [Essentials] Enabling Essentials v2.0.1-b581
[11:16:24 INFO]: Creating config from template: /hlserver/27043/plugins/Essentials/kits.yml
[11:16:24 INFO]: Attempting to convert old kits in config.yml to new kits.yml
[11:16:24 INFO]: Converting tools
[11:16:24 INFO]: Converting tools.delay
[11:16:24 INFO]: Converting tools.items
[11:16:24 INFO]: Converting invi
[11:16:24 INFO]: Converting invi.delay
[11:16:24 INFO]: Converting invi.items
[11:16:24 INFO]: Converting color
[11:16:24 INFO]: Converting color.delay
[11:16:24 INFO]: Converting color.items
[11:16:24 INFO]: Converting firework
[11:16:24 INFO]: Converting firework.delay
[11:16:24 INFO]: Converting firework.items
[11:16:24 INFO]: Done converting kits.
[11:16:24 INFO]: [Essentials] Using 1.8.3+ BlockStateMeta provider as mob spawner provider.
[11:16:24 INFO]: [Essentials] Using Reflection based provider as spawn egg provider.
[11:16:24 INFO]: [Essentials] Using 1.9+ BasePotionData provider as potion meta provider.
[11:16:24 INFO]: Using locale sk
[11:16:24 INFO]: [Essentials] Using Spigot 1.7.10+ ServerListPingEvent iterator
[11:16:24 INFO]: [Essentials] Starting Metrics. Opt-out using the global bStats config.
[11:16:24 INFO]: [Vault][Economy] Essentials Economy hooked.
[11:16:24 INFO]: [Essentials] Using Vault based permissions (PermissionsEx)
[11:16:24 INFO]: [EssentialsGeoIP] Enabling EssentialsGeoIP v2.0.1-b581
[11:16:24 INFO]: Downloading GeoIP database... this might take a while (country: 0.6 MB, city: 20MB)
**[11:16:25 ERROR]: Failed to read GeoIP database!**
com.maxmind.db.InvalidDatabaseException: Could not find a MaxMind DB metadata marker in this file (Geo2-City.mmdb). Is this a valid MaxMind DB file?
at com.maxmind.db.Reader.findMetadataStart(Reader.java:227) ~[EssentialsXGeoIP-2.0.1.jar:?]
at com.maxmind.db.Reader.<init>(Reader.java:87) ~[EssentialsXGeoIP-2.0.1.jar:?]
at com.maxmind.db.Reader.<init>(Reader.java:80) ~[EssentialsXGeoIP-2.0.1.jar:?]
at com.maxmind.geoip2.DatabaseReader.<init>(DatabaseReader.java:38) ~[EssentialsXGeoIP-2.0.1.jar:?]
at com.maxmind.geoip2.DatabaseReader$Builder.build(DatabaseReader.java:123) ~[EssentialsXGeoIP-2.0.1.jar:?]
at com.earth2me.essentials.geoip.EssentialsGeoIPPlayerListener.reloadConfig(EssentialsGeoIPPlayerListener.java:144) [EssentialsXGeoIP-2.0.1.jar:?]
at com.earth2me.essentials.geoip.EssentialsGeoIPPlayerListener.<init>(EssentialsGeoIPPlayerListener.java:45) [EssentialsXGeoIP-2.0.1.jar:?]
at com.earth2me.essentials.geoip.EssentialsGeoIP.onEnable(EssentialsGeoIP.java:31) [EssentialsXGeoIP-2.0.1.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [minecraft_server.jar:git-Spigot-4bd94dc-bdcc7c7]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [minecraft_server.jar:git-Spigot-4bd94dc-bdcc7c7]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [minecraft_server.jar:git-Spigot-4bd94dc-bdcc7c7]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [minecraft_server.jar:git-Spigot-4bd94dc-bdcc7c7]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [minecraft_server.jar:git-Spigot-4bd94dc-bdcc7c7]
at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [minecraft_server.jar:git-Spigot-4bd94dc-bdcc7c7]
at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [minecraft_server.jar:git-Spigot-4bd94dc-bdcc7c7]
at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [minecraft_server.jar:git-Spigot-4bd94dc-bdcc7c7]
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [minecraft_server.jar:git-Spigot-4bd94dc-bdcc7c7]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [minecraft_server.jar:git-Spigot-4bd94dc-bdcc7c7]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
[11:16:25 INFO]: [EssentialsGeoIP] This product includes GeoLite2 data created by MaxMind, available from http://www.maxmind.com/.
[11:16:25 INFO]: [EssentialsChat] Enabling EssentialsChat v2.0.1-b581
...
[11:16:25 INFO]: [EssentialsSpawn] Enabling EssentialsSpawn v2.0.1-b581
...
[11:16:25] "player joined"
...
[11:16:26 WARN]: [Essentials] Plugin Essentials v2.0.1-b581 generated an exception while executing task 39
java.lang.NullPointerException: null
at com.earth2me.essentials.geoip.EssentialsGeoIPPlayerListener.delayedJoin(EssentialsGeoIPPlayerListener.java:68) ~[?:?]
at com.earth2me.essentials.geoip.EssentialsGeoIPPlayerListener$1.run(EssentialsGeoIPPlayerListener.java:53) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-Spigot-4bd94dc-bdcc7c7]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [minecraft_server.jar:git-Spigot-4bd94dc-bdcc7c7]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]

**Comment by takatalvi** [comment] 2018-01-22 10:34
Sorry, just found another thread on GeoIP.. I reinstalled the module (wiped its data as well) and it starts normally.

**Comment by mdcfe** [comment] 2018-01-22 10:37
No worries - was about to say this appears to be a duplicate of #1783. #1784 will properly fix this.

**Closed as completed by mdcfe** 2018-01-22 10:37 UTC
