### ISSUE TITLE
Warning and Afk problems.

### ISSUE THREAD

**Issue by Andronachi-Marian** [EssentialsX/Essentials#2359] opened 2019-01-06 12:19 UTC
### Information

**Full output of `/ess version`**:
```
[14:12:38 INFO]: Server version: 1.13.2-R0.1-SNAPSHOT git-Spigot-518206a-a5b9c7b (MC: 1.13.2)
[14:12:38 INFO]: EssentialsX version: 2.16.0.16
[14:12:38 INFO]: LuckPerms version: 4.3.17
[14:12:38 INFO]: Vault version: 1.7.1-b91
[14:12:38 INFO]: EssentialsXProtect version: 2.16.0.16
[14:12:38 INFO]: EssentialsXSpawn version: 2.16.0.16
[14:12:38 INFO]: EssentialsXChat version: 2.16.0.16
[14:12:38 INFO]: EssentialsXAntiBuild version: 2.16.0.16
```

**1: Warning** 
```
[13:42:08] [Netty Server IO #2/WARN]: [Essentials] Could not hide vanished players while handling org.bukkit.event.server.ServerListPingEvent
java.lang.UnsupportedOperationException: null
	at org.bukkit.event.server.ServerListPingEvent.iterator(ServerListPingEvent.java:144) ~[Spigot_1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at com.earth2me.essentials.EssentialsServerListener.onServerListPing(EssentialsServerListener.java:74) [EssentialsX-2.16.0.16.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) [Spigot_1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [Spigot_1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [Spigot_1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [Spigot_1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callServerListPingEvent(CraftEventFactory.java:612) [Spigot_1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.LegacyPingHandler.channelRead(LegacyPingHandler.java:37) [Spigot_1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Spigot_1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Spigot_1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Spigot_1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [Spigot_1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Spigot_1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Spigot_1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Spigot_1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [Spigot_1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Spigot_1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Spigot_1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [Spigot_1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [Spigot_1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647) [Spigot_1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:547) [Spigot_1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:501) [Spigot_1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461) [Spigot_1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [Spigot_1.13.2.jar:git-Spigot-518206a-a5b9c7b]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```
**2: Auto-AFK**

```
1.
auto-afk-kick: 600
 I was disabled the:
    cancel-afk-on-interact: false
    cancel-afk-on-move: false
And was kicked out after 10 minutes. I was not in AFK mode.

2.
I shutdown the server and after i joined i was kicked out for AFK.
```

**Comment by DoNotSpamPls** [comment] 2019-01-06 14:27
What is your `server.properties` file. It has an AFK kick timeout there as well.

**Comment by Andronachi-Marian** [comment] 2019-01-06 19:21
No, is player-idle-timeout=0;
And the message is: {PLAYER} lost connection: You have been kicked for idling more than 10 minutes.
I don't think is from spigot.

**Comment by mdcfe** [comment] 2019-01-10 19:36
@Andronachi-Marian For updates on the ServerListPingEvent error, follow #2327.

I think the auto AFK kick setting ignores your AFK status? (Correct me if this isn't the intended behaviour)

**Comment by triagonal** [comment] 2019-05-07 03:04
The kick on join issue was fixed in #2458.

**Comment by mdcfe** [comment] 2019-05-07 08:47
I believe both bugs in this issue have been fixed - @Andronachi-Marian could you confirm whether these still occur on the latest version?

**Comment by pop4959** [comment] 2019-10-27 04:17
Closing due to lack of response. If it's still an issue, let us know and we'll re-open it.

**Closed as completed by pop4959** 2019-10-27 04:17 UTC
Labels: status: not enough info, bug: unconfirmed
