### ISSUE TITLE
/seen <vanishedPlayer>

### ISSUE THREAD

**Issue by Twonox** [EssentialsX/Essentials#896] opened 2016-09-17 14:37 UTC
The players with seen permission can do `/seen <vanishedPlayer>` to see if the player is in the server; if I'm in vanish they can see me presence.

**I have two solutions:**
1. If we are in vanish, Essentials consider us offline.
2. If I have a permission `like essentials.seen.exempt` the players can't /seen me

**Comment by mdcfe** [comment] 2018-01-03 21:07
Duplicate of #807.

**Closed as completed by mdcfe** 2018-01-03 21:07 UTC
