### ISSUE TITLE
Player Shop Stopped Working

### ISSUE THREAD

**Issue by SimmsRyan97** [EssentialsX/Essentials#4030] opened 2021-03-04 12:14 UTC
### Type of bug

Other unexpected behaviour

### `/ess version` output

[Thu, 4. Mar 2021 12:04:44 GMT INFO] Server version: 1.16.5-R0.1-SNAPSHOT git-Paper-"60e92c061" (MC: 1.16.5)
[Thu, 4. Mar 2021 12:04:44 GMT INFO] EssentialsX version: 2.19.0-dev+87-b43790e
[Thu, 4. Mar 2021 12:04:44 GMT INFO] LuckPerms version: 5.2.76
[Thu, 4. Mar 2021 12:04:44 GMT INFO] PlaceholderAPI version: 2.10.9
[Thu, 4. Mar 2021 12:04:44 GMT INFO] Vault version: 1.7.3-b131
[Thu, 4. Mar 2021 12:04:44 GMT INFO] Citizens version: 2.0.27-SNAPSHOT (build 2249)
[Thu, 4. Mar 2021 12:04:44 GMT INFO] EssentialsXProtect version: 2.19.0-dev+87-b43790e
[Thu, 4. Mar 2021 12:04:44 GMT INFO] EssentialsXChat version: 2.19.0-dev+87-b43790e
[Thu, 4. Mar 2021 12:04:44 GMT INFO] EssentialsXSpawn version: 2.19.0-dev+87-b43790e

### Server startup log

https://paste.gg/p/anonymous/7b308017d2b448dfb4a946f2a3b46892

### EssentialsX config files

https://paste.gg/p/anonymous/5dc7beff070648e894f4fcd5820c8254

### Error log (if applicable)

N/A

### Bug description

Existing buy signs do not work, new ones work fine.

### Steps to reproduce

Have buy signs in the world, right click.

### Expected behaviour

Player should be able to right click on a buy sign to receive items for money

### Actual behaviour

Right clicking the sign does nothing, it doesn't even produce an error. Creating a new sign works fine.

**Comment by JRoy** [comment] 2021-03-04 13:51
Cannot reproduce on latest paper, try updating your paper build to latest and see if it works

**Comment by SimmsRyan97** [comment] 2021-03-04 14:00
I am on the latest paper and someone in the Discord says this is a real issue that doesn't work on the latest paper.

**Comment by JRoy** [comment] 2021-03-04 14:03
> I am on the latest paper and someone in the Discord says this is a real issue that doesn't work on the latest paper.

Can you give me an exact way to reproduce this on a fresh test server?

**Comment by SimmsRyan97** [comment] 2021-03-04 14:05
I don't think that's possible as this issue has risen from updating paper while having signs already in place on the server, creating new signs work fine.

**Comment by JRoy** [comment] 2021-03-04 15:05
Can reproduce, issue is on Paper side.

**Comment by JRoy** [comment] 2021-03-04 15:18
See https://github.com/PaperMC/Paper/issues/5304

**Comment by JRoy** [comment] 2021-03-09 16:13
Should be fixed on the latest Paper! Please update and let me know if the issue still persists.

**Closed as completed by JRoy** 2021-03-09 16:13 UTC
Labels: bug: confirmed, bug: upstream
