### ISSUE TITLE
Using UUID instead of IGN in Eco Commands doesn't work!

### ISSUE THREAD

**Issue by RoosterBooster007** [EssentialsX/Essentials#2835] opened 2019-10-25 16:19 UTC
Whenever I type:

/eco (give or take) (uuid) (ammount)

It creates a new balance for the uuid.. Ex:

Bob's Existing balance = $750

/eco give (bob's uuid) 10
    vvv
$10 added to (uuid)! New balance $10..?

**Comment by RoosterBooster007** [comment] 2019-10-25 16:21
EssentialsX Version: 2.17.1.0
Vault Version: 1.7.2-b107

**Comment by VirtualParticle** [comment] 2019-10-26 03:00
I'm unable to reproduce this issue in version 2.17.1.22. Can you update and see if the problem persists? There's a chance that you're just using the wrong UUID.

**Comment by triagonal** [comment] 2019-10-26 13:31
The bug report template is provided for a reason. Please **completely** fill out the template so we have the necessary information we need to provide support.
```
<!-- EssentialsX help guide

Don't write inside the arrows as they will be hidden when you post your issue.

Want faster support? Come join our Discord server to get help sooner:
https://discord.gg/F7gexAQ

If you're happy to wait (or you were sent here from Discord), read on:

1.  Fill out the template.
      This will help us understand what problem you've encountered and help us
      find a solution.

2.  Check the Common Issues page.
      Read through the wiki page to see if you've encountered a regular issue:
      https://essentialsx.github.io/#/Common-Issues

3.  Delete this line and all above lines before posting your issue!       -->

### Information

Full output of `/ess version`:

<!-- Replace this with the command output -->

**Server log:** <!-- Upload `logs/latest.log` to https://gist.github.com/ -->

**EssentialsX config** <!-- Upload `plugins/Essentials/config.yml` to https://gist.github.com/ -->

### Help request

**Problem**
<!-- What problem did you encounter? -->

**What I have tried**
<!-- What have you tried so far? -->

**Screenshots**
<!-- If relevant, include any screenshots here. -->
```

**Comment by pop4959** [comment] 2019-10-30 16:49
I'm going to close this for now, since it isn't reproducible, and you have provided no additional information in order to allow further investigation. If you fill out the template ,we can re-open this issue.

**Closed as completed** 2019-10-30 16:49 UTC
Labels: status: not enough info, bug: unconfirmed
