### ISSUE TITLE
Bug With Home Deletion

### ISSUE THREAD

**Issue by N0tHorizon** [EssentialsX/Essentials#5669] opened 2024-02-13 12:21 UTC
### Type of bug

Data loss, Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=5b195550d7db438aa28f99a0051f82d4

### Error log (if applicable)

https://mclo.gs/y2yiHFX

### Bug description

This seems to appear on modified clients like Feather or Lunar but sometimes when ppl join, all their homes get cleared exactly when they join. This is now the 4th times its happened. On the most recent time I just edited some permissions that deal with homes.

### Steps to reproduce

1. Have homes enabled via permission plugin
2. Set a few homes
It wont happen right away but it will happen eventualy, i dont know and dont want to know how to trigger it on purpose.

### Expected behaviour

Homes should be kept on rejoin

### Actual behaviour

Homes were lost on modified clients (as far as i know right now) as soon as they join. before they joined i used /homes Jerry86T:
and 2 appeared 1 that he deleted ahile ago and bed, its like its rolling back the home data.
```[tasklist]
### Tasks
```

**Comment by Evidentsinger14** [comment] 2024-02-19 23:28
I actively use modified clients including Feather, and have not been able to reproduce this behavior. If this is something you are able to actually narrow down to what causes it, by all means please let us know so it can be investigated. 
For now, I'm closing this as "cant reproduce". Feel free to reach out on [Discord](https://discord.gg/PHpuzZS) if you can help reproduce this issue.

**Closed as not planned by Evidentsinger14** 2024-02-19 23:28 UTC
Labels: bug: unconfirmed
