### ISSUE TITLE
Unknown Item in Blacklist

### ISSUE THREAD

**Issue by DrunkMexican** [EssentialsX/Essentials#559] opened 2016-04-08 03:46 UTC
ERROR §4Unknown item 383 in item-spawn-blacklist list.

Blocking the ability to spawn in monster eggs using the essentials blacklist gives this error in console on start-up, even though using /iteminfo with a spawn egg in hand gives this item ID. Not really a huge issue but defiantly not something that is intended.

**Comment by Paxination** [comment] 2016-05-02 19:47
I can confirm this, 383 no longer works, but putting 383:50 for specific mob eggs works.  Manually adding every mob type will be very tedious......

**Comment by Eredrim** [comment] 2016-09-27 23:21
Up ! There are more than 20 different spawn eggs. Can you do something ?

**Comment by pop4959** [comment] 2019-12-28 11:47
Item IDs are not longer supported in MineCraft, and this is probably fixed by "the flattening" in 1.13 since all items now have their own unique name, rather than relying on damage values. So this is probably not an problem anymore (if it is, please create a new issue).

**Closed as completed by pop4959** 2019-12-28 11:47 UTC
Labels: type: enhancement, status: open to PR
