### ISSUE TITLE
Could not pass event BlockBreakEvent to Essentials v2.16.1.174-mc114-b90

### ISSUE THREAD

**Issue by EnderCjh** [EssentialsX/Essentials#2553] opened 2019-05-18 05:58 UTC
Caused by: java.lang.ClassCastException
18.05 15:50:57 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]
18.05 15:50:57 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [Spigot.jar:git-Spigot-8043ebc-f690957]
18.05 15:50:57 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [Spigot.jar:git-Spigot-8043ebc-f690957]
18.05 15:50:57 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [Spigot.jar:git-Spigot-8043ebc-f690957]
18.05 15:50:57 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1057) [Spigot.jar:git-Spigot-8043ebc-f690957]
18.05 15:50:57 [Server] INFO at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:346) [Spigot.jar:git-Spigot-8043ebc-f690957]
18.05 15:50:57 [Server] INFO at net.minecraft.server.v1_14_R1.World.a(World.java:745) [Spigot.jar:git-Spigot-8043ebc-f690957]
18.05 15:50:57 [Server] INFO at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:570) ~[Spigot.jar:git-Spigot-8043ebc-f690957]
18.05 15:50:57 [Server] INFO at net.minecraft.server.v1_14_R1.EntityPlayer.tick(EntityPlayer.java:346) ~[Spigot.jar:git-Spigot-8043ebc-f690957]
18.05 15:50:57 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:84) ~[Spigot.jar:git-Spigot-8043ebc-f690957]
18.05 15:50:57 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:286) ~[Spigot.jar:git-Spigot-8043ebc-f690957]
18.05 15:50:57 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[Spigot.jar:git-Spigot-8043ebc-f690957]
18.05 15:50:57 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[Spigot.jar:git-Spigot-8043ebc-f690957]
18.05 15:50:57 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Spigot.jar:git-Spigot-8043ebc-f690957]
18.05 15:50:57 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[Spigot.jar:git-Spigot-8043ebc-f690957]
18.05 15:50:57 [Server] INFO org.bukkit.event.EventException: null
18.05 15:50:57 [Server] Server thread/ERROR Could not pass event BlockBreakEvent to Essentials v2.16.1.174-mc114-b90

**Comment by mdcfe** [comment] 2019-05-18 13:57
Duplicate of #2529. This is a known issue.

**Closed as completed by mdcfe** 2019-05-18 13:57 UTC
Labels: status: duplicate
