### ISSUE TITLE
Trade signs blank on use

### ISSUE THREAD

**Issue by OffLuffy** [EssentialsX/Essentials#696] opened 2016-06-30 02:09 UTC
**Server:** Spigot 1.10.2 R0.1
**Essentials:** 2.0.1-b368

I've upgraded my server to 1.10 using the old world, and it seems that the old player trade signs blank out when someone uses one. It works, but then blanks the sign and no longer works. Perhaps it's a compatibility problem with another plugin or lack of Essentials module (I'm only using core, Chat, Spawn), but I've no clue how to go about testing those. It doesn't produce any errors or console output at all. If there's something you need me to test, I may be able to, but also trying to keep the server up and functional. Disabling the [trade] signs prevents the signs from being blanks out in the mean time. I'm not sure if this applies to other signs quite yet.

Perhaps worth noting that during the update, I switched from the original Essentials to EssentialsX. I do have a few of my own plugins installed that could quite possibly be conflicting, but I can't imagine why off the top of my head. I couldn't find a report for this already, so it's likely the case that it's something specific to my setup.

**Other plugins:**
- EnderVault2
- Enjin
- GriefPrevention
- Multiverse
- PEX
- Prism
- ProtocolLib
- SignEdit
- Vault
- Votifier
- WorldBorder
- WorldEdit & WorldGuard
- A few of my own plugins

**Comment by SupaHam** [comment] 2016-06-30 02:10
Duplicate of #687.

**Closed as completed by SupaHam** 2016-06-30 02:10 UTC
Labels: bug: confirmed, status: duplicate
