### ISSUE TITLE
A way to toggle receiving payment from others

### ISSUE THREAD

**Issue by AMDBartek** [EssentialsX/Essentials#3088] opened 2020-03-23 22:28 UTC
**Feature description**
A command that allows you to toggle receiving payment from other players (for yourself or others).

**How the feature is useful**
The feature is useful if a player does not want to receive payment from others or an admin wants to stop a player from receiving payment.

**Comment by pop4959** [comment] 2020-03-23 22:30
Closing as duplicate of #3087

**Closed as completed by pop4959** 2020-03-23 22:30 UTC
Labels: status: duplicate

**Comment by AMDBartek** [comment] 2020-03-23 22:34
@pop4959 Yes I understand that the issue is a duplicate, but I made this issue to explain the request more thoroughly because #3087 had the `not enough info` tag and this would be a good feature to have.

**Comment by pop4959** [comment] 2020-03-23 22:36
Please allow the other person to clarify it themselves, as their request can be re-opened (or they can open a new one). There is no reason for you to post on their behalf.

**Comment by AMDBartek** [comment] 2020-03-23 22:38
Ok, sorry about that.
