### ISSUE TITLE
Items being placed on armor slots (/invsee issue)

### ISSUE THREAD

**Issue by YellowZaki** [EssentialsX/Essentials#3735] opened 2020-10-17 14:11 UTC
### Information

**Full output of `/ess version`**:
![image](https://user-images.githubusercontent.com/13599841/96338948-b05b2e00-1091-11eb-8627-cafc8a8243aa.png)

**Server log**: Anything related to essentials and no exceptions.

**EssentialsX config**: Tested with default config.

### Details

**Description**  

When using /invsee <player>, if you move an item from their inventory to yours, sometimes the item is placed on the <player> armours slots.

**I've also tested on a fresh server with no plugins, just Essentials, and it happens too.**

**Steps to reproduce**  

1. Use /invsee <player>
2. <player> opens their inventory
3. You move an item of their inventory to yours several times until the item is placed on <player> armour slots.

**Expected behavior**  

No bugs.

**Screenshots**  

Video: https://www.youtube.com/watch?v=46IOLRZDMFo&feature=youtu.be

**Comment by Chew** [comment] 2020-10-17 18:08
Duplicate of #3065 
Upstream issue still

**Closed as completed by Chew** 2020-10-17 18:08 UTC
Labels: status: duplicate
