### ISSUE TITLE
Serious lagging caused by EssentialsX

### ISSUE THREAD

**Issue by Subilan** [EssentialsX/Essentials#3156] opened 2020-04-11 12:42 UTC
### Information

Full output of `/ess version`:

```
Server version: 1.15.2-R0.1-SNAPSHOT git-Tuinity-"ab11927" (MC: 1.15.2)
EssentialsX version: 2.17.2.54
PlaceholderAPI version: 2.10.6-DEV-87
Vault version: 1.7.2-b107
Citizens version: 2.0.26-SNAPSHOT (build 1865)
EssentialsXChat version: 2.17.2.54
EssentialsXSpawn version: 2.17.2.54
```

**Server log:** https://gist.github.com/Subilan/fe1b45ddf1e57b3d13045d5c26587ea9

**EssentialsX config:** https://gist.github.com/Subilan/ed135caaf2826256a985743f6e1f5639

**Timings:** https://timings.aikar.co/?id=37be253a9da94f5aa0e91efa6c68d544

### Help request

**Problem**

The CPU of my server is i9-9900K and has 16GB of memory, but recently the server is stuck in a very serious lagging situation. According to some analysis, it was the problem of the plugins, so I checked them one by one. I removed all the plugins and put some of them back, then I started the server and keep watching on the TPS and other data. Unbelievably, I found that the plugin that caused the server to lag was actually a basic plugin, the EssentialsX.

The current situation is that, with EssentialsX installed, even if there is no player in the server, the TPS still cannot reach 20, which is difficult to understand.

So I want to ask what the problem actually is.

**P.S.** I have also checked other plugins and found four of them which caused the server to lag, EssentialsX is one of them.

I don't want to remove this at all, because the plugin provided very useful function which is very important to the server.

**What I have tried**
See above.

**Screenshots**
The horrible TPS.

![Z6J6B84RP%(Z2{ YZIKMQ8B](https://user-images.githubusercontent.com/36447840/79043841-656ce380-7c34-11ea-9c33-3ae2796a1475.png)

The TPS data is from a plugin called [NyaaUtils](https://github.com/NyaaCat/NyaaUtils).

**Comment by pop4959** [comment] 2020-04-11 19:14
I've taken a careful look at your report and determined that there is no sign of any lag being caused by Essentials. Here are some things that I discovered:

1) You did not remove all other plugins except for Essentials when testing to see if Essentials causes lag. That already immediately invalidates your findings, because other plugins can run tasks in the background.
2) Essentials does not appear to cause lag by any metric (Lag/All/Plugins) in the timings report.
3) Your TPS readings do indicate possible lag, but not that it is related to Essentials. Also, you should try using TPS readings from something like [spark ](https://www.spigotmc.org/resources/spark.57242/) instead, which are more likely to be reliable. In addition, spark has a sampler command which lets you profile short intervals. Sampling would be a much better way to determine what is causing lag.
4) You aren't using Aikar's flags, which can make the server run more efficiently.
5) Similarly, you're running Windows server and you have a high timings cost. Why not Linux, which is free?
6) Truinity isn't officially supported by Essentials, nor is it a magical solution that will entirely eliminate lag issues on your server.

Closing this issue now. If you still believe there is significant lag caused by Essentials, please feel free to open another issue with better evidence.

**Closed as completed by pop4959** 2020-04-11 19:14 UTC
Labels: status: invalid

**Comment by ERROR710** [comment] 2021-01-22 20:56
How would you set up Aikar's flags for a linux server? I've been looking over it for a while and havent found anything.
