### ISSUE TITLE
EssentialsGeoIP, cant connect to database as it no longer exists geolite.maxmind.com does not exist.

### ISSUE THREAD

**Issue by TomLewis** [EssentialsX/Essentials#2946] opened 2020-01-14 19:44 UTC
There is a startup error with EssentialsGeoIP as geolite.maxmind.com no longer exists, its trying to load this url and its not working, which is resulting in people showing as `null` in-game.

/ess ver
```
[19:41:07] [Server thread/INFO]: Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1617 (MC: 1.12.2)
[19:41:07] [Server thread/INFO]: EssentialsX version: 2.17.1.48
[19:41:07] [Server thread/INFO]: PlaceholderAPI version: 2.10.0-DEV-68
[19:41:07] [Server thread/INFO]: LuckPerms version: 4.4.22
[19:41:07] [Server thread/INFO]: Vault version: 1.6.6-b${env.TRAVIS_BUILD_NUMBER}
[19:41:07] [Server thread/INFO]: Citizens version: 2.0.25-SNAPSHOT (build 1685)
[19:41:07] [Server thread/INFO]: EssentialsXChat version: 2.17.1.48
[19:41:07] [Server thread/INFO]: EssentialsXGeoIP version: 2.17.1.48
[19:41:07] [Server thread/INFO]: EssentialsXSpawn version: 2.17.1.48
```

Startup error 
```
[14:40:50] [Server thread/INFO]: [EssentialsGeoIP] Enabling EssentialsGeoIP v2.17.1.48
[14:40:50] [Server thread/INFO]: [EssentialsGeoIP] Downloading GeoIP database... this might take a while (country: 1.7 MB, city: 30MB)
[14:40:50] [Server thread/ERROR]: [EssentialsGeoIP] Failed to open connection.
java.net.UnknownHostException: geolite.maxmind.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220) ~[?:?]
	at java.net.Socket.connect(Socket.java:609) ~[?:?]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:177) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:474) ~[?:?]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:569) ~[?:?]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[?:?]
	at sun.net.www.http.HttpClient.New(HttpClient.java:341) ~[?:?]
	at sun.net.www.http.HttpClient.New(HttpClient.java:362) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1248) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015) ~[?:?]
	at com.earth2me.essentials.geoip.EssentialsGeoIPPlayerListener.downloadDatabase(EssentialsGeoIPPlayerListener.java:182) ~[?:?]
	at com.earth2me.essentials.geoip.EssentialsGeoIPPlayerListener.reloadConfig(EssentialsGeoIPPlayerListener.java:149) ~[?:?]
	at com.earth2me.essentials.geoip.EssentialsGeoIPPlayerListener.<init>(EssentialsGeoIPPlayerListener.java:43) ~[?:?]
	at com.earth2me.essentials.geoip.EssentialsGeoIP.onEnable(EssentialsGeoIP.java:28) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1617]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1617]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1617]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1617]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1617]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1617]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[14:40:50] [Server thread/WARN]: [com.fasterxml.jackson.databind.ext.Java7Support] Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
[14:40:50] [Server thread/INFO]: [EssentialsGeoIP] This product includes GeoLite2 data created by MaxMind, available from http://www.maxmind.com/.
[14:40:50] [Server thread/INFO]: [EssentialsSpawn] Enabling EssentialsSpawn v2.17.1.48
```

**Comment by mdcfe** [comment] 2020-01-14 19:49
Duplicate of #2919.

You need to update the GeoIP module and set up a license key to access the database. See [the GeoIP wiki page](https://essentialsx.cf/geoip) for instructions.

**Closed as completed** 2020-01-14 19:50 UTC

**Comment by TomLewis** [comment] 2020-01-14 20:05
Fancy new documentation website! Nice! Thanks man.

**Comment by pop4959** [comment] 2020-01-15 06:30
Yeah I just wanted to add on that you can technically also fix this by also changing the URL in the older version of GeoIP. However, the newer one comes with pre-updated URLs & a special license key field which you can fill in from your MaxMind account, which makes it far easier. It also directs you to the wiki page if you do not.
