### ISSUE TITLE
Autokick issue

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#695] opened 2016-06-29 21:44 UTC
Hey

For some reason the plugin don’t catch when people are afk, when on a normal or sticky piston.

**Comment by SupaHam** [comment] 2016-06-30 12:52
I don't understand the issue. Are you saying the players aren't being kicked when they are afk. Or they aren't being marked as AFK in the first place?

**Comment by ghost** [comment] 2016-06-30 13:31
They arent being marked as AFK or kicked

**Comment by SupaHam** [comment] 2016-06-30 13:51
Okay, well we can ignore the part about kicking as that requires them to actually be marked as AFK. So  we fix the first, we fix the second.

Can you pastebin your config.yml?

**Comment by ghost** [comment] 2016-06-30 14:55
Sure [here](http://paste.yu8.me/?9d241e6a7dfe854a#VMRJVwwI+i4j8i3r2COKlKDH0W92V0jxvERi1WsMA7s=)

**Comment by SupaHam** [comment] 2016-06-30 14:56
It says the paste does not exist. Please make sure you copied the correct URL.

**Comment by ghost** [comment] 2016-06-30 14:58
Okay, should work this [one](http://paste.yu8.me/?7b72426fe921e4b1#IXGpMMvgv6jEQAPgzRPBT3x4vch+Za1I0ZDe94In0YQ=)

**Comment by SupaHam** [comment] 2016-06-30 15:01
Okay, based on your config, players will not be marked as AFK if they move or interact in the world. Can you tell me more about what pistons have to do with this issue?

Are you saying players standing still on pistons never get marked as AFK? Or are you saying players standing on pistons that move are never being marked as AFK? If it is the latter, that should be expected in your case as the player is moving.

**Comment by ghost** [comment] 2016-06-30 15:47
Facing down in it players aren’t marked as AFK and they did not move.

**Comment by SupaHam** [comment] 2016-06-30 17:06
I have been unable to reproduce this on the build 368.
![](http://supa.me/yqg1Ok.png)

**Closed as completed by SupaHam** 2016-06-30 17:06 UTC
