### ISSUE TITLE
Custom Join Messages do not show up for players, but DO show up for OPs.

### ISSUE THREAD

**Issue by 0fEfF2Dto4KoNAVZu8cb5** [EssentialsX/Essentials#2823] opened 2019-10-16 21:50 UTC
### Information

Full output of `/ess version`:  https://pastebin.com/LY62U1hX

**Server log:** https://pastebin.com/iNR3gERq

**EssentialsX config:** https://pastebin.com/6MtZY0SR

### Help request

**Problem**
When I change anything from "none", regular players are not able to see it. Players who are OP'd are able to see the join message. Leave message works fine for everyone.

**What I have tried**
Updating everything to latest version. (Paper, EssX, and the rest of my plugins)
Messing with PEX, changing the configs, permissions, giving people *, nothing works.

**Screenshots**
https://imgur.com/a/uyJ7mvf

**Link to other post:** https://github.com/EssentialsX/Essentials/issues/1773

**Comment by triagonal** [comment] 2019-10-24 02:46
I can't seem to reproduce this issue. Both custom join and leave messages show up for OPs and non-OPs on the following versions: 
```
[13:45:25 INFO]: Server version: 1.14.4-R0.1-SNAPSHOT git-Paper-221 (MC: 1.14.4)
[13:45:25 INFO]: EssentialsX version: 2.17.1.19
[13:45:25 INFO]: Vault is not installed. Chat and permissions may not work.
```
Could you try disabling all of your other plugins and seeing if the issue still occurs with just EssentialsX installed?

**Comment by 0fEfF2Dto4KoNAVZu8cb5** [comment] 2019-11-27 23:56
Sorry for the month gap reply. I will try this when I can.

**Comment by SirKillian** [comment] 2019-12-31 03:32
I'm experiencing the same issue on v**2.17.1.45**. 1.15.1 Paper-32

However, for me, not even OP's can see the login message.
Edit: The login message does display in the console but not in-game.


The only plugins enabled are:
- Essentials
- EssentialsSpawn
- Vault
- LuckPerms

**Comment by FunkyNico** [comment] 2020-01-13 16:16
Same issue here:

**Server version:** 1.14.4-R0.1-SNAPSHOT git-Paper-239 (MC: 1.14.4)
**EssentialsX version:** 2.17.1.50
**LuckPerms version:** 5.0.39
**PlaceholderAPI version:** 2.10.4
**Vault version:** 1.7.2-b107
**EssentialsXChat version:** 2.17.1.50
**EssentialsXSpawn version:** 2.17.1.50

Only Op's can see the join message, or people who have the '*' permission.

**SOLUTION:** add the permission "bukkit.broadcast.user" to the default group, because i have the permission "bukkit.*" to false.

**Comment by triagonal** [comment] 2020-01-13 17:52
After a bit of testing, it seems that for some users this may be caused by negating `bukkit.*` on an inherited group. Granting the permission `bukkit.broadcast.user` for the group should solve the issue for these users.

EssentialsX uses the broadcast system for join messages, but not for leave messages, which causes the discrepancy here.

@SirKillian and @mcgrenoa, could you please try the fix above and let us know if it solves your issue?

**Comment by 0fEfF2Dto4KoNAVZu8cb5** [comment] 2020-01-13 19:35
@Ant4rez @triagonal This fixed to issue completely! Thank you everyone for your help!

**Comment by darbyjack** [comment] 2020-04-30 06:52
Closing this due to the solution being found (read above).

**Closed as completed by darbyjack** 2020-04-30 06:52 UTC
Labels: type: problem
