### ISSUE TITLE
Per World Economy

### ISSUE THREAD

**Issue by xXIOSCARIXx** [EssentialsX/Essentials#1856] opened 2018-02-17 18:38 UTC
I still can't belive there is no per world economy in essentials(x)

I know there are plugins for this but i would much rather have it included in essentials if possible

Thanks :)

**Comment by LaxWasHere** [comment] 2018-02-17 19:03
We only provide the essentials.

**Comment by mdcfe** [comment] 2018-02-17 19:13
It's not *impossible*, but we'd need to deprecate and replace the entire Economy API... (though #1853 does facilitate this)

I don't see this happening any time soon.

**Comment by xXIOSCARIXx** [comment] 2018-02-17 19:16
Ok well add per world economy ty

**Comment by mdcfe** [comment] 2018-02-17 19:18
To clarify the response:

For now, we will not be adding per-world economy.

**Comment by xXIOSCARIXx** [comment] 2018-02-17 19:31
I understand, i would really like to see this in the future though..

Thanks for the info <3

**Comment by mdcfe** [comment] 2018-02-17 20:08
This is actually a duplicate of #1011, so I'm closing this issue in favour of that one.

**Closed as completed by mdcfe** 2018-02-17 20:08 UTC
