### ISSUE TITLE
LuckPerms EssentialsX no prefixes on death

### ISSUE THREAD

**Issue by therealmikey** [EssentialsX/Essentials#1717] opened 2017-12-21 06:09 UTC
I have an issue with LuckPerms and EssentialsX. I asked The people on the LP discord and they said it was an essentials error. When players die they lose their prefix. The prefix will come back once the player talks.
[https://gfycat.com/QuarrelsomeMelodicCero](https://gfycat.com/QuarrelsomeMelodicCero)
I am using the newest versions of both plugins and vault. If anyone can help me please do :D

**Comment by DrewAMitchell** [comment] 2017-12-21 06:20
Duplicate chain https://github.com/EssentialsX/Essentials/issues/1642

**Comment by mdcfe** [comment] 2017-12-21 08:45
Duplicate of #1642.

**Closed as completed by mdcfe** 2017-12-21 08:45 UTC
