### ISSUE TITLE
Essentials v2.15.0.1 generated an exception while executing task 23

### ISSUE THREAD

**Issue by NorthWestTrees** [EssentialsX/Essentials#1975] opened 2018-04-18 23:44 UTC
EssentialsX Version 2.15.0.1 Using Spigot build 67 for 1.12.2
Using locale en_US
Using Spigot 1.7.10+ ServerListPingEvent iterator

Server log:
https://gist.github.com/NorthWestTrees/fca6b35e500560643b574100ab6f3260

EssentialsX config:
https://gist.github.com/NorthWestTrees/1fdabe94a0f6e671121eaa5fb4e83a97

I was able to narrow down the problem, however I am not sure why its just one file but it should help you figure out the rest when you go and fix it.

The server runs fine as long as no jails are set aka no Jails.yml file is in the config.
I have taken apart the essentials folder and reconfigured it to the old setting and the config file was not the issue. I then added one file at a time until I found the file being the problem being the jails.yml
I am no coder but I do know who to narrow down issues, hope that helps. Looking forward to your update :)

**Comment by LaxWasHere** [comment] 2018-04-19 00:07
Duplicate of #1974

**Comment by mdcfe** [comment] 2018-06-12 21:10
Closing due to lack of response, as well as duplicating #1974. If this is still a problem, feel free to respond and reopen the issue.

**Closed as completed by mdcfe** 2018-06-12 21:10 UTC
