### ISSUE TITLE
Invsee deletes / moves items

### ISSUE THREAD

**Issue by JHarris12345** [EssentialsX/Essentials#4401] opened 2021-07-28 09:27 UTC
### Type of bug

Other unexpected behaviour

### `/ess version` output

[10:24:30 INFO]: Server version: 1.16.5-R0.1-SNAPSHOT git-Airplane-"8c50125" (MC: 1.16.5)
[10:24:30 INFO]: EssentialsX version: 2.18.2.0
[10:24:30 INFO]: PlaceholderAPI version: 2.10.9
[10:24:30 INFO]: LuckPerms version: 5.3.3
[10:24:30 INFO]: Vault version: 1.7.3-b131
[10:24:30 INFO]: EssentialsXProtect version: 2.18.2.0
[10:24:30 INFO]: EssentialsXGeoIP version: 2.18.2.0
[10:24:30 INFO]: EssentialsXAntiBuild version: 2.18.2.0
[10:24:30 INFO]: EssentialsXSpawn version: 2.18.2.0
[10:24:30 INFO]: Citizens version: 2.0.27-SNAPSHOT (build Unknown)
[10:24:30 INFO]: ChestShop version: 3.11 (build 213)

### Server startup log

https://pastebin.com/EpnrgbL1

### EssentialsX config files

https://pastebin.com/ywp5r5uN

### Bug description

If you do /invsee [player] and start moving their items to your inv, the items start glitching. They delete, move slots etc etc. Here is a gif:

https://gyazo.com/c080707dde276b87d67a369f6bdb5890

### Steps to reproduce

1. Invsee a player
2. Move items from their inv to yours, just like the gif above

### Expected behaviour

Items shouldnt delete

### Actual behaviour

Items delete / move

**Comment by JHarris12345** [comment] 2021-07-28 09:31
Update:

The items that dissapear actually go into the armor / off hand slots. Look at this...

![image](https://user-images.githubusercontent.com/46936647/127299284-93708a77-e039-4434-9ee3-15eb323dd1d0.png)


Boots on my head and trident as leggings?

**Comment by triagonal** [comment] 2021-07-28 09:42
Duplicate of common issue: https://github.com/EssentialsX/Essentials/issues/3956#issuecomment-771694504

**Closed as completed by triagonal** 2021-07-28 09:42 UTC
Labels: status: wontfix
