### ISSUE TITLE
Essentials/src/com/earth2me/essentials/utils/VersionUtil.java "not in valid version format"

### ISSUE THREAD

**Issue by Romaq** [EssentialsX/Essentials#2621] opened 2019-06-24 22:07 UTC
### Information

**Full output of `/ess version`**:

```
Note: This is the cut & paste of my attempt at /ess version in the console.
The /ess version is EssentialsX-2.16.1.215.jar from https://ci.ender.zone/job/EssentialsX/

24.06 17:39:15 [Server] Server thread/WARN Unexpected exception while parsing console command "ess version"
24.06 17:39:15 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'ess' in plugin Essentials v2.16.1.215
24.06 17:39:15 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.14.3-2019-06-24a.jar:git-Spigot-4d2f30f-f1f3355]
24.06 17:39:15 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.3-2019-06-24a.jar:git-Spigot-4d2f30f-f1f3355]
24.06 17:39:15 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707) ~[spigot-1.14.3-2019-06-24a.jar:git-Spigot-4d2f30f-f1f3355]
24.06 17:39:15 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:692) [spigot-1.14.3-2019-06-24a.jar:git-Spigot-4d2f30f-f1f3355]
24.06 17:39:15 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:433) [spigot-1.14.3-2019-06-24a.jar:git-Spigot-4d2f30f-f1f3355]
24.06 17:39:15 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:397) [spigot-1.14.3-2019-06-24a.jar:git-Spigot-4d2f30f-f1f3355]
24.06 17:39:15 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:955) [spigot-1.14.3-2019-06-24a.jar:git-Spigot-4d2f30f-f1f3355]
24.06 17:39:15 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:800) [spigot-1.14.3-2019-06-24a.jar:git-Spigot-4d2f30f-f1f3355]
24.06 17:39:15 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
24.06 17:39:15 [Server] INFO Caused by: java.lang.NullPointerException
24.06 17:39:15 [Server] INFO at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:464) ~[?:?]
24.06 17:39:15 [Server] INFO at com.earth2me.essentials.Essentials.onCommand(Essentials.java:458) ~[?:?]
24.06 17:39:15 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.14.3-2019-06-24a.jar:git-Spigot-4d2f30f-f1f3355]
24.06 17:39:15 [Server] INFO ... 8 more
```

**Server log**: https://gist.github.com/Romaq/48dfa8c6337792ba2535afdc7601507c#file-latest-log

**EssentialsX config**: https://gist.github.com/Romaq/48dfa8c6337792ba2535afdc7601507c#file-config-yml

### Details

**Description**  
[17:31:54] [Server thread/ERROR]: Error occurred while enabling Essentials v2.16.1.215 (Is it up to date?)

java.lang.IllegalArgumentException: 1.14.3-SNAPSHOT is not in valid version format. e.g. 1.8.8-R0.1

**Steps to reproduce**  
24.06 18:05:34 [Server] Server thread/INFO This server is running CraftBukkit version git-Spigot-4d2f30f-f1f3355 (MC: 1.14.3) (Implementing API version 1.14.3-SNAPSHOT)
24.06 18:05:34 [Server] Server thread/INFO Checking version, please wait...
24.06 18:05:34 [Server] Thread-9/INFO You are running the latest version

Simply attempting to run the current latest Essentials with the current latest 1.14.3 Spigot release. 

**Expected behavior**  
Log Silence on Essentials Enable

**Comment by Romaq** [comment] 2019-06-25 00:23
24.06 20:21:14 [Server] Server thread/INFO Romaq issued server command: /back
24.06 20:21:14 [Server] Server thread/ERROR null
24.06 20:21:14 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'back' in plugin Essentials v2.16.1.215

It would seem all Essentials commands are crippled at this time. Anything "essentials" spams the console for Spigot 1.14.3.

**Comment by mdcfe** [comment] 2019-06-25 06:33
Duplicate of #2620.

**Closed as completed by mdcfe** 2019-06-25 06:33 UTC
