### ISSUE TITLE
[Trade] signs become inaccessible if player changes their username

### ISSUE THREAD

**Issue by whimsicalities** [EssentialsX/Essentials#4625] opened 2021-11-09 22:09 UTC
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=673e83ed82cd484f8ac8bcea60ea1181

### Bug description

A player on the server who changed their minecraft username reported that they could no longer access their [Trade] signs.

### Steps to reproduce

1. Create a [Trade] sign
2. Change minecraft account name
3. Try to access trade sign earnings

### Expected behaviour

Able to access earnings.

### Actual behaviour

Unable to access. Resources are locked into sign.

**Comment by JRoy** [comment] 2021-11-11 01:14
~~Duplicate of #81~~

Edit by @mdcfe: no it isn't

**Closed as completed by JRoy** 2021-11-11 01:14 UTC
Labels: bug: unconfirmed

**Comment by mdcfe** [comment] 2022-03-01 00:21
#4713 implements player UUID storage using `PersistentDataContainer` on 1.14+.

**Comment by mdcfe** [comment] 2022-03-01 00:23
In addition, for the sake of clarity, this issue was a duplicate of #1117.

**Comment by TheMattVid** [comment] 2022-09-22 00:42
Is this still an issue? I had a player lose access to their trade signs on EssentialsX 2.19.7 after changing usernames.
