### ISSUE TITLE
Use client locale instead of servers

### ISSUE THREAD

**Issue by BurkenDev** [EssentialsX/Essentials#3867] opened 2020-12-24 14:57 UTC
### Feature request

**Feature description:**  

An option to enable the use of using the essentials locale based on the current users client locale instead of only using the server locale or manually configured locale in config.yml.

**How the feature is useful:**  

If you run a server that uses multiple languages it would be very nice to have each player be able to automatically use their own locale setting from their minecraft client. This way people who aren't as fluent in say english can understand what's happening on the server when using essentials commands etc. And each  user gets their own language, making it all so nice for everyone.

**Comment by JRoy** [comment] 2020-12-27 20:15
Duplicate of #2029

**Closed as completed** 2020-12-27 20:18 UTC
Labels: type: enhancement
