### ISSUE TITLE
Clay & Bricks won't save to blocks.

### ISSUE THREAD

**Issue by jpeaceau** [EssentialsX/Essentials#1993] opened 2018-05-03 09:07 UTC
### Information

Full output of `/ess version`:

1.8.8-R0.1-SNAPSHOT git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8)
EssentialsX version: 2.15.0.1
PermissionsEx version: 1.23.4
INFO Vault version: 1.5.6-b49
INFO EssentialsXChat version: 2.15.0.1
INFO EssentialsXSpawn version: 2.15.0.1

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 

### Details

Describe your issue here.
When using /createkit as configured it will generate it into a hastebin link however it makes clay blocks into "CLAY" and brick blocks into "BRICKS" which don't return the same blocks.

**Comment by Xeyame** [comment] 2018-05-03 10:44
Clay blocks and brick blocks are different blocks, so whats the issue?

**Comment by mdcfe** [comment] 2018-05-03 17:10
@Xeyame I assume the OP means that running `/createkit` adds clay and brick items rather than blocks.

**Comment by Xeyame** [comment] 2018-05-03 17:44
Couldn't figure that out xD, Yeah he probs means that

**Comment by drtshock** [comment] 2018-05-21 21:31
Unable to reproduce with /createkit 

```[14:34:04 INFO]: CONSOLE issued server command: /ess version
[14:34:04 INFO]: Server version: 1.12.2-R0.1-SNAPSHOT git-Spigot-93e20b3-9ab758c (MC: 1.12.2)
[14:34:04 INFO]: EssentialsX version: 2.15.0.3
[14:34:04 INFO]: PermissionsEx version: 1.23.4
[14:34:04 INFO]: Vault version: 1.5.6-b49
[14:34:04 INFO]: EssentialsXSpawn version: 2.15.0.3
```

```yaml  colors:
    delay: 1
    items:
    - STAINED_GLASS:9 1
    - CONCRETE:1 1
    - CONCRETE_POWDER:2 1

**Comment by mdcfe** [comment] 2018-05-23 05:04
@drtshock Did you try replicating this with **clay blocks** and **brick blocks** in your inventory? The bug report is that those two specific items get saved as clay and brick **items**.

**Comment by jpeaceau** [comment] 2018-06-02 18:04
@drtshock also note it was configured for hastebin, not in the config directly although I haven't tested with just the regular /createkit command. When you use clay blocks and brick blocks it only returns the items. You can also see there are duplicate aliases for the items when using /itemdb

**Comment by triagonal** [comment] 2019-05-09 15:07
This no longer occurs on the latest build of EssentialsX, both when saving kits directly to file and to hastebin.

Essentials version:
```
[01:03:28 INFO]: CONSOLE issued server command: /ess version
[01:03:28 INFO]: Server version: 1.13.2-R0.1-SNAPSHOT git-Paper-624 (MC: 1.13.2)
[01:03:28 INFO]: EssentialsX version: 2.16.1.154
[01:03:28 INFO]: Vault is not installed. Chat and permissions may not work.
```
Local kit:
```yaml
kits:
  local:
    delay: -1
    items:
    - bricks 64
    - clay 64
```
Pastebin kit:
```yaml
kits:
  paste:
    delay: -1
    items:
    - bricks 64
    - clay 64
```
Inventory contents when creating kits:
![image](https://user-images.githubusercontent.com/10545540/57464518-3a5d6f80-72c0-11e9-841d-6c7fd6d737bf.png)

**Comment by mdcfe** [comment] 2019-06-16 12:10
Closing as both myself and @triagonal cannot replicate this.

**Closed as completed by mdcfe** 2019-06-16 12:10 UTC
Labels: type: problem, status: not enough info, bug: unconfirmed
