### ISSUE TITLE
Players sink when teleporting.

### ISSUE THREAD

**Issue by MithrandirCraft** [EssentialsX/Essentials#3474] opened 2020-07-09 00:59 UTC
**Full output of `/ess version`**:

```
[02:50:12 INFO]: CONSOLE issued server command: /ess version
[02:50:12 INFO]: Server version: 1.15.2-R0.1-SNAPSHOT git-Paper-375 (MC: 1.15.2)
[02:50:12 INFO]: EssentialsX version: 2.17.2.127
[02:50:12 INFO]: LuckPerms version: 5.1.55
[02:50:12 INFO]: PlaceholderAPI version: 2.10.6
[02:50:12 INFO]: Vault version: 1.7.2-b107
[02:50:12 INFO]: EssentialsXSpawn version: 2.17.2.127
```

**Server log**:  Irrelevant. No relevant info included within latest log. Plugin loads fine.

**EssentialsX config**: https://gist.github.com/MithrandirCraft/edd5c27a3c791250c4c74f809db349bd

### Details

**Description**  
Sometimes when you teleport (players frequently report this with essentials's /tpa and /tpahere), you can either end up underground and suffocate to death, or die in the void.

**Steps to reproduce**  
No one knows, but it's easier to reproduce if the teleport destination point is covered in carpets. I personally managed to sink my character 1 block deep by teleporting to unloaded chunks by accepting a tpahere. The chunks where unloaded, but it probably happens with loaded chunks too.

**Expected behavior**  
Players shouldn't sink.

**Screenshots**  
![2020-07-05_21 13 32](https://user-images.githubusercontent.com/6623704/86984892-17627000-c190-11ea-9f68-70dd42d4aa00.png)
![CAPP111](https://user-images.githubusercontent.com/6623704/86984905-247f5f00-c190-11ea-8806-6289fcce5a53.png)
Someone suffocating under ground after tp.

**Comment by pop4959** [comment] 2020-07-09 01:16
Duplicate of #2918. Not an Essentials issue; see [MC-153463](https://bugs.mojang.com/browse/MC-153463) for details about this bug.

**Closed as completed by pop4959** 2020-07-09 01:16 UTC
Labels: status: duplicate, bug: upstream
