### ISSUE TITLE
NPE in onServerListPing()

### ISSUE THREAD

**Issue by NachtRaben** [EssentialsX/Essentials#1455] opened 2017-08-09 02:28 UTC
EssentialsX version (`/essentials`): 2.0.1-b516

Server software (`/version`): git-Paper-1178 (MC: 1.12.1) (API: 1.12.1-R0.1-SNAPSHOT)

EssentialsX config (if applicable): Vanilla, not modified.

Paper.yml config: Vanilla, not modified.

Getting massive amounts of Null Pointers in my console. Happens on a fresh server with no name/player modifying plugins.

Happens with every ping:
https://gist.github.com/NachtRaben/5350ed9d731fc87a5391b96133a5e06f

**Comment by mdcfe** [comment] 2017-08-09 07:05
Duplicate of #1442.

**Closed as completed** 2017-08-09 07:05 UTC
Labels: bug: confirmed, status: duplicate
