### ISSUE TITLE
Bug /fly permission node

### ISSUE THREAD

**Issue by Guest1131** [EssentialsX/Essentials#2216] opened 2018-10-20 22:49 UTC
Hi, there,

There is a problem with /fly essentials.fly, I added this temporary permission to the "user" group, with LuckPerms

lp group default permission settemp essentials.fly true 5M

The problem is that, if the user is in flight, and the permission expires, he still manages to fly...does not drop it...

Only if he gets out of the game and back in...can't fly anymore, because his permit's expired.

Resolve, please.

**Comment by BluePlastics** [comment] 2018-10-22 07:08
Fly is a toggle (/fly once for on and /fly again for off) a user with the permission node can toggle fly on however even if that permission node is taken away (meaning the player can also not toggle fly off) fly does not get automatically toggled off.

While this could be a feature in future version, this is the "intended" behavior and is not a bug.

You should probably design a check somehow that makes sure users that do not have the fly permission any longer get their fly toggled off if it is on.

**Comment by mdcfe** [comment] 2018-10-22 10:50
Duplicate of #1322. This is [not something we intend to add to EssentialsX](https://github.com/EssentialsX/Essentials/issues/1322#issuecomment-371415934):
> I don't see that this can be done in a way that is efficient while supporting most permissions plugins. In addition, [...] `essentials.fly` should remain the permission for the `/fly` command and not have additional side effects like this.

**Closed as completed by mdcfe** 2018-10-22 10:50 UTC
Labels: status: duplicate, type: enhancement, status: wontfix
