### ISSUE TITLE
certain essentialsX commands in 1.21.3 break the game

### ISSUE THREAD

**Issue by minisat0shi** [EssentialsX/Essentials#5965] opened 2024-11-10 13:16 UTC
### Type of bug

Error in console, Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=6841a97ffb08486b9f14f71dc9fe4392

### Error log (if applicable)

https://paste.gg/p/anonymous/fd1c5d11ce4a4d75993fb400487804fa

### Bug description

Certain commands, such as "/spawn" or "/home <anyHome>" result in "java.lang.IllegalArgumentException: Modifier is already applied on this attribute!" and then all future interactions with the chat (be it chat or command) will return "Chat disabled in client options" until logging out and back into the server.

This only appears to happen with EssentialsX commands.

### Steps to reproduce

Same as Bug Description

### Expected behaviour

Commands should just work!

### Actual behaviour

java.lang.IllegalArgumentException: Modifier is already applied on this attribute!
Chat disabled in client options

**Comment by Evidentsinger14** [comment] 2024-11-10 21:49
I cannot reproduce this on my test environment using the latest 1.21.3 paper build, and essx dev build 128. 
i would try to isolate your server to only have essx, and supported plugins (luckperms, vault, and any essx addons) and see if the issue still occurs. 
I do see coreprotect being mentioned in the stacktrace you provided, but that would be odd if it was only essx commands. 
closing for now, can re-open if this is able to be replicated later.

**Closed as not planned by Evidentsinger14** 2024-11-10 21:49 UTC
Labels: status: invalid
