### ISSUE TITLE
Silentjoin-Bug

### ISSUE THREAD

**Issue by Bedah95** [EssentialsX/Essentials#1064] opened 2017-01-10 16:04 UTC
Silentvanished joining people are visible via tablist(Tab) for players who are already on the server.

Using:
Latest Spigot 1.11.2-Build
Latest EssentialsX-Build
zPermissions

**Comment by RasteKai** [comment] 2017-01-15 12:30
Same problem on my server.
Online players can see new connected admins with silentjoin permissions in the tablist.
We are using one of the latest versions of Paper.

**Comment by SupaHam** [comment] 2017-06-29 02:54
Can you confirm if this is still an issue?

**Comment by Bedah95** [comment] 2017-07-04 17:20
yeah, it´s still an issue on our server

**Comment by mdcfe** [comment] 2018-03-08 16:21
If this is still an issue, could you post the **full output** of `/ess version`? This is likely a duplicate of the known vanish list duplication bug.

**Comment by mdcfe** [comment] 2018-05-02 21:23
Closing due to lack of response. If this is still a problem, feel free to respond and reopen the issue.

**Closed as completed by mdcfe** 2018-05-02 21:23 UTC
Labels: status: not enough info
