### ISSUE TITLE
/invsee does not allow modifying equipment slots

### ISSUE THREAD

**Issue by pop4959** [EssentialsX/Essentials#1808] opened 2018-01-26 06:36 UTC
EssentialsX version (run `/essentials`): 2.0.1-bSNAPSHOT

Server software (run `/version`): git-Spigot-00128b5-558c5a3

Details:

Title should be self explanatory. Typing for example "/invsee <user> equipment" and trying to modify their equipment slots does not work, even with modify permissions enabled. In contrast, modifying a player's normal inventory with "/invsee <user>" works.

**Comment by mdcfe** [comment] 2018-01-26 22:16
Duplicate of #472.

`/invsee equip` was deemed an Easter egg in the original Essentials, as [at the time it was impossible to accomplish this](https://github.com/EssentialsX/Essentials/issues/472#issuecomment-196002401). The original issue remains open as an enhancement, so it may be considered in the future, but this is not a bug.

**Closed as completed by mdcfe** 2018-01-26 22:16 UTC
