### ISSUE TITLE
Could not pass BlockIgniteEvent, MaterialData cannot be cast to org.bukkit.material.Sign (1.14 PaperMC)

### ISSUE THREAD

**Issue by jason-s-yu** [EssentialsX/Essentials#2582] opened 2019-06-04 04:10 UTC
### Information

Full output of `/ess version`:
```
[00:08:28 INFO]: CONSOLE issued server command: /ess version
[00:08:28 INFO]: Server version: 1.14.2-R0.1-SNAPSHOT git-Paper-65 (MC: 1.14.2)
[00:08:28 INFO]: EssentialsX version: 2.16.1.167
[00:08:29 INFO]: LuckPerms version: 4.4.25
[00:08:29 INFO]: Vault version: 1.7.2-b107
[00:08:29 INFO]: EssentialsXSpawn version: 2.16.1.167
```

https://gist.github.com/jason-s-yu/4bfc525e1b133ebfa47d395edcea6558
```
[23:59:02 ERROR]: Could not pass event BlockIgniteEvent to Essentials v2.16.1.167
java.lang.ClassCastException: org.bukkit.material.MaterialData cannot be cast to org.bukkit.material.Sign
        at com.earth2me.essentials.signs.EssentialsSign.checkIfBlockBreaksSigns(EssentialsSign.java:217) ~[?:?]
        at com.earth2me.essentials.signs.SignBlockListener.onSignBlockIgnite(SignBlockListener.java:190) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor210.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.2.jar:git-Paper-65]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.2.jar:git-Paper-65]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.2.jar:git-Paper-65]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[patched_1.14.2.jar:git-Paper-65]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callBlockIgniteEvent(CraftEventFactory.java:1276) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.FluidTypeLava.b(FluidTypeLava.java:44) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.Fluid.b(SourceFile:78) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.BlockFluids.c(BlockFluids.java:30) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.IBlockData.b(IBlockData.java:205) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.WorldServer.a(WorldServer.java:450) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickChunks(ChunkProviderServer.java:374) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.tick(ChunkProviderServer.java:282) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:264) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1177) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.2.jar:git-Paper-65]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

Unsure what this indicates. I'm running Paper on 1.14.2. I know everything's still unstable but this seems out of the ordinary.

**Comment by mdcfe** [comment] 2019-06-04 06:50
Duplicate of #2529 - you can download a 1.14 experimental build from [here](https://github.com/EssentialsX/Essentials).

**Closed as completed by mdcfe** 2019-06-04 06:50 UTC
