### ISSUE TITLE
unlimited blocks fail

### ISSUE THREAD

**Issue by Stoniasawsome** [EssentialsX/Essentials#2892] opened 2019-12-22 06:05 UTC
1. unlimited blocks can not be given by the server.
2. If the server reboots while players have unlimited blocks enabled it breaks their essentials player data file. reason: 
unlimited:
- !!org.bukkit.Material 'GRANITE'

^(this is not how the information was input, i typed... 
 /unlimited blocks playername) then rebooted the server.

[unlimited fail.txt](https://github.com/EssentialsX/Essentials/files/3992178/unlimited.fail.txt)

[05:52:52] [User Authenticator #2/INFO]: UUID of player Steve_French_ is 25964d75-97aa-3426-bea9-91360a1caa3c
[05:52:52] [Server thread/ERROR]: The file /home/mch/multicraft/servers/server62612/plugins/Essentials/userdata/25964d75-97aa-3426-bea9-91360a1caa3c.yml is broken, it has been renamed to /home/mch/multicraft/servers/server62612/plugins/Essentials/userdata/25964d75-97aa-3426-bea9-91360a1caa3c.yml.broken.1576993972662
org.yaml.snakeyaml.constructor.ConstructorException: could not determine a constructor for the tag tag:yaml.org,2002:org.bukkit.Material
 in 'string', line 26, column 3:
    - !!org.bukkit.Material 'GRANITE'
      ^

	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructUndefined.construct(SafeConstructor.java:541) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:216) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:205) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequenceStep2(BaseConstructor.java:376) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequence(BaseConstructor.java:360) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlSeq.construct(SafeConstructor.java:499) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:216) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:205) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:465) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:184) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:446) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:521) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:216) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:205) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:164) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:148) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:525) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:438) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) ~[spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at com.earth2me.essentials.EssentialsConf.load(EssentialsConf.java:138) [EssentialsX-2.17.1.0.jar:?]
	at com.earth2me.essentials.UserData.reloadConfig(UserData.java:63) [EssentialsX-2.17.1.0.jar:?]
	at com.earth2me.essentials.UserData.<init>(UserData.java:46) [EssentialsX-2.17.1.0.jar:?]
	at com.earth2me.essentials.User.<init>(User.java:65) [EssentialsX-2.17.1.0.jar:?]
	at com.earth2me.essentials.UserMap.load(UserMap.java:159) [EssentialsX-2.17.1.0.jar:?]
	at com.earth2me.essentials.UserMap.load(UserMap.java:23) [EssentialsX-2.17.1.0.jar:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at com.earth2me.essentials.UserMap.getUser(UserMap.java:111) [EssentialsX-2.17.1.0.jar:?]
	at com.earth2me.essentials.Essentials.getUser(Essentials.java:693) [EssentialsX-2.17.1.0.jar:?]
	at com.earth2me.essentials.EssentialsPlayerListener$CommandSendListener.onCommandSend(EssentialsPlayerListener.java:847) [EssentialsX-2.17.1.0.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.CommandDispatcher.a(CommandDispatcher.java:270) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.PlayerList.a(PlayerList.java:861) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.PlayerList.d(PlayerList.java:712) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.PlayerList.a(PlayerList.java:152) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.LoginListener.c(LoginListener.java:154) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.LoginListener.tick(LoginListener.java:53) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:220) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:129) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1099) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:978) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:823) [spigot-1.15.jar:git-Spigot-047b6f8-e43416a]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[05:52:52] [Server thread/INFO]: Steve_French_[/74.78.203.15:57466] logged in with entity id 1414 at ([Spawn]-348.5699408338594, 5.0, -53.7795733953309)
[05:52:52] [pool-39-thread-1/INFO]: Creating empty config: /home/mch/multicraft/servers/server62612/plugins/Essentials/userdata/25964d75-97aa-3426-bea9-91360a1caa3c.yml

**Comment by triagonal** [comment] 2019-12-22 06:09
Duplicate of #2778. This will be fixed by PR #2811 when merged.

**Closed as completed by triagonal** 2019-12-22 06:09 UTC
Labels: status: duplicate
