### ISSUE TITLE
Trade Signs Not Updating After Transactions in Minecraft

### ISSUE THREAD

**Issue by tekikaito** [EssentialsX/Essentials#5577] opened 2023-11-11 15:14 UTC
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=fa654ab7f413432f8ce5acdaec567a1c

### Bug description

I encountered a bug in the latest version of the Minecraft EssentialX Plugin, specifically related to the "Trade" signs functionality. The Trade signs in this plugin are intended to facilitate buying and selling items between players.

### Steps to reproduce

1. Install the latest dev version of the EssentialX Plugin on a Minecraft server. (2.21.0-dev+21-c68b277)
2. Set up a Trade sign for selling/buying items according to the plugin's instructions.
3. As a player, interact with the sign to buy an item.
4. Observe the balance and item inventory of the player.

### Expected behaviour

Upon a successful transaction, the player's balance should decrease by the cost of the item, and the purchased item should be added to the player's inventory. Concurrently, the Trade sign should update to reflect the transaction: the money should be added to the sign's associated account, and the count of items available for sale should decrease.

### Actual behaviour

While the player's balance does decrease and they receive the item as expected, the Trade sign does not reflect the transaction. The sign's money balance does not increase, and the item count does not decrease. This inconsistency implies that the transaction is not fully processed on the server side concerning the Trade sign.

**Comment by Evidentsinger14** [comment] 2023-12-10 01:15
While testing, i have confirmed the signs are not being updated with the amount of items being put in, and the money was unable to be collected ("There is nothing to collect from this trade sign").

**Comment by tester43214** [comment] 2024-04-03 01:01
I have reported exactly the same problem on Spigot two weeks ago, but the problem still persists although I'm on 2.21.0-dev+73-2cb0af0 version: https://www.spigotmc.org/threads/essentialsx.76168/page-171#post-4709047. Can anyone provide an information when this bug will be fixed?

**Comment by xartuu** [comment] 2024-04-30 03:41
The owner of `Trade Sign` cannot replenish the items in the sign. When the owner clicks the right mouse button while holding a traded item, its amount is not updated on the sign. Which results in the player not getting the inserted items back after destroying the sign.

In fact, at colleague @tester43214 above is even more touched on.
> https://www.spigotmc.org/threads/essentialsx.76168/page-171#post-4709047

In addition, when you right-click on a sign to pick up items in the console, there is an error (I am sending a dump).
https://essentialsx.net/dump.html?id=c0a0c26d7a42438ab9984280fac4edbe

Demonstration on Discord: https://discord.com/channels/390942438061113344/426460575971672064/1234702082389315644

**Comment by jozlod** [comment] 2024-06-17 02:28
I'm really hoping this gets looked at at some point, is there anyway I can help with more logs or anything?

I would rather not have to change the way we do player shops, but it seems like not enough people use trade signs to worry about a fix, so it might have to happen at some point I guess.

**Comment by pop4959** [comment] 2024-06-17 03:00
> I'm really hoping this gets looked at at some point, is there anyway I can help with more logs or anything?
> 
> I would rather not have to change the way we do player shops, but it seems like not enough people use trade signs to worry about a fix, so it might have to happen at some point I guess.

This has been a bit of a tricky bug for us, however it *is* high priority, and the last item on our milestone goal for 2.20.2. I can't give an ETA but we'll most likely be looking at fixing this at least before the next release.

**Comment by jozlod** [comment] 2024-07-22 11:07
I believe this is fixed, seems to be from:

This commit: https://github.com/EssentialsX/Essentials/commit/80c3150
For this issue: https://github.com/EssentialsX/Essentials/issues/5814

It's working for me on paper-1.21-107 and EssentialsX 2.21.0-dev+105-80c3150
I haven't tested everything, but seems good so far. If there is no more updates I'll report back as I test a little more.

**Closed as completed** 2024-07-22 11:16 UTC
Labels: bug: confirmed
