### ISSUE TITLE
Not replacing UUID in usermap.

### ISSUE THREAD

**Issue by rejomy** [EssentialsX/Essentials#5091] opened 2022-08-26 16:12 UTC
### Type of bug

Error in console

### `/ess dump all` output

[19:13:21 WARN]: org.apache.commons.lang.UnhandledException: Plugin Essentials v2.19.6 generated an exception while executing task 558376
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: com.google.gson.JsonArray.add(Ljava/lang/String;)V
        at com.earth2me.essentials.utils.CommandMapUtil.toJson(CommandMapUtil.java:63)
        at com.earth2me.essentials.utils.CommandMapUtil.toJson(CommandMapUtil.java:34)
        at com.earth2me.essentials.utils.CommandMapUtil.toJsonPretty(CommandMapUtil.java:27)
        at com.earth2me.essentials.commands.Commandessentials.lambda$runDump$3(Commandessentials.java:381)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 4 more

### Error log (if applicable)

-

### Bug description

[19:09:40 INFO]: Found UUID 588c902c-c6d2-314a-bbcc-f0f89d47d4eb for player ЧЧ, but player already has a UUID (22f32752-7af6-31ac-bb04-fb1b7ab2b9b9). Not replacing UUID in usermap.
java.lang.RuntimeException: null
        at com.earth2me.essentials.UserMap.trackUUID(UserMap.java:155) ~[?:?]
        at com.earth2me.essentials.UserMap.load(UserMap.java:182) ~[?:?]
        at com.earth2me.essentials.UserMap.load(UserMap.java:30) ~[?:?]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3934) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at com.earth2me.essentials.UserMap.getUser(UserMap.java:129) ~[?:?]
        at com.earth2me.essentials.BalanceTopImpl.calculateBalanceTopMap(BalanceTopImpl.java:32) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23) ~[server.jar:git-PaperSpigot-"f6b10d47"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_301]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_301]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_301]

### Steps to reproduce

- I use the command /baltop, my server is supporting player а-яА-Я (Russian) nickname,

### Expected behaviour

-

### Actual behaviour

-

**Comment by osfanbuff63** [comment] 2022-08-26 16:34
Duplicate of #4342

**Closed as not planned** 2022-08-26 19:28 UTC
Labels: bug: unconfirmed
