### ISSUE TITLE
Some of the NBT Tags still aren't saved in kits.

### ISSUE THREAD

**Issue by MateoNikolic** [EssentialsX/Essentials#3324] opened 2020-05-23 17:04 UTC
Some of the NBT Tags still aren't saved while creating the kit.
I've made a gif that shows it really good.
The first or upper set I cover is the real set with good and corrent NBT Tags
The seconds or lower set is the set that's take after kit is saved and loaded with Essentials:

![0MrEcykDTt](https://user-images.githubusercontent.com/59744325/82736215-39ab4600-9d28-11ea-9ad2-881d99b6cf84.gif)

Also there are some NBT Tags that are being saved like Armor and Armor Toughness.
This were tested with plugin called MythicMobs, it allows creating custom items with nbt tags.

**Comment by JRoy** [comment] 2020-05-23 17:08
Duplicate of #3323

**Closed as completed by JRoy** 2020-05-23 17:08 UTC
Labels: status: duplicate

**Comment by MateoNikolic** [comment] 2020-05-23 18:51
What duplicates? Fix the fucking bugs, it's not even duplicated it's a new freaking thread you dumb fuck

**Comment by pop4959** [comment] 2020-05-23 18:57
Please have a better attitude. It's a duplicate because someone has posted exactly the same thing, and it's still open for someone to implement. Re-creating the same issue over and over is not going to make it happen faster. Watch or reply to the original "thread" (issue, this is not a forum) if you want to keep up to date on its progress.

**Comment by MateoNikolic** [comment] 2020-05-23 20:07
Sorry I was pissed off because I took my time taking the gif and reporting everything.
I just want this fixed, it's the problem that's like 2 years old. I don't wanna use external kit plugin just for this reason.

**Comment by pop4959** [comment] 2020-05-23 20:33
It's a low priority addition currently, so it might be a while before Essentials supports this. You must understand that Essentials development is mostly driven by individual efforts of contributors, which means that if no one is interested in adding the feature, it doesn't get added. Since these metadata tags are not very uncommon (pertaining only to plugins/modded experiences), my guess is not many people are interested or even know about them. Currently the recommendation for third party plugins (such as your "MythicMobs") is to add the item to the kit in the form of a command, provided that the plugin has something like that. You could ask them to add something like this if they don't already. Otherwise, you might want to look into another kit plugin, as you're at the mercy of someone willing to add this feature (it could be another 3 years, or longer!).
