### ISSUE TITLE
/jump lock command?

### ISSUE THREAD

**Issue by ProblemsSender** [EssentialsX/Essentials#2322] opened 2018-12-28 14:22 UTC
Related to #2317 

> `/jump lock` makes you teleport whenever you click on a block.
> `/kittycannon` fires (non-damaging) exploding kittens in the direction you are facing.
> `/nuke` causes TNT to rain down from the sky around each player.
 
Hello again, sorry for disturbing-but somehow /jump lock command hasn't work as intended, here's my ss versions
[14:04:41 INFO]: Server version: 1.12.2-R0.1-SNAPSHOT git-Spigot-dcd1643-e60fc34
 (MC: 1.12.2)
[14:04:41 INFO]: EssentialsX version: 2.15.0.57
[14:04:41 INFO]: PermissionsEx version: 1.23.4
[14:04:41 INFO]: Vault version: 1.6.7-b${env.TRAVIS_BUILD_NUMBER}
[14:04:41 INFO]: EssentialsXProtect version: 2.15.0.57
[14:04:41 INFO]: EssentialsXSpawn version: 2.15.0.57
[14:04:41 INFO]: EssentialsXChat version: 2.15.0.57
[14:04:41 INFO]: EssentialsXAntiBuild version: 2.15.0.57
 
Pls help me make this command to work, is this required some config to work? At first I thought that my problem is I didn't give my player a permissions to build.* - I added that and it still appear, what is the requirement to make this work? And additional question, can we use /jump lock instead of /jump?

**Comment by mdcfe** [comment] 2018-12-28 14:28
Please fill out the template, as requested previously; there is not enough detail to help.

---

```yaml
<!-- EssentialsX help guide

Don't write inside the arrows as they will be hidden when you post your issue.

Want faster support? Come join our Discord server to get help sooner:
https://discord.gg/F7gexAQ

If you're happy to wait (or you were sent here from Discord), read on:

1.  Fill out the template.
      This will help us understand what problem you've encountered and help us
      find a solution.

2.  Check the Common Issues page.
      Read through the wiki page to see if you've encountered a regular issue:
      https://essentialsx.github.io/#/Common-Issues

3.  Delete this line and all above lines before posting your issue!       -->

### Information

Full output of `/ess version`:

<!-- Replace this with the command output -->

**Server log:** <!-- Upload `logs/latest.log` to https://gist.github.com/ -->

**EssentialsX config** <!-- Upload `plugins/Essentials/config.yml` to https://gist.github.com/ -->

### Help request

**Problem**
<!-- What problem did you encounter? -->

**What I have tried**
<!-- What have you tried so far? -->

**Screenshots**
<!-- If relevant, include any screenshots here. -->

```

**Comment by ProblemsSender** [comment] 2018-12-28 14:48
### Information

Full output of `/ess version`:

[14:04:41 INFO]: Server version: 1.12.2-R0.1-SNAPSHOT git-Spigot-dcd1643-e60fc34
(MC: 1.12.2)
[14:04:41 INFO]: EssentialsX version: 2.15.0.57
[14:04:41 INFO]: PermissionsEx version: 1.23.4
[14:04:41 INFO]: Vault version: 1.6.7-b${env.TRAVIS_BUILD_NUMBER}
[14:04:41 INFO]: EssentialsXProtect version: 2.15.0.57
[14:04:41 INFO]: EssentialsXSpawn version: 2.15.0.57
[14:04:41 INFO]: EssentialsXChat version: 2.15.0.57
[14:04:41 INFO]: EssentialsXAntiBuild version: 2.15.0.57

**Server log:** Nothing bad

**EssentialsX config** Nothing bad

### Help request

**Problem**
Can't teleport to block by clicking it after using /jump lock command

**What I have tried**
Give player full ess.build.* permissions, /jump lock permission, and it still occurs,

**Comment by mdcfe** [comment] 2018-12-28 14:52
Could you post screenshots of what happens when:
* you run `/jump lock`,
* you right-click on a block, and
* you run `/jump lock` a second time?

**Comment by ProblemsSender** [comment] 2018-12-28 15:13
Pic 1 Jump lock disabled
-https://www.upsieutoc.com/image/GnINc8
Pic 2 Jump lock enabled + right click
-https://www.upsieutoc.com/image/GnIprC
Pic 3 Jump lock+right click survival mode
-https://www.upsieutoc.com/image/GnIJGD
Pic 4 Jump lock+ right click near grass
-https://www.upsieutoc.com/image/GnIL0r
...I think those picture don't proof anything...

**Comment by ProblemsSender** [comment] 2018-12-28 15:18
Bug confirmed, even with op it doesn't work

**Comment by ProblemsSender** [comment] 2018-12-28 15:21
additional question, is it /jump lock only work if we right click to a block that we can see near? if not can you make it? In adventure world there's alot of "death hole" with 2 block tall, if we fall in that is that the end of the player?

**Comment by triagonal** [comment] 2018-12-28 16:33
I was also unsure of what `/jump lock` did when you opened #2317, so I went and looked at the source to figure out exactly what happens. `/jump lock` actually toggles "flying wizard mode", which enables the player to **left-click the air** to jump only when also **flying at the same time**. This is confirmed by the code in EssentialsPlayerListener:
```
case LEFT_CLICK_AIR:
                if (event.getPlayer().isFlying()) {
                    final User user = ess.getUser(event.getPlayer());
                    if (user.isFlyClickJump()) {
                        useFlyClickJump(user);
                        break;
                    }
                }
```
as well as this comment above the `useFlyClickJump()` method
```
// This method allows the /jump lock feature to work, allows teleporting while flying #EasterEgg
```
So the behavior of `/jump lock` is actually to enable a player to jump by left clicking in the air, while also flying.

**Comment by mdcfe** [comment] 2018-12-28 16:54
@triagonal Thanks for writing this up - I was actually about to post an explanation before I got caught up trying to figure out an issue with the `items.json` generator.

**Comment by ProblemsSender** [comment] 2018-12-28 16:55
> I was also unsure of what `/jump lock` did when you opened #2317, so I went and looked at the source to figure out exactly what happens. `/jump lock` actually toggles "flying wizard mode", which enables the player to **left-click the air** to jump only when also **flying at the same time**. This is confirmed by the code in EssentialsPlayerListener:
> 
> ```
> case LEFT_CLICK_AIR:
>                 if (event.getPlayer().isFlying()) {
>                     final User user = ess.getUser(event.getPlayer());
>                     if (user.isFlyClickJump()) {
>                         useFlyClickJump(user);
>                         break;
>                     }
>                 }
> ```
> as well as this comment above the `useFlyClickJump()` method
> 
> ```
> // This method allows the /jump lock feature to work, allows teleporting while flying #EasterEgg
> ```
> So the behavior of `/jump lock` is actually to enable a player to jump by left clicking in the air, while also flying.

Thanks for your guiding, but if this is what /jump lock does, it seems it does not so useful, while I test it, it only "jump" horizontally few block, it doesn't help, it's good if we change that to affect to normal player

**Comment by triagonal** [comment] 2019-04-23 01:37
Closing - question seems to be resolved. Please comment on this issue if you require further support.

**Closed as completed by triagonal** 2019-04-23 01:37 UTC
Labels: type: question, status: not enough info
