### ISSUE TITLE
Duplicated  item when an admin dies

### ISSUE THREAD

**Issue by Pistakkio** [EssentialsX/Essentials#2695] opened 2019-07-29 15:30 UTC
### Information

Full output of `/ess version`:

[17:44:18 INFO]: Server version: 1.14.4-R0.1-SNAPSHOT git-Paper-152 (MC: 1.14.4)
[17:44:18 INFO]: EssentialsX version: 2.17.0.7
[17:44:18 INFO]: LuckPerms version: 4.4.27
[17:44:18 INFO]: Vault version: 1.7.2-b107
[17:44:18 INFO]: EssentialsXGeoIP version: 2.17.0.7
[17:44:18 INFO]: EssentialsXChat version: 2.17.0.7
[17:44:18 INFO]: EssentialsXSpawn version: 2.17.0.7

**Server log:** https://gist.github.com/Pistakkio/2672c4cf086843d44ab19e67d46c39aa.js

**EssentialsX config** https://gist.github.com/Pistakkio/2672c4cf086843d44ab19e67d46c39aa.js

### Help request

**Problem**
i have Paper 1.14.4 server. when I play as admin I have all the permissions with 'essentials. *', but if I die I have all the items left in the inventory and in addition I drop too. practically duplicate. how do i solve?

**What I have tried**
set permission 'essentials.keepinventory' false (i use LuckPerms)

**Comment by mbax** [comment] 2019-07-29 15:38
Looks like this is a duplicate issue of #2694 but you still have not followed the instructions. 

Please [click here](https://github.com/EssentialsX/Essentials/issues/new?template=help.md) and OBEY THE INSTRUCTIONS on the page.

**Comment by Pistakkio** [comment] 2019-07-29 15:41
nobody help me in #2694, and is locked...

**Comment by darbyjack** [comment] 2019-07-29 17:54
The issue is due to a change that spigot did. You'll just have to wait until we can accommodate it.

**Comment by Pistakkio** [comment] 2019-07-29 18:12
but I use Paper, what does spigot have to do with it?

**Comment by Pistakkio** [comment] 2019-07-29 18:13
before switching to Paper I used spigot, and in that version I didn't lose items but I didn't even drop them, so I didn't duplicate them.

**Comment by darbyjack** [comment] 2019-07-29 18:16
The change spigot did was this morning.

**Comment by mbax** [comment] 2019-07-29 18:17
> nobody help me in #2694, and is locked...

No, it isn't locked. *You* closed it, but that doesn't lock it.

Thank you for updating your issue with the information though. :)

**Comment by Pistakkio** [comment] 2019-07-29 18:33
I apologize for the disaster: /
I fixed re-using spigot 1.14.4 instead of Paper, and setting 'essentials.keepinv' false in the permission list.

**Comment by DuckDuckWhale** [comment] 2019-07-30 03:34
Also affected by this issue. Tested without EssentialsX and it worked okay, but once EssentialsX is turned back on again the issue reappears.

> The issue is due to a change that spigot did. You'll just have to wait until we can accommodate it.
> The change spigot did was this morning.

@darbyjack Can you please elaborate on that, e.g. how and when would it be "accommodated"?
I could see that this is probably related to [this commit](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/3e7b3862c7d1c718a47d1d5e54de8e3ea5845bbf) (`SPIGOT-5195 (#2): Player loot table does not drop when keepInventory is on`), but still don't quite grasp the full picture. Is it caused by Spigot's code? Are we waiting for Spigot to fix this?

**Comment by mdcfe** [comment] 2019-07-30 08:40
Reopening until either #2696 is merged or Spigot makes their position clear.

@DuckDuckWhale That commit changes the behaviour of every plugin that has ever used the standard Bukkit API to enable keepInventory.

Before that commit, Bukkit wouldn't drop the player's loot table (the items they would drop) onto the ground if a plugin enabled keepInventory. Since that commit, it drops the items anyway and now plugins are expected to clear the loot table when they change the keepInventory state.

The reason behind this was apparently to make datapacks work more consistently, but there are better ways to allow plugins to support this without breaking them all of a sudden. I would prefer a `PlayerDeathEvent#doDrops(boolean)` method so that plugins can *explicitly allow* drops when keepInventory is true, rather than the current system of forcing plugins to *explicitly deny* drops (which they've never had to do before and which came as a total surprise to everyone).

**Closed as completed** 2019-07-30 11:56 UTC
