### ISSUE TITLE
Add TPR multiworld support

### ISSUE THREAD

**Issue by Helyxst** [EssentialsX/Essentials#5489] opened 2023-08-23 09:34 UTC
### Feature description

Add TPR that can be enabled in each world(overworld, nether, end)
And the possibility to disable or enable them.

### How the feature is useful

After some time, all worlds get full nearby spawn, its useful to help players find places with no players.

**Comment by JRoy** [comment] 2023-11-11 01:10
Duplicate of #3469

**Closed as completed by JRoy** 2023-11-11 01:10 UTC
Labels: type: enhancement
