### ISSUE TITLE
Can't create [Buy] Sign

### ISSUE THREAD

**Issue by wardpieters** [EssentialsX/Essentials#824] opened 2016-08-17 04:10 UTC
When i create a buy sign and fill in everything correctly and press done, the sign is empty and got nothing on there.

This only happens on CB 1.10.X
To create the shop i have to use 1.9 and then switch back to 1.10.

I hope you can fix this.

**Comment by SupaHam** [comment] 2016-08-17 12:14
Duplicate of #687. Update server software.

**Closed as completed by SupaHam** 2016-08-17 12:14 UTC
Labels: status: duplicate
