### ISSUE TITLE
Signs not working

### ISSUE THREAD

**Issue by Vasquiinho** [EssentialsX/Essentials#854] opened 2016-08-29 13:41 UTC
Hi, i'm using EssentialsX 2.0.1-b370 and when i try to place signs like [buy] or [sell], etc.., after writting
[buy]
 1
stone
$1
on the sign (example) and confirmed, the sign stays without any thing and can´t use them.
Only color signs seems to work. Is that a bug of my version of spigot or is in the plugin? Can you check please? 
I have all signs enable in config.
Essentials debug only says:
[14:35:20 INFO]: [Essentials] checking if Vasquinho has essentials.signs.color - true
[14:35:20 INFO]: [Essentials] checking if Vasquinho has essentials.signs.magic - true
[14:35:20 INFO]: [Essentials] checking if Vasquinho has essentials.signs.format - true
[14:35:20 INFO]: [Essentials] checking if Vasquinho has essentials.signs.color - true
[14:35:20 INFO]: [Essentials] checking if Vasquinho has essentials.signs.magic - true
[14:35:20 INFO]: [Essentials] checking if Vasquinho has essentials.signs.format - true
[14:35:20 INFO]: [Essentials] checking if Vasquinho has essentials.signs.color - true
[14:35:20 INFO]: [Essentials] checking if Vasquinho has essentials.signs.magic - true
[14:35:20 INFO]: [Essentials] checking if Vasquinho has essentials.signs.format - true
[14:35:20 INFO]: [Essentials] checking if Vasquinho has essentials.signs.color - true
[14:35:20 INFO]: [Essentials] checking if Vasquinho has essentials.signs.magic - true
[14:35:20 INFO]: [Essentials] checking if Vasquinho has essentials.signs.format - true
[14:35:20 INFO]: [Essentials] checking if Vasquinho has essentials.signs.sell.create - true
[14:39:14 INFO]: [Essentials] checking if Vasquinho has essentials.afk.auto - true
[14:39:14 INFO]: [Essentials] checking if Vasquinho has essentials.sleepingignored - true

**Comment by SupaHam** [comment] 2016-08-29 17:57
Duplicate of #687. Update spigot.

**Closed as completed by SupaHam** 2016-08-29 17:57 UTC
Labels: status: duplicate
