### ISSUE TITLE
Start-Crash with Spigot 1.20.5 or 1.20.6 !

### ISSUE THREAD

**Issue by Jeppa** [EssentialsX/Essentials#5791] opened 2024-05-03 16:12 UTC
### Type of bug

Compatibility issue, Error in console

### `/ess dump all` output

"/ess dump all" not possible, since EssentialsX disables itself...

### Error log (if applicable)

https://paste.gg/p/anonymous/0f7c1bd5513342d3b68e1ee6cbb425fb

### Bug description

EssentialsX ist not working under 1.20.5 or 1.20.6 anymore!!! (Spigot)
Using Paper results in a similar crash.

The plugin crashes at server start and disables itself (again with an error...)

### Steps to reproduce

Use latest build from 30.4.2024 and start the server...

### Expected behaviour

Server should not crash ;)

### Actual behaviour

Not usable at all...

**Comment by mdcfe** [comment] 2024-05-03 16:14
1.20.6 support is a work in progress.
Closing as duplicate of #5779.

**Closed as completed by mdcfe** 2024-05-03 16:14 UTC
Labels: bug: unconfirmed

**Comment by Jeppa** [comment] 2024-05-03 16:16
OK, but shen you should NOT close the duplicate's 'original' https://github.com/EssentialsX/Essentials/issues/5779 ;)

**Comment by mdcfe** [comment] 2024-05-03 16:17
Work is already in progress at #5783. There is no need to open issues telling us to update to 1.20.6.
