### ISSUE TITLE
Could not pass event BlockBreakEvent to Essentials v2.16.1.156

### ISSUE THREAD

**Issue by Ghost-chu** [EssentialsX/Essentials#2586] opened 2019-06-07 07:44 UTC
### Information

**Full output of `/ess version`**:

```
[15:42:18 INFO]: CONSOLE issued server command: /ess version
[15:42:18 INFO]: Server version: 1.14.2-R0.1-SNAPSHOT git-Paper-67 (MC: 1.14.2)
[15:42:18 INFO]: EssentialsX version: 2.16.1.156
[15:42:18 INFO]: LuckPerms version: 4.4.1
[15:42:18 INFO]: Vault version: 1.7.2-b107
[15:42:18 INFO]: EssentialsXProtect version: 2.16.1.156
[15:42:18 INFO]: EssentialsXChat version: 2.16.1.156
[15:42:18 INFO]: EssentialsXAntiBuild version: 2.16.1.156
[15:42:18 INFO]: EssentialsXSpawn version: 2.16.1.156
[15:42:18 INFO]: You are running an unsupported server version!
```

**Server log**: https://paste.ubuntu.com/p/g2478wGvVw/

**EssentialsX config**: https://paste.ubuntu.com/p/MKzCjwCrX2/

### Details

**Description**  
When break the sign block

**Steps to reproduce**  
1. I don't know, my player said it break a sign and got this error.

**Expected behavior**  
Errors

**Screenshots**  
Nope

**Comment by triagonal** [comment] 2019-06-08 14:12
Duplicate of #2529. The stable builds of EssentialsX do not work on 1.14.x - you need to use the experimental builds until full 1.14 support is added, available at the [build server](https://ci.ender.zone/job/EssentialsX-Experimental/)

**Closed as completed by triagonal** 2019-06-08 14:12 UTC
Labels: status: duplicate
