### ISSUE TITLE
Safe TP teleporting players inside carpet

### ISSUE THREAD

**Issue by Technoguyfication** [EssentialsX/Essentials#2928] opened 2020-01-05 00:15 UTC
### Information

**Full output of `/ess version`**:

```
[17:11:09 INFO]: Server version: 1.14.4-R0.1-SNAPSHOT git-Paper-238 (MC: 1.14.4)
[17:11:09 INFO]: EssentialsX version: 2.17.1.17
[17:11:09 INFO]: LuckPerms version: 4.4.1
[17:11:09 INFO]: Vault version: 1.7.2-b107
[17:11:09 INFO]: EssentialsXChat version: 2.17.1.17
[17:11:09 INFO]: EssentialsXSpawn version: 2.17.1.17
```

**Server log**: https://pastebin.com/Eiqg8AUG

**EssentialsX config**: https://pastebin.com/WVEm833Q

### Details

**Description**  
With safe teleport enabled, players who teleport on carpet are placed inside the carpet and on top of the underlying block. This causes AAC to teleport them around because they are inside a block.

**Steps to reproduce**  
1. Install AAC with it's default config on the server
2. Stand on top of a carpet block
3. Teleport somewhere else like /spawn or /tpa
4. Do /back to return to your position on top of the carpet
5. The player is teleported inside the carpet

**Expected behavior**  
The player should be teleported on top of the carpet

**Comment by pop4959** [comment] 2020-01-05 01:36
Marking as a duplicate of #2918. Please also see [MC-153463](https://bugs.mojang.com/browse/MC-153463).

**Closed as completed by pop4959** 2020-01-05 01:36 UTC
Labels: status: duplicate, bug: upstream

**Comment by Technoguyfication** [comment] 2020-01-05 02:20
Couldn't this be fixed by changing the safe teleport algorithm to place players on top of carpets? @pop4959

**Comment by pop4959** [comment] 2020-01-05 02:44
It's possible that adding this to the unsafe block list would solve the problem. I spoke to md678685 about it, but the consensus was that such a change should probably be avoided as it can cause more harm than good by negatively impacting gameplay.

Also I forgot to mention, but you may want to report the issue with AAC to the developers of that plugin. I don't see why it should think someone is cheating when they were teleported legitimately via a plugin. Sounds like a bug in their detection.
