### ISSUE TITLE
/reply ignores mute?

### ISSUE THREAD

**Issue by molor** [EssentialsX/Essentials#1293] opened 2017-06-10 11:22 UTC
Is it really so? If a player is muted, but it someone wrote in the PM, he still may answer? Why?

If it is so intended, could you make /r command as alias of /reply, not vice versa? Just because commands in this case in the plugin.yml will look better.

**Comment by delbertina** [comment] 2017-07-08 02:47
I agree, this seems like it is not working as intended. Just looking at the commandmsg and commandr files looks like commandr is just missing : 

```
if (user.isMuted()) {
throw new Exception(tl("voiceSilenced"));
}
```

from the commandmsg file to check if a player is muted.

Disclaimer: Not a good plugin dev, just trying to help.

**Comment by delbertina** [comment] 2017-07-16 02:08
In my testing, issue is fixed after one of the latest dev versions with that merged PR.
#1375

**Closed as completed** 2017-07-16 05:36 UTC
Labels: type: enhancement

**Comment by mdcfe** [comment] 2017-07-16 09:49
This was fixed in a recent build - you can get the latest version from the [build server](https://ci.drtshock.net).
