### ISSUE TITLE
Plugin Essentials v2.15.0.17 generated an exception while executing task 23

### ISSUE THREAD

**Issue by M4rtyn4** [EssentialsX/Essentials#2094] opened 2018-07-30 14:56 UTC
### Information

![essversion](https://user-images.githubusercontent.com/29601346/43405052-e01dd0de-9410-11e8-90fb-b299a3d41631.png)

[latest.log](https://github.com/EssentialsX/Essentials/files/2241641/latest.log)

I have not touched anything in config file.

### Details

It worked first time I started server I did /sethome, /setspawn, and /spawn few times (like 3 or 4). 
It was still good but after restarting server /spawn just crash it. :(

**Comment by Xeyame** [comment] 2018-07-30 17:15
EssentialsX isn't compatible with 1.13 yet.

**Comment by mdcfe** [comment] 2018-08-01 14:49
This is a duplicate of #2080.

**Closed as completed by mdcfe** 2018-08-01 14:49 UTC
