### ISSUE TITLE
[bug] essentials.keepxp not functioning properly

### ISSUE THREAD

**Issue by Flavourized** [EssentialsX/Essentials#1583] opened 2017-10-08 10:11 UTC
EssentialsX: 2.0.1-b478 
Server: Paperspigot 1.11.2 R0.1 b1104
EssentialsX config: Fresh config

Problem:  
essentials.keepxp is not working at all for this build of essentials and pspig.
I have done a fresh install of our test server, installed PEX, essx, WE/WG. All are using fresh configs. I made 3 groups: Default, Middle, Admin. Server difficulty set to EASY
- Default has no permissions and does not inherit any groups
- Middle has permissions essentials.keepxp and inherits Default
- Admin has permissions '*' and isn't relevant

On an account with Admin, i gave an account with Default group xp (/xp give player 100). The Default account received 7 EXP levels. Then let the Default account die to a zombie. When the account respawned, it had lost its EXP. Okay, good.

Next, did the xp command (/xp give player2 100), giving player2 7 levels of xp. Player2 is has group Middle, and no other groups. Let player2 die to a zombie & respawned, player2 had no exp, even though essentials.keepxp is addded to Middle group and pex was reloaded prior to running these tests.

It may be that i am very tired, but i do not think im crazy.. If there is something im missing, please let me know

**Comment by mdcfe** [comment] 2017-10-08 10:57
Could you paste a plugin list from `/plugins`?

I can't see any reason for EssentialsX being the cause if the user has `essentials.keepxp`, so it seems likely that there is a plugin with a higher priority overriding this behaviour.

**Comment by Flavourized** [comment] 2017-10-09 07:54
On my phone ATM, let me do some testing first, I will come back and post my results. Like most problems with fundamental features: they need to work with the live server. Our live server runs ~75 plugins, but the feature only recently broke, and essx wasnt updated (my best guess is a conflict with TokenEnchant). 

I will post the results with interactions with diff plugins, and hopefully fix the problem that way.

**Comment by DrewAMitchell** [comment] 2017-12-17 09:22
@Flavourized Results?

**Comment by Flavourized** [comment] 2017-12-18 03:30
I tested it but couldn't figure it out. My best guess is that it is conflicting with TokenEnchant retainxp. 

I wrote a quick plugin to compensate for the issue and essentials not handling the keepxp on death. Still no idea what is casuing it though

**Comment by mdcfe** [comment] 2018-01-02 20:25
Closing as this doesn't appear to be an issue caused by EssentialsX.

**Closed as completed by mdcfe** 2018-01-02 20:25 UTC
Labels: type: problem, status: not enough info
