### ISSUE TITLE
Mob spawners issue 

### ISSUE THREAD

**Issue by DanielTravi** [EssentialsX/Essentials#1300] opened 2017-06-15 18:36 UTC
When I place a mob spawner I receive the following error and it is changed to the default one, the pig

Error:

15.06 20:36:02 [Server] WARN Skipping BlockEntity with id 
15.06 20:36:02 [Server] WARN Skipping BlockEntity with id 
15.06 20:36:02 [Server] WARN Skipping BlockEntity with id

**Comment by mdcfe** [comment] 2017-06-15 19:12
* What server software version are you running? `/version`
* What EssentialsX version are you running? `/ess`

**Comment by DanielTravi** [comment] 2017-06-15 20:21
15.06 21:13:49 [Server] INFO This server is running CraftBukkit version git-Spigot-d322acb-639aa0c (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

EssentialsX 2.0.1

**Comment by DanielTravi** [comment] 2017-06-15 20:28
EssentialsX 2.0.1-b483

**Comment by midnjerry** [comment] 2017-08-28 17:26
I can confirm this:

Replication Steps:
/give <player> mob_spawner 1 0 {BlockEntityTag:{EntityId:Creeper}}
Place spawner (as OP) --> WARN Skipping BlockEntity with id
Creeper spawns and then CreeperSpawner turns to PIgSpawner

Spigot: 1.12.1-R0.1-SNAPSHOT
Essentials: v2.0.1-b488

**Comment by ghost** [comment] 2017-09-30 03:45
I also have this problem too.

**Comment by mdcfe** [comment] 2018-01-22 11:24
Do you have the permission `essentials.spawnerconvert.*`?

**Comment by midnjerry** [comment] 2018-01-22 15:55
Confirmed.  You need to add `essentials.spawnerconvert.*`  This permission is very annoying.

**Comment by midnjerry** [comment] 2018-01-22 16:07
Sorry I take that back.  I reread the issue and went back and tried to replicate.  I ran the command:
/give mob_spawner 1 0 {BlockEntityTag:{EntityId:Creeper}}
It said "Error: Player not found".

I ran /give NoobDad mob_spawner 1 0 {BlockEntityTag:{EntityId:Creeper}}
If gave me an empty spawner.  PLacing it made it a pig spawner.

No warning,though
Version: git-Spigot-549c1fa-45c8386  1.12.2-R0.1-SNAPSHOT
ESS: Essentials: v2.0.1-b488

But I still find that permission annoying! :P

**Comment by mdcfe** [comment] 2018-01-22 16:20
Could you run `/ess debug` then post the console output when placing a spawner?

**Comment by midnjerry** [comment] 2018-01-22 16:55
Sorry I can't reproduce it anymore.

I tried removing essentials.spawnerconvert.* but I can still place spawners in normal and as OP.  I'm going to restart my server.

**Comment by midnjerry** [comment] 2018-01-22 17:22
Okay sorry for the delay. I couldn't reproduce it with my servers...  I think it was something to do with PEX.  So I used a brand new server:

Version: git-Spigot-549c1fa-45c8386 1.12.2-R0.1-SNAPSHOT
ESS: Essentials: v2.0.1-b488
PEX: 1.23.4 - fresh install no perms set
I'm executing this as OP

[09:20:50 INFO]: NoobDad issued server command: /give NoobDad mob_spawner 1 0 {BlockEntityTag:{EntityId:Creeper}}
[09:20:50 INFO]: [Essentials] checking if NoobDad has essentials.mail - true
[09:20:50 INFO]: [Essentials] checking if NoobDad has essentials.give - true
[09:20:50 INFO]: [Essentials] checking if NoobDad can afford charge.
[09:20:50 INFO]: [Essentials] calculated command (give) cost for NoobDad as 0
[09:20:50 INFO]: [Essentials] checking if NoobDad has essentials.itemspawn.exempt - true
[09:20:50 INFO]: [Essentials] checking if NoobDad has essentials.vanish.interact - true
[09:20:50 INFO]: [Essentials] checking if NoobDad has essentials.itemspawn.meta-vanilla - true
[09:20:50 INFO]: [Essentials] checking if NoobDad has essentials.oversizedstacks - true
[09:20:50 INFO]: [Essentials] attempting to charge user NoobDad
[09:20:50 INFO]: [Essentials] calculated command (give) cost for NoobDad as 0
[09:20:50 INFO]: [Essentials] charge user NoobDad completed
[09:20:51 WARN]: Skipping BlockEntity with id
[09:20:51 INFO]: [Essentials] checking if NoobDad has essentials.spawnerconvert.pig - true

**Comment by midnjerry** [comment] 2018-01-22 17:47
Okay I did a little bit more research.  I don't think this is a bug with 1.12.  

**** In  Single Player Minecraft  1.12 ****
I ran command: /give NoobDad mob_spawner 1 0 {BlockEntityTag:{EntityId:Creeper}}
I also used a command block: /give @p  mob_spawner 1 0 {BlockEntityTag:{EntityId:Creeper}}

Both times I got a "Monster Spawner" and when placed it was a PigSpawner

I tried this using Spigot BUT NO ESSENTIALS
I ran command: /give NoobDad mob_spawner 1 0 {BlockEntityTag:{EntityId:Creeper}}

I got a "Monster Spawner" and when placed it was a PigSpawner

This looks like expected Minecraft 1.12 vanilla behavior and it can be reproduced without installing the Essentials plugin.  Therefore this is not an Essentials bug and this issue can be closed.

**Comment by mdcfe** [comment] 2018-01-22 17:48
EssentialsX's `essentials.spawnerconvert.*` permission is a feature that is supposed to combat the bug - if those permissions don't work, then there is an issue. Otherwise, I agree that there isn't a problem here.

**Comment by bjorno43** [comment] 2018-05-13 17:10
The issue can't be closed. The correct command to place a mob spawner that doesn't revert to a pig spawner is:

/give @p mob_spawner 1 0 { BlockEntityTag: { SpawnData: { id:xp_orb }, SpawnCount:1, SpawnRange:1, RequiredPlayerRange:4, Delay:1, MinSpawnDelay:1, MaxSpawnDelay:3, MaxNearbyEntities:3, SpawnPotentials: [{ Entity: { id: "minecraft:xp_orb", Value: 10s }, Weight:"1" }] }, display: { Name:"XP Spawner" } }

The above command will give an XP Orb spawner that gives xp to any player close enough. It works perfectly fine in vanilla minecraft 1.12.2, but still reverts to a pig spawner with EssentialsX installed. Even after applying `essentials.spawnerconvert.*` and giving yourself OP rights just to be sure.

**Comment by NoopyyGaming** [comment] 2018-09-05 15:15
I'm still having this issue too, but with SilkSpawners, it has nothing to do with EssentialsX i think.

**Comment by mdcfe** [comment] 2018-09-05 18:09
@bjorno43 EssentialsX's spawner conversion doesn't take place unless a player has `essentials.spawnerconvert.<ENTITY>`. If spawners don't work correctly when you don't have that permission, it is not EssentialsX's problem. Try revoking the permission (in LuckPerms, add `essentials.spawnerconvert.*` and set it to `false`).

**Comment by pop4959** [comment] 2020-04-30 04:05
I've seen the error mentioned in the original post, however there is no indication that it comes from Essentials. It seems to be a generic server message. Most likely nothing to be very concerned about. I will close this issue for now, unless someone provides evidence that this is indeed an Essentials issue.

**Closed as completed by pop4959** 2020-04-30 04:05 UTC
Labels: help wanted, type: problem
