### ISSUE TITLE
Could not pass event EntityChangeBlockEvent

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#2585] opened 2019-06-05 22:49 UTC
### Information

**Full output of `/ess version`**:

```
Server version: 1.14.2-R0.1-SNAPSHOT git-Spigot-093165d-ba575a5 (MC: 1.14.2)
[01:46:26] [Server thread/INFO]: EssentialsX version: 2.16.1.167
[01:46:26] [Server thread/INFO]: PermissionsEx version: 1.23.4
[01:46:26] [Server thread/INFO]: Vault version: 1.7.2-b107
[01:46:26] [Server thread/INFO]: EssentialsXSpawn version: 2.16.1.167
[01:46:26] [Server thread/INFO]: EssentialsXChat version: 2.16.1.167
[01:46:26] [Server thread/INFO]: You are running unsupported plugins!
[01:46:26] [Server thread/INFO]: You are running an unsupported server version!
```

**Server log**: 

**EssentialsX config**: 

### Details

**Description**  
`[00:23:24] [Server thread/ERROR]: Could not pass event EntityChangeBlockEvent to Essentials v2.16.1.167
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEntityChangeBlockEvent(CraftEventFactory.java:1028) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.PathfinderGoalEatTile.e(PathfinderGoalEatTile.java:73) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.PathfinderGoalWrapped.e(SourceFile:55) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at net.minecraft.server.v1_14_R1.PathfinderGoalSelector.doTick(SourceFile:80) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.EntityInsentient.doTick(EntityInsentient.java:648) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.EntityLiving.movementTick(EntityLiving.java:2456) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.EntityInsentient.movementTick(EntityInsentient.java:501) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.EntityAgeable.movementTick(EntityAgeable.java:154) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.EntityAnimal.movementTick(EntityAnimal.java:29) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.EntitySheep.movementTick(EntitySheep.java:86) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2292) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.EntityInsentient.tick(EntityInsentient.java:272) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:570) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.World.a(World.java:745) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:346) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1057) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: java.lang.ClassCastException: class org.bukkit.material.MaterialData cannot be cast to class org.bukkit.material.Sign (org.bukkit.material.MaterialData and org.bukkit.material.Sign are in unnamed module of loader 'app')
        at com.earth2me.essentials.signs.EssentialsSign.checkIfBlockBreaksSigns(EssentialsSign.java:217) ~[?:?]
        at com.earth2me.essentials.signs.SignEntityListener.onSignEntityChangeBlock(SignEntityListener.java:52) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor29.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        ... 33 more`

**Steps to reproduce**  
1. Put a sign on the wall.
2. Put another sign in front.
3. Break the sign from front.

**Expected behavior**  
-

**Screenshots**  
-

**Comment by mdcfe** [comment] 2019-06-06 08:46
Duplicate of #2529.

**Closed as completed by mdcfe** 2019-06-06 08:46 UTC
