### ISSUE TITLE
Command /potion not working

### ISSUE THREAD

**Issue by Blamo27** [EssentialsX/Essentials#1533] opened 2017-09-02 01:10 UTC
EssentialsX version (`/essentials`):  2.0.1-b528

Server software (`/version`): 1.12-R0.1 (Paper-1196)

EssentialsX config (if applicable): x

Hello,

There is an issue with the /potion command. It doesn't seem to work with splash or lingering potions, it only works with normal potions (the command doesn't recognize that you are holding a potion if you are holding a splash or lingering one).

Thank you for looking into this.

**Comment by mdcfe** [comment] 2017-09-05 08:35
Duplicate of #1166.

**Closed as completed by mdcfe** 2017-09-05 08:35 UTC
