### ISSUE TITLE
Kits cannot save item attributes

### ISSUE THREAD

**Issue by MithrandirCraft** [EssentialsX/Essentials#916] opened 2016-10-04 14:42 UTC
Just as the title says. Essentials kit saving cannot manage item attributes. Please add support for the new 1.10.2 attributes.

I think specifying a version here is unnecesary. EssentialsX simply doesn't manage this, therefore saving items directly from inventory is innefective if these items have attributes.

**Comment by MithrandirCraft** [comment] 2016-11-11 20:05
plox.

**Comment by Kakifrucht** [comment] 2016-11-11 23:10
There are already 2 other tickets about the same thing, how about closing this one instead of bumping every single thread?

**Comment by MithrandirCraft** [comment] 2016-11-12 12:13
Yeah, I'm just trying to point out this issue. But that's obvious. Do as you wish.

**Comment by mdcfe** [comment] 2016-11-12 12:51
I'm fairly certain there's a lot of work to do before it's even worth adding support for attributes - including reworking the config system, which has been suggested numerous times.

**Comment by MithrandirCraft** [comment] 2016-11-12 13:02
A lot of work before it's even worth... It's 1.10.2, and attributes have been around since 1.6, but still no support for them allthough they are now a basic item component.

I don't know what Essentials's priorities are, so I won't judge. I'll just say I personally feel absolutely confortable with the current config format. So if remaking the config is prioritary, maybe Attributes could be added along the way.

**Comment by mdcfe** [comment] 2018-01-17 20:26
Closing as this is a duplicate of #838.

**Closed as completed by mdcfe** 2018-01-17 20:26 UTC
