### ISSUE TITLE
/back caused the server to stall for 20 seconds and then crash

### ISSUE THREAD

**Issue by mart-r** [EssentialsX/Essentials#2382] opened 2019-01-17 08:03 UTC
### Information

**Full output of `/ess version`**:

```
This server is running Essentials 2.16.0.3
```

**Server log**: https://gist.github.com/mart-r/080d3091f857e3d3bdc6b464427071a8

**EssentialsX config**: I'm not sure it's relevant, but here: https://gist.github.com/mart-r/80095f0c20293b7267612fb007fc4d6d

### Details

**Description**  
It's only happened once so far, but all the teleportation commands have been causing hick-ups more often (nothing near 20 seconds before, however)

**Steps to reproduce**  
Only happened once as far as I'm aware so not sure.

**Expected behavior**  
I'd expect the server not to crash when someone does `/back`

**Screenshots**  
I've only got the logs

**Comment by kennyrkun** [comment] 2019-01-17 22:33
This isn't exactly relevant to your issue, but you should [update to the latest version](https://ci.ender.zone/job/EssentialsX/) if you can. I believe the version you're using does have a few issues which have been fixed in the latest release.

**Comment by MasterDash5** [comment] 2019-01-19 22:45
This happens to me every 5 times I teleport. Its annoying and seriously an issue.

**Comment by darbyjack** [comment] 2019-01-23 17:01
No one else has this issue and has not been able to be recreated.

**Comment by MasterDash5** [comment] 2019-01-25 01:41
I can recreate it every 20 seconds. Want me to?

**Comment by darbyjack** [comment] 2019-01-25 01:43
I mean go ahead, but you're the only server out of 22,000 that has experience this issue.

**Comment by MasterDash5** [comment] 2019-01-25 02:46
Took me 23 tries. Yes I counted.

https://youtu.be/Offxj263etc

**Comment by darbyjack** [comment] 2019-01-25 02:49
Going to assume that it's another plugin doing this. Have you tried recreating it with ONLY essentials on the server?

**Comment by MasterDash5** [comment] 2019-01-25 02:50
Yes, I have. Couldn't record it with none on though. I'm working on homework right now.

**Comment by darbyjack** [comment] 2019-01-25 02:52
Alrighty well I can look into it but there's not really much to be done. I've looked through the original error and there's not really anything out of the ordinary. Like I said before, we have over 22,000 servers running the plugin right now and you are the only one that has reported this issue.

**Comment by MasterDash5** [comment] 2019-01-25 02:53
Understandable. Let me know if anything changes

**Comment by mart-r** [comment] 2019-01-25 07:49
> Alrighty well I can look into it but there's not really much to be done. I've looked through the original error and there's not really anything out of the ordinary. Like I said before, we have over 22,000 servers running the plugin right now and you are the only one that has reported this issue.

MasterDash5 is not the only one to have the issue. In fact, he wasn't the one that reported it, I was.
With that said, I've only had a single instance of the issue. I just posted the report to make sure it's documented, more than anything else.

I do believe this could have something to do with Multiverse as it's been acting up when TP'ing between worlds ever since 1.13.

**Comment by MasterDash5** [comment] 2019-02-23 00:25
> MasterDash5 is not the only one to have the issue. In fact, he wasn't the one that reported it, I was.
> With that said, I've only had a single instance of the issue. I just posted the report to make sure it's documented, more than anything else.
> 
> I do believe this could have something to do with Multiverse as it's been acting up when TP'ing between worlds ever since 1.13.

I've tested this with EssentialsX by itself. Crash still occurs. I wouldn't think its caused by multiverse.

**Comment by mdcfe** [comment] 2019-02-23 13:17
@mart-r @MasterDash5 Could you try the [latest EssentialsX build](https://ci.ender.zone/job/EssentialsX) on the [latest version of Paper](https://papermc.io/downloads)? We've recently optimised teleportation on EssentialsX when using Paper.

Also, @MasterDash5 could you get the output of `/ess version`? It looks like you might have mistyped the command than first time round.

**Comment by pop4959** [comment] 2019-10-27 04:11
Looking at the server log, it appears that the crash is not directly caused by Essentials. You can see that the plugin is not at the top of the stack trace, which means that the server is locking up elsewhere.

For example, the top line for the topmost error is this:
```
[06:40:28] [Paper Watchdog Thread/ERROR]: 	Stack:
[06:40:28] [Paper Watchdog Thread/ERROR]: 		net.minecraft.server.v1_13_R2.IWorldReader.lambda$a$1(IWorldReader.java:135)
```

My best guess is that perhaps there is a problem with your world. Perhaps it is corrupt, or perhaps some other obscure issue within Minecraft. It probably happens using any plugin (or maybe even without a plugin, when travelling to that location).

In any case, we really can't even begin to do anything about it unless you can confirm that it is an issue with Essentials and we're able to reproduce it on our end. Feel free to open a new issue if it is still a problem for you, and you all of the information required for us to be able to fix it.

**Closed as completed by pop4959** 2019-10-27 04:11 UTC
Labels: status: not enough info, bug: unconfirmed
