### ISSUE TITLE
Duplicating the items in /invsee [player] armor

### ISSUE THREAD

**Issue by Elric02** [EssentialsX/Essentials#3884] opened 2020-12-29 13:59 UTC
### Information

**Full output of `/ess version`:**
Version Server : 1.16.4-R0.1-SNAPSHOT git-Paper-282 (MC: 1.16.4)
Version EssentialsX : 2.18.2.0
Version PlaceholderAPI : 2.10.9
Version LuckPerms : 5.2.35
Version Vault : 1.7.3-b131
Version Citizens : 2.0.27-SNAPSHOT (build 2183)
Version ChestShop : 3.11 (build 213)
Version EssentialsXChat : 2.18.2.0
Version EssentialsXSpawn : 2.18.2.0
```

```

**Server startup log:**
https://gist.github.com/Elric02/7bf747f98eef3ce61a8e4d8315dbad4d

**EssentialsX config:**
https://gist.github.com/Elric02/033e5de3a2b699fcdaf59fe6a6d3ff99

### Details

**Description:**  
I can't duplicate (using middle mouse click) the content of the /invsee [player] armor GUI. I know that's a read-only GUI (sadly) but someone on Discord told me that I should still be able to duplicate its content.
I'm OP, I have all permissions and I'm in creative mode.

**Comment by JRoy** [comment] 2020-12-29 14:14
Duplicate of #3065

Pretty much an issue in Spigot, nothing we can do about it. In the meantime don't give invsee to people you do not trust.

**Comment by JRoy** [comment] 2021-01-02 16:40
Noticed that this was a feature request, added in #3893

**Closed as completed** 2021-01-02 20:36 UTC
Labels: type: enhancement
