### ISSUE TITLE
Player Interact Event ERROR (1.12.1) Likely a Repost of the issue Below

### ISSUE THREAD

**Issue by MatheweB** [EssentialsX/Essentials#1434] opened 2017-08-03 15:47 UTC
LOG:
https://hastebin.com/ciwunebici.vbs

EssentialsX version (v2.0.1-b501)

Server software (Spigot 1.12.1)

EssentialsX config (N/A)

**Comment by mdcfe** [comment] 2017-08-03 18:43
Duplicate of #1433.

**Closed as completed by mdcfe** 2017-08-03 18:43 UTC
Labels: status: duplicate
