### ISSUE TITLE
[request] /nicklist

### ISSUE THREAD

**Issue by TomLewis** [EssentialsX/Essentials#2188] opened 2018-09-18 20:44 UTC
When you have a lot of players, you loose track of who is nicked and who isn't, if there offline or live in different timezones, or you have multiple staff that nick players, there isn't a way to list everyone that currently has a nickname, being able to list everyone that is currently nick'ed would be very helpful, also being able to reset everyone on the server at once, would also be fantastic, maybe /resetallnicks, or /clearallnicks.

**Comment by mdcfe** [comment] 2018-10-09 17:53
It's unlikely that this will be added to EssentialsX itself, as it would involve loading every single userdata file and checking whether it has a nick, which is not good performance-wise.

**Comment by Magnum97** [comment] 2018-10-10 04:37
Related but slightly different question- /realname tell you ign of a nickname if player is online. /whois will show you the nick of an ign if they are online. Is it possible to have these translate names while player is offline?

**Comment by TomLewis** [comment] 2018-10-10 08:54
@md678685 cache file? When /nick toggled the user is added/removed from the nick json/yml file, and then there's as separate command to scan for all existing nicks? that you would only do if the cache file got removed or you need to re-populate it?

**Comment by mdcfe** [comment] 2018-10-10 10:29
@Magnum97 That's definitely possible - I'd suggest opening a separate issue so we can track it separately.

---

@FrozenBeard Storing them in a separate file means we're simply creating a duplicate of all the data that serves no other purpose.

This feature can be easily achieved in a separate plugin, and I don't see that this serves a purpose for the vast majority of users.

**Closed as completed by mdcfe** 2018-10-10 10:29 UTC
Labels: type: enhancement

**Comment by TomLewis** [comment] 2018-10-10 11:31
So there is no way for me to find out which of the 110000 users I have nicknamed?

**Comment by mdcfe** [comment] 2018-10-10 16:39
There isn't an EssentialsX command to do that. It can be done through other means, such as through another plugin or a shell script.
