### ISSUE TITLE
Vanish? Tab? Can not see online players. (Fixed)

### ISSUE THREAD

**Issue by Linebeck** [EssentialsX/Essentials#1071] opened 2017-01-14 18:11 UTC
Ok, I have been using the latest version as of 1/14/2017 (463). So I have done some troubleshooting and discovered that EssentialsX is causing issues with seeing players online. Whether they are normal players without the /vanish permission or a admin with /vanish, the problem still occurs. Now I am using the latest version of paperspigot, so I don't know if that may have something to do with the issue. So basically, what happens is that it'll show the player online, however once I get a distance away from him. They appear to be offline as if they never existed. When I do /list, they're not there either. It constantly does this, sometimes they're online and sometimes they are not. I can assure you that when this happens they are in view. I could type /tpa [name] and it show them as being online without actually being online through tab or /list. I don't get any errors through console, so I don't know what other information you need. If you need anymore info, ask. Thanks!

**Comment by mdcfe** [comment] 2017-01-14 21:22
Could you post a list of plugins you have installed?

**Comment by Linebeck** [comment] 2017-01-14 22:15
Okay, after some more digging I figured out the problem. My anti cheat doesn't like essentials. lol I am using a custom anti cheat, and it is the reason tab is acting up etc. Thanks anyways!

**Comment by mdcfe** [comment] 2017-01-15 16:20
If the issue is resolved, feel free to close the issue.

**Closed as completed** 2017-01-16 06:10 UTC

**Comment by ScuroK** [comment] 2017-02-12 18:24
@md678685 just tested again on latest versioins (spigot 1.11.2).
Sometimes i join the server vanished and players can see me in the tablist! they confirmed.
