### ISSUE TITLE
[1.15.1] The /createkit command ignores the &f formatting tag

### ISSUE THREAD

**Issue by Nevrai** [EssentialsX/Essentials#2967] opened 2020-01-22 20:23 UTC
### Information

Full output of `/ess version`:

```
Server version: 1.15.1-R0.1-SNAPSHOT git-Paper-62 (MC: 1.15.1)
EssentialsX version: 2.17.1.52
LuckPerms version: 5.0.39
Vault version: 1.7.2-b107
EssentialsXChat version: 2.17.1.52
```

**Server log:** https://gist.github.com/DeleteMetaInf/d9664ae84cbc6b2a065cc4efd620b14c

**EssentialsX config** https://gist.github.com/DeleteMetaInf/40ce76faf4d96d481220931218ee368b

### Details

**Description**
Essentials’ /createkit command ignores the colour tag `&f` (white).
If you give yourself an item named `&fTest` and then create a kit, it creates a kit with an item named `Test` instead. This causes the text to be italic rather than non-italic.

In kits.yml, `&f` is nowhere to be found, but if it’s added manually, it works as expected. However, the /kitcreate command shouldn’t ignore `&f`.

**Steps to reproduce**
1. Give yourself an item named `&fTest`.
2. Use /createkit testkit 1.
3. Use /kit testkit. Notice that the name is italic.

If you then look in kits.yml, you’ll see that `&f` is nowhere to be found.

**Expected behavior**
`&f` should be included with the item’s NBT data in the kit. While white _is_ the default text colour, not including `&f` causes text to be italic, and if it’s an enchanted item, it also causes the colour of the item to be light blue rather than white since that’s the default name colour for enchanted items.

**Screenshots**
##### Item I gave myself
![1](https://user-images.githubusercontent.com/59761487/72930893-3180d100-3d5d-11ea-82a0-e8a2005c4473.png)

##### The same item added to my inventory using the /kit command
![2](https://user-images.githubusercontent.com/59761487/72930894-32b1fe00-3d5d-11ea-8cba-4c5ce1f3dcc3.png)

**Comment by Nevrai** [comment] 2020-01-27 06:02
I don’t see how this is an enhancement. I’d call it a bug.

**Comment by pop4959** [comment] 2020-01-27 09:39
You're correct, it appears to be a bug. Although, it seems like this is not a bug within Essentials, but CraftBukkit instead.

Consider the following line in AbstractItemDb which handles the serialisation of ItemStacks:
https://github.com/EssentialsX/Essentials/blob/e230cee91e5727c1866cbbca21ee4318b171894b/Essentials/src/com/earth2me/essentials/items/AbstractItemDb.java#L159

Noteworthy is that the white color is not directly being stripped out here, but the method `ItemMeta::getDisplayName` is called.

Please see the [implementation of `ItemMeta::getDisplayName`](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/inventory/CraftMetaItem.java#756-759) provided by CraftBukkit's CraftMetaItem class, which utilises `CraftChatMessage::fromComponent(IChatBaseComponent, EnumChatFormat)`. The problem is caused by the fact that this method is called with `EnumChatFormat.WHITE` and thus [this line of code](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/util/CraftChatMessage.java#195) ultimately ends up removing the white color. This is perfectly fine for actual chat messages, but not really for items as we can clearly see here.

It's not likely that this will be fixed anytime soon, so for the time being an appropriate workaround may be to use `&r` (reset) instead of `&f` (white) since that does not appear to get removed.

**Comment by pop4959** [comment] 2020-03-05 05:02
Closing as an upstream bug.

**Closed as completed by pop4959** 2020-03-05 05:02 UTC
Labels: bug: upstream
