### ISSUE TITLE
Playerhomes get deleted

### ISSUE THREAD

**Issue by Stoermy** [EssentialsX/Essentials#4780] opened 2022-01-26 10:52 UTC
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

ERROR

### Bug description

Essentials delete all Playerhomes after Server Restarts or randomly.... 

idk how to fix this but the Problem is kinda annoying.

Ess version https://prnt.sc/26jjyf8

### Steps to reproduce

No steps

### Expected behaviour

Homes shouldnt deleted

### Actual behaviour

Playerhomes get randomly deleted

**Comment by tatteaid** [comment] 2022-01-30 05:31
Have you tried a stable EssentialsX build? No dump, no errors, no steps to reproduce, nothing. It's impossible to even have the slightest clue as to what is going on. Maybe it's something on your end (a plugin). It would be helpful if you could provide some more information.

**Comment by Stoermy** [comment] 2022-01-30 13:21
> Have you tried a stable EssentialsX build? No dump, no errors, no steps to reproduce, nothing. It's impossible to even have the slightest clue as to what is going on. Maybe it's something on your end (a plugin). It would be helpful if you could provide some more information.

Maybe i found a solution. I had a outdated Plugin and outdatet Essentials on my Server, after Update Essentials, the Bug was always there... but after deleting the other outdated Plugin, Essentials Homes and the other Functions works fine.

**Comment by JRoy** [comment] 2022-01-30 13:44
Closing since this is an issue with a third party plugin

**Closed as completed by JRoy** 2022-01-30 13:44 UTC
Labels: bug: unconfirmed
