### ISSUE TITLE
/create kit Armor & Shield

### ISSUE THREAD

**Issue by HunterJacobs** [EssentialsX/Essentials#471] opened 2016-03-07 20:17 UTC
Something I have always wanted in essentials is to have the ability to allow the armor to spawn on the player when the /kit command is executed. Also, there is no way to keep shield textures in kits. Shields would also be nice to have spawn in the secondary spot.

**Comment by NoobPlayer03** [comment] 2016-03-09 20:13
This would be amazing!

**Comment by HunterJacobs** [comment] 2016-03-11 05:30
It would be very nice!

**Comment by mdcfe** [comment] 2017-12-16 16:46
Closing, as this is a duplicate of #347.

**Closed as completed by mdcfe** 2017-12-16 16:46 UTC
Labels: type: enhancement
