### ISSUE TITLE
Players able to tell if another is in vanish

### ISSUE THREAD

**Issue by 10becja** [EssentialsX/Essentials#852] opened 2016-08-28 02:51 UTC
Players are able to bypass vanish and tell if a vanished player is online by using commands that attempt to autocomplete a user name. Tested in builds 421 and 424

Steps to reproduce
1. Log in as a player with vanish permissions, and vanish
2. Log in as a player without permissions.
3. As the unvanished player, run the command /bal (first few letters of vanished players name). For example, if the vanished player's name is notch, run "/bal not"

Expected results:
The command should return "Error: Player not found."

Actual results:
The command returns the vanished players balance.

**Comment by mdcfe** [comment] 2018-03-10 15:58
Could anyone confirm if this still happens with recent versions that include the tab completion framework?

**Comment by pop4959** [comment] 2019-12-29 10:22
Unable to reproduce the issue myself, so this should be fixed. Seems like no one else has had this issue for a while either. If someone finds a new vanish / tab completion problem like this, please create a new issue for it.

**Closed as completed by pop4959** 2019-12-29 10:22 UTC
Labels: help wanted, bug: unconfirmed
