### ISSUE TITLE
EssentialsX sign shop not working

### ISSUE THREAD

**Issue by 19celtic71** [EssentialsX/Essentials#955] opened 2016-11-02 01:27 UTC
I have installed EssentialsX and my sign shop will allow me to build the sign but won't display any text nor will it allow me to use it. Any ideas?

**Comment by saturnux** [comment] 2016-11-03 11:01
have you enable the functionality in the list ?

**Comment by Trickster489** [comment] 2016-11-03 11:33
Paste configuration file, sounds like sign functionality is disabled.

**Comment by 19celtic71** [comment] 2016-11-05 08:16
Essentials

[http://pastebin.com/UeXBAz0H]

**Comment by mdcfe** [comment] 2016-11-05 08:32
~~To use code blocks on GitHub, wrap them with three backticks (`)~~

~~It's much easier to use a paste site like Gists though.~~

**Comment by mdcfe** [comment] 2016-11-05 08:40
Could you paste the output of `/ess debug`?

**Comment by saturnux** [comment] 2016-11-05 10:06
in fact if your sign is bad, the sell or buy is in red.
if nothing appear in sign it's probably another plugin in cause.

i think...

**Comment by 19celtic71** [comment] 2016-11-05 14:21
Here is my plugin list.

http://prntscr.com/d3einy

**Comment by SupaHam** [comment] 2016-12-02 17:07
I'm going to mark this as a duplicate of #687. Where you have needed to update your Spigot server software to fix the bug. However there's a chance you have already done this since 1.11 has been out. If I am mistaken please reply with your startup log.

Steps:

1. Open `logs` directory in server directory.
1. Find and open a file called `latest.log`.
1. Go to [www.pastebin.com](http://pastebin.com).
1. Copy all `latest.log` contents and paste into the big text area.
1. Copy & paste the URL in your browser into a reply here.

**Closed as completed by SupaHam** 2016-12-02 17:07 UTC
Labels: status: duplicate
