### ISSUE TITLE
Books in kits

### ISSUE THREAD

**Issue by ToXiCHaZe541** [EssentialsX/Essentials#397] opened 2016-01-27 11:01 UTC
When you write a book in-game and make it spaced and organized to make it easy to read and clean and decide you want to put it in a kit and do by using /createkit that said book decides to remove all of that spacing and puts everything together into one big mess. Everything is still readable but it completely ignores the spacing between lines and makes it harder to read and not look very nice.

**Comment by drtshock** [comment] 2016-02-04 17:31
Yes, /createkit doesn't have support for written books yet.

**Comment by chillerkraft** [comment] 2017-06-01 19:30
BUMP :)

**Comment by pop4959** [comment] 2020-04-01 03:12
Closing as duplicate of #31

**Closed as completed by pop4959** 2020-04-01 03:12 UTC
Labels: status: duplicate, type: enhancement
