### ISSUE TITLE
"writtenbook" does not work in kits

### ISSUE THREAD

**Issue by girlinterred** [EssentialsX/Essentials#2651] opened 2019-07-03 21:16 UTC
### Information

**Full output of `/ess version`**: 

```
Server version: 1.14.3-R0.1-SNAPSHOT git-Spigot-d05d3c1-604c8bf (MC: 1.14.3)
EssentialsX version: 2.17.0.0
LuckPerms version: 4.4.26
Vault version: 1.7.2-b107
EssentialsXGeoIP version: 2.17.0.0
EssentialsXChat version: 2.17.0.0
EssentialsXSpawn version: 2.17.0.0
```

**Server log**: https://gist.github.com/BluDragyn/e67dbc27ed40071610c6b3d5e2516e15

**EssentialsX config**: https://gist.github.com/BluDragyn/2845d11e58549670c929029f9076d68a

### Details

**Description**  
Using `writtenbook` in a kit gives a plain book instead of a written book. Using `written_book` works as expected (gives the written book)

**Steps to reproduce**  
1) Add a written book to a kit using `writtenbook` instead of `written_book`
2) Give the kit
3) ???
4) Profit

**Expected behavior**  
For `writtenbook` to work like other shortcuts (`lboots`, `gshovel`, etc.)

**Comment by triagonal** [comment] 2019-07-05 02:55
I'm not able to reproduce this on the following version:
```
[12:54:29 INFO]: CONSOLE issued server command: /ess version
[12:54:29 INFO]: Server version: 1.14.3-R0.1-SNAPSHOT git-Paper-124 (MC: 1.14.3)
[12:54:29 INFO]: EssentialsX version: 2.17.0.3
```
and with example kit:
```yaml
kits:
  testkit:
    delay: 0
    items:
    - writtenbook 1
```

Try deleting your `items.json` file and letting Essentials generate a new copy.

**Comment by girlinterred** [comment] 2019-07-05 19:44
My kits.yml:
```
kits:
  newb:
    delay: -1
    items:
    - woodsword 1
    - woodshovel 1
    - woodpickaxe 1
    - woodaxe 1
    - lhelm 1
    - lchestplate 1
    - lboots 1
    - lpants 1
    - apple 32
    - gshovel 1 name:Land_Claim_Tool lore:Stake_your_claim_in_the_wilderness
    - stick 1 name:Claim_information lore:Use_this_tool_to_get_information_about_a_claim
    - written_book 1 title:How_to_Claim_Land author:vertigh0st lore:How_to_stake_your_claim_in_the_Gates_of_Iceloch book:How_to_Claim_Land
```

My book is defined so: 
```
#How_to_Claim_Land
&0   &nHow to Claim Land&r
Click: &9bit.ly/gpusage&r
&0 
&lStake your claim in the &1Gates of Iceloch!&r
&0 
Use the &ngolden shovel&r
to create/resize a claim
&0 
&0 
&0    &nUseful Commands:&r
/Trust /UnTrust
/TrustList
/ClaimsList
/AbandonClaim
&0 
/Claim /ExtendClaim
/IgnorePlayer
&0 
/SubdivideClaims
/AccessTrust
/ContainerTrust
```

Perhaps it won't reproduce because you're not defining any metadata for the book in your kit?

**Comment by triagonal** [comment] 2019-07-22 06:03
Sorry for the delay, but it seems like I still cannot reproduce the issue even with added book meta. Have you tried deleting `items.json` and letting Essentials generate a new copy?

**Comment by girlinterred** [comment] 2019-07-22 08:21
Yup. Even after deleting it, the issue persisted.

**Comment by pop4959** [comment] 2019-10-27 03:07
This sounds like a definite items.json issue. If you haven't, make sure you fully restarted your server after deleting the file. If writtenbook is not in the file, update EssentialsX.

Since this can't be replicated, I will close the issue now.

**Closed as completed by pop4959** 2019-10-27 03:07 UTC
Labels: help wanted, bug: unconfirmed
