### ISSUE TITLE
[1.15.1] Text in book and quills are not saved in kits

### ISSUE THREAD

**Issue by Nevrai** [EssentialsX/Essentials#2945] opened 2020-01-14 18:15 UTC
### Information

**Full output of `/ess version`**:

```
Server version: 1.15.1-R0.1-SNAPSHOT git-Paper-48 (MC: 1.15.1)
EssentialsX version: 2.17.1.52
LuckPerms version: 5.0.39
Vault version: 1.7.2-b107
EssentialsXChat version: 2.17.1.52
```

### Details

**Description**  
Text in book and quills are not saved in kits.

Other NBT data such as enchantments on weapons, tools, and armour are saved in kits, so is text in written books, but text in book and quills isn’t saved. This may be by design, or it may be a bug, but I would like for it to be saved so that I can keep a book and quill as a personal notepad to give to myself with the kit command.

**Steps to reproduce**  
1. Give yourself a book and quill.
2. Put text into it, but don’t sign the book.
3. Create a kit
4. Give yourself the kit.

**Expected behavior**  
The text in a book and quill is part of an NBT tag, so it should be saved in kits.

**Comment by mdcfe** [comment] 2020-01-14 19:46
EssentialsX does not read or save NBT, as Bukkit doesn't expose NBT directly to plugins. Instead, `/createkit` stores a specific set of data exposed by Bukkit in the [Essentials Item Meta format](https://wiki.mc-ess.net/wiki/Item_Meta). This supports spawning in written books with [content from `book.txt`](http://wiki.mc-ess.net/wiki/Help_Files#Book) but not book and quills, and EssentialsX doesn't currently edit `book.txt` or contain the code necessary to convert book contents to this format.

If someone is willing to contribute this, I'm not opposed to discussing and merging a PR to add this, but this is currently a low priority for us.

**Comment by darbyjack** [comment] 2020-04-30 17:06
Closing this because I feel this is similar enough to be a duplicate of https://github.com/EssentialsX/Essentials/issues/31, if you feel like that issue is missing anything from this, feel free to comment over there on it so we can take it into consideration if it's ever looked at.

**Closed as completed by darbyjack** 2020-04-30 17:06 UTC
Labels: type: enhancement
