### ISSUE TITLE
Afk on join?

### ISSUE THREAD

**Issue by FlippantCactus** [EssentialsX/Essentials#97] opened 2015-07-19 01:23 UTC
http://i.imgur.com/3MBNEVH.png
AFK on join apparently, bug?

**Comment by vemacs** [comment] 2015-07-19 01:25
Can't reproduce. Need way more information. What's timeout in config? 0?

**Comment by FlippantCactus** [comment] 2015-07-19 02:01
https://paste.sway.pw/ajaxumafah.vala - AFK part of config.
2.0.1 Beta 174
Spigot
Sorry for lack of information.

**Comment by vemacs** [comment] 2015-07-20 22:52
Still can't repro at all. Closing.

**Closed as completed by vemacs** 2015-07-20 22:52 UTC

**Comment by Kakifrucht** [comment] 2015-07-21 01:12
Me neither.

**Comment by SupaHam** [comment] 2016-01-02 10:20
Fixed in 0641791.
