### ISSUE TITLE
Error on tabcomplete

### ISSUE THREAD

**Issue by EvilOlaf** [EssentialsX/Essentials#257] opened 2015-11-05 15:25 UTC
The discussion about this issue started quite a while ago (see  related issues at the report below) and neither BanManager nor PermissionsEx had an answer for this. As a few times suggested maybe Essentials has a final answer for this.

https://github.com/BanManagement/BanManager/issues/444

tl;dr: If you run Spigot 1.8 with Essentials(X), BanManager and PermissionsEx and try to use tab completion of usernames on a BM command an error gets thrown where Essentials also interferes.

Thanks for reading.

**Comment by SupaHam** [comment] 2015-11-05 16:36
Could you please paste your Essentials config?

I've tried using `/ban`, `/bminfo`, `/unban` with tab completion, and they work just fine with essentials.

**Comment by EvilOlaf** [comment] 2015-11-05 16:42
http://pastebin.com/ESiPegnN

Tried to reproduce a few minutes ago and failed too. 
I could not perfectly replicate this issue earlier though.

**Comment by SupaHam** [comment] 2015-11-05 17:46
Essentials config looks solid. What about a list of plugins.

**Comment by Kakifrucht** [comment] 2015-11-05 17:53
I'm also running both Essentials and BanManager and I can't reproduce neither. Might be something very specific.

**Comment by JANEXLEBJAKOT** [comment] 2015-11-05 18:48
Have this problem. 
PluginList:
http://puu.sh/lawNp/044691b22f.png

**Comment by Kakifrucht** [comment] 2015-11-05 20:11
@JANEXLEBJAKOT we share lots of plugins. Maybe Protocollib is interfering somehow?

**Comment by mdcfe** [comment] 2017-08-20 13:29
Closing, as tab completion has been properly implemented so this should no longer be an issue.

**Closed as completed by mdcfe** 2017-08-20 13:29 UTC
