### ISSUE TITLE
Potion issue in 1.8.8

### ISSUE THREAD

**Issue by Nrc0611** [EssentialsX/Essentials#3525] opened 2020-07-21 21:11 UTC
### Information

**Full output of `/ess version`**:

```
21.07 15:05:00 [Server] INFO Server version: 1.8.8-R0.2-SNAPSHOT MedievalPvP (MC: 1.8.8)
21.07 15:05:00 [Server] INFO EssentialsX version: 2.18.0.0
21.07 15:05:00 [Server] INFO GroupManager version: Pre2.14.1.3 FINAL (Phoenix)
21.07 15:05:00 [Server] INFO PlaceholderAPI version: 2.9.1
21.07 15:05:00 [Server] INFO Vault version: 1.5.6-b49
21.07 15:05:00 [Server] INFO Citizens version: 2.0.16-SNAPSHOT (build 1267)
21.07 15:05:00 [Server] INFO EssentialsXChat version: 2.18.0.0
21.07 15:05:00 [Server] INFO EssentialsXProtect version: 2.18.0.0
21.07 15:05:00 [Server] INFO EssentialsXAntiBuild version: 2.18.0.0
21.07 15:05:00 [Server] INFO EssentialsXSpawn version: 2.18.0.0
```

**Server log**: https://gist.github.com/Nrc0611/d589120223d536a925943b4b732b99c0

**EssentialsX config**: https://gist.github.com/Nrc0611/8feb9e70d3e9df8f63010eea89087440

### Details

**Description**  
I originally discovered this when testing my kits, they no longer work because of the potions. There simply is no 1.8 potion support in the newest version of EssentialsX.

**Steps to reproduce**  
Simply type /i strengthpotion on any 1.8.8 server and it will throw the error.

**Expected behavior**  
You receive a strength potion.

**Screenshots**  
Doesn't tell you anything ingame.

**Comment by pop4959** [comment] 2020-07-21 21:18
Closing as a duplicate of https://github.com/EssentialsX/Essentials/issues/2867.

**Closed as completed by pop4959** 2020-07-21 21:18 UTC
Labels: status: invalid

**Comment by Nrc0611** [comment] 2020-07-21 21:51
Hey, I figured out the issue to this problem, it works fine if you use 1.8.8-R0.1, because in the code it says this: https://pastebin.com/s223dw82
This is in the file: Essentials/src/com/earth2me/essentials/Essentials.java

I was wondering if you guys could change the part where it says VersionUtil.v1_8_8_R01 and change it to VersionUtil.v1_8_8_R02. You would have to add in a VersionUtil for v1_8_8_R02 tho.

Or just make it so it checks if its lower than 1.9 instead of isLowerThanOrEqualTo

**Comment by pop4959** [comment] 2020-07-21 21:54
@Nrc0611 Did it work in versions prior to 2.18?

**Comment by Nrc0611** [comment] 2020-07-21 21:58
I don't know, I just switched to EssentialsX as many developers have stopped supporting Essentials. Honestly love EssentialsX fixed a lot of my teleportation issues. I simply only have errors with Spawn Eggs and Potions, due to the fact that I am on 1.8.8 R02 which should be considered under the legacy versions of spawn eggs and potions but it currently is not.

I downloaded 1.8.8 R01 to test and see if it works and it works great but my custom jar is on 1.8.8 R02, so I am hoping there is a way to switch it to check if the version is lower than 1.9 and then use the Legacy versions.

**Comment by Nrc0611** [comment] 2020-07-21 21:59
![image](https://user-images.githubusercontent.com/25806006/88111418-def16780-cb7b-11ea-969b-d7ac1ff625c4.png)
That is what I would need to be changed for it to work properly.

**Comment by pop4959** [comment] 2020-07-21 22:02
Doesn't appear to be an issue -- R2 doesn't exist in CraftBukkit/Spigot/Paper, which are the server implementations that EssentialsX supports.

Latest version of Paper for 1.8.8:
```
[15:00:17 INFO]: This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
```

**Comment by JRoy** [comment] 2020-07-21 22:04
You're running a StellarSpigot, which modified the version number to something not in the spigot ecosystem (There is no official R02). I *could* add a fix which would account for this but this is StellarSpigot messing with the version number when it shouldn't. Not really an essentials problem

**Comment by Nrc0611** [comment] 2020-07-21 22:04
Would it be possible to then just change isLowerThanOrEqualTo to just isLowerThan 1.9? I am currently using Stellar Spigot, so I can see if he will change it to R01 maybe

**Comment by Nrc0611** [comment] 2020-07-21 22:05
I did not realize stellar changed that.

**Comment by Nrc0611** [comment] 2020-07-21 22:18
![image](https://user-images.githubusercontent.com/25806006/88112763-7fe12200-cb7e-11ea-8c0f-962512fa0902.png)
Some people with stellar are gonna help me, thanks had no idea Stellar changed that.

**Comment by pop4959** [comment] 2020-07-21 22:20
Yeah, definitely a Stellar problem then. Forked server implementations should not be randomly changing the version string from the upstream project.
