### ISSUE TITLE
/condense does not condense Melon Slices into a Melon block

### ISSUE THREAD

**Issue by CathalCraft** [EssentialsX/Essentials#2438] opened 2019-02-27 04:27 UTC
### Information

PaperMC 1.13.2 b541
EssentialsX 2.16.0.46 b703

### Details

**Description**  
/condense command does not turn Melon Slices into a Melon block, and instead prints the message below:
You have no items that can be converted into blocks.

**Steps to reproduce**  
Have at least 9 Melon Slices and type /condense

**Expected behavior**  
Condense the Melon Slices into a Melon block

**Comment by Xeyame** [comment] 2019-02-27 14:57
This is not working because [Reverse crafting is also validated](https://github.com/EssentialsX/Essentials/blob/849efa9756495a34260d57ff1d81df1283e5f5e7/Essentials/src/com/earth2me/essentials/commands/Commandcondense.java#L68), and you can't craft a melon block into melon slices

**Comment by mdcfe** [comment] 2019-02-27 15:04
This is intended - as Xeyame correctly pointed out, you can't craft both ways between melon blocks and melon slices, so it isn't a valid `/condense` type.

**Comment by mdcfe** [comment] 2019-03-07 15:50
Closing as a duplicate of #1431.

**Closed as completed by mdcfe** 2019-03-07 15:50 UTC
