### ISSUE TITLE
Comma Separated Money

### ISSUE THREAD

**Issue by GiansCode** [EssentialsX/Essentials#371] opened 2016-01-14 17:57 UTC
Hello,

i was wondering if it would be possible to add comma separated money styling to all economy based/money based commands. This will make it easier for everyone to read, as well as more ascetically pleasing.

Thanks.

**Comment by SupaHam** [comment] 2016-01-14 18:19
Duplicate of #369

**Closed as completed by SupaHam** 2016-01-14 18:19 UTC

**Comment by SupaHam** [comment] 2016-01-14 18:22
This feature has been implemented in [build 251](https://ci.drtshock.net/job/EssentialsX/251).
