### ISSUE TITLE
Possible problem with teleport function

### ISSUE THREAD

**Issue by WolferAlpha** [EssentialsX/Essentials#2648] opened 2019-07-02 05:48 UTC
I have had problem when any player on the server (being affected by the teleport delay) when using any warp or even / tpa, I was told that it is not teleported, counts the time and does not teleport, the console does not show any error nor " without permission", returns to normal when I restart the server and it happens again. (EssentialsX is the only plugin that handles these commands on the server)

**Comment by mdcfe** [comment] 2019-07-02 06:52
I've also encountered this, but I have yet to figure out a reliable way to replicate it.

Could you post the output of `/ess version`? In addition, could you post your `config.yml` and `latest.log` on [Gist](https://gist.github.com/)?

**Comment by WolferAlpha** [comment] 2019-07-02 07:08
output "/ess version"
{Server version: 1.14.3-SNAPSHOT git-Spigot-4d2f30f-f1f3355 (MC: 1.14.3)
EssentialsX version: 2.17.0.0
PermissionsEx version: 1.23.4
Vault version: 1.7.2-b107
EssentialsXChat version:2.17.0.0
EssentialsXSpawn version: 2.17.0.0
You are running unsupported plugins!
You are running as unsupported server version!}

EssentialsX config: https://gist.github.com/WolferAlpha/57f5316a5382a273f81c7feaf634ee06
Latest log: https://gist.github.com/WolferAlpha/57de97b8917914fcd828a0781f8022fb

**Comment by CJOS100** [comment] 2019-07-17 23:32
Also having this issue

Server version: 1.14.3-R0.1-SNAPSHOT git-Paper-131 (MC: 1.14.3)
EssentialsX version: 2.17.0.0
LuckPerms version: 4.4.27
Vault version: 1.7.2-b107
EssentialsXGeoIP version: 2.17.0.0
EssentialsXChat version: 2.17.0.0
EssentialsXSpawn version: 2.17.0.0

Config: https://gist.github.com/CJOS100/41807a6a2ac053fa71b73fdf575fc4b4
Latest Log: https://gist.github.com/CJOS100/9273b49206bb386ccd815a85ab56ef00

**Comment by MrTrinax** [comment] 2019-08-29 02:30
Server version: 1.14.4-R0.1-SNAPSHOT git-Paper-167 (MC: 1.14.4)
EssentialsX version: 2.17.1.15
LuckPerms version: 4.4.1
PlaceholderAPI version: 2.10.3
Vault version: 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
EssentialsXSpawn version: 2.17.1.15

Config: https://hasteb.in/oqunixiq.yaml
Latest Log: https://hasteb.in/izujuwir.md

**Comment by MrTrinax** [comment] 2019-08-30 20:59
From troubleshooting the issue with a player not being able to do `/home Example1`.

The player were able to do `/home Example2` successfully, but `/home Example1` were according to EssentialsX "Successful", but nothing happend.

The issue seems to only affect certain areas/locations.

**Comment by Varijon** [comment] 2019-09-10 13:52
Also have this issue. The teleport commands function properly as soon as the delay is disabled..
Rarely, the teleport will work as intended, but extremely high rate of nothing happening.
Admins who have the delay bypass permissions can also use teleports properly with delay enabled.

EssentialsX version: 2.17.1.0
LuckPerms version: 4.4.30
Vault version: 1.7.2-b107
EssentialsXGeoIP version: 2.17.1.0
EssentialsXChat version: 2.17.1.0
EssentialsXSpawn version: 2.17.1.0
Paper build 186

The problem seemed to have started after we did:
Added Plan
Added spark
Added Tablist
Added PlaceholderAPI
Removed GroupManager after migrating to luckperms

If you need more information I'd be glad to help.

**Comment by darbyjack** [comment] 2019-09-10 14:13
So, for non-op players that have the delay, from time to time, it will just simply do the countdown and then not teleport, yet it said it did it successfully? And this is all completely random?

**Comment by Varijon** [comment] 2019-09-10 15:47
Correct, it will put the "Teleporting in 5 seconds. Teleporting to home" immediately like usual.
But then nothing will happen, if you move it also doesn't give a cancelled teleport message.
You can also use the command rapidly with nothing but the "teleporting in 5 seconds" message happening.
We have a 5 minute cooldown on teleports set as well, which isn't activated by said failed teleport either.

**Comment by darbyjack** [comment] 2019-09-10 15:56
Can you throw your config and latest log here where the issue is occurring with the homes? Thanks.

**Comment by Varijon** [comment] 2019-09-10 16:51
Sadly there's no feedback in any way, would love it if it would just spit out an error.
Config currently has teleport delay set to 0 as temporary measure.
[Config](https://gist.github.com/Varijon/9b055cd1986eca58a51e36d7bf5524f0)
[Latest log snippet](https://gist.github.com/Varijon/fd442badc0d357e2c85f2820acbc08a8)
[Ingame footage](https://gfycat.com/remorsefulgiantgermanwirehairedpointer)
Edit: Also running paper build 186.

**Comment by Varijon** [comment] 2019-09-11 02:17
Adding GroupManager back, while keeping Luckperms, seems to fix the issue.
Will need to leave the server going for longer, but this seems rather strange.
Would be interesting if others with this issue could confirm.
We also recently discovered some /r weren't actually arriving at the recipient, this also seems fixed now.

Edit: It looked fixed at first, but one user reported to have the issue again.
Didn't seem like it would make sense groupmanager would fix it I guess.

**Comment by PachiMc** [comment] 2019-09-17 16:33
same

**Comment by JRoy** [comment] 2020-05-24 19:54
Duplicate of #2287

**Comment by mdcfe** [comment] 2020-05-25 10:43
@JRoy This isn't a duplicate of #2287 - these reports have `teleport-safety: true`.

Edit: they're probably related, but not the exact same issue.

**Comment by 7Sweeny** [comment] 2020-08-13 01:10
Hi i know this post is old but i was having this issue and manager to fix it by removing TABLIST - dont know if it will be the same for everyone but if you have it try disabling, i replaced it with this plugin: https://www.spigotmc.org/resources/tab-1-8-x-1-12-x.50065/ and it's much better in my opinion.

**Comment by 7Sweeny** [comment] 2020-08-13 01:11
Hi i know this post is old but i was having this issue and manager to fix it by removing TABLIST - dont know if it will be the same for everyone but if you have it try disabling, i replaced it with this plugin: https://www.spigotmc.org/resources/tab-1-8-x-1-12-x.50065/ and it's much better in my opinion.

**Comment by JRoy** [comment] 2021-01-11 15:26
Should be fixed as of the latest dev builds. Please let me know if the issue persists.

**Closed as completed by JRoy** 2021-01-11 15:26 UTC
Labels: help wanted, bug: unconfirmed
