### ISSUE TITLE
/setspawn and /spawn crash the server on spigot 1.13

### ISSUE THREAD

**Issue by iCrazykillerGR** [EssentialsX/Essentials#2105] opened 2018-08-06 14:11 UTC
### Information

Full output of `/ess version`:

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 

### Details

Describe your issue here.

if i either press /setspawn or /spawn server crashes after 10 seconds.

**Comment by mdcfe** [comment] 2018-08-06 14:23
Duplicate of #2080 - please search issues before posting new ones.

**Closed as completed by mdcfe** 2018-08-06 14:23 UTC
