### ISSUE TITLE
AFK and /realname "fixes"

### ISSUE THREAD

**Issue by Zaphara94** [EssentialsX/Essentials#3539] opened 2020-07-25 16:28 UTC
### Feature request

**Feature description**

I suggest that, like the original Essentials, both the AFK messages and /realname ignore colour codes when displayed/used respectively. 
**How the feature is useful**

This is a very helpful feature since currently you have to type in all colour/formatting codes a player has used in their nickname in order to get their realname using the command, and when a player is AFK or returning from AFK all of the formatting codes appear in the grey text, which looks messy. (The example below isn't a good example of this, because some players choose names that are nowhere near their original name, however this still demonstrates the issue)
![image](https://user-images.githubusercontent.com/25303524/88461514-2d4f8080-ce72-11ea-8093-6f6ebf4ab1ef.png)

**Comment by JRoy** [comment] 2020-08-24 15:58
Cannot reproduce and I don't see how this would be the case by looking at the code.

Closing.

**Closed as completed by JRoy** 2020-08-24 15:58 UTC
Labels: bug: unconfirmed
