### ISSUE TITLE
Firework command not working

### ISSUE THREAD

**Issue by AmazedMender16** [EssentialsX/Essentials#1931] opened 2018-03-27 21:20 UTC
Language file: https://pastebin.com/GZYsqeP2

Essentials version: b604
Server version: CraftBukkit version git-Spigot-c3093ef-7e94e65 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Details:

When using the firework command nothing either applies to the firework. No output from the command no console errors nothing basically happens.

**Comment by Infinityy1** [comment] 2018-03-29 23:56
Can Not Reproduce | 
CraftBukkit version git-Spigot-c3093ef-7e94e65 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Essentials Version: 2.1.5 (Also tested on b614)

**Comment by mdcfe** [comment] 2018-06-15 18:54
@AmazedMender16 If this is still an issue, could you:
* Update to the latest EssentialsX version
* Reproduce on the latest version
* Run `/ess version` and paste the output

**Comment by mdcfe** [comment] 2018-12-23 19:40
Closing as I can't reproduce this (on 2.16-pre1.14).

**Closed as completed by mdcfe** 2018-12-23 19:40 UTC
Labels: help wanted, bug: unconfirmed
