### ISSUE TITLE
EssentialsXSpawn issue (I really need some help).

### ISSUE THREAD

**Issue by swooftlol** [EssentialsX/Essentials#1851] opened 2018-02-16 13:13 UTC
Okay here's the problem. When a new player joins the server, they spawn on the top of the spawn roof without the starting kit, or the "welcome" message popping up. I've been trying to find a solution for the past week but have found nothing that works. And yes, I've done /setspawn newbies several times, but they just keep spawning on the roof of the building.
My plugins (Spigot):
- Clearlag
- CombatTagPlus
- CrateReloaded
- EpicWorldGenerator
- EssentialsX (Config: https://pastebin.com/aXrrt2VQ)
- EssentialsXChat
- EssentialsXSpawn
- EssentialsXProtect
- GriefPrevention
- PermissionsEx (default rank is listed as 'default')
- KoTH
- LiteBans
- MultiverseCore
- Vault
- WE
- WG
Please, any help would be greatly appreciated! Let me know if you need me to provide anything else.

**Comment by mdcfe** [comment] 2018-02-16 14:25
In the future, please follow the given template and provide *all of the information* that the instructions ask for.

> Don't put anything inside this block, as it won't be included in the issue.
>
> If you have a question about using EssentialsX, it may be more helpful to ask
in our Discord server: https://discord.gg/F7gexAQ
>
> If you have a feature suggestion for EssentialsX, please delete the template.
>
> Otherwise, if you are reporting a bug, read on:
> 1.  Fill out the template, running the commands either in the console or 
>     as a player. Don't simply put "latest" or we will ignore it.
> 2.  When linking files, do not attach them to the post! Paste them on 
>     https://gist.github.com/, then paste a link to them in the relevant parts
>     of the template. Avoid using Hastebin or Pastebin, as files are deleted
>     after a period of time.
> 3.  If you are reporting an issue with lag, please include a timings report.
> 4.  If you are reporting an issue with messages or in-game behaviour, please
>     include screenshots detailing the problem.
> 5.  Include a description and any other details that may be helpful under the
>     Details section.

---

* What Spigot version are you using? `/version`
* What EssentialsX version are you using? `/essentials`
* What EssentialsXSpawn version are you using? `/version EssentialsXSpawn`
* Could you paste the console output when a new player joins - please use [Gist](https://gist.github.com), as Pastebin and Hastebin don't support line references.
* Are you sure that the spawn location is a safe location? Try teleporting to a player standing at the intended spawn location to see if it is.

**Comment by swooftlol** [comment] 2018-02-16 14:46
Spigot version is 1.11.2
EssentialsX version is 2.0.1
EssentialsXSpawn version is 2.0.1

I think I may have found the issue, https://gist.github.com/swooftlol/d31c4c5bbeb7704c1e01bf41adc80c3b.
That's what pops up every time I restart, though that's the latest version of the plugin I've found.
And yes, spawn location is safe as players are able to use /spawn.

**Comment by LaxWasHere** [comment] 2018-02-16 14:57
Please do not truncate version numbers...

Update your EssentialsX https://ci.ender.zone/job/EssentialsX/

**Comment by mdcfe** [comment] 2018-02-17 20:12
Closing as this is caused by running an outdated version of EssentialsX and/or EssentialsXSpawn.

**Closed as completed by mdcfe** 2018-02-17 20:12 UTC
Labels: status: not enough info
