### ISSUE TITLE
Essentials Generating error and making server Stop Responding

### ISSUE THREAD

**Issue by EthanC-8** [EssentialsX/Essentials#1976] opened 2018-04-20 22:17 UTC
### Information
Ess Version output - https://image.ibb.co/ikbTcS/Ess_Version.png

> Server Version :1.12.2-R0.1-Snapshot
> git-spigot-a630691-bea5a84
> EssentialsX Version: 2.15.0.1
> Vault Version: 1.5.6-b49
> EssentialsXSpawn versio: 2.15.0.1

Server Log file - https://gist.github.com/EthanC-8/a695e6a93d6fa867b79d615912700221
EssentialsX Config - https://gist.github.com/EthanC-8/bcd9b5ad677edbf55678c4874669180c

### Details

When the server is fully loded the Essentials Creates a Error in console and sometimes when Essential is added it overloads the server and makes it Not Respoding

### 

> [00:12:00] [Craft Scheduler Thread - 6/WARN]: [Essentials] Plugin Essentials v2.15.0.1 generated an exception while executing task 435
> java.lang.NoSuchMethodError: com.earth2me.essentials.storage.BukkitConstructor.constructScalar(Lorg/yaml/snakeyaml/nodes/ScalarNode;)Ljava/lang/Object;
> 	at com.earth2me.essentials.storage.BukkitConstructor.access$600(BukkitConstructor.java:19) ~[?:?]
> 	at com.earth2me.essentials.storage.BukkitConstructor$ConstructBukkitMapping.construct(BukkitConstructor.java:184) ~[?:?]
> 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[spigot.jar:git-Spigot-a630691-bea5a84]
> 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[spigot.jar:git-Spigot-a630691-bea5a84]
> 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:453) ~[spigot.jar:git-Spigot-a630691-bea5a84]
> 	at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:184) ~[spigot.jar:git-Spigot-a630691-bea5a84]
> 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:434) ~[spigot.jar:git-Spigot-a630691-bea5a84]
> 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:136) ~[spigot.jar:git-Spigot-a630691-bea5a84]
> 	at com.earth2me.essentials.storage.BukkitConstructor$ConstructBukkitMapping.construct(BukkitConstructor.java:214) ~[?:?]
> 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[spigot.jar:git-Spigot-a630691-bea5a84]
> 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[spigot.jar:git-Spigot-a630691-bea5a84]
> 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.newInstance(Constructor.java:283) ~[spigot.jar:git-Spigot-a630691-bea5a84]
> 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:246) ~[spigot.jar:git-Spigot-a630691-bea5a84]
> 	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149) ~[spigot.jar:git-Spigot-a630691-bea5a84]
> 	at com.earth2me.essentials.storage.BukkitConstructor$ConstructBukkitMapping.construct(BukkitConstructor.java:214) ~[?:?]
> 	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:309) ~[spigot.jar:git-Spigot-a630691-bea5a84]
> 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[spigot.jar:git-Spigot-a630691-bea5a84]
> 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[spigot.jar:git-Spigot-a630691-bea5a84]
> 	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:159) ~[spigot.jar:git-Spigot-a630691-bea5a84]
> 	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:146) ~[spigot.jar:git-Spigot-a630691-bea5a84]
> 	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[spigot.jar:git-Spigot-a630691-bea5a84]
> 	at org.yaml.snakeyaml.Yaml.load(Yaml.java:467) ~[spigot.jar:git-Spigot-a630691-bea5a84]
> 	at com.earth2me.essentials.storage.YamlStorageReader.load(YamlStorageReader.java:41) ~[?:?]
> 	at com.earth2me.essentials.storage.AbstractDelayedYamlFileReader.run(AbstractDelayedYamlFileReader.java:33) ~[?:?]
> 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot.jar:git-Spigot-a630691-bea5a84]
> 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-a630691-bea5a84]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
>

**Comment by LaxWasHere** [comment] 2018-04-21 00:16
Please rebuild your spigot.

Duplicate of #1974

**Closed as completed** 2018-04-21 06:32 UTC
