### ISSUE TITLE
BUNGEECORD/WATERFALL SUPPORT (Tpa, msg, balance and homes)

### ISSUE THREAD

**Issue by Ruymanphone** [EssentialsX/Essentials#3017] opened 2020-02-18 13:06 UTC
I have a server Waterfall, that i have a Survival server, with the main EssentialsX, EssentialsChat and EssentialsSpawn, I have to put the same plugin with the same configuration in three differents servers in the Waterfall, but the information doesn't update with the money that I use with Vault, I see now a plugin named Bessentials that try to fix these problems but the developer have some problems in the plugin when the version updates and the data compability its not very good, so, I want sync all userdata (homes and money) and tpa/msg across servers

My servers are in version 1.15.2

**Comment by triagonal** [comment] 2020-02-18 15:23
Duplicate of #912, please search for similar issues before creating new ones.

**Closed as completed by triagonal** 2020-02-18 15:23 UTC
Labels: status: duplicate
