### ISSUE TITLE
Error while executing /tp to a offline player

### ISSUE THREAD

**Issue by siBalda** [EssentialsX/Essentials#5465] opened 2023-08-05 14:58 UTC
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=04eb521a91f8437f970c959386f84ce2

### Error log (if applicable)

14:30:36] [Server thread/INFO]: Balda_ issued server command: /tp MasterMC5801 [14:30:36] [Server thread/ERROR]: [Essentials] Comando tp fallito: java.lang.AbstractMethodError: Receiver class com.earth2me.essentials.OfflinePlayerStub does not define or inherit an implementation of the resolved method 'abstract boolean isVisibleByDefault()' of interface org.bukkit.entity.Entity. 	at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.canSee(CraftPlayer.java:2035) ~[purpur-1.20.1.jar:git-Purpur-2017] 	at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.canSee(CraftPlayer.java:2030) ~[purpur-1.20.1.jar:git-Purpur-2017] 	at com.earth2me.essentials.Essentials.canInteractWith(Essentials.java:1055) ~[EssentialsX-2.20.1-dev+37-b2ae28b.jar:?] 	at com.earth2me.essentials.Essentials.matchUser(Essentials.java:996) ~[EssentialsX-2.20.1-dev+37-b2ae28b.jar:?] 	at com.earth2me.essentials.commands.EssentialsCommand.getPlayer(EssentialsCommand.java:163) ~[EssentialsX-2.20.1-dev+37-b2ae28b.jar:?] 	at com.earth2me.essentials.commands.EssentialsCommand.getPlayer(EssentialsCommand.java:154) ~[EssentialsX-2.20.1-dev+37-b2ae28b.jar:?] 	at com.earth2me.essentials.commands.Commandtp.run(Commandtp.java:29) ~[EssentialsX-2.20.1-dev+37-b2ae28b.jar:?] 	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:170) ~[EssentialsX-2.20.1-dev+37-b2ae28b.jar:?] 	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:820) ~[EssentialsX-2.20.1-dev+37-b2ae28b.jar:?] 	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:723) ~[EssentialsX-2.20.1-dev+37-b2ae28b.jar:?] 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?] 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1020) ~[purpur-1.20.1.jar:git-Purpur-2017] 	at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.20.1.jar:git-Purpur-2017] 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[purpur-1.20.1.jar:?] 	at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[?:?] 	at net.minecraft.commands.Commands.performCommand(Commands.java:316) ~[?:?] 	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2392) ~[?:?] 	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2352) ~[?:?] 	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?] 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] 	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2017] 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?] 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?] 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[purpur-1.20.1.jar:git-Purpur-2017] 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2017] 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?] 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[purpur-1.20.1.jar:git-Purpur-2017] 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[purpur-1.20.1.jar:git-Purpur-2017] 	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?] 	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1314) ~[purpur-1.20.1.jar:git-Purpur-2017] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[purpur-1.20.1.jar:git-Purpur-2017] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2017] 	at java.lang.Thread.run(Thread.java:1589) ~[?:?]

### Bug description

When I run /tp to a offline player (which exists, the player has joined the server before), No message is sent to me, but it should tell me to use /otp because the player is offline, and in console appears the error.

### Steps to reproduce

- Join with 2 accounts
- Quit with 1
- Run /tp to the offline player with the other account

### Expected behaviour

It should send me a message like "the player is offline, use /otp"

### Actual behaviour

No message and error in console

**Comment by Octol1ttle** [comment] 2023-08-05 15:04
Duplicate of #5318

**Comment by Evidentsinger14** [comment] 2023-08-05 15:08
If you can reproduce on paper, this issue can be re-opened and investigated. Closing as duplicate

**Closed as not planned** 2023-08-05 15:09 UTC
Labels: status: wontfix
