### ISSUE TITLE
Request: Socialspy

### ISSUE THREAD

**Issue by Anesitas** [EssentialsX/Essentials#982] opened 2016-11-23 20:26 UTC
Can you please add an option to change the way SocialSpy looks? Right now its the exact same as /msg and my staff gets confused :")

**Comment by Kakifrucht** [comment] 2016-11-23 22:15
Did you use the search function first?
#788

**Comment by Anesitas** [comment] 2016-11-24 08:58
I did indeed, much more than messages to be filtered upon can't be found
though

2016-11-23 23:15 GMT+01:00 Fabian <notifications@github.com>:

**Comment by Kakifrucht** [comment] 2016-11-24 13:23
I linked the correct ticket.

**Comment by bagelcoder** [comment] 2016-12-02 15:46
There's a couple of configurable things (in regards of SocialSpy) in the language file, https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/messages_en.properties#L409

**Comment by boredhero** [comment] 2016-12-24 18:24
Man, you should take the messeges_en.lang out of the jar using Winrar. You can edit that to be totally customized, change all colors in the Plugins, change phrases, everything! Then you just use winrar to put your custom locale file back in, and load up the Plugin. Make sure you delere/overwrite the edited one so there is no conflict.

**Comment by mdcfe** [comment] 2016-12-24 20:37
@boredherobrine13 What are you on about? The messages files should be edited inside the Essentials config folder. And no, this doesn't fix the issue. The locale file does not control this part of formatting.

**Comment by boredhero** [comment] 2016-12-25 15:52
@md678685 The actual config file offers little fine grained customization. I remember once upon a time you used to be able to do something with Lang files without messing with the ones actually inside of the jars, but I could never get it to work back in 1.7.10/1.8 and I've just used the alternate method since. Does that work now?

**Comment by mdcfe** [comment] 2016-12-26 11:52
@boredherobrine13 There are `messages_xx.properties` files in the config folder. If they're not there, try setting `locale: xx` to a valid language code then restarting.

Very late edit: you need to download them from the repo.

**Comment by mdcfe** [comment] 2017-08-24 10:04
Duplicate of #788, will be fixed by #1460 once merged.

**Closed as completed by mdcfe** 2017-08-24 10:04 UTC
