### ISSUE TITLE
Player UUID Usermap Error

### ISSUE THREAD

**Issue by RocketManKian** [EssentialsX/Essentials#5025] opened 2022-07-31 17:07 UTC
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=9bc1a8a4e30e4be7844a96cdd46cd520

### Error log (if applicable)

https://paste.gg/p/anonymous/068cf3fb94ea415d95797d7f37706df1

### Bug description

Whenever loading up my Paper 1.19.1-91 I get an error when the Server has successfully loaded up, the error appears to be harmless but it is weird nonetheless.

### Steps to reproduce

1. Update to Essentials 2.19.5-dev+32-908189a.
2. Update to Paper 1.19.1-91
3. Load up the Server
4. When the Server has successfully loaded up you will see the error.

### Expected behaviour

No error

### Actual behaviour

Nothing but a harmless console error upon launch

**Comment by pop4959** [comment] 2022-07-31 18:46
Duplicate of #4342

**Closed as completed by pop4959** 2022-07-31 18:46 UTC
Labels: status: duplicate
