### ISSUE TITLE
Jenkins down

### ISSUE THREAD

**Issue by ScuroK** [EssentialsX/Essentials#1589] opened 2017-10-14 13:34 UTC
Hi the Jenkins page for essentialsx is down. could you pls fix it?

thx alot in advance!

**Comment by ItzLevvie** [comment] 2017-10-14 13:42
Grab a build from a mirror at https://ci.akpmakes.tech/job/EssentialsX/ and http://ci.ender.zone/job/EssentialsX/

**Comment by mdcfe** [comment] 2017-10-14 13:52
Duplicate of #1587.

**Closed as completed by mdcfe** 2017-10-14 13:52 UTC
