### ISSUE TITLE
/whois throws an error in console

### ISSUE THREAD

**Issue by Jay9519** [EssentialsX/Essentials#2136] opened 2018-08-21 00:59 UTC
### Information

Full output of `/ess version`:
Server Version: 1.13-R0.1-SNAPSHOT git-Spigot-fe3ab0d-82f4b3b (MC: 1.13)
EssentialsX version: 2.15.0.28
PermissionsEx version: 1.23.4
EssentialsXSpawn version: 2.15.0.28
EssentialsXChat version: 2.15.0.28
Vault is not installed - chat and permissions may not work.

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):
https://pastebin.com/6KZe7SC8
EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 
https://pastebin.com/B2YYAkfn
### Details

topic says it all, I understand the plugin is still in testing phase
Just letting you know of this error

**Comment by mdcfe** [comment] 2018-08-21 23:51
Duplicate of #2115. Fixed by 52d814f2cc410169f0e72d1a2e8f585e3d773e91, available in unsupported [1.13 experimental builds](https://ci.ender.zone/job/EssentialsX-Experimental/).

**Closed as completed** 2018-08-24 14:49 UTC
Labels: bug: confirmed
