### ISSUE TITLE
Json support in locale

### ISSUE THREAD

**Issue by xFrann** [EssentialsX/Essentials#2814] opened 2019-10-07 16:28 UTC
Sorry about the suggestion i made previously, made it by mistake without text lol?

An addition of json support to all the messages in the Locale of essentialsX would be very useful.
Mainly because it will modernise it really much and we could do many things we were not being able before without external plugins.
I know json it's not easy for beginners to understand but there are generators out there, i'm open about even making a tutorial about it on youtube but i'm preety sure there are some arleady.

Also i read some requests and a dev was writing about json being something that we could see in the future but never confirmed it.

I'm sure more than 50% of all essentialx users would love to see this implemented.
And i know it would be a long time we will see it for the amount of time it takes to implement, but i'm hopeful.

Would this be a benefit in some way? Of course, in the first place we don't have to download external plugins to format chat/messages etc, and could add more click interactions with players than before.

I'm waiting for a confirm or a decline, just to be sure of what to expect to see in the future.
Thank you very much.

**Comment by pop4959** [comment] 2019-10-07 20:14
Please don't ignore the template. Consider taking the time to fill it out, otherwise the EssentialsX team will certainly not consider adding it.

**Comment by xFrann** [comment] 2019-10-09 13:09
Updated my infos

**Comment by caojohnny** [comment] 2019-10-14 19:36
> Would this be a benefit in some way?

The problem is that you're the one making the case for this to be added. Why do *you* think it would benefit EssX?

> we don't have to download external plugins to format chat/messages etc, and could add more click interactions with players than before.

You already don't need to download any external plugins to format chat...? Changing it to JSON won't make it any easier to harder to add click interactions that I'm aware of.

At the end of the day JSON vs YAML is just the file format. You can achieve the same thing in both formats with essentially the same level of effort. I think the fact that Ess/EssX has already been using YAML for several years, along with YAML being the standard format for configuration files among all Bukkit/Spigot/whatever plugins makes it a valid case to continue using YAML. This is the format that is universally being used, regardless of the plugin, so I think that it would be unwise to change locale files to JSON.

**Comment by pop4959** [comment] 2019-10-14 23:55
You say that JSON support would be very useful. Please elaborate. Also, can you explain how JSON "modernise(s)" the plugin, and what isn't currently possible without external tools. Practical examples would help because I do not follow what you mean here.

What dev was writing about JSON? Can you provide a link to the source? Similarly, why do you say over 50% of EssentialsX users would like this feature? Have you conducted a poll, or is this just a random number you're throwing out?

I'm mostly with AgentTroll on this. The thing about Java Properties files is that they're extremely simple. All it is are key-value pairs. All server owners that have run a MineCraft server (not even Spigot, even just vanilla) have configured the server.properties file (`eula=true` at the very least :stuck_out_tongue:). There is nothing preventing something like click interactions being added to messages currently, as they could probably be integrated with the current placeholder system (`{0}`, etc). The real problem there is that Spigot actually doesn't provide modern methods to be able to use those features effectively, to my knowledge, because it itself uses legacy chat formatting, rather than JSON chat formatting.

As a result, I will say right now as-is this will probably not be considered anytime soon. Based on your arguments, I'm not certain that you fully understand the impacts of your suggestion. Unless you have any other strong arguments for which you can clearly explain your reasoning, I think we can probably close this.

**Comment by caojohnny** [comment] 2019-10-15 01:10
I think I understand what OP is trying to get at. OP wants to be able to send raw JSON messages. They aren’t talking about the file, but rather the locale strings. 

That being said, I’m still not sure how exactly this would help. I think it adds unnecessary complexity because it requires the entire codebase to be changed in order to support the JSON text components. I don’t think it is worth implementing this unless there’s a clear example of it being significantly more useful in more than a few edge cases.

**Comment by pop4959** [comment] 2019-10-15 01:37
Yeah that's what they were getting at. Full use of the component system would require a major rewrite, and for the parts where it would actually be relevant, it could just be made into a placeholder or something. I may stand corrected, but I don't think Spigot's component system is even very good. Not to mention again, that using the component system instead of the simple properties format would likely make it harder for server owners.

**Comment by pop4959** [comment] 2019-11-30 21:15
I'm closing this on the premise that no one actually wants to develop this feature as it stands right now. There's no enough of a point to, as has been mentioned. I'm sure it could be considered if someone actually made a PR for it, but that's if anyone does.

**Closed as completed by pop4959** 2019-11-30 21:15 UTC
