### ISSUE TITLE
Monster and weather bug

### ISSUE THREAD

**Issue by mvez73** [EssentialsX/Essentials#2740] opened 2019-08-14 15:52 UTC
### Information

**Full output of `/ess version`**:i dont' know how to copy/paste the result. But i have paper 1.67 (1.14.4) with Essentialsx 2.17.1, EssentialsxSpawn 2.17.1 and EssentialsChat 2.17.1

```
<!-- Run the command in your console, and copy and paste the whole output here -->
```

**Server log**: https://gist.github.com/mvez73/13f2c565f87ac0427e0b226ae4ecd2ac#file-latest-log

**EssentialsX config**: https://gist.github.com/mvez73/ebd4382f3d756da6223cf150849ed00a

### Details

**Description**  
When using EssentialsX weather don't cycle and pratically no monsters spawn.
For monsters: In 30 minutes i didn't see a single monster and my daughter only saw 2. I shuted down the server and delete EssentialsX, restart the server and there is monsters everywhere. Of course i tried all that at night.
For weather it's simple. Weather don't cycle at all with EssentialsX. If i start rain with /weather storm it never ends. If i set sun it never rains

**Steps to reproduce**  
I don't really know. I tried on a fresh new server with only Paper 1.67 (1.14.4) and EssentialsX 2.17.1 with only Essentials, chat and spawn modules. The first time i notice the bug it was with spigot 1.14.4. All these servers are host localy on my pc and it's just for fun to play with my daughter.

**Expected behavior**  
Monster spawning "normally" and weather cycle "normally"

**Screenshots**  
I don't think screenshot would help. If you want to see something in particular just let me know.

Sorry if i didn't fill the form correctly it's my first time here. And i speak french so i'm sure i miss something somewhere.

**Comment by mvez73** [comment] 2019-08-14 17:58
I will not delete post to let people read my update. 2 hours later i finally see rain in my server and monsters start slowly to appear more frequently.  I don't understand why and if it's normal, but without Essentialsx it's almost instant for the monsters to spawn and i see more monster. For the rain i think it's more frequent too. Anyway it seems that i don't have any bugs but i wonder why it's different with Essentialsx loaded.

**Comment by pop4959** [comment] 2019-09-19 22:40
EssentialsX does not modify these behaviours. In addition, there have been no further reports of any kind of major issue like this in the past month, and since you have no way of reproducing it, I will go ahead and close this now.

**Closed as completed by pop4959** 2019-09-19 22:40 UTC
Labels: status: invalid, status: not enough info
