### ISSUE TITLE
[Idea] /tempbanip command

### ISSUE THREAD

**Issue by voodootje0** [EssentialsX/Essentials#233] opened 2015-10-20 23:22 UTC
Hey drtshock,

First nice that you have updated essentials <3

I have a idea for the ban commands, now you have /ban, /tempban and /banip.
But there is no /tempbanip, I hope you will add that command.

Thanks for reading it.
- voodootje0

**Comment by EvilOlaf** [comment] 2015-10-21 05:35
https://github.com/drtshock/Essentials/issues/115

**Comment by drtshock** [comment] 2015-10-21 20:03
duplicate of ^

**Closed as completed by drtshock** 2015-10-21 20:03 UTC
