### ISSUE TITLE
When using trade method in API it fires an AsssertionError: TRAP

### ISSUE THREAD

**Issue by ctooley21** [EssentialsX/Essentials#1136] opened 2017-02-16 00:25 UTC
Line i've narrowed it down to
`final Trade charge = new Trade("Commandhome", plugin.getEssentials());
 user.getTeleport().teleport(user.getHome("home"), charge, PlayerTeleportEvent.TeleportCause.COMMAND);
`
 2nd line, as once I comment that line out, there is no issue.
error: http://pastebin.com/bUT50JW0

**Comment by ctooley21** [comment] 2017-02-16 00:27
Using Spigot 1.11,

if it helps, here is where the error is thrown in Spigot code
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/nms-patches/ItemStack.patch#64
Also, error only happens when the item is only 1, if it's > 1 then no error.

**Comment by mdcfe** [comment] 2018-02-04 16:25
Closing as this doesn't appear to be directly caused by EssentialsX - if you've found any other hints, feel free to reopen the issue and report back.

**Closed as completed by mdcfe** 2018-02-04 16:25 UTC
Labels: type: problem, status: not enough info
