### ISSUE TITLE
/i invalid item meta cause client crash.

### ISSUE THREAD

**Issue by Done84** [EssentialsX/Essentials#624] opened 2016-05-23 02:45 UTC
Players with access to /i can use it to get items with invalid metadata (?) if that item is placed it crashes the player. 

Here is an example

Player does the command:
/i 145:3
Since theres only anvils valid codes for 145:0 145:1 and 145:2 any higher number gives the player a block that does not exist.
http://prntscr.com/b79yf3

Then the player can give someone else that block, if anyone places it they crash their client.

It works for any item with invalid data after the main block ID

**Comment by drtshock** [comment] 2016-05-30 16:30
Can you run that without op?

**Comment by Done84** [comment] 2016-06-25 00:43
In my case i have ranks limited access to /i, so yes.

**Comment by SupaHam** [comment] 2016-06-28 05:29
Hi, I am unable to reproduce this bug on 1.10.2. I assume this was an issue in 1.9 and has since been fixed by the Minecraft team.

**Closed as completed by SupaHam** 2016-06-28 05:29 UTC
