### ISSUE TITLE
Signs dont work

### ISSUE THREAD

**Issue by chaioo** [EssentialsX/Essentials#2588] opened 2019-06-08 18:59 UTC
### Information

Full output of `/ess version`:

**Server log:** 

**EssentialsX config** 

### Help request

**Problem**

**What I have tried**

**Screenshots**

**Comment by mdcfe** [comment] 2019-06-08 20:06
You didn't provide any information about your issue.

Please fill out the template.

**Comment by YanisBft** [comment] 2019-06-09 10:33
If I refer to their title, I can also confirm that Essentials' signs don't work. Clicking on a [Buy], [Sell], [Warp] or any other custom sign do nothing.

**Comment by mdcfe** [comment] 2019-06-09 10:44
@Yanis48 To provide any support, we need to know the following:
* What version of Minecraft and EssentialsX you're running
* What your config looks like
* What happens during server startup (what compatibility code is being used + what other plugins may be interfering)
* What happens in the server console when you encounter the issue
* What happens in-game when you encounter the issue

---

I can confirm that EssentialsX signs *do* work when:
* You use the correct EssentialsX version for the Spigot/Paper version you're running
* You've enabled the relevant signs in the EssentialsX config
* No errors show up in the console when you place, interact with or break the sign or supporting block

**Comment by YanisBft** [comment] 2019-06-09 15:02
- Paper 1.14.2 build 70 with Essentials 2.16.1.168
- Almost default config, all signs are enabled
- No errors show up in the console
- EditableSign 6.0.0 plugin is also on the server

**Comment by mdcfe** [comment] 2019-06-09 15:05
@Yanis48 Update to the [experimental build](https://ci.ender.zone/job/EssentialsX-Experimental/), or wait for 1.14 support to be merged into regular builds.

The OP still hasn't confirmed what their issue is.

**Comment by YanisBft** [comment] 2019-06-10 10:49
The 1.14 experimental builds seem quite stable, so I use them and it works. Thanks!

**Comment by KrepelkaCZ** [comment] 2019-06-10 19:12
Hello i can confirm that signs are not working for me as well:
[console.txt](https://github.com/EssentialsX/Essentials/files/3273423/console.txt)
[config.txt](https://github.com/EssentialsX/Essentials/files/3273425/config.txt)
version: 2.16.1.169 (EssX, Chat, Protect, Spawn jars)
version of server 1.14.2-R0.1-SNAPSHOT

When i use the enchant sign for instance nothing happens (though there is an error in the log)

**Comment by mdcfe** [comment] 2019-06-11 06:45
@KrepelkaCZ [As mentioned above](https://github.com/EssentialsX/Essentials/issues/2588#issuecomment-500219300), you currently need to use experimental builds for 1.14.x.

**Comment by triagonal** [comment] 2019-07-05 03:17
Closing due to insufficient information. 

For others experiencing this issue on 1.14, please update to the latest version of EssentialsX (`2.17.0` and above), as 1.14 is now officially supported.

**Closed as completed by triagonal** 2019-07-05 03:17 UTC
Labels: status: not enough info
