### ISSUE TITLE
Problem with tpa and home

### ISSUE THREAD

**Issue by DoreK333** [EssentialsX/Essentials#2194] opened 2018-09-22 20:18 UTC
### Information

Full output of `/ess version`:
![`/ess version` output](https://i.imgur.com/YbgvBDE.png)

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):
https://gist.github.com/DoreK333/965070a729703588f75a47979f6ca7ee
EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 
https://gist.github.com/DoreK333/838c0e4474c373972df0710ab0bb188e
### Details

There is sometimes a problem with teleportation:
- players can not move to their homes, they are informed that they have to wait 5 seconds for teleportation, but they are not transferred
- when the player receives a teleport request and executes the /tpaccept command, an error appears indicating that there is no teleport request.

The problem began to occur today, I suspect that after updating the paper.

**Comment by vergara2090** [comment] 2018-09-26 21:10
I have the same problem !

**Comment by A-Valk** [comment] 2018-10-02 18:07
same!

**Comment by mdcfe** [comment] 2018-10-09 18:03
I imagine this is related to EssentialsX not supporting Paper's async chunk loading, but this needs further investigation.

**Comment by A-Valk** [comment] 2018-10-10 10:41
I'm having this issue on normal spigot

**Comment by favorit5503** [comment] 2018-10-14 19:12
I have this same problem but. If you change "teleport-delay: 0" in essentials config, the problem dissapears. So there is a problem i think whit the delay function. Try out.

**Comment by DoreK333** [comment] 2018-10-15 11:09
I noticed that you have to enter /tpaccept a few times for the teleportation to work.

**Comment by favorit5503** [comment] 2018-10-15 11:52
You dont need /tpaccept for teleporting home. And mostly i have problems with /home command.

**Comment by DoreK333** [comment] 2018-10-15 11:53
This was information about the problem with /tpa.

**Comment by favorit5503** [comment] 2018-10-15 11:55
Did you tried the change teleport delay i mentioned before?

**Comment by DoreK333** [comment] 2018-10-15 11:56
Yes and problem with home has been fixed ;]

**Comment by favorit5503** [comment] 2018-10-15 12:05
Okay. :) @md678685 i found a temporary solution for this problem.

> I have this same problem but. If you change "teleport-delay: 0" in essentials config, the problem dissapears. So there is a problem i think whit the delay function. Try out.

For me and DoreK333 fixed the home problem.

**Comment by A-Valk** [comment] 2018-10-15 20:46
My teleport delay has always been 0, so not fixed for me 🤷

**Comment by JRoy** [comment] 2020-05-24 19:28
Cannot reproduce, closing...

**Closed as completed by JRoy** 2020-05-24 19:28 UTC
Labels: status: invalid, bug: unconfirmed
