### ISSUE TITLE
Add /playtime top

### ISSUE THREAD

**Issue by BAD7777** [EssentialsX/Essentials#5516] opened 2023-09-14 16:48 UTC
### Feature description

Create a command to show the top players with the most playtime using the '/playtime top' command, similar to the '/balancetop' command.

### How the feature is useful

It displays the TOP players who have spent the most time playing on the server. Players will compete to play more on the server.

Similar to the /balancetop command.

**Comment by Chew** [comment] 2023-09-14 21:13
Closing for the same thing discussed in https://github.com/EssentialsX/Essentials/discussions/4639#discussioncomment-1701961, and as a duplicate of #4940. tl;dr, better left to a separate plugin

**Closed as not planned by Chew** 2023-09-14 21:13 UTC
Labels: status: duplicate, type: enhancement
