### ISSUE TITLE
Kitcreate error

### ISSUE THREAD

**Issue by Lunatik934** [EssentialsX/Essentials#1681] opened 2017-12-05 12:59 UTC
EssentialsX version (`2.0.1-b546`): 

Server software (`This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)`): 

Server (logs/latest.log): https://gist.github.com/Lunatik934/f99c7371aecf172ac6916072990e7480

EssentialsX config (if applicable):

**Comment by mdcfe** [comment] 2017-12-06 08:36
Are you using a shared host or running your server behind a firewall? It appears that your server is unable to reach Gist, so the kit can't be uploaded.

**Comment by Lunatik934** [comment] 2017-12-06 15:14
I use a server with firewall but the problem provide from java, use this method https://stackoverflow.com/a/40020183/4297304

**Comment by mdcfe** [comment] 2017-12-06 21:35
The link is unrelated to this issue - this issue is a duplicate of #1214. If using dedicated hosting, please make sure your server is up-to-date, and try disabling your firewall. If using shared hosting, we cannot provide any assistance with this error.

**Comment by mdcfe** [comment] 2017-12-16 18:17
Closing due to a lack of response; if this is still a problem, feel free to reopen the issue.

**Closed as completed by mdcfe** 2017-12-16 18:17 UTC
Labels: type: problem, status: not enough info
