### ISSUE TITLE
Unlimited command breaks userdata

### ISSUE THREAD

**Issue by Motytheultimate** [EssentialsX/Essentials#2509] opened 2019-04-27 15:47 UTC
### Information

**Full output of `/ess version`**:

```
Server Version: ┬1.13.2-R0.1-SNAPSHOT git-Paper-624 (MC: 1.13.2)
┬EssentialsX Version: ┬2.16.1.0
┬LuckPerms Version: ┬4.4.1
┬Vault Version: ┬1.7.1-b91
┬EssentialsXChat Version: ┬2.16.1.0
┬EssentialsXGeoIP Version: ┬2.16.1.0
```

**Server log**: 

**EssentialsX config**: 

### Details

**Description**  
/unlimited Command breaks Userdata
the ulimited command produces
unlimited:
- !!org.bukkit.Material 'STONE_BRICKS'
in userdata

which is not valid yml

**Steps to reproduce**  
/unlimited stone_bricks
produces
unlimited:
- !!org.bukkit.Material 'STONE_BRICKS'
in Userdata

**Expected behavior**  
no broken Userdata

**Comment by mdcfe** [comment] 2019-04-27 16:35
There is no indication in your report that the YAML is broken. This is valid YAML - `!!` is used to define types and is how SnakeYAML knows the entry is a Bukkit `Material`.

You also didn't include a log in your report. If you think this is wrong somehow or is causing other issues, please add more information **including a log**.

Closing as this is not a bug.

**Closed as completed by mdcfe** 2019-04-27 16:35 UTC
Labels: status: invalid, type: problem, status: not enough info

**Comment by iGuillem** [comment] 2019-09-06 11:26
https://pastebin.com/Kc7CqkB4
