### ISSUE TITLE
This came to me as a SHOCK!

### ISSUE THREAD

**Issue by MrKiller01** [EssentialsX/Essentials#1640] opened 2017-11-11 12:53 UTC
This error occurred during startup. I went to bukkit to download the latest version, but i already had that one. 

EssentialsX version (`/essentials`): Essentials v2.0.1-b488

Server software (`/version`): [13:51:25 INFO]: This server is running CraftBukkit version git-Spigot-d21162c-6
1e0c69 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[13:51:25 INFO]: Checking version, please wait...
[13:51:25 INFO]: You are running the latest version
>

EssentialsX config (if applicable): 

((( The error it gave in console on my server)))

[13:46:00 WARN]: [Essentials] Plugin Essentials v2.0.1-b488 generated an excepti
on while executing task 71
org.yaml.snakeyaml.constructor.ConstructorException: Can't construct a java obje
ct for tag:yaml.org,2002:com.earth2me.essentials.settings.Jails; exception=java.
lang.NoSuchFieldException: typeDefinitions
 in 'reader', line 1, column 1:
    jails:
    ^

        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.constr
uct(Constructor.java:313) ~[spigot-1.12.2.jar:git-Spigot-d21162c-61e0c69]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck
(BaseConstructor.java:207) ~[spigot-1.12.2.jar:git-Spigot-d21162c-61e0c69]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseCo
nstructor.java:196) ~[spigot-1.12.2.jar:git-Spigot-d21162c-61e0c69]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(Base
Constructor.java:161) ~[spigot-1.12.2.jar:git-Spigot-d21162c-61e0c69]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseCons
tructor.java:147) ~[spigot-1.12.2.jar:git-Spigot-d21162c-61e0c69]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[spigot-1.12.2
.jar:git-Spigot-d21162c-61e0c69]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:467) ~[spigot-1.12.2.jar:git-S
pigot-d21162c-61e0c69]
        at com.earth2me.essentials.storage.YamlStorageReader.load(YamlStorageRea
der.java:41) ~[?:?]
        at com.earth2me.essentials.storage.AbstractDelayedYamlFileReader.run(Abs
tractDelayedYamlFileReader.java:33) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.jav
a:71) ~[spigot-1.12.2.jar:git-Spigot-d21162c-61e0c69]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsy
ncTask.java:52) [spigot-1.12.2.jar:git-Spigot-d21162c-61e0c69]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:
1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?
:1.8.0_144]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: org.yaml.snakeyaml.error.YAMLException: java.lang.NoSuchFieldExceptio
n: typeDefinitions
        at com.earth2me.essentials.storage.BukkitConstructor$ConstructBukkitMapp
ing.constructJavaBean2ndStep(BukkitConstructor.java:231) ~[?:?]
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct
(Constructor.java:149) ~[spigot-1.12.2.jar:git-Spigot-d21162c-61e0c69]
        at com.earth2me.essentials.storage.BukkitConstructor$ConstructBukkitMapp
ing.construct(BukkitConstructor.java:217) ~[?:?]
        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.constr
uct(Constructor.java:308) ~[spigot-1.12.2.jar:git-Spigot-d21162c-61e0c69]
        ... 13 more
Caused by: java.lang.NoSuchFieldException: typeDefinitions
        at java.lang.Class.getDeclaredField(Unknown Source) ~[?:1.8.0_144]
        at com.earth2me.essentials.storage.BukkitConstructor$ConstructBukkitMapp
ing.constructJavaBean2ndStep(BukkitConstructor.java:224) ~[?:?]
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct
(Constructor.java:149) ~[spigot-1.12.2.jar:git-Spigot-d21162c-61e0c69]
        at com.earth2me.essentials.storage.BukkitConstructor$ConstructBukkitMapp
ing.construct(BukkitConstructor.java:217) ~[?:?]
        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.constr
uct(Constructor.java:308) ~[spigot-1.12.2.jar:git-Spigot-d21162c-61e0c69]
        ... 13 more

**Comment by smmmadden** [comment] 2017-11-11 13:29
This was fixed as part of Issue 1631 - upgrade Essentials to build 542 or higher

**Comment by mdcfe** [comment] 2017-11-11 13:38
Duplicate of #1631. Update EssentialsX to the [latest version](https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild).

**Closed as completed by mdcfe** 2017-11-11 13:38 UTC

**Comment by MrKiller01** [comment] 2017-11-11 14:08
But why is the version exactly the same? Why not a change in version number so that we can compare it as the newest one....
You guys obviously did not read the text I wrote, i said that I downloaded the latest version, 2.0.1. How am I to tell which is newer/better???

**Comment by MrKiller01** [comment] 2017-11-11 14:36
Uncertain: >essentials version
[15:29:45 INFO]: CONSOLE issued server command: /essentials version
[15:29:45 INFO]: Using locale en_US
[15:29:45 INFO]: [Essentials] Using Spigot 1.7.10+ ServerListPingEvent iterator
[15:29:45 INFO]: Essentials reloaded 2.0.1-bSNAPSHOT.
> This version was the one i downloaded and it was version found on link provided by MD678685
https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild/

**Comment by Kakifrucht** [comment] 2017-11-11 14:40
There is an issue that the build number is not added to the artifact.
I have reported it a while ago in #1602
