### ISSUE TITLE
[REQUEST] Bungee support

### ISSUE THREAD

**Issue by Fireant456** [EssentialsX/Essentials#1051] opened 2016-12-31 05:29 UTC
Can you please add support so that essentials can be synced across bungeecord, maybe port to a bungeecord version of the plugin or just add mysql support so that player individual data is synced across servers in the network

**Comment by mdcfe** [comment] 2016-12-31 10:30
Duplicate of #912 and #241.

**Comment by mdcfe** [comment] 2017-01-03 14:28
As a side note, developers have previously said that MySQL support in Essentials isn't very feasible for one reason or another.

**Closed as completed** 2018-01-06 20:51 UTC
