### ISSUE TITLE
I would love the 1.16+ gradient feature to allow you to choose two HEX colors to fade into each other without having to each letter

### ISSUE THREAD

**Issue by namelessghoul87** [EssentialsX/Essentials#3937] opened 2021-01-23 18:57 UTC
-->

### Feature request

**Feature description:**  

A feature where two hex color could make name/sign text fade into each other to give a gradient effect without having to do each letter one by one.

**How the feature is useful:**  

I think the HEX color additions for 1.16+ servers has been a great addition to make everything a bit more colorful. My players love it for their usernames and signs mostly but there's no website that creates a quick code for them. I'd only like to reference Zrips CMI plugin to give an example. If you take a look [here](https://www.zrips.net/cmi/hex-colors/), scroll down to color gradients and you'll see that the plugin gives an option for one color to fade into another with only 2 hex values or colors. I'll always prefer EssentialsX to any other all-in-one plugin but I will admit that this would be would a great addition.

**Comment by JasonHorkles** [comment] 2021-01-23 18:58
Duplicate of #3541

**Comment by Chew** [comment] 2021-01-23 19:39
Which was closed in favor of #2391. I do agree it's a good idea, but let's not have multiple issues for the same general idea. Thank you for your contribution!

**Closed as completed by Chew** 2021-01-23 19:39 UTC
Labels: type: enhancement

**Comment by James-P-Bennett** [comment] 2023-09-12 16:36
This ought to be reconsidered as it would be fairly simple to add this to the current essentialsx color formating listener using a regex method.

Something like &gr#RGB1#RGB2Text:
```
private String parseGradient(String message) {
    // Regular expression to match gradient codes
    String regex = "&gr#([0-9A-Fa-f]{6})#([0-9A-Fa-f]{6})";

    return message.replaceAll(regex, "<gradient>$1:$2</gradient>");
}
```

**Comment by JasonHorkles** [comment] 2023-09-12 16:38
> This ought to be reconsidered as it would be fairly simple to add this to the current essentialsx color formating listener using a regex method.
> 
> Something like:
> `private String parseGradient(String message) {
>     // Regular expression to match gradient codes
>     String regex = "&gr#([0-9A-Fa-f]{6})#([0-9A-Fa-f]{6})";
> 
>     return message.replaceAll(regex, "<gradient>$1:$2</gradient>");
> }`

Minimessage support is already underway which will solve this issue (see #4717)
