### ISSUE TITLE
Armor And Off Hand Slots

### ISSUE THREAD

**Issue by CryptoMorin** [EssentialsX/Essentials#1425] opened 2017-08-01 07:19 UTC
Add Armor Slot + OffHand (Left Hand) Slot to /inventorysee. (You can make it 5 raw. It's currently 4 right? 3 For inventory, 1 top for Hot bar and 1 down for Armor Slot (The last one must show the first 4 slots as Helmet - Chestplate - Leggings - Boots and the last slot must show the offhand item)

**Comment by mdcfe** [comment] 2017-08-01 08:24
Could you post one suggestion per issue so we can keep track of them?

**Comment by mdcfe** [comment] 2017-08-03 15:26
Armor slots are already supported by doing `/invsee <player> equip`, although you can't move items to/from them.

EssX just directly shows the remote players inventory when using the command without `equip` at the end, so I'm not sure if there's an easy way to alter the inventory and still be able to move items in the target inventory.

**Comment by CryptoMorin** [comment] 2017-08-05 11:28
Well honestly it doesn't show off hand plus i think it would be better if you make it with 5 raw... like i explained in my first post. It would be even easier to access everything in 1 inventory.
Isn't it better?

**Comment by mdcfe** [comment] 2017-08-05 13:20
No, because we're not creating a clone of the player's inventory, we're showing the actual 4 row inventory. We can't increase the rows of the player's real inventory and as far as I can tell we'd need to rework how inventory viewing for this to happen (listening to inventory events, adding/deleting ItemStacks) which could cause further reliability issues down the road.

This isn't to say that the feature is impossible, but it would require a lot of careful thought and effort to implement.

**Comment by CryptoMorin** [comment] 2017-08-05 14:50
I understand what you're talking about.
It's okay, Thanks for the help!

**Comment by CryptoMorin** [comment] 2017-08-06 11:34
I recently found this plugin.
https://dev.bukkit.org/projects/openinv
I really enjoyed it and it's working with the latest 1.12.1 Spigot.
I would like to see this in EssentialsX.
Btw... the offhand slot acts somehow weird idk if it's really coded to be like that...
Thought it would be good to show you this plugin. Idk maybe you can somehow work with it?...
If you could somehow merge this plugin or what...
Just asking...

**Comment by CryptoMorin** [comment] 2017-08-07 07:33
Bump!

**Comment by mdcfe** [comment] 2017-08-07 13:23
Please don't bump issues, especially ones that are less than a week old. This will be done whenever it's done, and not before.

**Comment by pop4959** [comment] 2020-04-30 04:35
Closing as a duplicate of #472. Please see khobbit's answer as to why this doesn't already exist in the plugin.

**Closed as completed by pop4959** 2020-04-30 04:35 UTC
Labels: status: duplicate, type: enhancement
