### ISSUE TITLE
Cooldown for permissionless commands

### ISSUE THREAD

**Issue by DebuffPvP** [EssentialsX/Essentials#4510] opened 2021-09-02 09:29 UTC
### Type of bug

Other unexpected behaviour

### `/ess dump *` output

N/A

### Bug description

When a user does not have permission for that command it still gives the cooldown

### Steps to reproduce

N/A

### Expected behaviour

N/A

### Actual behaviour

N/A

**Comment by Chew** [comment] 2021-09-03 05:14
Duplicate of #4507

**Closed as completed by Chew** 2021-09-03 05:14 UTC
Labels: status: duplicate
