### ISSUE TITLE
Server startup issue with EssentialsGeoIP

### ISSUE THREAD

**Issue by smmmadden** [EssentialsX/Essentials#2380] opened 2019-01-14 02:32 UTC
Server is Paper Spigot 1.13.2 behind Waterfall Proxy build 246.

**Full output of `/ess version`**:
[21:44:25] [Server thread/INFO]: CONSOLE issued server command: /ess version
[21:44:25] [Server thread/INFO]: Server version: 1.13.2-R0.1-SNAPSHOT git-Paper-500 (MC: 1.13.2)
[21:44:25] [Server thread/INFO]: EssentialsX version: 2.16.0.31
[21:44:25] [Server thread/INFO]: LuckPerms version: 4.3.76
[21:44:25] [Server thread/INFO]: Vault version: 1.7.1-b91
[21:44:25] [Server thread/INFO]: EssentialsXProtect version: 2.16.0.31
[21:44:25] [Server thread/INFO]: EssentialsXChat version: 2.16.0.31
[21:44:25] [Server thread/INFO]: EssentialsXGeoIP version: 2.16.0.31
[21:44:25] [Server thread/INFO]: EssentialsXAntiBuild version: 2.16.0.31
[21:44:25] [Server thread/INFO]: EssentialsExtras version: 2.15.0.1
[21:44:25] [Server thread/INFO]: EssentialsXSpawn version: 2.16.0.31
[21:44:25] [Server thread/INFO]: You are running unsupported plugins!

**Description**  
Startup issue with Paper build 500 and Essentials 2.16.0.31 build.  Behind Waterfall Build 246.  Also tested on my test server (without Waterfall) and the results are the same.  I was on 2.16.0.3 so I renamed the items.csv and items.json and regenerated new files.

**Steps to reproduce**  
Downloaded latest jars for EssentialsXSpawn, EssentialsXProtect, EssentialsXGeoIP, EssentialsXChat, EssentialsXAntiBUild and EssentialsX builds 2.16.0.31 and restarted server.

**Expected behavior**  
No warnings or exceptions with EssentialsX

**Screenshots**  
WARN: [com.fasterxml.jackson.databind.ext.Java7Support] Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added.

Note that I am running with Oracle JDK 1.8.0_92 x64 on Windows 10 Professional O/S

Full startup log and plugins can be seen here: https://hastebin.com/enecufilog.md

**Comment by triagonal** [comment] 2019-01-14 06:35
Duplicate (?) of #2376 

As long as GeoIP is working correctly, you can ignore the message. It shouldn't affect how the plugin works. The Maxmind GeoIP library was recently updated, and that's what's causing the message to appear.

**Comment by mdcfe** [comment] 2019-01-15 09:51
Closing as duplicate of #2376 (thanks @triagonal).

**Closed as completed by mdcfe** 2019-01-15 09:51 UTC
