### ISSUE TITLE
In-game location permission node for /whois

### ISSUE THREAD

**Issue by VideoGameSmash12** [EssentialsX/Essentials#5582] opened 2023-11-23 15:53 UTC
### Feature description

When a player with the proposed permission node `essentials.whois.position` (or `essentials.whois.location`) runs the /whois command, the command will include the target player's location. If they don't have the node, the line related to location will be omitted from the command's output.

### How the feature is useful

Servers who want to allow the /whois command for players would be able to control who is able to get coordinates of other players and optionally prevent them from abusing it to bypass their /tptoggle status. This is not the case currently.

**Comment by pop4959** [comment] 2023-12-10 00:52
Duplicate of #3429. This is not something that we're planning, as `/whois` is meant more as an admin command rather than for players so you will likely want to find an alternative instead which only displays the information that you want players to see.

**Closed as not planned by pop4959** 2023-12-10 00:52 UTC
Labels: status: duplicate, type: enhancement
