### ISSUE TITLE
Teleportation kick bug

### ISSUE THREAD

**Issue by feroxmc** [EssentialsX/Essentials#2649] opened 2019-07-02 21:58 UTC
### Information

**Full output of `/ess version`**:

```
2.07 17:53:53 [Server] INFO Server version: 1.13.2-R0.1-SNAPSHOT git-Paper-636 (MC: 1.13.2)
02.07 17:53:53 [Server] INFO EssentialsX version: 2.17.0.0
02.07 17:53:53 [Server] INFO LuckPerms version: 4.4.1
02.07 17:53:53 [Server] INFO Vault version: 1.7.2-b107
02.07 17:53:53 [Server] INFO EssentialsXChat version: 2.17.0.0
02.07 17:53:53 [Server] INFO EssentialsXSpawn version: 2.17.0.0
```

**Server log**:  https://gist.github.com/FeroxDrood/d1bfdd987284db31a1ea7246f0bc794b

**EssentialsX config**: https://gist.github.com/FeroxDrood/77952afcb78e58d9727d072b0b4d8ebc

### Details

**Description**  
When a player teleports to another world either using /home /back or /warp they will get kicked to the lobby with a message saying the server they were on has gone down so they were kicked. This only happens around 50% of the time. https://gist.github.com/FeroxDrood/72effe89ea60e4fb6189b2a1a2b84fd0 this error is printed in the bungee console when the player is kicked, i am running the latest bungee build along with the latest version of via version.

**Steps to reproduce**  
1.13.2 paper spigot, latest essentials version and then try and teleport using /home, /back or a warp to a different world/

**Expected behavior**  
The player should not get kicked.

**Screenshots**  
N/A

**Comment by mdcfe** [comment] 2019-07-07 14:30
Can you replicate this without ViaVersion installed? There's nothing that suggests this is definitely a problem with EssentialsX - it sounds like an issue sending packets across the network, which ViaVersion is heavily involved with.

**Comment by pop4959** [comment] 2019-10-27 00:41
There's no indication that this is actually caused by EssentialsX. Closing for now. If you are able to find a reliable way to reproduce the issue using only Paper/EssentialsX, feel free to let us know so that we can look into it further.

**Closed as completed by pop4959** 2019-10-27 00:41 UTC
Labels: help wanted, bug: unconfirmed
