### ISSUE TITLE
Fishing not detected as AFK

### ISSUE THREAD

**Issue by Owenftw** [EssentialsX/Essentials#1093] opened 2017-01-24 10:01 UTC
If you cast a line in the water and leave it, it will never detect you as AFK meaning players can bypass the AFK kick set in config.

**Comment by TNTUP** [comment] 2017-01-31 09:02
See here #1050 (But thanks for the bump, this is urgent because some players are abusing this bug which forces us to warn them)

**Comment by mdcfe** [comment] 2018-01-24 19:27
Duplicate of #1050.

**Closed as completed by mdcfe** 2018-01-24 19:27 UTC
