### ISSUE TITLE
Commands with commands.yml alias cannot use command-cooldowns

### ISSUE THREAD

**Issue by andrewkm** [EssentialsX/Essentials#2191] opened 2018-09-20 16:15 UTC
Due to McMMO overriding essentials repair command, I must do the following in my commands.yml:

```
  repair:
  - erepair $1-
```

However, any commands located in commands.yml cannot be used with command-cooldowns.

Example:

```
command-cooldowns:
  repair: 302400
```

or even

```
command-cooldowns:
  '.*repair': 302400
```

both work on a user running /fix or running /erepair, however when running /repair, due to it going through commands.yml, it NEVER obeys the command-cooldowns. I have tested this with several other commands in commands.yml and it's all the exact same problem.

**Comment by molor** [comment] 2018-09-26 08:57
Developer now in hibernation.. https://github.com/EssentialsX/Essentials/issues/2058

**Comment by mdcfe** [comment] 2018-10-09 17:44
Closing as a duplicate of #2058.

**Closed as completed by mdcfe** 2018-10-09 17:44 UTC
