### ISSUE TITLE
potion bugs in kits

### ISSUE THREAD

**Issue by Elgorond** [EssentialsX/Essentials#865] opened 2016-09-01 05:33 UTC
In my inventory I have a potion of regen 45 seconds:
/createkit
https://gist.github.com/anonymous/d08ab628f15ae3bb577a8c12e63a5fcb

using the kit gives me a potion of regen 11 seconds?? (not even a real potion)

Trying regen 2 minutes also is broken, results in regen 30 seconds (not real as well)

**Comment by Elgorond** [comment] 2016-09-09 07:37
Another example is using /createkit with splash potion of healing II's. It'll input it as splash healing regulars.

**Comment by pop4959** [comment] 2020-01-05 05:29
Since no one has confirmed this bug in several years, I am closing this issue. However currently there is also a bug creating any potion in kits when using the Essentials syntax. If this is still an issue when fixing that, we will probably end up fixing it. Right now the best way to give people certain items with highly involved metadata is to use a command in the kit, for example with `minecraft:give`.

**Closed as completed by pop4959** 2020-01-05 05:29 UTC
Labels: type: problem, bug: unconfirmed
