### ISSUE TITLE
/unlimited and /unl do not work with arrows and fireworks

### ISSUE THREAD

**Issue by AMDBartek** [EssentialsX/Essentials#3005] opened 2020-02-09 21:02 UTC
### Details

**Output of /ess version**

Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1618 (MC: 1.12.2)
EssentialsX version: 2.17.1.53
LuckPerms version: 5.0.39
PlaceholderAPI version: 2.10.4
Vault version: 1.7.2-b107
EssentialsXProtect version: 2.17.1.53
EssentialsXChat version: 2.17.1.53
EssentialsXSpawn version: 2.17.1.53

**Server files**

Log not provided due to no error/warning
EssentialsX config: https://gist.githubusercontent.com/AMD-Mario27639/51410838c4a3ddf16cf4f8b88003c02f/raw/fc8eb20d5107a5962308021918e5de08f8ca6bba/config.yml

**Description**  
The /unlimited command does not work for fireworks and arrows.
For example when I get a bow and use the command "/unl arrow" and use the bow it runs out of arrows even though it is meant to be unlimited. This also happens with fireworks, when you place the fireworks they run out like normal.

**Steps to reproduce (Fireworks)**  
1. Use the /unlimited command or /unl, like this: "/unlimited firework"
2. Use the fireworks
3. The fireworks run out as normal

**Steps to reproduce (Bow and arrows**
1. Use the /unlimited command or /unl, like this: "/unlimited arrow"
2. Get a bow and shoot arrows
3. The arrows run out as normal

**Expected behavior**  
The items to be unlimited and not run out

**Screenshots**

**Comment by pop4959** [comment] 2020-02-10 02:02
Duplicate of #2974. Please search existing issues before creating another one.

**Closed as completed by pop4959** 2020-02-10 02:02 UTC
Labels: status: duplicate
