### ISSUE TITLE
SUGGESTION: Implement confirmation dialogue for `/ci`

### ISSUE THREAD

**Issue by CheatSupport** [EssentialsX/Essentials#1309] opened 2017-06-19 18:16 UTC
Just like https://github.com/drtshock/Essentials/pull/1002

but instead for /ci (clear inventory)

@SupaHam @Kakifrucht @drtshock @vemacs

**Comment by mdcfe** [comment] 2017-06-19 19:53
Please don't close and reopen issues to bump them.

This is a duplicate of #1040.

**Comment by Sikatsu** [comment] 2017-06-19 20:59
Would love to see this too! Often had issues with players performing /ci or trolling eachother to use /ci.

**Comment by CheatSupport** [comment] 2017-06-26 18:56
Agreed Sikatsu!

**Comment by mdcfe** [comment] 2018-03-29 09:10
This was added ages ago, didn't realise this was still open.

**Closed as completed by mdcfe** 2018-03-29 09:10 UTC
Labels: type: enhancement
