### ISSUE TITLE
[feature] Custom /list

### ISSUE THREAD

**Issue by Flavourized** [EssentialsX/Essentials#1868] opened 2018-02-24 19:31 UTC
I want to suggest adding a custom /list, so we dont need to use another plugin to do something so simple. The current /list in essentials allows you to organize players in /list based on their primary group. 

However, some servers (like mine) have an entire rank up system where players can have multiple groups. Their primary group probably isnt the group that /list is looking for. 

An example for this would be players who have a staff rank as well as a donator rank and a main rank. The /list will be looking for the staff ranks, but the players primary group is his main rank, so he is skipped from showing up on /list. 

I want to say make it where /list is looking for a permission, maybe essentials.list.<groupname>. This permission would be added to the groups, and then /list would check if the player has this permission. This will solve the need for changing primary group.

And then (probably goes w/o saying), keep the customtext option so we can customize how we want the command to look.

**Comment by mdcfe** [comment] 2018-02-24 20:12
Duplicate of #29.

**Closed as completed by mdcfe** 2018-02-24 20:12 UTC
