### ISSUE TITLE
Make /condense condense things like Quartz and Bone Blocks

### ISSUE THREAD

**Issue by Atticuss26** [EssentialsX/Essentials#5385] opened 2023-06-07 16:16 UTC
### Feature description

the title

### How the feature is useful

because they are expecting it to condense everything

**Comment by LaxWasHere** [comment] 2023-06-07 16:49
Please see this [answer](https://github.com/EssentialsX/Essentials/issues/3360#issuecomment-640193805) as to why EssentialsX will not condense certain materials.

**Comment by mdcfe** [comment] 2023-06-07 16:52
Duplicate of #1027, #1431, #2438, #2718, #3360... - please search for existing issues before opening new ones. As per https://github.com/EssentialsX/Essentials/issues/2718#issuecomment-518139894, this is intended behaviour and not something we will change.

You can only use `/condense` on items which have a *reversible* crafting recipe (for example, you can craft 9 iron ingots into 1 iron block **and** 1 iron block back into 9 ingots). If `/condense` ignored this, players would lose items like quartz and bone that they can't get back.

If you want to enable this on your server, you can use a plugin or datapack to add reverse crafting recipes that turns quartz and bone blocks back into their raw counterparts.

**Closed as not planned by mdcfe** 2023-06-07 16:52 UTC
Labels: type: enhancement, status: wontfix
