### ISSUE TITLE
Disable Fly per world

### ISSUE THREAD

**Issue by Sikatsu** [EssentialsX/Essentials#1895] opened 2018-03-12 14:49 UTC
I tried to disable fly in the end. So I denied the permission essentials.fly and essentials.fly.safelogin for that world. However, when I fall in the void and logout before I die and log back in, my fly is enabled. Is there anyway to prevent this?

**Comment by LaxWasHere** [comment] 2018-03-12 14:54
`/ess debug`
log out, log back in, post your entire log to https://gist.github.com

**Comment by Sikatsu** [comment] 2018-03-12 16:51
https://gist.github.com/Sikatsu/6d6ae8c56b9060ac32797b933e9f324d

**Comment by Sikatsu** [comment] 2018-03-12 16:52
This is how the permissions are setup: http://prntscr.com/iq7cnl

**Comment by LaxWasHere** [comment] 2018-03-12 16:54
You have `essentials.fly.safelogin`

Also those errors are caused by your customgui plugin.

**Comment by Sikatsu** [comment] 2018-03-12 16:58
I do, but it's set to false on the ''world2_the_end'' world. 

How would the errors be caused by the customgui plugin?

**Comment by mdcfe** [comment] 2018-03-12 16:58
Please follow the issue template. It exists for a reason and would allow us to narrow down the cause of the issue.

It is likely that your permissions plugin is not able to do per-world permissions checks at the point that EssentialsX is trying to check for the safelogin permission.

**Comment by Sikatsu** [comment] 2018-03-12 17:01
Sorry for that. I'm using luckperms.

**Comment by mdcfe** [comment] 2018-03-12 17:51
Could you post the output when logging in with both `/lp debug` and `/ess debug` enabled?

**Comment by Sikatsu** [comment] 2018-03-12 22:04
./lp debug says: https://pastebin.com/ueqcNuRF

Using these permissions: http://prntscr.com/iqc5n1

**Comment by LaxWasHere** [comment] 2018-03-12 22:10
Are you OP? Do you have '*'? 

Please give the [luckperms support](https://discord.gg/W3FzxHA) the full error.

**Comment by mdcfe** [comment] 2018-03-12 22:16
As I said, this is likely due to the fact that LP can't determine what world you're in when you may not have even spawned yet, so I doubt there's anything we can do.

You probably want to report the error with `/lp debug` to LuckPerms as Lax suggested.

**Comment by mdcfe** [comment] 2018-03-13 15:54
My proposal for a solution to this problem would be to:
* Have per-world permissions `essentials.fly.safelogin.<world>` to enable safelogin in that world
* Make `essentials.fly.safelogin` always enable safelogin in **all worlds**

This would mean you could give a group `essentials.fly.safelogin.*` then negate `essentials.fly.safelogin.noflyworld`, but assumes that we're able to know what world they're in before they log in.

We could have per-world `/fly` permissions, but that wouldn't make a whole lot of sense when the only time they would make sense is safelogin.

**Comment by Sikatsu** [comment] 2018-03-13 16:00
Sounds nice.

**Comment by mdcfe** [comment] 2020-10-02 12:59
Re-reviewing this issue (due to #3697 and concerns about whether this was a suitable fix):

> It is likely that your permissions plugin is not able to do per-world permissions checks at the point that EssentialsX is trying to check for the safelogin permission.

> this is likely due to the fact that LP can't determine what world you're in when you may not have even spawned yet

Both of these assertions had no evidence at the time as the LuckPerms debug tool wasn't functioning properly. As a result, there isn't any evidence to support whether the solution previously proposed in this comment actually makes sense, nor to determine whether #3697 is relevant to this issue.

For now I'm going to close this issue as there hasn't been enough information to solve this.

@Sikatsu If this is still an issue you're still interested in finding a solution for, please could you respond with the output of `/lp verbose on <player> & essentials.fly`? If not, feel free to ignore this issue.

**Closed as completed by mdcfe** 2020-10-02 12:59 UTC
Labels: type: problem, status: not enough info
