### ISSUE TITLE
/fspeed (/flyspeed) and /wspeed (/walkspeed) do the exact same thing as /speed does

### ISSUE THREAD

**Issue by AMDBartek** [EssentialsX/Essentials#2989] opened 2020-02-03 20:38 UTC
### Details

**Output of /ess version**

Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1618 (MC: 1.12.2)
EssentialsX version: 2.17.1.54
LuckPerms version: 5.0.39
Vault is not installed. Chat and permissions may not work.

(There is also a Vault and EssentialsX issue #2988)

**Description**  
The /fspeed and the /wspeed command do the same thing.
The /flyspeed and the /walkspeed command also do the same thing.

So I think that the /fspeed (/flyspeed) and /wspeed (/walkspeed) commands are unnecessary cause you could do /speed fly 10 or /speed walk 10

**Steps to reproduce**  
1. Do the command /fspeed 10 (The same happens with /walkspeed and /flyspeed)
2. It will then say "Set walking speed to 10 for [USERNAME]"
3. Then try to do /fspeed fly 10
4. And then it says "Set flying speed to 10 for [USERNAME]"

**Expected behavior**  
For /fspeed (/flyspeed) to affect flying speed and for /wspeed (/walkspeed) to affect walking speed

**Screenshots**

**Comment by pop4959** [comment] 2020-02-10 21:58
It looks like this is intentional. `/walkspeed` is probably meant to be used as an alias while walking, and `/flyspeed` likewise for flying. Neither is really necessary since the speed command will by default set the speed for your current movement (e.g. if you are walking, it sets your walk speed, or if you are flying, it sets your flying speed). The only sane "fix" for this would be to remove support for those aliases.

**Comment by thehydrogen** [comment] 2020-02-20 20:36
Basically what's happening is that the code doesn't know you're specifying for fly speed / walk speed when doing /fspeed or /wspeed as they're simply aliases to the regular /speed command. This has fooled me many times.

For example, if you try and do `gmc <player>` from the Console, it won't work you'd have to do `gmc c/creative <player` because it's just an alias to /gm.

**Comment by pop4959** [comment] 2020-02-20 21:12
@thehydrogen Yep, that is also exactly why this is labelled as a problem rather than a bug. It is working as intended, however the question here is whether people find these aliases useful, or if we should perhaps consider removing them to avoid this kind of confusion.

Removing them would not be a bad option in my opinion. People can always re-add aliases themselves through commands.yml if they liked using it.

**Comment by mdcfe** [comment] 2020-02-22 09:57
This is how `/fspeed` and `/wspeed` have always worked. I don't personally see any benefit to removing these aliases - people who have used EssentialsX for a long time might not have even realised that these aliases aren't the actual name for the command and will likely just find it an extra annoyance if these are removed.

Changing the command's behaviour to recognise the `f`/`w` prefix is probably better as it's more predictable without just flat out removing the command, though this still changes existing behaviour.

**Comment by ghost** [comment] 2020-02-22 21:43
+1 for changing fspeed and wspeed's behaviour to control their respective speeds.

**Comment by pop4959** [comment] 2020-03-05 05:14
Closing, but leaving as open to PR in case someone is interested in suggesting an improvement here.

**Closed as completed by pop4959** 2020-03-05 05:14 UTC
Labels: type: problem, status: open to PR
