### ISSUE TITLE
Suggestion: Add a tag to make items of kits irreparable

### ISSUE THREAD

**Issue by jsuarezl** [EssentialsX/Essentials#1365] opened 2017-07-04 01:51 UTC
Hi, I was working in a factions server with a friends and we want to make some items of kits irreparable so the players can't repair it, I don't know if is some tag yet to make this.

**Comment by YellowZaki** [comment] 2017-07-06 01:07
Just add unbreakable:true.

**Comment by mdcfe** [comment] 2017-07-06 07:51
Irreparable with `/repair`, an anvil or both?

**Comment by Shivelight** [comment] 2017-07-06 12:26
I like this suggestion, I'll go with both

**Comment by jsuarezl** [comment] 2017-07-08 20:56
Irreparable with both, or something like the nbt tag RepairCost that allows to set a custom repair cost for an item

**Comment by SupaHam** [comment] 2017-08-07 13:11
Duplicate of #377

This has been fixed in 203d656. You can grab the fix from [build 516](https://ci.drtshock.net/job/EssentialsX/) on the CI server.

**Closed as completed by SupaHam** 2017-08-07 13:11 UTC
Labels: type: enhancement
