### ISSUE TITLE
Signs become Blank

### ISSUE THREAD

**Issue by Bergyrr** [EssentialsX/Essentials#786] opened 2016-08-01 16:06 UTC
I'm running Bukkit 1.10.2
Signs don't work, when I enable them and try the sign becomes blank. I tried have essentials as the only plugin and it still didn't work. 
Current plugins: creative gates, dynmap, factions, hub that, massive core, multiverse core, per world plugin, per world inventory, sky wars, vampires, world edit, world guard.
Start up log: http://pastebin.com/ZhbJBsEr

**Comment by SupaHam** [comment] 2016-08-01 16:06
Duplicate of #687. Spigot bug, update spigot.

**Closed as completed by SupaHam** 2016-08-01 16:06 UTC
Labels: bug: confirmed, status: duplicate, status: invalid

**Comment by Bergyrr** [comment] 2016-08-02 02:02
not running spigot and bukkit is current

**Comment by SupaHam** [comment] 2016-08-02 02:05
Update craftbukkit then.

**Comment by Bergyrr** [comment] 2016-08-02 02:21
it is 1.10.2

**Comment by SupaHam** [comment] 2016-08-02 02:22
Yes but there are individual builds for each Minecraft version. Just rerun buildtools and use that jar.

**Comment by Bergyrr** [comment] 2016-08-02 02:25
get back to you after i do that

**Comment by Bergyrr** [comment] 2016-08-02 02:52
it's working thx for the help
