### ISSUE TITLE
Problem with UTF-8 / Cyrillic in messages_xx.properties

### ISSUE THREAD

**Issue by dyanakiev** [EssentialsX/Essentials#596] opened 2016-04-28 15:28 UTC
I tried many encodings ANSI too: and i get this on chat
![4](https://cloud.githubusercontent.com/assets/11967079/14868425/2bf8a818-0cd6-11e6-99e0-099b832b281a.png)
This is /bal command it need to output : "Пари: xsum."

I have this problem only with essentials no other plugin is doing this problem :cry:

Thanks!

**Comment by mbax** [comment] 2016-05-04 13:52
This is a duplicate of #409

**Closed as completed** 2017-08-28 15:38 UTC
