### ISSUE TITLE
Bug with essentials nick

### ISSUE THREAD

**Issue by SladeHazard** [EssentialsX/Essentials#3784] opened 2020-11-21 14:04 UTC
# Information

**Full output of `/ess version`:**

```
[13:59:23 INFO]: Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-33d42c8e (MC: 1.12.2)
[13:59:23 INFO]: EssentialsX version: 2.18.2.1
[13:59:23 INFO]: LuckPerms version: 5.2.32
[13:59:23 INFO]: PlaceholderAPI version: 2.10.9
[13:59:23 INFO]: Vault version: 1.7.3-b131
[13:59:23 INFO]: Citizens version: 2.0.27-SNAPSHOT (build 2153)
[13:59:23 INFO]: EssentialsXSpawn version: 2.18.2.1
[13:59:23 INFO]: ChestShop version: 3.9.3-1.12 (build 22)
```

**Server startup log:**

0 errors in startup, plugin loads fine.

**EssentialsX config:**

https://gist.github.com/SladeHazard/c01b595aadb40c71af48228ba036b133

### Details

**Description:**  

Permission bug with nicknames.

**Steps to reproduce:**  

Give the player following permissions:
essentials.nick, essentials.nick.color, essentials.nick.format
Since the latest version where multiple colour permissions were added this bug came:
player can't type this command when having all 3 perms ^ "/nick &6&ltest"

**Expected behavior:**  

Player's nickname is suppose to change to bold orange test, but instead there's an error "nicknames must be alphanumeric" however this does happen if player has those 3 permissions + essentials.nick.orange

**Console stack trace:**  

```
no errors.
```

**Screenshots:**  

not needed.

**Comment by Octol1ttle** [comment] 2020-11-21 14:19
![image](https://user-images.githubusercontent.com/61277953/99879373-81a31b00-2c2e-11eb-87cc-0ec47ec97bb0.png)
Could not reproduce on latest EssentialsX

**Comment by SladeHazard** [comment] 2020-11-21 17:01
> ![image](https://user-images.githubusercontent.com/61277953/99879373-81a31b00-2c2e-11eb-87cc-0ec47ec97bb0.png)
> Could not reproduce on latest EssentialsX

server ver : 1.12.2
and make sure ur not opped.

**Comment by SladeHazard** [comment] 2020-11-26 18:45
help!

**Comment by Xeyame** [comment] 2020-11-26 21:08
You can maybe try to give `essentials.nick.changecolors.bypass` and/or `essentials.nick.changecolors`

**Comment by SladeHazard** [comment] 2020-11-30 21:47
still dosen't work even with both of those perms.

**Comment by triagonal** [comment] 2020-12-24 11:53
I am unable to reproduce this issue while using the following:

<img width="586" alt="image" src="https://user-images.githubusercontent.com/10545540/103087012-5602be80-463a-11eb-8011-59ec9991064a.png">

Closing as neither @l1ttleO nor myself are able to reproduce this issue. This is almost certainly an issue with your permissions setup. Double-check using tools like LuckPerms verbose mode or `/ess debug` to verify that your permissions are correct.

**Closed as completed by triagonal** 2020-12-24 11:53 UTC
Labels: status: invalid
