### ISSUE TITLE
1.13 /spawn dont work

### ISSUE THREAD

**Issue by ychannes** [EssentialsX/Essentials#2083] opened 2018-07-24 16:14 UTC
Fix /spawn command and bungee money

**Comment by RikoDEV** [comment] 2018-07-26 07:29
https://github.com/EssentialsX/Essentials/issues/2081

**Comment by mdcfe** [comment] 2018-07-26 17:11
`Bungee money` is nothing to do with us.

The `/spawn` issue is a duplicate of #2080.

**Closed as completed** 2018-07-26 17:12 UTC
