### ISSUE TITLE
tppos @p

### ISSUE THREAD

**Issue by seema84** [EssentialsX/Essentials#2274] opened 2018-11-23 15:35 UTC
Server version: 1.13.2-R0.1-SNAPSHOT git-Spigot-9b4b0a2-f489f0f (MC: 1.13.2)
EssentialsX version: dev-39.182
PermissionsEx version: 1.23.4
Vault version: 1.7.1-b91
EssentialsXChat version: dev-39.182

i cant use @p with tppos in commandblocks
output: player not found

example: /tppos @p 1 2 3 0 0

**Comment by Xeyame** [comment] 2018-11-23 17:20
Looks like #2217

**Comment by BluePlastics** [comment] 2018-11-23 20:59
For now I'd suggest using something like CommandHook or PsuedoCommands.

**Comment by mdcfe** [comment] 2018-11-25 08:53
Closing as a duplicate of #2217.

**Closed as completed by mdcfe** 2018-11-25 08:53 UTC
