### ISSUE TITLE
Teleporting on top of carpets glitches you through the world

### ISSUE THREAD

**Issue by MellenIO** [EssentialsX/Essentials#3421] opened 2020-06-28 11:54 UTC
#Information

Full output of `/ess version`:
![image](https://user-images.githubusercontent.com/1464589/85946664-cd7ebc00-b93d-11ea-8db4-696ca7b81cd9.png)

**Server log:** No errors/warnings are present during the time this occurs - if there are specific things in the logfile you're looking for please let me know as I'm not keen on uploading the entire server log here.

**EssentialsX config** https://gist.github.com/MellenIO/730a1c351b77e3f19c49fbce6fdf45fb

### Help request

**Problem**
When players tp to each other, or use /home commands to a location that is slightly raised (eg: using snow, or carpets) the user seems to fall through the world and subsequently die. This only occurs on raised blocks, on slabs or full-height blocks teleports and /home works as expected.

**What I have tried**
Nothing; users on my server now just try and make sure that they don't tpa or /home to a place that has a raised block.

**Screenshots**

**Comment by triagonal** [comment] 2020-06-28 15:48
Closing as a duplicate of #2918 - this is a Minecraft bug, not an Essentials bug. Please see prior issues for more information.

**Closed as completed** 2020-06-28 15:48 UTC
Labels: status: duplicate
