### ISSUE TITLE
Error spam on console.

### ISSUE THREAD

**Issue by MithrandirCraft** [EssentialsX/Essentials#4539] opened 2021-09-18 23:09 UTC
### Type of bug

Error in console

### `/ess dump all` output

https://essentialsx.net/dump.html?id=23cbe35310554f928e2d2ab0ac5787b0

### Error log (if applicable)

https://gist.github.com/MithrandirCraft/4173c0cda9cfa0f99a2d4f8ba21cb988

### Bug description

The provided error spams on console without any aparent trigger. It spams specially during start and stop, but it can spam at any time.

### Steps to reproduce

Unknown.

### Expected behaviour

These errors shouldn't show up on console.

### Actual behaviour

The errors appear, and they're quite spammy, yes.

**Comment by Chew** [comment] 2021-09-19 01:17
Duplicate of #4342 

Try: https://github.com/EssentialsX/Essentials/issues/4342#issuecomment-877651547

**Closed as completed by Chew** 2021-09-19 01:17 UTC
Labels: bug: unconfirmed
