### ISSUE TITLE
Spawners revert to Pig when being placed

### ISSUE THREAD

**Issue by jwc65** [EssentialsX/Essentials#2437] opened 2019-02-26 21:23 UTC
### Information

Essentials Version output:

[16:19:32 INFO]: CONSOLE issued server command: /ess version
[16:19:32 INFO]: Server version: 1.8.8-R0.1-SNAPSHOT git-PaperSpigot-"4c7641d" (MC: 1.8.8)
[16:19:32 INFO]: EssentialsX version: 2.16.0.46
[16:19:32 INFO]: Vault version: 1.7.1-b91

Server log has no details when placing spawners even with Debug enabled so I haven't uploaded, no errors on startup.
Have reset config to default and enabled debug, no other changes.

I can upload both at a later date if really required. 

### Details

**Description**  

When placing Spawners they are always pig spawner

**Steps to reproduce**  

Any form of gaining spawners from Essentials, /give, /i and through Kits is what I tested

**Expected behavior**  

Spawner is given, renamed to the correct mob so data is applied correctly.
Once placed the Spawner is reverted to the default of Pig whereas should be the Spawner type. In this instance Creeper

**Screenshots**  

https://gyazo.com/0e79ce81e68b87ba9bba92b14970f605
https://gyazo.com/ebd908b2a8096bebc59181df6acc23fe

**Comment by mdcfe** [comment] 2019-02-27 11:52
Thanks for opening an issue. This is usually fixed by giving players `essentials.spawnerconvert.<mob>`. However, it looks like you don't have a (supported) permissions plugin - could you get a full **startup log**?

**Comment by jwc65** [comment] 2019-02-27 17:31
Startup log: https://gist.github.com/ipr0james/4893cfaf4a5c96f24e8eb2cddcd814bc

To test this theory, I've installed zPermissions and given myself essentials.spawnerconvert.Creeper which is the mob type I have been testing with, this doesn't seem to have made a difference and I am also op. 
I'm not sure if the method of obtaining spawners has changed with the 1.8 editions of the latest essentials. I am still using /give {player} Spawner:50 1 as I could not find documentation on how else to obtain it. 

After doing some searching, then checking for perms with debug enabled it should log that I had the perm when I came to placing the spawner, after trying to place multiple types of spawners I still don't see the debug message being thrown as if it isn't making it to this check.

**Comment by triagonal** [comment] 2019-08-08 07:42
I can't reproduce this on the following version (with LuckPerms):
```
[17:32:22 INFO]: CONSOLE issued server command: /ess version
[17:32:22 INFO]: Server version: 1.14.4-R0.1-SNAPSHOT git-Paper-162 (MC: 1.14.4)
[17:32:22 INFO]: EssentialsX version: 2.17.1.11
[17:32:22 INFO]: LuckPerms version: 4.4.1
[17:32:22 INFO]: Vault version: 1.7.2-b107
```

In all cases I used either `/i <name>spawner` or created a kit with the spawner inside, example:
```
horse:
  delay: -1
  items:
  - horsemobspawner 64 name:&rHorse_Spawner
```

When testing, I used a Horse spawner. As a default player, the spawner turned into Pig spawners upon place. However, when in a group with `essentials.spawnerconvert.*` or `essentials.spawnerconvert.horse` (tested separately) the spawner is successfully placed as a Horse spawner.

I also tested with a Creeper spawner, and it placed as a Creeper spawner when given the permission `essentials.spawnerconvert.creeper`.

I also tested with no permissions plugin at all, just as an OP with only EssentialsX installed and found that the spawners placed as their intended spawner types as well.

---

Could you please confirm if this is still an issue? It seems to be working fine in the latest builds.

**Comment by triagonal** [comment] 2019-09-25 13:00
Closing - issue appears to be fixed in latest builds (when using a supported permissions plugin). Please reply to the thread if you still require support.

**Closed as completed by triagonal** 2019-09-25 13:00 UTC
Labels: status: not enough info, bug: unconfirmed

**Comment by TerryDavis1** [comment] 2019-10-12 17:57
I am also having this issue on 1.12.2 and the original poster is on 1.8

Maybe this only effects outdated versions?

Reverting back to a really old version of essentials fixes the issue for me
