### ISSUE TITLE
Optimization code

### ISSUE THREAD

**Issue by Sitmobedaf** [EssentialsX/Essentials#728] opened 2016-07-11 11:55 UTC
Hi drtshock, please, optimise section in EssentialsSpawn.
This is the only weak spot in Essentials at bot attacks.
http://img10.lostpic.net/2016/07/11/e3c90753b3192aaf3466885c838131cd.jpg

**Comment by SupaHam** [comment] 2016-07-11 13:30
What version of Essentials and Spigot are you using?

**Comment by Kakifrucht** [comment] 2016-07-11 14:09
Do your players by any chance have lots of homes? I know that this can cause issues, since Essentials rewrites the whole file after every teleport which takes longer with many homes.

**Comment by SupaHam** [comment] 2016-07-11 14:14
This has **should** be fixed in 04f1428. You can grab the fix from [build 392](https://ci.drtshock.net/job/EssentialsX/) on the CI server.

Thanks @Kakifrucht.

Please confirm whether this fixes the issue in a day or so @Sitmobedaf

**Comment by Sitmobedaf** [comment] 2016-07-11 15:34
Is actual. I use EssentialsX b-393 and PaperSpigot b-813

http://img10.lostpic.net/2016/07/11/aafa25c8cc1428c5fbe4bfe64a76d881.jpg

**Comment by Sitmobedaf** [comment] 2016-07-11 15:40
I'm probably wrong. New timings poorly understood for me https://timings.aikar.co/v2/?id=2f9e4dc897c14032bebd58dad1b4f35c&section=lag#21_

**Comment by SupaHam** [comment] 2016-07-11 15:49
I was about to say that's impossible... With 392+ it does even less than it did before. There must another plugin interfering. What Essentials does is it teleports a player to a location. When that happens, the PlayerTeleportEvent is sent to all other plugins loaded. At that point in time, Essentials is still waiting on those plugins to do their code before it stops executing its own. So although it says Essentials as being very slow, that is very likely to be caused by other plugins.

**Closed as completed by SupaHam** 2016-07-11 15:49 UTC
Labels: status: invalid
