### ISSUE TITLE
/time set commands not functioning on command blocks

### ISSUE THREAD

**Issue by DrWolfyLords** [EssentialsX/Essentials#3732] opened 2020-10-14 23:29 UTC
All commands related to time adjustments are met with "Error: null".
![image](https://user-images.githubusercontent.com/17698576/96056313-19953400-0e3b-11eb-864b-6f91395ab047.png)

**Comment by triagonal** [comment] 2020-10-14 23:30
Duplicate of #3621.

This was fixed in #3622. Download the newest version of EssentialsX [here](https://essentialsx.net/downloads.html).

**Closed as completed by triagonal** 2020-10-14 23:30 UTC
Labels: bug: confirmed, status: duplicate

**Comment by pop4959** [comment] 2020-10-14 23:36
@DrWolfyLords There isn't any reason to hide your post when it's closed -- it just makes it more annoying to search back through old issues.

Hope the latest version works for you. 😃
