### ISSUE TITLE
Join/quit message not disabling for custom messages

### ISSUE THREAD

**Issue by Ironic8b498** [EssentialsX/Essentials#2289] opened 2018-12-05 14:30 UTC
### Information

**Full output of `/ess version`**:

```
09:12:38] [Server thread/INFO]: CONSOLE issued server command: /ess version
--
[09:12:38] [Server thread/INFO]: Server version: 1.13.2-R0.1-SNAPSHOT git-Spigot-a1f2566-282dad1 (MC: 1.13.2)
[09:12:38] [Server thread/INFO]: EssentialsX version: 2.15.0.55
[09:12:38] [Server thread/INFO]: LuckPerms version: 4.3.39
[09:12:38] [Server thread/INFO]: Vault version: 1.7.1-b91
[09:12:38] [Server thread/INFO]: EssentialsXSpawn version: 2.15.0.55
```

**Server log**: https://gist.github.com/Ironic8b498/c861d108f666c609c0cf444218db90bc

**EssentialsX config**: https://gist.github.com/Ironic8b498/592d2bc985f8109f6e64edab75bc745f

### Details

**Description**  
custom-join-message: "" display an blank line in chat
custom-quit-message: "" display an blank line in chat
essentials.silentquit and essentials.silentjoin still get blank line if using custom messages

custom-join-message: "none" & custom-quit-message: "none" you get the spigot default join/leave message.
essentials.silentquit and essentials.silentjoin works for no messages or blank line in chat.

If I wanted to use custom messages I can't due to it not working

**Steps to reproduce**  

**Expected behavior**  

**Screenshots**

**Comment by mdcfe** [comment] 2018-12-06 13:57
Thanks for filing a bug report.

> essentials.silentquit and essentials.silentjoin still get blank line if using custom messages

According to [your config](https://gist.github.com/Ironic8b498/592d2bc985f8109f6e64edab75bc745f#file-config-yml-L410), you don't have `allow-silent-join-quit` enabled, so this will happen. Set that option to `true` to use `silentjoin` and `silentquit`.

---

Unfortunately, this is a duplicate of #991.

**Closed as completed** 2018-12-06 13:57 UTC
Labels: type: question
