### ISSUE TITLE
Blocking powertools?

### ISSUE THREAD

**Issue by FrankHeijden** [EssentialsX/Essentials#1586] opened 2017-10-08 21:21 UTC
EssentialsX version (`/essentials`): 
b530
Server software (`/version`): 
git-Spigot-93e20b3-e8b6e4f (MC: 1.12.2)

Heya,
Whenever i try to block powertools using WorldGuard or GriefPrevention claims, essentials still let them bypass the block.

I used the command `/rg flag {region} blocked-cmds /home,/spawn` for example to block some commands in a worldguard region, but when a user has a powertool of `/home` on a block, they are still allowed to process the command.

Is there a way this could be fixed/done?

Thanks 👍

**Comment by emanh1** [comment] 2017-10-19 09:26
Add /powertool to the blocked-cmds

**Comment by FrankHeijden** [comment] 2017-10-19 10:25
That wouldn’t work, as people could then set a powerfool somewhere else and still execute the powertool

**Comment by DrewAMitchell** [comment] 2017-12-17 07:58
https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java#L633
The problem is when getServer().dispatchCommand(user.getBase(), command) is called, this can be fixed by calling .chat(), as that causes a PlayerCommandPreprocessEvent that WorldGuard catches.
Opinions? @md678685 
I guess you could either call a PlayerCommandPreprocessEvent or just leave it how it is.

**Comment by mdcfe** [comment] 2017-12-17 11:09
@Drkmaster83 If it *is* the case that `dispatchCommand` doesn't fire a `PlayerCommandPreprocessEvent`, then I can see why the two approaches above could make sense. This would allow power tools to respect EssentialsX features like mutes, command cooldowns and social spy, while also letting other plugins block powertools.

However, I prefer the idea of using `Player.chat` over firing our own PlayerCommandPreprocessEvent, as I've encountered a few issues where custom events that extend the API are fired without fully implementing the event, causing errors when EssentialsX tries to handle them which are incorrectly traced back to EssentialsX.

@EssentialsX/contributors Thoughts?

**Comment by DrewAMitchell** [comment] 2017-12-17 18:09
@md678685 Yeah, I just didn't know if using `dispatchCommand` was purposeful or not, as `Player.chat` was used for the command starting with `c:`. Just wanted to bring light onto the problem, I did some research and I could probably test with `dispatchCommand` and the event.

One thing's for sure, it exists as an issue.

**Comment by NewBestX** [comment] 2018-01-21 16:01
Any updates on this? I ran into the same issue. I am really looking forward for this to be fixed.

**Comment by MDMCK10** [comment] 2018-11-04 13:35
Is there an ETA on when this will be fixed? I've recently ran into this exact same issue with not being able to block powertool commands.

**Closed as completed** 2019-04-17 06:33 UTC
Labels: type: enhancement

**Comment by mdcfe** [comment] 2019-04-17 07:54
This has now been fixed - you can download the latest version from the [build server](https://ci.ender.zone/job/EssentialsX).
