### ISSUE TITLE
Trade sign problem

### ISSUE THREAD

**Issue by VceHytaleProject** [EssentialsX/Essentials#2737] opened 2019-08-12 21:56 UTC
### Information

Hi, i'm having some issue with the [trade] sign in Essentials 2.17.1.0
The buy and sell sign work perfectly but the trade sign won't work...
I set the sign like this:

[trade]
$10
1 dirt:10

I get no answer in chat, the [trade] on the first line is still red and the console give me this output:

**Server log:**

12.08 23:39:50 [Server] INFO ... 17 more
12.08 23:39:50 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_211]
12.08 23:39:50 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_211]
12.08 23:39:50 [Server] INFO at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source) ~[?:?]
12.08 23:39:50 [Server] INFO at com.earth2me.essentials.signs.SignBlockListener.onSignSignChange(SignBlockListener.java:130) ~[?:?]
12.08 23:39:50 [Server] INFO at com.earth2me.essentials.signs.EssentialsSign.onSignCreate(EssentialsSign.java:58) ~[?:?]
12.08 23:39:50 [Server] INFO at com.earth2me.essentials.signs.SignTrade.onSignCreate(SignTrade.java:29) ~[?:?]
12.08 23:39:50 [Server] INFO at com.earth2me.essentials.signs.SignTrade.getTrade(SignTrade.java:244) ~[?:?]
12.08 23:39:50 [Server] INFO at com.earth2me.essentials.signs.EssentialsSign.getItemStack(EssentialsSign.java:350) ~[?:?]
12.08 23:39:50 [Server] INFO at com.earth2me.essentials.api.IItemDb.getFromLegacy(IItemDb.java:138) ~[?:?]
12.08 23:39:50 [Server] INFO at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_211]
12.08 23:39:50 [Server] INFO at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_211]
12.08 23:39:50 [Server] INFO at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_211]
12.08 23:39:50 [Server] INFO Caused by: java.lang.NumberFormatException: For input string: "dirt"
12.08 23:39:50 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
12.08 23:39:50 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:820) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:903) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:910) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInUpdateSign.a(SourceFile:10) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInUpdateSign.a(SourceFile:44) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2381) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO org.bukkit.event.EventException: null
12.08 23:39:50 [Server] Server thread/ERROR Could not pass event SignChangeEvent to Essentials v2.17.1.0

Full output of `/ess version`:

Any advice?

**Comment by mdcfe** [comment] 2019-08-13 13:33
Could you post the full output of `/ess version`?

**Comment by mdcfe** [comment] 2019-08-13 14:13
In addition, could you update to the [latest build](https://essentialsx.netlify.com/downloads.html) to see if the issue is resolved?

**Comment by mbax** [comment] 2019-08-13 15:11
Stacktrace oriented the correct direction:

```
12.08 23:39:50 [Server] Server thread/ERROR Could not pass event SignChangeEvent to Essentials v2.17.1.0
12.08 23:39:50 [Server] INFO org.bukkit.event.EventException: null
12.08 23:39:50 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2381) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInUpdateSign.a(SourceFile:44) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInUpdateSign.a(SourceFile:10) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:910) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:903) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:820) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
12.08 23:39:50 [Server] INFO Caused by: java.lang.NumberFormatException: For input string: "dirt"
12.08 23:39:50 [Server] INFO at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_211]
12.08 23:39:50 [Server] INFO at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_211]
12.08 23:39:50 [Server] INFO at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_211]
12.08 23:39:50 [Server] INFO at com.earth2me.essentials.api.IItemDb.getFromLegacy(IItemDb.java:138) ~[?:?]
12.08 23:39:50 [Server] INFO at com.earth2me.essentials.signs.EssentialsSign.getItemStack(EssentialsSign.java:350) ~[?:?]
12.08 23:39:50 [Server] INFO at com.earth2me.essentials.signs.SignTrade.getTrade(SignTrade.java:244) ~[?:?]
12.08 23:39:50 [Server] INFO at com.earth2me.essentials.signs.SignTrade.onSignCreate(SignTrade.java:29) ~[?:?]
12.08 23:39:50 [Server] INFO at com.earth2me.essentials.signs.EssentialsSign.onSignCreate(EssentialsSign.java:58) ~[?:?]
12.08 23:39:50 [Server] INFO at com.earth2me.essentials.signs.SignBlockListener.onSignSignChange(SignBlockListener.java:130) ~[?:?]
12.08 23:39:50 [Server] INFO at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source) ~[?:?]
12.08 23:39:50 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_211]
12.08 23:39:50 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_211]
12.08 23:39:50 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
12.08 23:39:50 [Server] INFO ... 17 more
```

**Comment by VceHytaleProject** [comment] 2019-08-13 19:21
> In addition, could you update to the [latest build](https://essentialsx.netlify.com/downloads.html) to see if the issue is resolved?

Ty it worked

**Comment by mdcfe** [comment] 2019-08-13 22:05
This has been fixed in the [latest build](https://essentialsx.netlify.com/downloads.html).

**Closed as completed** 2019-08-13 22:05 UTC
Labels: help wanted, status: not enough info, bug: unconfirmed
