### ISSUE TITLE
EssentialsAntiBuild Unknown items

### ISSUE THREAD

**Issue by lantren** [EssentialsX/Essentials#2238] opened 2018-10-29 11:41 UTC
### Information

**Server log**: https://gist.github.com/lantren/b77bb0bcf41105ae9165a5c4a02c1cd3

**EssentialsX config**: https://gist.github.com/lantren/534e7deff86efaca70446228b945fcaa

### Details

**Description**  

I get this error in startup. I also get it if i DELETE the existing config.yml,  items.jsom AND items.csv and let essentialsX create brand new files 

[07:22:06 INFO]: [EssentialsAntiBuild] Enabling EssentialsAntiBuild vdev-29.155
[07:22:06 ERROR]: §4Unknown item 10 in protect.alert.on-placement list.
[07:22:06 ERROR]: §4Unknown item 11 in protect.alert.on-placement list.
[07:22:06 ERROR]: §4Unknown item 46 in protect.alert.on-placement list.
[07:22:06 ERROR]: §4Unknown item 327 in protect.alert.on-placement list.
[07:22:06 ERROR]: §4Unknown item 327 in protect.alert.on-use list.
[07:22:06 ERROR]: §4Unknown item 10 in protect.blacklist.placement list.
[07:22:06 ERROR]: §4Unknown item 11 in protect.blacklist.placement list.
[07:22:06 ERROR]: §4Unknown item 46 in protect.blacklist.placement list.
[07:22:06 ERROR]: §4Unknown item 327 in protect.blacklist.placement list.
[07:22:06 ERROR]: §4Unknown item 327 in protect.blacklist.usage list.
**Full output of `/ess version`**:
[07:31:59 INFO]: CONSOLE issued server command: /ess version
[07:31:59 INFO]: Server version: 1.13.2-R0.1-SNAPSHOT git-Spigot-a1ba5fe-3359cb1 (MC: 1.13.2)
[07:31:59 INFO]: EssentialsX version: dev-29.155
[07:31:59 INFO]: LuckPerms version: 4.2.58
[07:31:59 INFO]: Vault version: 1.5.6-b49
[07:31:59 INFO]: EssentialsXProtect version: dev-29.155
[07:31:59 INFO]: EssentialsXChat version: dev-29.155
[07:31:59 INFO]: EssentialsXAntiBuild version: dev-29.155
[07:31:59 INFO]: EssentialsXSpawn version: dev-29.155
**Steps to reproduce**  
run server and observed startup messages

**Expected behavior**  
I don't expect to see see error messages in start up 

**Screenshots**

**Comment by mdcfe** [comment] 2018-10-29 11:45
Thanks for filing a report! AntiBuild hasn't been updated to support the 1.13 item system yet, so these errors are to be expected.

**Comment by lantren** [comment] 2018-10-29 11:54
That's what i thought. The 1.13.x support thread listed  json/csv compatibility, but this seemed a bit different so I thought i'd report it anyway.  Thanks!

**Comment by mdcfe** [comment] 2018-11-19 13:16
@lantren Could you try updating to the latest [experimental build](//ci.ender.zone/job/EssentialsX-Experimental/lastSuccessfulBuild)? You'll need to update your `config.yml` to use [Material enum names](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html#enum.constant.summary) instead of item IDs - see [the default config](https://github.com/EssentialsX/Essentials/blob/1.13/Essentials/src/config.yml#L819-L841) as an example.

**Comment by lantren** [comment] 2018-11-19 14:18
Great , It functions as expected.  It also displays properly in-game but the console text has color codes and isn't displaying properly.  
 
"§3[playername] §r used: §6 LAVA_BUCKET at: Minecrack,355,85,190

**Comment by mdcfe** [comment] 2018-12-06 18:01
> Great , It functions as expected. It also displays properly in-game [...]

Good to hear that AntiBuild is now working!

> [...] but the console text has color codes and isn't displaying properly.
>
> "§3[playername] §r used: §6 LAVA_BUCKET at: Minecrack,355,85,190

This might be caused by your system or terminal setup. Does it happen with other messages from EssentialsX itself?

**Comment by lantren** [comment] 2018-12-06 19:42
> > Great , It functions as expected. It also displays properly in-game [...]
> 
> Good to hear that AntiBuild is now working!
> 
> > [...] but the console text has color codes and isn't displaying properly.
> > "§3[playername] §r used: §6 LAVA_BUCKET at: Minecrack,355,85,190
> 
> This might be caused by your system or terminal setup. Does it happen with other messages from EssentialsX itself?

Not that I've noticed but other plugins have colored text console messages that display properly.

**Comment by mdcfe** [comment] 2018-12-22 16:54
Closing as the main issue here is solved.

If the issue with console messages is still occurring, could you open a new bug report?

**Closed as completed by mdcfe** 2018-12-22 16:54 UTC
Labels: bug: confirmed, help wanted
