### ISSUE TITLE
Essentials Login Console Issue

### ISSUE THREAD

**Issue by DebuffPvP** [EssentialsX/Essentials#5006] opened 2022-07-21 04:40 UTC
### Type of bug

Other unexpected behaviour

### Error log (if applicable)

https://www.toptal.com/developers/hastebin/afulilisal.properties

### Bug description

This happened to me upon login and it's random and i forgot to do the dump command 

### Steps to reproduce

I don't know but was wondering if you guys may know what it means

### Expected behaviour

To not do it

### Actual behaviour

it does it

**Comment by pop4959** [comment] 2022-07-21 04:48
Duplicate of #4342

**Closed as completed by pop4959** 2022-07-21 04:48 UTC
Labels: status: duplicate

**Comment by DebuffPvP** [comment] 2022-07-21 04:59
that's someone else that posted that?

**Comment by pop4959** [comment] 2022-07-21 05:11
> that's someone else that posted that?

It's a duplicate because it's the same issue, not because you posted it. That's fine, but generally only one issue is kept open to make things easier to track.
