### ISSUE TITLE
Default worth.yml is not parsing as intended

### ISSUE THREAD

**Issue by zzApotheosis** [EssentialsX/Essentials#3770] opened 2020-11-12 05:04 UTC
### Information

**Full output of `/ess version`:**

```
Server version: 1.16.4-R0.1-SNAPSHOT git-Paper-263 (MC: 1.16.4)
EssentialsX version: 2.18.1.32
LuckPerms version: 5.2.26
Vault version: 1.7.3-b131
EssentialsXSpawn version: 2.18.1.32
EssentialsXChat version: 2.18.1.32
```

**Server startup log:**

https://gist.github.com/zzApotheosis/75ac2c8fa979ab5bbc7fe30188521657

**EssentialsX config:**

https://gist.github.com/zzApotheosis/75ac2c8fa979ab5bbc7fe30188521657

### Details

**Description:**  

Using the default worth.yml, the general fields near the top of the file are not being parsed correctly on startup (config loading). Logs, wool, leaves, and saplings do not have any value with the `/worth`, or `/sell` commands.

I've forked the project to see if I can take a look myself (this would be my very first open-source project contribution ever!).

**Steps to reproduce:**  

The issue can be seen by holding any log, any wool, any leaves, or any saplings and using `/worth hand` or `/sell hand` to see they do not have any value.

**Expected behavior:**  

Items whose worth is defined in worth.yml should be parsed correctly and pass data properly to the `/worth` and `/sell` commands.

**Screenshots:**  

![2020-11-11_23 00 39](https://user-images.githubusercontent.com/11908793/98897859-f4173c80-2471-11eb-9232-2bf8fab4f316.png)

**Comment by pop4959** [comment] 2020-11-15 22:30
Some items have been renamed over the last few Minecraft versions (especially after 1.13) and I think the worth.yml is used for all versions between Minecraft 1.8-1.16, unlike with items.csv and items.json which are used for 1.8-1.12 and 1.13-1.16+ respectively.

So the cause of this issue could be related simply to naming. Feel free to PR changes if you find a way to update the file, which may include adding mappings for both old and new item names. Just make sure to test that your changes work on both 1.8 and 1.16. Thanks!

**Comment by JRoy** [comment] 2021-01-11 05:51
Closing due to staleness and this largely being an alias issue. OP may open a PR if they'd like

**Closed as completed by JRoy** 2021-01-11 05:51 UTC
Labels: bug: unconfirmed
