### ISSUE TITLE
Problem with /whois

### ISSUE THREAD

**Issue by Xezzur** [EssentialsX/Essentials#2215] opened 2018-10-20 12:49 UTC
### Information

Full output of `/ess version`:
[14:33:46 INFO]: CONSOLE issued server command: /ess version
[14:33:46 INFO]: Server version: 1.13.1-R0.1-SNAPSHOT git-Spigot-f6a273b-db10914 (MC: 1.13.1)
[14:33:46 INFO]: EssentialsX version: 2.15.0.52
[14:33:46 INFO]: LuckPerms version: 4.3.2
[14:33:46 INFO]: Vault version: 1.7.1-b91
[14:33:46 INFO]: EssentialsXSpawn version: 2.15.0.52
[14:33:46 INFO]: EssentialsXGeoIP version: 2.15.0.52
[14:33:46 INFO]: EssentialsXChat version: 2.15.0.52
[14:33:46 INFO]: EssentialsXAntiBuild version: 2.15.0.52
[14:33:46 INFO]: EssentialsXProtect version: 2.15.0.52

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):
https://gist.github.com/Xezzur/ace872d3178cd7db784643cf548e753d

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)):
https://gist.github.com/Xezzur/6da0b005d51a144b8d1e2a1b0bdd595d
https://gist.github.com/Xezzur/0bb720af1f96fcd720d62dffb09c0f69

### Details

Describe your issue here:
Hello,
after using a command /whois XXX my console shows up problem:
[14:36:20 INFO]: Player2 issued server command: /whois Player1
[14:36:20 ERROR]: Command whois failed:
java.lang.NoSuchFieldError: PLAY_ONE_TICK
at com.earth2me.essentials.commands.Commandwhois.run(Commandwhois.java:39) ~[?:?]
at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:162) ~[?:?]
at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:157) ~[?:?]
at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:522) ~[?:?]
at com.earth2me.essentials.Essentials.onCommand(Essentials.java:435) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Spigot-f6a273b-db10914]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[minecraft_server.jar:git-Spigot-f6a273b-db10914]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699) ~[minecraft_server.jar:git-Spigot-f6a273b-db10914]
at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1646) ~[minecraft_server.jar:git-Spigot-f6a273b-db10914]
at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1481) ~[minecraft_server.jar:git-Spigot-f6a273b-db10914]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[minecraft_server.jar:git-Spigot-f6a273b-db10914]
at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[minecraft_server.jar:git-Spigot-f6a273b-db10914]
at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[minecraft_server.jar:git-Spigot-f6a273b-db10914]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [minecraft_server.jar:git-Spigot-f6a273b-db10914]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [minecraft_server.jar:git-Spigot-f6a273b-db10914]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [minecraft_server.jar:git-Spigot-f6a273b-db10914]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [minecraft_server.jar:git-Spigot-f6a273b-db10914]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [minecraft_server.jar:git-Spigot-f6a273b-db10914]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]

**Comment by mdcfe** [comment] 2018-10-20 14:01
Duplicate of #2115. If you're running 1.13.x, use the [experimental builds](https://ci.ender.zone/job/EssentialsX-Experimental/), where this issue has already been fixed.

**Closed as completed by mdcfe** 2018-10-20 14:01 UTC
