### ISSUE TITLE
EssentialsX Teleportation Causes 8 Second Lag Spike

### ISSUE THREAD

**Issue by TheMattVid** [EssentialsX/Essentials#2958] opened 2020-01-20 22:32 UTC
### Information

**Full output of `/ess version`**:

```
Server version: 1.15.1-R0.1-SNAPSHOT git-Paper-57 (MC: 1.15.1)
EssentialsX version: 2.17.1.52
LuckPerms version: 5.0.39
Vault version: 1.7.2-b107
EssentialsXChat version: 2.17.1.52
EssentialsXSpawn version: 2.17.1.52
You are running an unsupported server version!
```

**EssentialsX config**: https://gist.github.com/TheMattVid/00e355adbfa338152e48884f664911d5

### Details

**Description**  
When players runs an Essentials command (I think only the teleportation ones), the server freezes for about 8 seconds. The tick takes about that long to process.

**Steps to reproduce**  
Run an EssentialsX teleportation command. (I'm not sure, but the problem might only happen after the server has been running for at least a few hours.)

**Expected behavior**  
No lag upon running an Essentials command.

**Additional Info**  
This problem does not occur on my server when I run EssentialsX version 2.17.1.27
Here is a profiler taken of a sample of ticks when this problem occurs:
https://sparkprofiler.github.io/#65yDiZYO8r

**Comment by mdcfe** [comment] 2020-01-21 19:35
Duplicate of #2861. We're working on improving this, but if your server takes 8 seconds to load in one area, you may need to consider upgrading your server hardware.

**Closed as completed by mdcfe** 2020-01-21 19:35 UTC
Labels: status: duplicate

**Comment by TheMattVid** [comment] 2020-01-22 00:23
I'd agree, but the 8 second spike issue happened with one version of EssentialsX and not another.

**Comment by mdcfe** [comment] 2020-01-22 06:20
Chunk loading in 1.14+ is considerably slower and less consistent than before. As your profile report shows, most of that time is spent waiting for the chunk loading thread to finish loading that chunk, which can take anywhere from a couple milliseconds to over 10 seconds. Both 2.17.1.27 and the latest build currently block and wait for the chunk to load before teleporting as this was the default prior to 1.13, so any difference between the versions is likely coincidental.
