### ISSUE TITLE
Teleport system conflict bug?

### ISSUE THREAD

**Issue by PachiMc** [EssentialsX/Essentials#2788] opened 2019-09-16 15:32 UTC
### Information

Server version: 1.14.4-R0.1-SNAPSHOT git-Spigot-94af569-6ddeb98 (MC: 1.14.4)
EssentialsX version: 2.17.1.0
LuckPerms version: 4.4.1
Vault version: 1.7.2-b107
EssentialsXProtect version: 2.17.1.0
EssentialsXSpawn version: 2.17.1.0

config: https://justpaste.it/37j64
No crash/error/lag
all plugins from the screenshot are in the last version for 1.14
**Problem**
The teleport system is bug in random times, for example when you put home/tpa or spawn, after the teleport delay (3 second on my config) finish, sometimes work and other no. i fix it reloading the server and work for a whille again.
i am 80% sure is a plugin causing it and 20% is a bug of ess, because i dont remember this happend before, not sure which one could cause it.
my guess is anticheat matrix but not sure, because i dont know how to recreate it
**What I have tried**
testing witthout some plugins 
tried essentials 2.17.1.15 too
reset config too

**Screenshots**
![image](https://user-images.githubusercontent.com/24804138/64971581-495fba00-d87e-11e9-9ff3-5b0ab69358ee.png)

**Comment by triagonal** [comment] 2019-09-17 15:22
Thanks for reporting! We're aware of the issue but don't have a reliable way to reproduce the issue yet. Your data will help us move closer to a fix 😄 

Possible duplicate of #2648.

**Comment by PachiMc** [comment] 2019-09-17 19:41
> Thanks for reporting! We're aware of the issue but don't have a reliable way to reproduce the issue yet. Your data will help us move closer to a fix 😄
> 
> Possible duplicate of #2648.

Thanks!, i am almost sure the ops player dont get this problem, only default player, so probaby anticheat!

**Comment by PachiMc** [comment] 2019-09-18 18:04
> Thanks for reporting! We're aware of the issue but don't have a reliable way to reproduce the issue yet. Your data will help us move closer to a fix 😄
> 
> Possible duplicate of #2648.

i fixed it disabing delay!

**Comment by pop4959** [comment] 2019-10-27 03:10
Closing this since it is indeed a duplicate -- although this is referenced in the original issue, so we will be sure to look here in case we want to use the information you provided for debugging purposes.

**Closed as completed by pop4959** 2019-10-27 03:10 UTC
Labels: status: duplicate
