### ISSUE TITLE
Constant errors in console (Could not pass event BlockPistonRetractEvent to Essentials v2.17.0.0)

### ISSUE THREAD

**Issue by s1h4d0w** [EssentialsX/Essentials#2662] opened 2019-07-09 14:56 UTC
**I'll preface this with the fact that I know this error has been reported before. I found the other issues detailing this, but [the reply there said it was fixed in the latest 1.14 build](https://github.com/EssentialsX/Essentials/issues/2529#issuecomment-496179431). However I'm on 1.12.2 and am using the latest version of EssentialsX, 2.17.0. I really need a fix for this because it's making the server console unusable. I mainly manage my server through that.**

### Information

**Full output of `/ess version`**:

```
[16:46:52 INFO]: Server version: 1.12.2-R0.1-SNAPSHOT git-Spigot-79a30d7-acbc348 (MC: 1.12.2)
[16:46:52 INFO]: EssentialsX version: 2.17.0.0
[16:46:52 INFO]: PermissionsEx version: 1.23.4
[16:46:52 INFO]: Vault version: 1.7.2-b107
[16:46:52 INFO]: EssentialsXSpawn version: 2.17.0.0
[16:46:52 INFO]: You are running unsupported plugins!
```

**Server log**: https://gist.github.com/s1h4d0w/c6d1862be6f9a45352cf74400cb3e32e

**EssentialsX config**: https://gist.github.com/s1h4d0w/ae3a7a1bae97e39fec684a6d990478ef

### Details

**Description**  
Constant piston errors because a users has made an automatic farm

**Steps to reproduce**  
Every time his farm runs the error shows, I don't know much redstone so I don't know how it works. This is the tutorial he used: https://www.youtube.com/watch?v=2VbkFTFjFww

**Expected behavior**  
No errors

**Screenshots**  
![2019-07-09_16 52 48](https://user-images.githubusercontent.com/5654654/60899038-15f32480-a26a-11e9-830a-60c39cc7cd3e.png)

**Comment by mdcfe** [comment] 2019-07-09 15:16
This is a duplicate of #2635, which concerns 1.13 and below. It is not the same issue as #2529, which is solely related to 1.14+.

> `EssentialsX version: 2.17.0.0`

You aren't running the latest build of EssentialsX - download it from the [build server](https://ci.ender.zone/job/EssentialsX).

**Closed as completed by mdcfe** 2019-07-09 15:16 UTC
