### ISSUE TITLE
Tridents vs /pweather storm

### ISSUE THREAD

**Issue by Scorpionvssub** [EssentialsX/Essentials#2126] opened 2018-08-17 18:02 UTC
![image](https://user-images.githubusercontent.com/12249763/44281493-4435d300-a258-11e8-9f68-f6e2c2709d7d.png)

![image](https://user-images.githubusercontent.com/12249763/44284655-c75c2680-a262-11e8-95b8-2ae53b53f07f.png)

When a player has the riptide enchant on a trident which lets you go faster in rain, it will also allow the usage of this mechanic when their personal weather is set to storm.

My expectation:
That a player with a trident can only perform these actions when the actuall world is raining while still being able to use the item normally during the day

**Comment by mdcfe** [comment] 2018-08-17 20:34
This sounds like a vanilla/CB/Spigot bug - all Essentials does is tell the server to set the player's weather.

**Comment by SupaHam** [comment] 2018-08-18 17:40
Although this has nothing to do with EssentialsX, this issue is invalid. I've checked and riptide only works based on the world raining, not the player raining.

Edit: Also, if you are in water, it will trigger riptide, even if it is not raining.

**Comment by PiggiesGoSqueal** [comment] 2019-02-05 06:02
@SupaHam Well, 2 of my players reported the same issue @Scorpionvssub reported. /pweather allows players to have infinite riptide with trident + elytra. And /pweather is an Essentials / EssentialsX command I thought so... how does it not have to do with EssentialsX? I **don't** mean this in a smartass way, I mean that I am confused so could you please elaborate?

**Comment by mdcfe** [comment] 2019-02-05 09:46
@pinkpig3777 EssentialsX tells Bukkit to change that player's weather. Riptide behaviour should be based on world weather, not player weather, so if this has somehow broken then it's down to the server not implementing this properly.

In addition, can you actually reliably replicate this yourself?

**Comment by PiggiesGoSqueal** [comment] 2019-02-07 00:51
Ah okay @md678685.

**Deleted my old message has it had incorrect information.**

**UPDATE:**
I can replicate the issue after disabling a CMI plugin feature that disables riptide in storms. So to be clear, I CAN use /pweather storm then riptide + elytra to gain speed (while global weather is clear).

Also, worth noting that if you are familiar with CMI, it is not conflicting with EssentialsX. I use them alongside each other. I use Essentials for most commands then use CMI for other additional features.

**Comment by mdcfe** [comment] 2019-02-07 08:03
Can you replicate this **without having CMI installed**? If not, CMI is interfering.

**Comment by triagonal** [comment] 2019-02-07 12:30
I was able to replicate this with only EssentialsX installed on 1.13.2 Paper and Spigot installs
```
[23:04:41 INFO]: Server version: 1.13.2-R0.1-SNAPSHOT git-Paper-485 (MC: 1.13.2)
[23:04:41 INFO]: EssentialsX version: 2.16.0.34
[23:04:41 INFO]: Vault is not installed. Chat and permissions may not work.
```
```
[23:23:51 INFO]: Server version: 1.13.2-R0.1-SNAPSHOT git-Spigot-f56e2e7-b634e05 (MC: 1.13.2)
[23:23:51 INFO]: EssentialsX version: 2.16.0.34
[23:23:51 INFO]: Vault is not installed. Chat and permissions may not work.
```
I recorded the results (on Paper, but both cases were identical): https://youtu.be/GD2gV-frC8M
- 00:00 - 00:15: normal behaviour, world weather set to rain, riptide/elytra works as expected
- 00:20 - 00:40: world weather set to sun, pweather to storm, riptide/elytra works, but part of the audio (trident release) is missing for some reason 
- 00:50 - 1:10: world weather set to storm, pweather to sun, trident animation and audio happens, but riptide is not triggered.

Seems like a Bukkit/Spigot bug to me.

**Comment by mdcfe** [comment] 2019-02-07 14:44
I've checked how the game implements the riptide effect, and it doesn't appear to check the player weather at any point - it specifically checks the world's weather, not the player's weather. I'm not sure if this caused by the client not being aware that riptide should be disabled?

**Comment by pop4959** [comment] 2019-04-23 03:22
Since this doesn't seem to be within the scope of Essentials to fix I'm going to go ahead and close this. If that is a mistake please feel free to re-open it, but I see that most points to this being some sort of other clientside/serverside issue.

**Closed as completed by pop4959** 2019-04-23 03:22 UTC
Labels: status: invalid

**Comment by Vresod** [comment] 2019-09-01 21:07
The reason that riptide would activate is that the client _thinks_ that it is raining and therefore would allow riptide to activate, but the server does not think it is raining and would therefore not allow the animation or sound to happen. It's not detected as invalid movement because riptide movement is similar to elytra movement with fireworks.

this is just a guess however
