### ISSUE TITLE
Creation of new signs doesn't work

### ISSUE THREAD

**Issue by Zabuden** [EssentialsX/Essentials#870] opened 2016-09-04 17:42 UTC
I have an issue with the creation of new essentials signs. I have enable sign use in the config file for the appropriate signs by removing the # in front of it. Additionally, old signs that I already had on the server from a while ago still work. However, when I create a new sign it always ends up blank. Regardless of what type of sign it is (Warp, Buy, Sell, Heal, etc.) it always ends up blank. When I use the wrong format it provides me with errors, but when it is done correctly nothing happens except the placement of a blank sign

I have used the correct syntax for the sign:
[Warp]
Warptower

**Comment by SupaHam** [comment] 2016-09-04 20:16
Duplicate of #687. Update spigot.

**Closed as completed by SupaHam** 2016-09-04 20:16 UTC
Labels: status: duplicate
