### ISSUE TITLE
/down /bottom command

### ISSUE THREAD

**Issue by kristouffe** [EssentialsX/Essentials#3390] opened 2020-06-18 11:53 UTC
### Feature request

**Feature description**

As EssentialsX provides a /top command, I'm wondering why it woudn't provide a /down or /bottom command in opposition. 
The command would teleport the player to the first safe or unsafe (configurable) position straight below the player, if no suitable position is found, nothing happens (or maybe just a configurable warning message). Having the possibility to blacklist blocks (like water or lava, configurable) to tp on, would definitly be a plus.

**How the feature is useful**

I really love using /top when I'm building, it's much faster than flying all arround to get to the highest block. The /down command would be the perfect complement to the /top command, for builders, but also to give some funny extra rights to players.
Another point is that it makes it easy to teleport down into caverns if there is a cavern.

I think it belongs to essentialsX since it provides a /top command and since i can't find any other plugin providing me a /down command. Would be an EssentialsX exclusivity.
BTW, add /down and a /wild like command as already suggested, would make EssentialsX the most complete plugin to manage your teleports.

Thank you

**Comment by triagonal** [comment] 2020-06-18 11:55
Duplicate of #1999. Please do not open multiple issues for the same feature. Your previous issue has been marked as a potential feature and is open for anyone who wishes to implement it.

**Closed as completed by triagonal** 2020-06-18 11:55 UTC
