### ISSUE TITLE
Shulker boxes can't be added to trade signs if they were ever placed, even if they're empty

### ISSUE THREAD

**Issue by oskarkk** [EssentialsX/Essentials#4860] opened 2022-03-19 10:29 UTC
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=19eaf5c0e31848c6ac263d9ac5b33121

### Bug description

You can't sell shulker boxes using the trade signs if they were ever placed. A new shulker box, which was never placed, doesn't have  NBT tag "tag" with "BlockEntityTag". If a shulker box has that tag, it can't be traded, event if it's empty. If you try to place a trade sign, when you only have an used shulker box, you'll get a message that you don't have a shulker box.

![image](https://user-images.githubusercontent.com/16339637/159115653-efe1c615-8014-4668-a6f9-6ef8f4a72551.png)

The NBT on the top is an empty shulker box that has been placed and mined. NBT on the bottom is a fresh, just crafted shulker box.

### Steps to reproduce

1. Craft or `/give` yourself a shulker box.
2. Try to make a `[trade]` sign to sell it. It'll work.
3. Take again a new shulker box, but this time place it somewhere.
4. Break it, you don't even have to open it.
5. Now try to make a trade sign. You'll get message that you don't have a shulker box.

### Expected behaviour

I think that empty shulker boxes should trade just fine. Shulker boxes with items in them shouldn't be allowed to be traded because that would mean losing the items. Maybe there could be a separate error message telling the player that the only shulker box that he has has items in it and can't be traded if it's not empty.

### Actual behaviour

Empty shulker boxes that had been placed can't be traded.

**Comment by pop4959** [comment] 2022-05-22 04:38
Closing as a duplicate of #81 and #3516.

**Closed as completed by pop4959** 2022-05-22 04:38 UTC
Labels: status: duplicate
