### ISSUE TITLE
NoSuchMethodError in BlockIgniteEvent

### ISSUE THREAD

**Issue by BoomEaro** [EssentialsX/Essentials#2644] opened 2019-06-30 20:40 UTC
### Information

[23:35:07] [Server thread/INFO]: Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1615 (MC: 1.12.2)
[23:35:07] [Server thread/INFO]: EssentialsX version: 2.17.0.0
[23:35:07] [Server thread/INFO]: LuckPerms version: 4.3.2
[23:35:07] [Server thread/INFO]: Vault version: 1.5.6-b49
[23:35:07] [Server thread/INFO]: EssentialsXChat version: 2.17.0.0
[23:35:07] [Server thread/INFO]: EssentialsXSpawn version 2.17.0.0

### Details

**Description**  
https://pastebin.com/v9VUaX2K

**Steps to reproduce**  
It is in itself

**Expected behavior**  
There should probably be no exceptions.

**Comment by mdcfe** [comment] 2019-06-30 22:32
Duplicate of #2635. This has already been fixed - you can download the latest version from the [build server](https://ci.ender.zone/job/EssentialsX).

**Closed as completed by mdcfe** 2019-06-30 22:32 UTC
