### ISSUE TITLE
hat command

### ISSUE THREAD

**Issue by noikonoikola** [EssentialsX/Essentials#2767] opened 2019-08-31 11:39 UTC
I'm trying to use the / hat command on my server but there is an error message:
hatfail: You must have something to wear in your hand.
I have permission to that command and op on the server.
The command doesn't work on any item: e.g. Helmet, Zombie head, On any block or item, etc..
Normal players who dont have op has permission to use command /hat can put everything on its head.
![bug](https://user-images.githubusercontent.com/52139801/64063452-14f0ca80-cbfd-11e9-9956-6f3074d98993.jpg)

**Comment by montlikadani** [comment] 2019-08-31 16:59
Fill out the release template to prevent closing this issue.

**Comment by triagonal** [comment] 2019-09-01 02:58
Please search for duplicate issues before creating your own. This issue is a duplicate of #2763, which contains a fix for your issue.

**Closed as completed by triagonal** 2019-09-01 02:58 UTC
Labels: status: duplicate
