### ISSUE TITLE
Sign break bug

### ISSUE THREAD

**Issue by successed** [EssentialsX/Essentials#2567] opened 2019-05-26 14:52 UTC
[17:51:59 ERROR]: Could not pass event BlockBreakEvent to Essentials v2.16.1.150
java.lang.ClassCastException: org.bukkit.material.MaterialData cannot be cast to org.bukkit.material.Sign
        at com.earth2me.essentials.signs.EssentialsSign.checkIfBlockBreaksSigns(EssentialsSign.java:217) ~[?:?]
        at com.earth2me.essentials.signs.SignBlockListener.protectSignsAndBlocks(SignBlockListener.java:50) ~[?:?]
        at com.earth2me.essentials.signs.SignBlockListener.onSignBlockBreak(SignBlockListener.java:40) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor474.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.1.jar:git-Paper-43]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.1.jar:git-Paper-43]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.1.jar:git-Paper-43]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:534) ~[patched_1.14.1.jar:git-Paper-43]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:291) ~[patched_1.14.1.jar:git-Paper-43]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:224) ~[patched_1.14.1.jar:git-Paper-43]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1322) ~[patched_1.14.1.jar:git-Paper-43]
        at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.14.1.jar:git-Paper-43]
        at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.14.1.jar:git-Paper-43]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.1.jar:git-Paper-43]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.1.jar:git-Paper-43]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.1.jar:git-Paper-43]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.1.jar:git-Paper-43]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.1.jar:git-Paper-43]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:998) ~[patched_1.14.1.jar:git-Paper-43]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:991) ~[patched_1.14.1.jar:git-Paper-43]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91) ~[patched_1.14.1.jar:git-Paper-43]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:974) ~[patched_1.14.1.jar:git-Paper-43]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.1.jar:git-Paper-43]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by Scremonetu** [comment] 2019-05-26 17:56
> [16:27:23] [Server thread/ERROR]: Could not pass event BlockBreakEvent to Essentials v2.16.1.180-mc114-b95
> org.bukkit.event.EventException: null
> 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
> 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
> 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
> 	at net.minecraft.server.v1_14_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:286) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
> 	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:219) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
> 	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1199) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
> 	at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
> 	at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
> 	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
> 	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
> 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
> 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
> 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
> 	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895) [spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
> 	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
> 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
> 	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:872) [spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
> 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
> Caused by: java.lang.ClassCastException: org.bukkit.material.MaterialData cannot be cast to org.bukkit.material.Sign
> 	at com.earth2me.essentials.signs.EssentialsSign.checkIfBlockBreaksSigns(EssentialsSign.java:217) ~[?:?]
> 	at com.earth2me.essentials.signs.SignBlockListener.protectSignsAndBlocks(SignBlockListener.java:49) ~[?:?]
> 	at com.earth2me.essentials.signs.SignBlockListener.onSignBlockBreak(SignBlockListener.java:39) ~[?:?]
> 	at sun.reflect.GeneratedMethodAccessor248.invoke(Unknown Source) ~[?:?]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
> 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.1.jar:git-Spigot-8043ebc-f690957]
> 	... 19 more

**Comment by mdcfe** [comment] 2019-05-27 11:21
Duplicate of #2529.

This was fixed in the latest experimental build for 1.14.x - you can download it from the [build server](https://ci.ender.zone/job/EssentialsX-Experimental).

**Closed as completed by mdcfe** 2019-05-27 11:21 UTC

**Comment by successed** [comment] 2019-05-27 15:24
> Duplicate of #2529.
> 
> This was fixed in the latest experimental build for 1.14.x - you can download it from the [build server](https://ci.ender.zone/job/EssentialsX-Experimental).

t,y for update.
