### ISSUE TITLE
Bad gateway error on drtshock.net

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#1587] opened 2017-10-13 14:09 UTC
When trying to download the latest version of EssentialsX from the website, I get a bad gateway error from CloudFlare.

![error](https://user-images.githubusercontent.com/29130685/31550222-eb630302-b030-11e7-83ad-23dc3379ab09.png)

**Comment by Kakifrucht** [comment] 2017-10-13 14:32
Grab a build from a mirror at https://ci.akpmakes.tech/job/EssentialsX/ and http://ci.ender.zone/job/EssentialsX/

**Comment by smmmadden** [comment] 2017-10-14 02:20
still getting a bad gateway error when trying to get the latest build.

**Comment by smmmadden** [comment] 2017-10-14 14:04
I'm confused @md678685 - why would you close this when the Jenkins server is still down?  You updated this as duplicate of 1589 and 1589 as duplicate of 1587 (this one) which is a circular reference. :-)

**Comment by mdcfe** [comment] 2017-10-14 14:20
@smmmadden I didn't close this issue. GitHub will detect the phrase `duplicate of` and then show the "marked as a duplicate of" event in both issues (though that event hasn't shown up for me anywhere on the site for the last few weeks). There's no box to set the duplicates anywhere.

**Comment by k-lj** [comment] 2017-10-16 03:19
When will this site be back up

**Comment by SupaHam** [comment] 2017-10-16 07:07
https://ci.akpmakes.tech/job/EssentialsX/lastSuccessfulBuild/

**Comment by k-lj** [comment] 2017-10-16 14:18
I was trying to download dev builds of mcmmo and factionsUUID.

**Comment by smmmadden** [comment] 2017-10-21 15:52
hey guys, just wondering what's up with the main repository site to download from?  Will it be back up or are you at some point going to change the button to go to a new site?  Unless someone searches through the issues and finds this post with the other links, no one will know what to do.  

If anyone else is like me (scary I know), I have a bookmark so I can directly to it for the builds.

**Comment by SupaHam** [comment] 2017-10-29 00:53
@smmmadden I've switched download links to direct to http://ci.ender.zone.

**Closed as completed by SupaHam** 2017-10-29 00:53 UTC
