### ISSUE TITLE
EssentialsSpawn doesn't work! [Found an another way to teleport all players to spawn]

### ISSUE THREAD

**Issue by MrMarvel** [EssentialsX/Essentials#1674] opened 2017-12-01 16:13 UTC
EssentialsX version 2.0.1-b488

Server software 1.11

EssentialsX config default 
![image](https://user-images.githubusercontent.com/24212110/33491433-55f4deaa-d6cb-11e7-8152-f8b492680436.png)

error in EssentialsSpawn:
[19:00:24] [Server thread/ERROR]: Error occurred while enabling EssentialsSpawn v2.0.1-bSNAPSHOT (Is it up to date?)
java.lang.NoSuchMethodError: com.earth2me.essentials.ISettings.getSpawnJoinPriority()Lorg/bukkit/event/EventPriority;
	at com.earth2me.essentials.spawn.EssentialsSpawn.onEnable(EssentialsSpawn.java:56) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[multiFIX.jar:git-Spigot-f950f8e-0a81101]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [multiFIX.jar:git-Spigot-f950f8e-0a81101]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [multiFIX.jar:git-Spigot-f950f8e-0a81101]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375) [multiFIX.jar:git-Spigot-f950f8e-0a81101]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325) [multiFIX.jar:git-Spigot-f950f8e-0a81101]
	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419) [multiFIX.jar:git-Spigot-f950f8e-0a81101]
	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380) [multiFIX.jar:git-Spigot-f950f8e-0a81101]
	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335) [multiFIX.jar:git-Spigot-f950f8e-0a81101]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272) [multiFIX.jar:git-Spigot-f950f8e-0a81101]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [multiFIX.jar:git-Spigot-f950f8e-0a81101]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]

------------------------------------
It doesn't work :/

**Comment by jsgunman** [comment] 2017-12-02 07:44
Confirmed same issue, same NoSuchMethodError thrown to console. :(

**Comment by mdcfe** [comment] 2017-12-02 17:15
Please update both EssentialsX and EssentialsXSpawn to the [latest versions](https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild).

**Comment by MrMarvel** [comment] 2017-12-02 17:43
I fixed this. But i have new problem: setting spawn on join doesn't work. i set spawn but every time i join i spawn at last location not spawn!

**Comment by ghost** [comment] 2017-12-03 05:11
@MrMarvel Please note that this may be consistent if you are OP / have all permissions through a permissions manager. If you are no longer OP or anything, you will likely find that this is a non-issue.

**Comment by mdcfe** [comment] 2017-12-03 14:15
@MrMarvel This is likely caused by another plugin having a higher spawn handler priority. Could you paste a list of plugins (`/plugins`)?

**Comment by MrMarvel** [comment] 2017-12-03 23:04
My plugins:  WorldEdit, OpenInv, PermissionsEx,Chairs, Vault, ProtocolLib, WorldGuard, BungeePortals, Essentials, EssentialsProtect, EssentialsChat, EssentialsGeoIP, EssentialsAntiBuild, EssentialsSpawn, EssentialsXMMP, AuthMe, AuthMeBridge

**Comment by DrewAMitchell** [comment] 2017-12-12 23:22
@MrMarvel Well, this is how it is normally handled... If the players need to get to spawn, they should type spawn. But once they join the first time and spawn at spawn, afterward they will log in where they left off. Otherwise, /spawn needs to be typed.

**Comment by MrMarvel** [comment] 2017-12-13 14:16
so that is impossible to turn on spawn on join?

**Comment by Drkmaster83** [comment] 2017-12-13 23:44
@MrMarvel Yeah, with Essentials. If you want the player to be teleported to spawn every time they join, get a JoinSpawn plugin of some sort - they're really simple, almost any developer could make it in 2 minutes.

**Comment by mdcfe** [comment] 2017-12-14 07:58
You need to set [`spawn-on-join`](https://github.com/drtshock/Essentials/wiki#teleport-to-spawn-when-joining) to an appropriate value. You may also need to change or add [`spawn-join-listener-priority`](https://github.com/drtshock/Essentials/blob/2.x/Essentials/src/config.yml#L894) for EssentialsXSpawn to set the spawn point correctly.

**Comment by DrewAMitchell** [comment] 2017-12-17 09:46
@MrMarvel If your issue is solved, please close it! There is a value in the config that you can modify to teleport them to the spawnpoint every time they login!

**Comment by MrMarvel** [comment] 2017-12-17 11:50
not solved!

**Comment by mdcfe** [comment] 2017-12-17 12:27
@MrMarvel See [my previous reply](https://github.com/EssentialsX/Essentials/issues/1674#issuecomment-351635672).

**Comment by MrMarvel** [comment] 2017-12-17 12:53
I have high priority

**Comment by MrMarvel** [comment] 2017-12-17 13:07
@md678685 i can send Ess config
```
respawn-listener-priority: high

# What priority should we use for handling spawning on joining the server?
# See respawn-listener-priority for possible values.
# Note: changing this may impact or break spawn-on-join functionality.
spawn-join-listener-priority: high

# When users die, should they respawn at their first home or bed, instead of the spawnpoint?
respawn-at-home: false

# Teleport all joining players to the spawnpoint
spawn-on-join: true
# The following value of `guests` states that all players in group `guests` will be teleported to spawn when joining.
#spawn-on-join: guests
# The following list value states that all players in group `guests` and `admin` are to be teleported to spawn when joining. 
#spawn-on-join:
#- guests
#- admin
_
```
And sorry for not solved. I didn't see previous reply (>_<)
but it doesn't work

**Comment by MrMarvel** [comment] 2017-12-17 13:13
May be Authme?

```
        displayOtherAccounts: true
        # Spawn priority; values: authme, essentials, multiverse, default
        spawnPriority: 'essentials,authme,multiverse,default'
        # Maximum Login authorized by IP
        maxLoginPerIp: 1
        # Maximum Join authorized by IP
        maxJoinPerIp: 1
        # AuthMe will NEVER teleport players if set to true!
        noTeleport: false

```

**Comment by MrMarvel** [comment] 2017-12-17 13:15
how to check - who controls the spawn option?
And how to teleport ALL players(admins, default players and etc..)

**Comment by MrMarvel** [comment] 2017-12-17 13:38
@md678685 Ok That is not Authme problem. I just need to set spawn for all players not only default players. @Drkmaster83 was right. It's problem with OP. So how to fix it

**Comment by DrewAMitchell** [comment] 2017-12-17 18:48
@MrMarvel 
So you changed `spawn-on-join` to `true` in the config.yml?
Try and set `spawn-join-listener-priority` to `highest`, as well.
Make sure to update to the [most recent build](http://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild/)

**Comment by MrMarvel** [comment] 2017-12-18 17:34
*Default players teleport is working. Admins stay. I want to spawn admins too

**Comment by mdcfe** [comment] 2017-12-18 17:41
Revoke the permission `essentials.spawn-on-join.exempt` from the group that may have a wildcard. You may need to place it above the wildcard in the list of permissions, depending on how your permissions plugin is configured.

**Comment by MrMarvel** [comment] 2017-12-18 17:42
hmmmm.... gonna check it

**Comment by MrMarvel** [comment] 2017-12-18 17:45
I have permissionEx
Owner group:
-* permissions (all)
so how to (* not essentials.spawn-on-join.exempt(all but not this))

**Comment by mdcfe** [comment] 2017-12-18 17:47
Grant the group `-essentials.spawn-on-join.exempt`, which will negate the permission from the group.

**Comment by MrMarvel** [comment] 2017-12-18 19:24
@md678685 I don't need to restrict spawning on join. I want to spawn on join all players, not only default players. If it is impossible - I can make spawn on join in Authme but that will cause some problems with login(because only not logged players teleport(some players don't need to login(for them spawn doesn't work)))

**Comment by MrMarvel** [comment] 2017-12-18 19:25
I wrote
```
- '*'
- essentials.spawn-on-join.exempt
```
i need to spawn this group

**Comment by mdcfe** [comment] 2017-12-18 19:30
You need to *negate* the permission by adding `-essentials.spawn-on-join.exempt`. Note that there is a `-` before the start of the permission, so your permissions list should look like:
```yaml
- '*'
- -essentials.spawn-on-join.exempt
```

**Comment by DrewAMitchell** [comment] 2017-12-21 06:25
@MrMarvel Any luck/progress?

**Comment by MrMarvel** [comment] 2017-12-22 14:48
@Drkmaster83 I don't have progress. I disabled authme spawn and put `-essentials.spawn-on-join.exempt` permission to admins. It doesn't work at all

**Comment by DrewAMitchell** [comment] 2017-12-22 18:54
@md678685 I just tested this myself using PermissionsEx (1.23.4) and build 547 on 1.12.2; The negation of the permission didn't work at first as a user-specific permission node (I tried before and after the '*'), but then I added it to a group and set my group, and then the negation permission applied. Then, I went back to user-specific permissions (removing myself from the group I created) and it continued to work. Perhaps the discrepancy is caused by PEX?

**Comment by MrMarvel** [comment] 2017-12-22 19:13
may be I just need to turn on teleport to spawn unauthorized players. But not always they need to login = spawn will not work always. D:

**Comment by mdcfe** [comment] 2017-12-22 21:18
@Drkmaster83 PEX follows certain rules that are not always particularly clear when calculating permissions - I would recommend LuckPerms for testing permissions behaviour, as it's much more predictable.

@MrMarvel We don't support offline mode servers, but could you try removing AuthMe temporarily to see if it is causing the issue?

**Comment by MrMarvel** [comment] 2017-12-23 09:52
@md678685 I disabled authme.(Without it it doesn't work too). So if that is impossible should i close issue?

**Comment by mdcfe** [comment] 2017-12-23 10:25
Try moving the `- -essentials.spawn-on-join.exempt` line above the `- *` line in your permissions.

**Comment by MrMarvel** [comment] 2017-12-23 13:28
doesn't work:
`
  Owner:
    options:
      default: false
      prefix: '&2[&4Гл.Администратор&2]&f '
      suffix: '&6'
    inheritance:
    - default
    permissions:
    - -essentials.spawn-on-join.exempt
    - '*'
`

**Comment by mdcfe** [comment] 2018-01-12 08:30
If this is still an issue, could you run `/ess debug` then paste the console output when a player joins but doesn't get teleported to spawn?

**Comment by MrMarvel** [comment] 2018-01-12 15:35
Ok. Result is:
1) It works for default players.
2) not for admins
3) I found an another way to teleport all to spawn when join - authme
Thanks for helping!

**Comment by MrMarvel** [comment] 2018-01-12 15:35
and.... how to close issue?

**Closed as completed** 2018-01-12 15:36 UTC
Labels: type: problem, status: not enough info
