### ISSUE TITLE
/tpa and /tpahere always charge the player

### ISSUE THREAD

**Issue by FayoraRose** [EssentialsX/Essentials#5556] opened 2023-10-27 16:51 UTC
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=9859e91ebe63449998f83fa970e9d37c

### Bug description

When running /tpa or /tpahere with command-costs set, the player is immediately charged for the teleport attempt without waiting for the outcome

### Steps to reproduce

1. Set a command costs for either tpa and/or tpahere
2. Have 2 players online
3. Attempt to run one of the commands directed at the other player

### Expected behaviour

No money should be deducted until teleport has been accepted by the other player and the teleport fully completed after any configured teleport delays. (Standard /tp and /tphere work correctly and wait until after warmups before charging money)

### Actual behaviour

Money is charged immediately after running the command.

**Comment by pop4959** [comment] 2023-11-11 04:04
Arguably this works as intended, as the cost is tied to using the command, not whatever the implied usage of the command is.

**Comment by pop4959** [comment] 2023-12-10 01:44
Command costs charge for using the command, this is not a bug. Closing this as "works as intended" however if you would like to open a *feature request* instead for charging on command outcome I think that would be valid.

**Closed as not planned by pop4959** 2023-12-10 01:44 UTC
Labels: status: works as intended
