### ISSUE TITLE
vanish player switch world cause vanish bug

### ISSUE THREAD

**Issue by cyilin** [EssentialsX/Essentials#1764] opened 2018-01-11 07:02 UTC
thanks @phoenixlzx to test this bug
if admin in vanish status and teleport to other worlds, Essentials will duplicate add player name to ess.vanishedPlayers
when a player join to the server, will can't see this admin even if this admin is unvanish status

[EssentialsPlayerListener.java#L237](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java#L237)
[EssentialsPlayerListener.java#L578](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/EssentialsPlayerListener.java#L578)
[User.java#L718](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/User.java#L718)

**Comment by mdcfe** [comment] 2018-01-11 08:33
That's a great observation - I've been wondering what caused unpredictable issues with the vanish functionality, but never found the cause.

@khobbits Just out of interest, what was the reasoning behind having the `vanishedPlayers` list?

**Comment by khobbits** [comment] 2018-01-11 10:51
@md678685 Two reasons I think:

It's part of the public API, so other plugins can see who's vanished.

It's used to handle the vanish.see permissions when logging in.  Ie when a new player joins the server, he shouldnt see people who are 'vanished', unless he has 'ess.vanish.see'.

**Comment by phoenixlzx** [comment] 2018-01-11 14:33
Thanks @cyilin for reporting this to EssentialsX. I believe this issue exists in origin Essentials as well.

Some details to reproduce:

1. Create a server, install EssentialsX and multi world management plugin (multiworld/multiverse... etc)
2. Create another world.
3. Issue server command `/vanish`
4. Teleport to another world.

Result:

You are not vanishing in Essentials, but when you move (anyway to move/teleport) to other players, they can't see you unless you toggle `/v` twice in front of them - However even toggled vanish status and let others see you, you are still in the list of 'ess.vanishedPlayers', confirmed by our plugin invoking this.

**Comment by caojohnny** [comment] 2018-01-15 05:43
I must ask, why exactly was the vanished players collection not a `Set` in the first place? Isn't it common sense for it to not contain duplicates, or simply oversight?

**Comment by mdcfe** [comment] 2018-01-16 08:29
I've worked on a very simple solution which simply avoids adding existing usernames to the list. However, I'm considering that we could replace the list with a Set and deprecate the existing `getVanishedPlayers`, especially considering since there's no reason for plugins to directly mutate the `ess.vanishedPlayers` list instead of using the appropriate `User` method.

**Comment by mdcfe** [comment] 2018-03-25 21:13
This should be fixed by #1796.

**Closed as completed by mdcfe** 2018-03-25 21:13 UTC
Labels: bug: confirmed
