### ISSUE TITLE
Multiple requests from tpa

### ISSUE THREAD

**Issue by 7wOv6ySCjo** [EssentialsX/Essentials#4161] opened 2021-05-19 02:30 UTC
### Type of bug

Other unexpected behaviour

### `/ess version` output

> ess version
[22:30:01 INFO]: CONSOLE issued server command: /ess version
[22:30:01 INFO]: Server version: 1.16.5-R0.1-SNAPSHOT git-Paper-703 (MC: 1.16.5)
[22:30:01 INFO]: Brand version: Paper
[22:30:01 INFO]: EssentialsX version: 2.19.0-dev+121-d00b90c
[22:30:01 INFO]: PlaceholderAPI version: 2.10.9
[22:30:01 INFO]: Vault version: 1.7.3-b131
[22:30:01 INFO]: Fetching version information...
[22:30:01 INFO]: You're running the latest EssentialsX dev build!

### Bug description

If a player receives multiple /tpa requests he cannot choose who to accept and who not to accept with `/tpa <name>` command. He simply accepts the last request received. With the /tpadeny command the same thing happens.

With `/tpacancel <name>` this works.

it's some kind of command's dictatorship or something ? xD

**Comment by JRoy** [comment] 2021-05-19 02:56
Duplicate of #3769

Will be added in #3801

**Closed as completed by JRoy** 2021-05-19 02:56 UTC
Labels: status: duplicate
