### ISSUE TITLE
Ability to enable and have a tax on /pay

### ISSUE THREAD

**Issue by lukemango** [EssentialsX/Essentials#3135] opened 2020-04-05 01:09 UTC
### Feature request

**Feature description**

Ability to add a tax to /pay (in %) (helps take money out of the economy)

**How the feature is useful**

Very very useful, would help our economy stabilize immensely.

**Comment by pop4959** [comment] 2020-04-05 02:00
I think something similar is already open in #3080

**Comment by mdcfe** [comment] 2020-04-05 14:11
Duplicate of #1480.

**Closed as completed by mdcfe** 2020-04-05 14:11 UTC
Labels: status: duplicate, type: enhancement
