### ISSUE TITLE
Trade sign not returning items when placed on ground

### ISSUE THREAD

**Issue by Pjooo** [EssentialsX/Essentials#2558] opened 2019-05-23 16:17 UTC
### Information

```
Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1612 (MC: 1.12.2)
EssentialsX version: 2.16.1.0
LuckPerms version: 4.3.73
Vault version: 1.6.6-b${env.TRAVIS_BUILD_NUMBER}
EssentialsXSpawn version: 2.16.1.0
```

### Details

**Description**  
When I place trade sell sign (as player) on ground, and then break it, it doesn't return my items. When sign is hanged on block, and then broken, it returns items no problem.

**Steps to reproduce**  
Place trade sell sign as player on ground (sign is on it's leg), and break it. Make sure that sign is "holding" items.

**Expected behavior**  
Items don't return to player (they should).

**Comment by mdcfe** [comment] 2019-05-24 08:59
You're on an old version of EssentialsX. Could you update to the [latest build](https://ci.ender.zone/job/EssentialsX/) and see if this still occurs?

**Comment by Pjooo** [comment] 2019-05-27 23:30
Yes, this problem still appears in latest build.

**Comment by triagonal** [comment] 2019-07-10 11:45
I can't reproduce this on the following version:
```
[21:42:53 INFO]: CONSOLE issued server command: /ess version
[21:42:53 INFO]: Server version: 1.12.2-R0.1-SNAPSHOT git-Paper-1594 (MC: 1.12.2)
[21:42:53 INFO]: EssentialsX version: 2.17.0.3
```
The items are returned regardless of whether or not the sign is on the ground or hanging. Could you try to provide some more accurate steps to reproduce? Also, please try updating to see the latest version of EssentialsX (at least `2.17.0.x`) and see if the bug still occurs.

**Comment by pop4959** [comment] 2019-10-30 19:06
Many issues regarding signs were present around 1.13 (due to internal changes), however they should be fixed by now, in the latest versions. It also seems no one has had this issue for quite some time.

I'm going to close this for now as a result. If this is still an issue, please let us know and work with us to confirm it on the latest version of Essentials. Thanks!

**Closed as completed by pop4959** 2019-10-30 19:06 UTC
Labels: help wanted, bug: unconfirmed
