### ISSUE TITLE
/Invsee bug

### ISSUE THREAD

**Issue by MrFadeFancy** [EssentialsX/Essentials#5916] opened 2024-08-21 00:10 UTC
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=0baee549f87f47cb9d1cd4bfccbf0eb9

### Bug description

so when I do /invsee player and if I mess around with arrows (moving arrows around and double clicking arrows to combine them / shift clicking arrows into player's inventory) while I am in invsee gui. Sometimes it replaces that player's armor to arrows and deleted their armor.

### Steps to reproduce

do /invsee player and if I mess around with arrows (moving arrows around and double clicking arrows to combine them / shift clicking arrows into player's inventory) while I am in invsee gui. test it with a stack of arrows for higher chance for it to happen

### Expected behaviour

it should not remove players armor with arrows

### Actual behaviour

Idk it should not happen

**Comment by JRoy** [comment] 2024-10-20 21:32
Duplicate of #3065

**Closed as not planned by JRoy** 2024-10-20 21:32 UTC
Labels: bug: unconfirmed
