### ISSUE TITLE
EssentialsX make a bunch of new random region in dim 0 world 

### ISSUE THREAD

**Issue by Meltwin** [EssentialsX/Essentials#3531] opened 2020-07-22 19:37 UTC
### Information

**Full output of `/ess version`**:

```
Version Server : 1.16.1-R0.1-SNAPSHOT git-Paper-108 (MC: 1.16.1)
Version EssentialsX : 2.18.0.0
```

**Server log**: [https://gist.github.com/Meltwin/41f446dfd9a0a1b3cb5c2875b634a0b8](https://gist.github.com/Meltwin/41f446dfd9a0a1b3cb5c2875b634a0b8)

**EssentialsX config**: https://gist.github.com/Meltwin/c7fe6351baf321d8e4767d3e15d54740

### Details

**Description**  
EssentialsX create some new region at random coordinate in the world "world" (not in world_nether nor world_the_end) after about 30s after the server launches. These files don't disappear after stopping the server and each time the server is starting, some new files are generated making the world very big after somes starts.

Tested with EssentialsX 2.17 and it doesn't happened with it.
Delete essentials config don't change anything.

**Steps to reproduce**  
Create a Spigot or Paper -Spigot server and install EssentialsX on it.
Run the server and wait about 30s.

**Expected behavior**  
After that some regions should have been created in world/regions/ that you doesn't have explored.

**Screenshots**  
![After one start & stop of the server](https://user-images.githubusercontent.com/58667575/88220587-75e51f00-cc63-11ea-89b3-1225af02cdc6.jpg)

**Comment by pop4959** [comment] 2020-07-22 19:46
Duplicate of #3493. Fixed in 41ae12ed3de6ccdb759a1726b903f46090ff906d. Please download the [latest version of EssentialsX](https://essentialsx.net/downloads.html).

**Closed as completed by pop4959** 2020-07-22 19:46 UTC
Labels: status: duplicate
