### ISSUE TITLE
Jail Command ignore MultiVerse change gamemode

### ISSUE THREAD

**Issue by Doc94** [EssentialsX/Essentials#3685] opened 2020-09-23 18:15 UTC
**EssentialsX config**: https://gist.github.com/Doc94/4c094a65c35d4bc2b21c8139b427f0aa

### Details

**Description**  
If you have Multiverse, and you are in a world in Creative and then get Jailed with Jail in another World in survival you still in Creative mode (ignoring the multiverse change of gamemode per world)

**Steps to reproduce**  
- With Multiverse create two worlds (one with the Jail in Survival Mode, and another with Creative Mode)
- Player in Creative world
- Send to Jail the Player

**Expected behavior**  
Multiverse detect the changeworld per teleport from Creative to Survival world and change gamemode to survival.

**Note**
In another cases you can return to jail using /back command

**Screenshots**  
N/A

**Comment by pop4959** [comment] 2020-09-23 18:39
I still fail to understand what the issue is here. Isn't Multiverse responsible for maintaining the correct game mode across worlds? Essentials as far as I can tell just teleports the player to jail. If the jail is closed off they are probably not able to fly out anyways.

**Comment by Doc94** [comment] 2020-09-23 18:43
> I still fail to understand what the issue is here. Isn't Multiverse responsible for maintaining the correct game mode across worlds? Essentials as far as I can tell just teleports the player to jail. If the jail is closed off they are probably not able to fly out anyways.

Multiverse change the gamemode in any TP but only with Jail cases Multiverse cant change the gamemode of teleported player, maybe for the block in the GameModeChangeEvent make here? https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/Jails.java#L227

**Comment by pop4959** [comment] 2020-09-23 18:45
You might be right. Do you think it would be better for Multiverse to handle the game mode changes in the case that it is installed? Or do you have some sort of special config in Multiverse that causes the issue?

**Comment by Doc94** [comment] 2020-09-23 18:53
i dont have custom configs with multiverse, then in teory all work like spected, the issue is how to Essentials handle the change of gamemode, maybe can add support for Multiverse and avoid in the PlayerGameModeChangeEvent the new gamemode can be different from the default gamemode in this world?

or a patch for avoid Creative players can get items from the Creative Inventory, because the root issue are players Jailed from creative world get items from creative inventory and when are released have all this.

**Comment by pop4959** [comment] 2020-09-23 19:15
This would probably need to be fixed in Multiverse, or you should make a jail in the creative world instead of the survival world and send them there instead.

**Comment by Doc94** [comment] 2020-09-23 19:43
> This would probably need to be fixed in Multiverse, or you should make a jail in the creative world instead of the survival world and send them there instead.

Maybe but not sure if make a Jail in a creative world can work in case of...

i prefer if can add a cancel in the Creative Inventory (get items or middle mouse)

**Comment by pop4959** [comment] 2020-10-01 23:07
This won't be fixed in Essentials, since it is intentional that users' game modes are not changed when they are jailed. When they are un-jailed, they return to the same world that they were in, with the game mode they were in. Your jails should still work if the player is in another game mode, or you will need a custom plugin to un-cancel the event if the user is jailed in the specific worlds you are concerned about.

**Closed as completed by pop4959** 2020-10-01 23:07 UTC
Labels: status: wontfix, type: problem
