### ISSUE TITLE
Error in the selector (@) of the command blocks

### ISSUE THREAD

**Issue by Vicentey** [EssentialsX/Essentials#2217] opened 2018-10-21 18:57 UTC
**Dear friends of the Essentials team:**

I'm Vicentey, I have a 1.13 server with the EssentialsX version 2.15.0.52 (all the Essentials plugins). I have the following problem: when I want to use the command "/ eco (give, take, reset) @p (amount)" the @ does not appear, on the contrary * and my username appear in a predictive way. Also if I write the corresponding @p, when executing the command the message appears: "ERROR: Player not found" (Being that there is a player nearby).
I have reviewed the configuration several times, but well, I do not know what happens.

Thank you for your attention, I hope a quick response.

![image](https://user-images.githubusercontent.com/44346323/47270937-3d258c80-d549-11e8-90bb-2b33731d33cb.png)

**Comment by mdcfe** [comment] 2018-10-22 10:52
Please follow the issue template.

```markdown
<!--
Don't put anything inside this block, as it won't be included in the issue.

If you have a question about using EssentialsX, it may be more helpful to ask
in our Discord server: https://discord.gg/F7gexAQ

If you have a feature suggestion for EssentialsX, please delete the template.

Otherwise, if you are reporting a bug, read on:
1.  Fill out the template, running the commands either in the console or 
    as a player. Don't simply put "latest" or we will ignore it.

2.  When linking files, do not attach them to the post! Paste them on 
    https://gist.github.com/, then paste a link to them in the relevant parts
    of the template. Avoid using Hastebin or Pastebin, as files are deleted
    after a period of time.

3.  If you are reporting an issue with lag, please include a timings report.

4.  If you are reporting an issue with messages or in-game behaviour, please
    include screenshots detailing the problem.

5.  Include a description and any other details that may be helpful under the
    Details section.

6.  Delete this line and all above lines before posting your issue!       -->

### Information

Full output of `/ess version`:




Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 

### Details

Describe your issue here.


```

**Comment by BluePlastics** [comment] 2018-10-23 15:27
Use something like PsudoCommands or CommandHook.

**Comment by mdcfe** [comment] 2018-11-25 08:52
Spigot does not support command selectors on 1.13+. This may be added to EssentialsX in the future, but for now, there is no way to use command selectors in most plugins without the use of utility plugins.

**Comment by Vicentey** [comment] 2018-11-25 17:23
But, for example ¿how do I replace the command "/eco take @p"? I need yes or yes this command for the Permission Books store on my server ...

**Comment by BluePlastics** [comment] 2018-12-02 08:01
Use a plugin like psuedocommands, as stated by md above SPIGOT does not support this, it may be added at a later date in essentialsx but you'd need to use something like the plugin stated earlier in this reply.

**Comment by mdcfe** [comment] 2018-12-06 18:09
Closing as this is both a duplicate of #2102 and something that can easily be solved by another plugin.

**Closed as completed by mdcfe** 2018-12-06 18:09 UTC
Labels: status: invalid, status: not enough info
