### ISSUE TITLE
Unbreakable option for kit

### ISSUE THREAD

**Issue by Kiruzx** [EssentialsX/Essentials#1449] opened 2017-08-07 04:28 UTC
Can you update unbreakable option to kit i need it :(

**Comment by SupaHam** [comment] 2017-08-07 13:11
Duplicate of #377

This has been fixed in 203d656. You can grab the fix from [build 516](https://ci.drtshock.net/job/EssentialsX/) on the CI server.

**Closed as completed by SupaHam** 2017-08-07 13:11 UTC
Labels: status: duplicate
