### ISSUE TITLE
Using version 2.0.1 Buy/Sell Signs are BLANK

### ISSUE THREAD

**Issue by TwiistedMC** [EssentialsX/Essentials#940] opened 2016-10-22 21:03 UTC
I have enabled all signs by removing the # but everytime i make a buy/sell sign there just blank. Please help!

**Comment by mdcfe** [comment] 2016-10-22 21:41
What version are you using?

**Comment by SupaHam** [comment] 2016-10-29 21:54
Duplicate of #687.

**Closed as completed by SupaHam** 2016-10-29 21:54 UTC
