### ISSUE TITLE
Received kit message

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#1927] opened 2018-03-26 15:37 UTC
### Information

Using locale en
Using Spigot 1.7.10+ ServerListPingEvent iterator
Essentials reloaded 2.0.1-b612.

### Details

Is it possible to make the kit received in the kit message be printed exactly as it's named? This includes capital letters which in this case is my issue.

Showcase: http://prntscr.com/iwly31

Would be awesome if it could be printed exactly as I named the kit. 👍

**Comment by mdcfe** [comment] 2018-03-29 23:00
I don't believe this is possible, and last time we looked at case-sensitive kit names I believe we never added them as it could break people's configs.

**Comment by mdcfe** [comment] 2018-04-03 16:13
Closing as a duplicate of #1374.

**Closed as completed by mdcfe** 2018-04-03 16:13 UTC
Labels: type: question
