### ISSUE TITLE
Task N# X for Essentials v2.17.2.54 generated an exception

### ISSUE THREAD

**Issue by kalinzange** [EssentialsX/Essentials#3178] opened 2020-04-18 13:09 UTC
Hi,

So every time a person log's in and log's off (at least for I just did in the beginning - not much more of a test) I get a Task N# X (where the X is a completely random number) for Essentials v2.17.2.54 generated an exception and then some java error.

I believe that I have something wrong or something not configured, or actually not working?
I'm here to get some best support.

PrintScreen: https://imgur.com/XGQGXlb

Thanks!

**Comment by triagonal** [comment] 2020-04-18 13:14
Duplicate of multiple issues. Please search for similar issues before creating a new one.

This is due to EssentialsXMPP being improperly configured. If you're not using EssentialsXMPP, then you should remove the EssentialsXXMPP.jar file from your `plugins` folder.

**Closed as completed by triagonal** 2020-04-18 13:14 UTC
Labels: status: duplicate

**Comment by kalinzange** [comment] 2020-04-18 13:15
Hi, I did search for Task for essentials v2.17.2.54 generated an exception but couldn't find it.

Many thanks anyway.
