### ISSUE TITLE
Improve /createkit

### ISSUE THREAD

**Issue by enterih** [EssentialsX/Essentials#1981] opened 2018-04-26 00:21 UTC
I have ideas to improve the /createkit feature. 

at first: When i tell something that already implemented, so please say where an how to use.  

My first Idea:
Add support for Attributes like MovementSpeed, MaxHealth etc.

My Second Idea:
/createkit use the next in a written book (import it itself). (Actually it get this error: Invalid book tags

My Tirth idea:
If a player get a kit with armor and they have any armor equipped, so he should equipped automatically.

My fourthly idea:
Support Potions. Every Potions i got was a waterbottle. 

Thanks for reading. I'm ready to discuss every idea. I hope, that I can help the project :)

Enterih/Sprungente

**Comment by mdcfe** [comment] 2018-04-26 19:09
#750, #838 and #1105 already exist to request item attribute support. For now, you can add items with attributes by using `/give` inside the kit. 

Support for automatically saving books was requested in #31 - if you want to replicate a book, add it to the books file and add the `book:` tag in your kit.

Auto-equipping armor was already requested in #347.

Potions and tipped arrows are known to not work - see #468, #486, #1962 and #1965.

Closing as a duplicate of 9 separate issues - *please* use the search function before submitting issues.

**Closed as completed by mdcfe** 2018-04-26 19:09 UTC
Labels: type: enhancement
