### ISSUE TITLE
Trade sign doesn't recognizes potions and eggs meta

### ISSUE THREAD

**Issue by matcracker** [EssentialsX/Essentials#958] opened 2016-11-03 14:12 UTC
For reproduce this issue follow these steps:
- Create a sign trade that sell a potion (for example speed) or an egg.
- Now add to sign more potion or egg of another type (for example jump, or a normal potion with ID 373)
- You see that you can add different type of potion or egg in a sign that sell another type of potion, but if someone buy the potion it returns the potion type written in the sign.

**Comment by mdcfe** [comment] 2016-11-03 16:01
So the more sign is broken or the buy sign is?

**Comment by matcracker** [comment] 2016-11-05 16:43
I don't try on other sign, I've tried only on Trade sign

**Comment by saturnux** [comment] 2016-12-05 08:36
sell and buy not work too

**Comment by matcracker** [comment] 2016-12-05 14:09
Yes, I can confirm too

**Comment by SupaHam** [comment] 2016-12-05 16:14
Have you tried on the latest build on our [CI server](https://ci.drtshock.net)?

**Comment by saturnux** [comment] 2016-12-06 09:12
yes, i use a last. #453

**Comment by Rakdos8** [comment] 2017-10-08 13:26
Issue still up to date with build #532
__Server version:__ CraftBukkit version git-Spigot-da42974-8f47214 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

**Comment by Rakdos8** [comment] 2017-11-17 21:18
The Trade sign with potion are still broken: [screenshot](https://redmine.modulmonde.com/attachments/download/63/2017-09-16_22.03.17.png)
Latest version used (546) and latest 1.12.1 version of spigot.
(The date of the screen is old, yeah, but the problem is strictly the same)

**Comment by Rakdos8** [comment] 2019-02-09 21:17
The latest build now allow to trade back potions.
Thank you !

**Comment by pop4959** [comment] 2019-12-29 10:42
Closing since according to Rakdos8 this is fixed. Feel free to make a new issue if there is still another issue with trade signs.

**Closed as completed by pop4959** 2019-12-29 10:42 UTC
Labels: status: not enough info, bug: unconfirmed
