### ISSUE TITLE
Error on load essentials with 1.13

### ISSUE THREAD

**Issue by FabioZumbi12** [EssentialsX/Essentials#2092] opened 2018-07-30 07:11 UTC
### Information

Full output of `/ess version`: 
[04:09:25 INFO]: Server version: 1.13-R0.1-SNAPSHOT git-Paper-64 (MC: 1.13)
[04:09:25 INFO]: EssentialsX version: 2.15.0.17
[04:09:25 INFO]: PermissionsEx version: 1.23.4
[04:09:25 INFO]: Vault version: 1.6.6-b67
[04:09:25 INFO]: EssentialsXGeoIP version: 2.15.0.17
[04:09:25 INFO]: EssentialsXSpawn version: 2.15.0.17

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)): https://gist.github.com/FabioZumbi12/0fae4b8a38a811d6310b434c476ef416

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): https://gist.github.com/FabioZumbi12/3c50eee9c828d5890f825e45aa44aa70

### Details

Describe your issue here.
After load the server, i having this problem. When i try to teleport to Spawn my server freezes and crashes.

**Comment by saturnux** [comment] 2018-07-30 09:05
1.13 essentialsx version for 1.13 is not build.

**Comment by mdcfe** [comment] 2018-08-01 14:50
This is a duplicate of #2080. Do not upgrade your server to 1.13 yet.

**Closed as completed by mdcfe** 2018-08-01 14:50 UTC
