### ISSUE TITLE
Wrong arguments in VanishStatusChangeEvent (VanishCommand)

### ISSUE THREAD

**Issue by ByteExceptionM** [EssentialsX/Essentials#4153] opened 2021-05-16 00:58 UTC
### Type of bug

Other unexpected behaviour

### `/ess version` output

[02:44:14 INFO]: Server version: 1.16.5-R0.1-SNAPSHOT git-Paper-629 (MC: 1.16.5)
[02:44:14 INFO]: EssentialsX version: 2.18.1.0
[02:44:14 INFO]: LuckPerms version: 5.3.30
[02:44:14 INFO]: Vault version: 1.7.3-b131
[02:44:14 INFO]: ChestShop version: 3.11 (build 213)

### Server startup log

Not relevant 

### EssentialsX config files

Not relevant 

### Error log (if applicable)

Not relevant 

### Bug description

In the following class the variables are swapped:

https://github.com/EssentialsX/Essentials/blob/1e0d7fb0a3545d15c3b0cc1d180b47551f98cb22/Essentials/src/main/java/com/earth2me/essentials/commands/Commandvanish.java#L31

I have checked other events for example FlyStatusChangeEvent and GodStatusChangeEvent, that inherit StatusChangeEvent and I think that the variable "affected" has been swapped with "controller" here

https://github.com/EssentialsX/Essentials/blob/1e0d7fb0a3545d15c3b0cc1d180b47551f98cb22/Essentials/src/main/java/com/earth2me/essentials/commands/Commandfly.java#L31

https://github.com/EssentialsX/Essentials/blob/1e0d7fb0a3545d15c3b0cc1d180b47551f98cb22/Essentials/src/main/java/com/earth2me/essentials/commands/Commandgod.java#L31

Already created a pr which is ready to get merged

### Steps to reproduce

See bug description 

### Expected behaviour

See bug description

### Actual behaviour

See bug description

**Comment by imDaniX** [comment] 2021-05-17 21:24
Duplicate of https://github.com/EssentialsX/Essentials/issues/2604

**Closed as completed** 2021-05-17 21:25 UTC
Labels: bug: unconfirmed
