### ISSUE TITLE
See offline users' inventories/enderchests and edit them.

### ISSUE THREAD

**Issue by Srborjaa** [EssentialsX/Essentials#3508] opened 2020-07-15 18:01 UTC
### Feature request

**Feature description**
"/oinvsee" and "/oendersee" commands to see and edit offline player's inventories and enderchests. It could be useful, like the /otp one.

**How the feature is useful**
Sometimes users get objects illegally and the staff needs to remove them from their inventories, and that's impossible if they are offline.

**Comment by ToonTown0909** [comment] 2020-07-15 18:03
I think this would be an outstanding addition. As a thought, perhaps it wouldn't be necessary to add an `o` in front of the command, leaving them the same easy to recognize commands people are already used to, just with added functionality. I assume this would have its own permission? `essentials.invsee.offline` or something like that. Either way, a great idea and I look forward to seeing what others think about it.

**Comment by ghost** [comment] 2020-07-15 18:06
offline player inventory editing would require modifying the player’s NBT data (through reflection as do this doesn’t break cross version), if the EssX maintainers are fine with that +1

**Comment by Srborjaa** [comment] 2020-07-15 18:07
Yep, it could be a great idea to add **essentials.invsee.offline** and **essentials.invsee.modify.offline** if you think it's necessary ;)

I wrote the "o" in the commands because I thought that the **o** in /**o**tp means /**offline**tp, and it was a simple suggestion to distinguish them. But yes, if it could be done with the same command it would be great :)

Thanks! :P

**Comment by ToonTown0909** [comment] 2020-07-15 18:17
> I wrote the "o" in the commands because I thought that the **o** in /**o**tp means /**offline**tp, and it was a simple suggestion to distinguish them. But yes, if it could be done with the same command it would be great :)

I just, personally, didn't think it was necessary. Having said that, it probably couldn't hurt to add it as an alias. Not sure.

**Comment by pop4959** [comment] 2020-07-15 18:27
Closing as a duplicate of #98

**Closed as completed by pop4959** 2020-07-15 18:27 UTC
Labels: status: duplicate

**Comment by ToonTown0909** [comment] 2020-07-15 18:35
Do we know why the original feature request was closed? Just had a read-through. I see that it's five years old and doesn't really have much conversation or details on the matter.

**Comment by ToonTown0909** [comment] 2020-07-15 18:40
My apologies for another comment again; I feel that my last comment lacks clarity for what I was trying to say, and I hope to rectify that now. One of my primary concerns having this ticket closed as a duplicate, especially considering the age and lack of detail on the original ticket, is that we are preventing the community from engaging in a productive discussion on the grounds that we've already had one, when the linked older ticket seems to indicate that this is not the case.

**Comment by pop4959** [comment] 2020-07-15 18:52
If you take a look at the other linked issues, you can see that we are not planning to add this to Essentials. Sure, someone can still submit a PR for it, but there is no guarantee that it will be accepted, and it is certainly not something the Essentials team is going to be working on. The main problem is as discussed above -- this requires reading the player's NBT data file from the world, which is a huge task in it of itself to do correctly, and has the potential for some really nasty bugs.
