### ISSUE TITLE
Make an option to add a confirmation message when using a command that costs money.

### ISSUE THREAD

**Issue by V1nc3VD** [EssentialsX/Essentials#2812] opened 2019-10-05 21:31 UTC
### Feature request

**Feature description**

In Essentials there's the option command-costs:
where you can make commands cost money. 

It would be great to make an option to send a confirmation message when using the command that it costs money. So that you need to do the command twice for it to work.
**How the feature is useful**

It would be great because now you can't see if a command costs money. So players will reconsider if they really want to do that command, instead of getting ripped off.

**Comment by triagonal** [comment] 2019-10-06 23:25
Thanks for making a suggestion! 

This has already been suggested and flagged as a possible feature. Please search for similar suggestions before submitting your own.

Duplicate of #2107.

**Closed as completed by triagonal** 2019-10-06 23:25 UTC
Labels: status: duplicate
