### ISSUE TITLE
Unjail command doesn't work

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#4904] opened 2022-05-02 19:27 UTC
### Type of bug

Error in console, Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=29b6504835214a5ea800ad845fa145dc

### Error log (if applicable)

https://www.toptal.com/developers/hastebin/pamuriqazu.yaml

### Bug description

Users are unable to be unjailed unless the jail time is extended by 1 second, which then the plugin proceeds to throw errors as specified in the error log.

It also doesn't tp users back when jailtime is over.

### Steps to reproduce

1. /jail <user> 1 <same with time specified or not>
2. /unjail <user>
3. it didn't work
4. /unjail <user> 1
5. it didn't work
6. /jail <user> 1s
7. extended jail time by 1 second?
8. it did work, didn't teleport user back to location which it should have, throwed error on the log

### Expected behaviour

User teleports back to location and continues playing.

### Actual behaviour

User is stuck at jail, admin has to extend 1s jailtime so user can use /home or /spawn commands.

#4802 is related to this.

**Comment by ghost** [comment] 2022-05-02 19:29
Forgot to add the output of /unjail <player> :

`Error: Cannot invoke "org.bukkit.Location.getWorld()" because "targetLoc" is null`

**Comment by pop4959** [comment] 2022-05-22 05:26
Closing as a duplicate of #4802. The comments I left on that issue also apply to this one. Please also make sure you leave clear reproduction steps, as the commands you listed are not valid.

**Closed as not planned by pop4959** 2022-05-22 05:26 UTC
Labels: status: duplicate, status: not enough info
