### ISSUE TITLE
I need help with @p in the plugin

### ISSUE THREAD

**Issue by vspres** [EssentialsX/Essentials#3127] opened 2020-04-03 11:21 UTC
Is it possible to do via command block @p
I want a player to press a button attached to a command block and then only he gets the money. Can you explain to me how to get money without registering the player name (/ eco give @p 100)
And I really liked the plugin.
![2020-04-03_14 20 51](https://user-images.githubusercontent.com/62903664/78355446-5c39a200-75b6-11ea-860e-19e50d4987d1.png)

**Comment by triagonal** [comment] 2020-04-03 12:27
Duplicate of #2600 - please search for similar issues before creating new ones.

**Closed as completed by triagonal** 2020-04-03 12:27 UTC
Labels: status: duplicate
