### ISSUE TITLE
Could not pass event BlockPistonRetractEvent to Essentials

### ISSUE THREAD

**Issue by travilist** [EssentialsX/Essentials#2547] opened 2019-05-15 13:08 UTC
### Information

**Full output of `/ess version`**:

```
15.05 09:00:50 [Server] INFO CONSOLE issued server command: /ess version
15.05 09:00:50 [Server] INFO Server version: 1.14.1-R0.1-SNAPSHOT git-Paper-22 (MC: 1.14.1)
15.05 09:00:50 [Server] INFO EssentialsX version: 2.16.1.174-mc114-b90
15.05 09:00:50 [Server] INFO LuckPerms version: 4.4.17
15.05 09:00:50 [Server] INFO Vault version: 1.7.2-b107
15.05 09:00:50 [Server] INFO EssentialsXProtect version: 2.16.1.174-mc114-b90
15.05 09:00:50 [Server] INFO EssentialsXChat version: 2.16.1.174-mc114-b90
15.05 09:00:50 [Server] INFO EssentialsXGeoIP version: 2.16.1.174-mc114-b90
15.05 09:00:50 [Server] INFO EssentialsXAntiBuild version: 2.16.1.174-mc114-b90
15.05 09:00:50 [Server] INFO EssentialsXSpawn version: 2.16.1.174-mc114-b90
```

**Server log**: https://gist.github.com/anony55/c857164d68b3caa6a8bcba4d009c2c84

**EssentialsX config**: https://gist.github.com/anony55/4dae30abfe610b7591de384ff0e85f57

### Details

**Description**  

Upon placing a sign onto the side of a minecraft:piston_head facing up and then retracting the piston, this error is printed in the console.

**Steps to reproduce**  

1. Place a sticky piston facing up.
2. Extend piston.
3. Place a sign on the side of the extended piston head.
4. Retract piston.
5. Profit?

**Expected behavior**  

No errors.

**Screenshots**  

https://i.imgur.com/nXZw1tQ.png

**Comment by mdcfe** [comment] 2019-05-18 13:59
Though the error in the log is slightly different, this is a duplicate of #2529.

**Closed as completed by mdcfe** 2019-05-18 13:59 UTC
Labels: status: duplicate
