### ISSUE TITLE
custom-join/quit-message: "none" & custom-join-message: "" doesn't disable message

### ISSUE THREAD

**Issue by Twonox** [EssentialsX/Essentials#1393] opened 2017-07-14 22:27 UTC
`custom-join-message: "none"` & `custom-quit-message: "none"` doesn't disable the join/leave message.
`custom-join-message: ""` display an empty message
`custom-quit-message: ""` disable the leave message.

_(during test, there was only essentials plugins)_

Server version: Spigot 1.8.8
Essentials version: latest build

**Comment by mdcfe** [comment] 2017-07-16 06:00
Duplicate of #991. You can give players the `silentjoin` permission, or just leave the custom messages with a blank line.

**Closed as completed** 2017-07-16 06:02 UTC
Labels: status: duplicate
