### ISSUE TITLE
1.15.2 items missing from items.json

### ISSUE THREAD

**Issue by SlimeDog** [EssentialsX/Essentials#2966] opened 2020-01-22 17:41 UTC
### Information

**Full output of `/ess version`**:
```
>ess version
[09:41:16] [Server thread/INFO]: CONSOLE issued server command: /ess version
[09:41:16] [Server thread/INFO]: Server version: 1.15.2-R0.1-SNAPSHOT git-Spigot-800b93f-a81f6ed (MC: 1.15.2)
[09:41:16] [Server thread/INFO]: EssentialsX version: 2.17.1.53
[09:41:16] [Server thread/INFO]: LuckPerms version: 5.0.63
[09:41:16] [Server thread/INFO]: PlaceholderAPI version: 2.10.5-DEV-84
[09:41:16] [Server thread/INFO]: Vault version: 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
[09:41:16] [Server thread/INFO]: Citizens version: 2.0.26-SNAPSHOT (build 1815)
[09:41:16] [Server thread/INFO]: EssentialsXChat version: 2.17.1.53
```

**Server log**: irrelevant

**EssentialsX config**: irrelevant

### Details

**Description**  
items.json in the latest dev releases do not contain the 1.15 items
- bee_spawn_egg
- honeycomb
- honey_bottle

**Comment by pop4959** [comment] 2020-01-22 19:24
Duplicate of #2934

**Closed as completed by pop4959** 2020-01-22 19:24 UTC
Labels: status: duplicate
