### ISSUE TITLE
Hover player message

### ISSUE THREAD

**Issue by mattisadev** [EssentialsX/Essentials#2061] opened 2018-06-28 02:25 UTC
Suggestion: When you hover over a players name in chat it will show a message similar to this. It should be editable in the EssentialsChat section in the config and supports all placeholders that are available to a player.

**Comment by mdcfe** [comment] 2018-06-28 11:42
Duplicate of #1843 and #190, related to #607.

Please search for tickets to see if features have already been requested before opening a new issue.

**Closed as completed by mdcfe** 2018-06-28 11:42 UTC
Labels: status: duplicate, type: enhancement
