### ISSUE TITLE
Add new locale config option

### ISSUE THREAD

**Issue by Hyronymos-Old** [EssentialsX/Essentials#3878] opened 2020-12-27 19:39 UTC
Add a new config option that makes Essentials to use the language from the client(s) instead of one language for the whole Server.

You can use the Spigot method player.spigot().getLocale to resolve the client language or you could use the Protocollib packet PacketType.Play.Client.SETTINGS which is a bit faster.

**Comment by pop4959** [comment] 2020-12-27 19:55
Good idea, #2502 is actually currently already open for this but it's not clear that it will be merged soon.

**Comment by JRoy** [comment] 2020-12-27 20:15
Duplicate of #2029

**Closed as completed by JRoy** 2020-12-27 20:15 UTC
Labels: type: enhancement
