### ISSUE TITLE
Enchant command throwing error

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#993] opened 2016-11-30 04:28 UTC
Hi whenever i try and do /enchant this error

http://hastebin.com/begaqehobi.vbs

Let me know if i am doing something wrong :)

**Comment by mdcfe** [comment] 2016-11-30 06:11
Please downgrade to build 439. Duplicate of #986

**Comment by vemacs** [comment] 2016-12-04 16:09
Builds 450+ have restored most pre-1.11 functionality.

**Closed as completed by vemacs** 2016-12-04 16:09 UTC
