### ISSUE TITLE
Human Readable Banner colors

### ISSUE THREAD

**Issue by chexo3** [EssentialsX/Essentials#2493] opened 2019-04-21 22:30 UTC
### Feature request

**Feature description**

Human readable banner meta color

**How the feature is useful**

Just add the ability to refer to colors in banners by their [DyeColor](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/DyeColor.html)

**Comment by jvdoorn** [comment] 2019-05-16 14:47
I'm on it 😃

**Comment by chexo3** [comment] 2019-05-16 18:47
Oh nice. I forgot about this. Thank you for your help!

**Comment by pop4959** [comment] 2020-05-27 05:30
Closing as duplicate of #123, which also suggests both banner colors + meta tags.

**Closed as completed by pop4959** 2020-05-27 05:30 UTC
Labels: status: duplicate, type: enhancement, status: open to PR
