### ISSUE TITLE
Vanish bug

### ISSUE THREAD

**Issue by FrankHeijden** [EssentialsX/Essentials#1432] opened 2017-08-02 20:30 UTC
People who're joining (player1) after you joined (player2) will see the you (player2) in vanish, despite he's not. Tested as OP with negotiated permission `essentials.silentjoin.vanish` and config section regarding this below.

EssentialsX version (`/essentials`): 
b501

Server software (`/version`): 
CraftBukkit version git-Spigot-596221b-2c5c611 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

EssentialsX config (if applicable): 
`allow-silent-join-quit: true`

**Comment by arturek1666** [comment] 2017-08-03 09:22
I have a bit different issue in my case every admin when join server is automatically vanished. And I have to use command /vanish 2 times to be not vanished xD

**Comment by mdcfe** [comment] 2017-08-03 10:20
Same as @arturek1666 - on my server we have an alias, `/vfix`, that runs `/vanish` twice to ensure that staff are visible or invisible as needed.

**Comment by FrankHeijden** [comment] 2017-08-03 15:17
Yes i have the same issue, i need to enable vanish, and disable to actually be not vanished on join

**Comment by Azewilous** [comment] 2017-08-13 04:14
I can put some time into finding a fix for this if it's still needed.

**Comment by SupaHam** [comment] 2017-08-13 12:55
That'd be amazing @Azewilous.

**Comment by mdcfe** [comment] 2018-03-10 16:03
This appears to be caused by the bug in #1764.

**Closed as completed by mdcfe** 2018-03-10 16:03 UTC
Labels: bug: confirmed
