### ISSUE TITLE
kit bug

### ISSUE THREAD

**Issue by StefvanderMeer** [EssentialsX/Essentials#1966] opened 2018-04-10 13:16 UTC
### Information

Full output of `/ess version`:

10.04 13:11:10 [Server] INFO Server version: 1.8.8-R0.1-SNAPSHOT git-PaperSpigot-"4c7641d" (MC: 1.8.8) 10.04 13:11:10 [Server] INFO EssentialsX version: 2.15.0.1 
10.04 13:11:10 [Server] INFO PermissionsEx version: 1.23.4 
10.04 13:11:10 [Server] INFO Vault version: 1.5.6-b49 
10.04 13:11:10 [Server] INFO EssentialsXChat version: 2.15.0.1 
10.04 13:11:10 [Server] INFO EssentialsXSpawn version: 2.15.0.1

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)):

No errors found

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): 

https://gist.github.com/blijgozertje/0c42cfe483a24760f238f9b58e9a2358

### Details

When using a donator kit there will not come a line on the text. Like other kits have when they are used.

But the delay is still there and people can't use it.

**Comment by mdcfe** [comment] 2018-04-10 14:10
Closing as duplicate of #1779.

**Closed as completed by mdcfe** 2018-04-10 14:10 UTC
