### ISSUE TITLE
add-prefix-in-playerlist & add-suffix-in-playerlist ignored?

### ISSUE THREAD

**Issue by molor** [EssentialsX/Essentials#902] opened 2016-09-22 07:06 UTC
I have the following settings:

```
change-displayname: true
change-playerlist: true
add-prefix-suffix: true
add-prefix-in-playerlist: false
add-suffix-in-playerlist: false
```

But prefix and suffix is still added in playerlist after player with prefix and/or suffix joined the server.

**Comment by rye761** [comment] 2016-09-22 22:42
Did you restart the server?

**Comment by molor** [comment] 2016-09-23 11:53
@rye761, yes, restarted.

**Comment by molor** [comment] 2016-09-23 20:04
This is also happens if I change "change-playerlist" to "false" (other settings not changed) and any player with prefix/suffix go to AFK mode (afk-list-name: "&7{PLAYER}"). I'm use PermissionsEx prefixes and suffixes.

**Comment by NewBestX** [comment] 2016-12-23 21:23
I have the same issue, can confirm it happens in Build #460 (from Jenkins).

**Comment by mdcfe** [comment] 2016-12-24 10:54
@molor @NewBestX What other plugins do you have installed?

**Comment by NewBestX** [comment] 2017-01-07 20:47
@md678685 I did not manage to reply in time, however I can confirm it has been fixed in build #462

EDIT: Actually, it isn't properly fixed. In the builds before the bug occurred, if you added a colored prefix, the player would get the color in the playerlist from the prefix. For instance, the prefix "&4Moderator " would result in a red colored name of the player in the playerlist. I hope you can make it the way it was before as soon as possible. Thank you!

**Comment by NewBestX** [comment] 2017-01-21 20:40
Build #466 reverted the previous fix.
Can you please do a proper fix in the near future? Have in mind what I explained in the previous comment.

**Comment by Andronachi-Marian** [comment] 2017-09-01 03:31
Still not working. I change a little bit the function getNick(). If want to change.
`
    public String getNick(final boolean longnick, final boolean withPrefix, final boolean withSuffix)
	{
        final StringBuilder prefix = new StringBuilder();
        String nickname, suffix = "";
        final String nick = getNickname();
		
        if (ess.getSettings().isCommandDisabled("nick") || nick == null || nick.isEmpty() || nick.equals(getName()))
		{
            nickname = getName();
        }
		else if (nick.equalsIgnoreCase(getName()))
		{
            nickname = nick;
        }
		else
		{
            nickname = FormatUtil.replaceFormat(ess.getSettings().getNicknamePrefix()) + nick;
            suffix = "§r";
        }

        if (this.getBase().isOp())
		{
            try
			{
                final ChatColor opPrefix = ess.getSettings().getOperatorColor();
                if (opPrefix != null && opPrefix.toString().length() > 0)
				{
                    prefix.insert(0, opPrefix.toString());
                    suffix = "§r";
                }
            }
			catch (Exception e) {}
        }
		
		// The variable with final name:
		String output = nickname;
		
		// Checks the prefix and the suffix:
        if (ess.getSettings().addPrefixSuffix())
		{
			// Gets the prefix and the suffix if is not disabled:
            if (!ess.getSettings().disablePrefix())
			{
                final String ptext = ess.getPermissionsHandler().getPrefix(base).replace('&', '§');
                prefix.insert(0, ptext);
                suffix = "§r";
            }
            if (!ess.getSettings().disableSuffix())
			{
                final String stext = ess.getPermissionsHandler().getSuffix(base).replace('&', '§');
                suffix = stext + "§r";
                suffix = suffix.replace("§f§f", "§f").replace("§f§r", "§r").replace("§r§r", "§r");
            }
			
			// Add the prefix and the suffix if is true:
			if (withPrefix)
			{
				output = prefix + nickname;
				
				if (!longnick && output.length() > 16)
				{
					output = FormatUtil.lastCode(prefix) + nickname;
				}
			}
			else
			{
				output = FormatUtil.lastCode(prefix) + nickname;
				
				if (!longnick && output.length() > 16)
				{
					output = FormatUtil.lastCode(prefix) + nickname.substring(0, 14);
				}
			}
			if (withSuffix)
			{
				final outWithSuffix = output + suffix;
				
				if (!longnick && outWithSuffix.length() > 16)
				{
					// No add the suffix to output.
				}
				else
				{
					output = outWithSuffix;
				}
			}
        }
		else if (!longnick && output.length() > 16)
		{
			output = nickname.substring(0, 14);
		}
		
        if (output.charAt(output.length() - 1) == '§')
		{
            output = output.substring(0, output.length() - 1);
        }
        return output;
    }`

**Comment by pop4959** [comment] 2020-04-30 03:24
Since there haven't been any reports of this being an issue in over 3 years, nor confirmed as a bug, I will be closing this issue. If it's still a problem for you guys please feel free to make a new issue on the latest version of Essentials.

**Closed as completed by pop4959** 2020-04-30 03:24 UTC
Labels: type: problem, bug: unconfirmed

**Comment by mdcfe** [comment] 2020-05-08 13:03
This is technically still broken, but most people now assume the current behaviour is the intended behaviour and so it doesn't get reported as a bug any more. At some point it may be worth changing this but right now it's too much of an inconvenience to break the current behaviour.
