### ISSUE TITLE
Direct download link for latest dev build?

### ISSUE THREAD

**Issue by capsload2** [EssentialsX/Essentials#5288] opened 2023-03-28 14:21 UTC
### Feature description

Hey,

i wanted to fully automate my Update Script.

Is there any direct url that always redirects to the latest available dev build?

For now its: https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild/artifact/jars/EssentialsX-2.20.0-dev+45-bf14b88.jar

It would be nice to have:

https://ci.ender.zone/job/EssentialsX/lastSuccessfulBuild/artifact/jars/EssentialsX-dev+latest.jar

as well.

### How the feature is useful

For update scripts

**Comment by flleeppyy** [comment] 2023-04-03 14:44
Take a look here
https://github.com/EssentialsX/Essentials/actions
You could build a REST api that will grab the latest action every hour, download its artifacts and then when you want to download the latest jars, you access the endpoint that does so.

Here's Github's API documentation for Artifacts
https://docs.github.com/en/rest/actions/artifacts?apiVersion=2022-11-28

**Comment by mdcfe** [comment] 2023-04-03 15:08
Duplicate of #4719.

We don't intend to make any changes to facilitate automatic updates. You should review changes in dev builds before you run them, or wait for the stable releases and review the full changelogs.

**Closed as not planned by mdcfe** 2023-04-03 15:08 UTC
Labels: type: enhancement
