### ISSUE TITLE
When setting the Chinese name warp, the Chinese part of the landmark configuration file name will be replaced with an underline

### ISSUE THREAD

**Issue by wkea** [EssentialsX/Essentials#5889] opened 2024-08-01 04:04 UTC
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

null

### Bug description

When setting the Chinese name warp, the Chinese part of the landmark configuration file name will be replaced with an underline
This makes it very easy to cause duplicate landmark names that cannot be added because they are replaced with underscores

### Steps to reproduce

/setwarp 资源世界_home
/setwarp 生存世界_home

### Expected behaviour

The files saved by ESS should support compatibility with some characters except a-zA-Z0-9

### Actual behaviour

![image](https://github.com/user-attachments/assets/fb4e17d7-f3ec-4ac6-9fcb-2986e9fad68b)

**Comment by wkea** [comment] 2024-08-01 04:06
![image](https://github.com/user-attachments/assets/adec4bc9-aa3d-48d3-8bd5-731f3508d19f)

**Comment by Evidentsinger14** [comment] 2024-12-08 02:06
duplicate of #5430 - this is planned to be addressed in that issue.

**Closed as not planned by Evidentsinger14** 2024-12-08 02:06 UTC
Labels: status: duplicate
