### ISSUE TITLE
/back command teleporting players to nether roof

### ISSUE THREAD

**Issue by TheAmazingZote** [EssentialsX/Essentials#4483] opened 2021-08-26 01:30 UTC
### Type of bug

Other unexpected behaviour

### `/ess version` output

[01:22:16 INFO]: Server version: 1.17.1-R0.1-SNAPSHOT git-Paper-214 (MC: 1.17.1)
[01:22:16 INFO]: Brand version: Paper
[01:22:16 INFO]: EssentialsX version: 2.19.0-dev+252-c746a1c
[01:22:16 INFO]: LuckPerms version: 5.3.57
[01:22:16 INFO]: Vault version: 1.7.3-b131
[01:22:16 INFO]: EssentialsXChat version: 2.19.0-dev+252-c746a1c
[01:22:16 INFO]: EssentialsXSpawn version: 2.19.0-dev+252-c746a1c
[01:22:16 INFO]: Capa de economía: None
[01:22:16 INFO]: Obteniendo información de versión...
[01:22:16 INFO]: ¡Estás ejecutando la última compilación de EssentialsX!

### Server startup log

https://paste.gg/p/anonymous/51c89bca8e0e43ce9da56bf79bfbd25f

### EssentialsX config files

https://paste.gg/p/anonymous/7eec07f10b674f659ab4e6ca48347840

### Bug description

When a players die in the nether (mostly on a lava lake) and there is no "safe" points above that, the /back command will return the player to the roof of the nether

### Steps to reproduce

1.- Die in a lave lake in the nether with no space until the roof
2.- Do /back

### Expected behaviour

Deny the command or prevent the tp

### Actual behaviour

The player get tp'd onto the roof of the nether

**Comment by JRoy** [comment] 2021-09-15 20:42
Duplicate of #3318

**Closed as completed by JRoy** 2021-09-15 20:42 UTC
Labels: bug: unconfirmed

**Comment by TheHappyHopper** [comment] 2021-10-17 07:17
getting this same bug recently players stranded on nether roof and cant get down, they really need to implement a max safe height for the nether
