### ISSUE TITLE
Console error.

### ISSUE THREAD

**Issue by Insperful** [EssentialsX/Essentials#2557] opened 2019-05-21 11:39 UTC
### Information

Full output of `/ess version`:

When somebody join the server this appears in console. (Its BOLD)

**Server log:** 

> [FakaHeda] Succesfully authorized (rw)!
Java HotSpot(TM) 64-Bit Server VM warning: Using the ParNew young collector with the Serial old collector is deprecated and will likely be removed in a future release
Loading libraries, please wait...
[13:28:18 INFO]: Starting minecraft server version 1.12.2
[13:28:18 INFO]: Loading properties
[13:28:18 INFO]: Default game type: SURVIVAL
[13:28:18 INFO]: Generating keypair
[13:28:18 INFO]: Starting Minecraft server on 82.208.17.39:27872
[13:28:18 INFO]: Using epoll channel type
[13:28:18 INFO]: This server is running CraftBukkit version git-Bukkit-2b93d83 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[13:28:18 INFO]: [WorldEdit] Loading WorldEdit v6.1.9;caf0ad9
[13:28:18 INFO]: [Vault] Loading Vault v1.7.2-b107
[13:28:18 INFO]: [FakaHedaMinequery] Loading FakaHedaMinequery v1.8
[13:28:18 INFO]: [Essentials] Loading Essentials v2.16.1.0
[13:28:18 INFO]: [EssentialsSpawn] Loading EssentialsSpawn v2.16.1.0
[13:28:18 INFO]: [EssentialsChat] Loading EssentialsChat v2.16.1.0
[13:28:18 INFO]: [EssentialsGeoIP] Loading EssentialsGeoIP v2.16.1.0
[13:28:18 INFO]: [EssentialsAntiBuild] Loading EssentialsAntiBuild v2.16.1.0
[13:28:18 INFO]: [EssentialsXMPP] Loading EssentialsXMPP v2.16.1.0
[13:28:18 INFO]: [EssentialsProtect] Loading EssentialsProtect v2.16.1.0
[13:28:18 INFO]: [Vault] Enabling Vault v1.7.2-b107
[13:28:18 INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[13:28:18 INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[13:28:18 INFO]: [Vault] Enabled Version 1.7.2-b107
[13:28:18 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[13:28:18 WARN]: The server will make no attempt to authenticate usernames. Beware.
[13:28:18 WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[13:28:18 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[13:28:18 INFO]: Preparing level "world"
[13:28:19 INFO]: Preparing start region for level 0 (Seed: 5686553935074829450)
[13:28:20 INFO]: Preparing spawn area: 82%
[13:28:20 INFO]: Preparing start region for level 1 (Seed: 5686553935074829450)
[13:28:21 INFO]: Preparing start region for level 2 (Seed: 5686553935074829450)
[13:28:21 INFO]: [WorldEdit] Enabling WorldEdit v6.1.9;caf0ad9
[13:28:21 INFO]: [WorldEdit] Default configuration file written: config.yml
[13:28:21 INFO]: WEPIF: Updated config file
[13:28:21 INFO]: WEPIF: Using the Bukkit Permissions API.
[13:28:21 INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_12_R2 as the Bukkit adapter
[13:28:21 INFO]: [FakaHedaMinequery] Enabling FakaHedaMinequery v1.8
[13:28:21 INFO]: Starting FakaHedaMinequery server on 82.208.17.39:28872
[13:28:21 INFO]: [Essentials] Enabling Essentials v2.16.1.0
[13:28:22 INFO]: Attempting to convert old kits in config.yml to new kits.yml
[13:28:22 INFO]: No kits found to migrate.
[13:28:22 INFO]: [Essentials] Using legacy item data provider as mob spawner provider.
[13:28:22 INFO]: [Essentials] Using Reflection based provider as spawn egg provider.
[13:28:22 INFO]: [Essentials] Using 1.9+ BasePotionData provider as potion meta provider.
[13:28:22 INFO]: Loaded 852 items from items.csv.
[13:28:22 INFO]: Using locale en_US
[13:28:22 INFO]: [Essentials] ServerListPingEvent: Spigot iterator API
[13:28:22 INFO]: [Essentials] Starting Metrics. Opt-out using the global bStats config.
[13:28:22 INFO]: [Vault] [Vault][Economy] Essentials Economy hooked.
[13:28:22 INFO]: [Essentials] Using superperms-based permissions.
[13:28:22 INFO]: [EssentialsSpawn] Enabling EssentialsSpawn v2.16.1.0
[13:28:22 INFO]: [EssentialsChat] Enabling EssentialsChat v2.16.1.0
[13:28:22 INFO]: [EssentialsGeoIP] Enabling EssentialsGeoIP v2.16.1.0
[13:28:22 WARN]: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
[13:28:22 INFO]: [EssentialsGeoIP] This product includes GeoLite2 data created by MaxMind, available from http://www.maxmind.com/.
[13:28:22 INFO]: [EssentialsAntiBuild] Enabling EssentialsAntiBuild v2.16.1.0
[13:28:22 INFO]: [EssentialsXMPP] Enabling EssentialsXMPP v2.16.1.0
[13:28:22 WARN]: config broken for xmpp
[13:28:22 INFO]: [EssentialsProtect] Enabling EssentialsProtect v2.16.1.0
[13:28:22 INFO]: [EssentialsProtect] Continuing to enable Protect.
[13:28:22 INFO]: Server permissions file permissions.yml is empty, ignoring it
[13:28:22 INFO]: Done (3.706s)! For help, type "help" or "?"
[13:28:22 INFO]: Starting GS4 status listener
[13:28:22 INFO]: Query running on 82.208.17.39:27872
[13:28:22 INFO]: [Vault] Checking for Updates ... 
[13:28:23 INFO]: [Vault] No new version available
[13:29:07 INFO]: Insperful[/37.48.32.37:28803] logged in with entity id 413 at ([world]-1541.147175438596, 70.0, -327.4127280484809)
**[13:29:07 WARN]: [Essentials] Task #12 for Essentials v2.16.1.0 generated an exception
java.lang.NullPointerException: null
at com.earth2me.essentials.xmpp.XMPPManager.updatePresence(XMPPManager.java:146) ~[?:?]
at com.earth2me.essentials.xmpp.EssentialsXMPP.updatePresence(EssentialsXMPP.java:113) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[minecraft_server.jar:git-Bukkit-2b93d83]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:360) [minecraft_server.jar:git-Bukkit-2b93d83]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:690) [minecraft_server.jar:git-Bukkit-2b93d83]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:371) [minecraft_server.jar:git-Bukkit-2b93d83]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651) [minecraft_server.jar:git-Bukkit-2b93d83]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555) [minecraft_server.jar:git-Bukkit-2b93d83]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]**

**EssentialsX config** Its the original one.

### Help request

**Problem**
Error in console.

**What I have tried**
Nothing, i dont know what to do

**Comment by triagonal** [comment] 2019-05-22 05:20
Duplicate of multiple issues. Please search for similar issues before creating a new one.

This is due to EssentialsXMPP being improperly configured. If you're not using EssentialsXMPP, then you should remove the `EssentialsXXMPP.jar` file from your `/plugins` folder.

**Closed as completed by triagonal** 2019-05-22 05:20 UTC
Labels: status: duplicate
