### ISSUE TITLE
Essentails GeoIP  fasteraml warning?

### ISSUE THREAD

**Issue by EchocallingEarth** [EssentialsX/Essentials#2714] opened 2019-08-03 22:11 UTC
**Server log:** 
https://pastebin.com/vPWKYMbr

**EssentialsX config** 
https://gist.github.com/EchocallingEarth/1b80f37004e5ac0061301cba11191a13

### Help request
Requesting this matter be researched and solution found or a fix by version be recommended. Please note version running is 1.14.3 Any additional information I can provide I will thank you in advance ~ EchocallingEarth

**Problem**

In console warning

> [22:08:09 WARN]: [com.fasterxml.jackson.databind.ext.Java7Support] Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added

**What I have tried**

Researched issue as just a warning, only references are to EssentialsGeoIP and Java

**Comment by triagonal** [comment] 2019-08-04 06:36
Duplicate of #2376. The message comes from the GeoIP library that EssentialsXGeoIP uses. You can ignore the message, as it won't affect how the plugin works. If the message is bothering you, consider installing a log filtering plugin to stop the message from appearing.

**Closed as completed** 2019-08-04 12:19 UTC
Labels: status: duplicate
