### ISSUE TITLE
EssentialsX's Mini Message Error

### ISSUE THREAD

**Issue by ItzFabb-repo** [EssentialsX/Essentials#5675] opened 2024-02-15 13:37 UTC
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=ae35ba6bc7434d8b867e47452a2700a8

### Error log (if applicable)

https://prnt.sc/40Kr-zDeLtaX

### Bug description

Whenever you typed some commands on the console the Mini Message is not yet working properly.., and still showing the MiniMessages's Formats

### Steps to reproduce

1. Type any commands in-game Let say /pay awdawd 10k
2. There you go you have found the Bug.

### Expected behaviour

The mini message should be working properly :D.

https://prnt.sc/zdzIN4NwebYb 

### Actual behaviour

https://prnt.sc/zdzIN4NwebYb

**Comment by ItzFabb-repo** [comment] 2024-02-15 13:38
Also occur with /pay invalid username command MiniMessage format.

**Comment by JRoy** [comment] 2024-02-19 21:32
duplicate of #5670

**Closed as completed by JRoy** 2024-02-19 21:32 UTC
Labels: status: duplicate
