### ISSUE TITLE
Essentials is resetting flight state of player on world change despite ``world-change-fly-reset: false`` being set.

### ISSUE THREAD

**Issue by mibby** [EssentialsX/Essentials#4745] opened 2022-01-11 11:09 UTC
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=c16c39d3d15c4448859595b2cf2d0d2a

### Bug description

Essentials is resetting flight state of player on world change despite ``world-change-fly-reset: false`` being set.

```
# When a player changes world, should EssentialsX reset their flight?
# This will disable flight if the player does not have essentials.fly.
world-change-fly-reset: false

# When a player changes world, should we reset their speed according to their permissions?
# This resets the player's speed to the default if they don't have essentials.speed.
# If the player doesn't have essentials.speed.bypass, this resets their speed to the maximum specified above.
world-change-speed-reset: false
```

### Steps to reproduce

* Login as OP.
* Enable fly with ``/fly``.
* Confirm you can and are able to fly by entering the air.
* Switch worlds with ``/world``.
* Flight is disabled. Have to re-enable with ``/fly``.

This only seems to affect survival gamemode. Changing worlds in creative, fly still works fine.

### Expected behaviour

Flight state to persist across world change.

### Actual behaviour

Flight state resets on world change while in survival.

https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/main/java/com/earth2me/essentials/EssentialsPlayerListener.java#L691-L721

I have also tested this with LuckPerms and the player having the ``essentials.fly`` permission. This minimal test environment of no other plugins and just Paper came about when trying to diagnose why players on my main server kept complaining about fly state in survival resetting on every world change / teleport back to spawn.

**Comment by JRoy** [comment] 2022-01-11 12:00
Duplicate of #4325

**Closed as completed** 2022-01-11 12:01 UTC
Labels: status: duplicate
