### ISSUE TITLE
Not compatible with the new version of Minecraft 1.20.5

### ISSUE THREAD

**Issue by 4ixya** [EssentialsX/Essentials#5785] opened 2024-04-30 10:34 UTC
### Type of bug

Compatibility issue

### `/ess dump all` output

Essentials version 2.21.0-dev+81-cde7184

### Error log (if applicable)

[15:23:23 ERROR]: [Essentials] java.lang.NoClassDefFoundError: org/bukkit/potion/PotionData
java.lang.NoClassDefFoundError: org/bukkit/potion/PotionData
        at java.base/java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
        at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3549) ~[?:?]
        at java.base/java.lang.Class.getConstructor0(Class.java:3754) ~[?:?]
        at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2930) ~[?:?]
        at com.google.gson.internal.ConstructorConstructor.newDefaultConstructor(ConstructorConstructor.java:212) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.ConstructorConstructor.get(ConstructorConstructor.java:120) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:129) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.getAdapter(Gson.java:556) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1226) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1329) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1271) ~[gson-2.10.1.jar:?]
        at EssentialsX-2.21.0-dev+81-cde7184.jar/com.earth2me.essentials.items.FlatItemDb.loadJSON(FlatItemDb.java:85) ~[EssentialsX-2.21.0-dev+81-cde7184.jar:?]
        at EssentialsX-2.21.0-dev+81-cde7184.jar/com.earth2me.essentials.items.FlatItemDb.rebuild(FlatItemDb.java:64) ~[EssentialsX-2.21.0-dev+81-cde7184.jar:?]
        at EssentialsX-2.21.0-dev+81-cde7184.jar/com.earth2me.essentials.items.FlatItemDb.reloadConfig(FlatItemDb.java:53) ~[EssentialsX-2.21.0-dev+81-cde7184.jar:?]
        at EssentialsX-2.21.0-dev+81-cde7184.jar/com.earth2me.essentials.Essentials.reload(Essentials.java:651) ~[EssentialsX-2.21.0-dev+81-cde7184.jar:?]
        at EssentialsX-2.21.0-dev+81-cde7184.jar/com.earth2me.essentials.Essentials.onEnable(Essentials.java:496) ~[EssentialsX-2.21.0-dev+81-cde7184.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.5-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.5.jar:git-Paper-22]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.5.jar:git-Paper-22]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.5-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.5.jar:git-Paper-22]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.5.jar:git-Paper-22]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:682) ~[paper-1.20.5.jar:git-Paper-22]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:441) ~[paper-1.20.5.jar:git-Paper-22]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:324) ~[paper-1.20.5.jar:git-Paper-22]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1140) ~[paper-1.20.5.jar:git-Paper-22]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.5.jar:git-Paper-22]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.potion.PotionData
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.20.5-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.5-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 28 more
[15:23:23 ERROR]: [Essentials] Похоже, что вы решили перезагрузить свой сервер используя /reload. Неужели вы настолько ненавидите себя? Не ожидайте поддержки от команды EssentialsX при использовании /reload.

[15:23:23 ERROR]: Error occurred while enabling Essentials v2.21.0-dev+81-cde7184 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.earth2me.essentials.Backup.setPendingShutdown(boolean)" because the return value of "com.earth2me.essentials.Essentials.getBackup()" is null
        at EssentialsX-2.21.0-dev+81-cde7184.jar/com.earth2me.essentials.Essentials.onDisable(Essentials.java:604) ~[EssentialsX-2.21.0-dev+81-cde7184.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[paper-api-1.20.5-R0.1-SNAPSHOT.jar:?]
        at EssentialsX-2.21.0-dev+81-cde7184.jar/com.earth2me.essentials.Essentials.handleCrash(Essentials.java:1136) ~[EssentialsX-2.21.0-dev+81-cde7184.jar:?]
        at EssentialsX-2.21.0-dev+81-cde7184.jar/com.earth2me.essentials.Essentials.onEnable(Essentials.java:534) ~[EssentialsX-2.21.0-dev+81-cde7184.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.5-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.5.jar:git-Paper-22]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.5.jar:git-Paper-22]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.5-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.5.jar:git-Paper-22]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.5.jar:git-Paper-22]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:682) ~[paper-1.20.5.jar:git-Paper-22]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:441) ~[paper-1.20.5.jar:git-Paper-22]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:324) ~[paper-1.20.5.jar:git-Paper-22]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1140) ~[paper-1.20.5.jar:git-Paper-22]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.5.jar:git-Paper-22]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Bug description

When starting the server (paper 1.20.5-22), the plugin refuses to work because the plugin is not compatible with the new version of Minecraft 1.20.5.  The plugin prevents many other plugins that need it from working.

### Steps to reproduce

start the server on the new version of Minecraft 1.20.5

### Expected behaviour

The plugin must be compatible with the new version of Minecraft 1.20.5, and work correctly.

### Actual behaviour

The plugin is not compatible with the new version of Minecraft 1.20.5, and does not work correctly.

**Comment by ImDarkLaw** [comment] 2024-04-30 10:39
Duplicate of #5779

**Comment by 4ixya** [comment] 2024-04-30 12:45
> Дубликат #5779

Sorry, I didn't know that there was already such an appeal.

**Comment by 4ixya** [comment] 2024-04-30 12:46
> Дубликат #5779

sorry, I didn't know that there was already such an appeal

> Дубликат #5779

**Closed as completed** 2024-04-30 13:20 UTC
Labels: bug: unconfirmed
