### ISSUE TITLE
/give doesn't seem to work correctly with fireworks

### ISSUE THREAD

**Issue by Turbotailz** [EssentialsX/Essentials#1035] opened 2016-12-24 10:17 UTC
Using the /give command to give a player more than 127 fireworks appears to spawn "blank" fireworks, they have no data.

The max amount I can /give fireworks is a stack of 64 + 65. Anything higher than that will spawn blanks.

My default stack size is 64 and I'm running Essentials 2.0.1-b460 on Paper 1.11.2

**Comment by mdcfe** [comment] 2016-12-24 10:58
I'm guessing this is something to do with the handling of splitting large stacks and not respecting the firework data, but I have yet to look at this. Has anyone replicated this on 1.10.x and below?

**Comment by smmmadden** [comment] 2016-12-24 12:43
I don't believe the issue is related to fireworks at all even though the additional are blank.  The problem is that Essentials hasn't supported a stack size larger than 127 for any block.  While the setting is clearly in the config.yml to change it to any value we want, the most any one inventory block can be is 127.  If you change it to 128 in 1.10 and earlier, you may get the block but shift+right click on that stack will make the entire stack disappear.  Now, with build 460, if you have an oversized stack of a block and try to give another 128, the previous stack gets removed.  For example, I set mine to 127 initially for torches.  I then changed it to 128 and tried to give myself 128 more torches.  The first time I did /give smmmadden torch 128, the previous stack of 127 changed to 126.  I repeated the command again and then the previous stack changed from 126 to 64.

So the recommended size to make it work properly is no larger than 127.  I'd love to see this fixed but not sure it can be given the mechanics in how it works.
Over-sized stacks are stacks that ignore the normal max stack size.
They can be obtained using /give and /item, if the player has essentials.oversizedstacks permission.
How many items should be in an over-sized stack?
oversized-stacksize: 127

**Comment by smmmadden** [comment] 2016-12-25 02:13
Related to the above /give command, is the /item command which does not behave the same way.  If Essentials is set to have an **oversized-stacksize: 127** and a player issues the **/item cookie** command, the player should be granted 127 cookies.  Instead, only 64 are granted even though the confirmation states 127 were given - shown in screen shot.  I've tried with other foods as well and the same behavior applies.
![2016-12-24 21_05_00-minecraft 1 11 2](https://cloud.githubusercontent.com/assets/10309346/21469460/8ed55148-ca1d-11e6-8e8a-01cfb5a4f06f.png)
Note that using **/give smmmaddenn cookie 127** works fine.  But **/item cookie** or **/item cookie 127** only gives 64.  I have also confirmed that the item command is not overridden by any other plugin.

**Comment by smmmadden** [comment] 2017-02-17 13:35
Hi, just checking to see if this will be fixed in the next update?  Still not working properly with build 467.
Thanks - Steve

**Comment by SupaHam** [comment] 2017-06-28 18:50
Not sure if this is still to be considered a problem? Minecraft does limit item stack sizes since a couple major versions ago.

**Comment by mdcfe** [comment] 2018-03-10 15:22
I think this can probably be closed, as there was never any guarantee that oversized stacks would be stable and there are restrictions on maximum stack sizes in vanilla.

**Closed as completed by mdcfe** 2018-03-10 15:22 UTC
Labels: type: problem
