### ISSUE TITLE
Random issue. When joining server

### ISSUE THREAD

**Issue by Misio12320** [EssentialsX/Essentials#2587] opened 2019-06-08 11:05 UTC
### Information

**Full output of `/ess version`**:

ver=> [13:03:11 INFO]: This server is running Paper version git-Paper-68 (MC: 1.14.2) (Implementing API version 1.14.2-R0.1-SNAPSHOT)
[13:03:11 INFO]: Previous version: git-Paper-67 (MC: 1.14.2)
[13:03:11 INFO]: You are running the latest version
ver ess=> [13:03:18 INFO]: Essentials version 2.16.1.167
[13:03:18 INFO]: Provides an essential, core set of commands for Bukkit.
[13:03:18 INFO]: Website: http://tiny.cc/EssentialsCommands
[13:03:18 INFO]: Authors: Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally, drtshock, vemacs, SupaHam and md678685
[13:03:18 INFO]: EssentialsGeoIP version 2.16.1.167
[13:03:18 INFO]: Shows the country or city of a user on login and /whois.
[13:03:18 INFO]: Website: http://tiny.cc/EssentialsCommands
[13:03:18 INFO]: Authors: Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology and kjiang
[13:03:18 INFO]: EssentialsChat version 2.16.1.167
[13:03:18 INFO]: Provides chat control features for Essentials. Requires Permissions.
[13:03:18 INFO]: Website: http://tiny.cc/EssentialsCommands
[13:03:18 INFO]: Authors: Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Okamosy and Iaccidentally

https://pastebin.com/Qb9DRp4g

https://pastebin.com/9VshQXiC

### Details

**Description**  
When I joined the server succesfull the server sent me this into console 

**Steps to reproduce**  
Console: https://pastebin.com/hZZW9NCd

**Expected behavior**  
Nothing should happen. Just me join server and play. https://timings.aikar.co/?id=d1d82c240df3407bbaf75bef81835cee

**Screenshots**

**Comment by Misio12320** [comment] 2019-06-09 18:20
Could not pass event EntityExplodeEvent to Essentials v2.16.1.167
java.lang.ClassCastException: org.bukkit.material.MaterialData cannot be cast to org.bukkit.material.Sign
at com.earth2me.essentials.signs.EssentialsSign.checkIfBlockBreaksSigns(EssentialsSign.java:217) ~[?:?]
at com.earth2me.essentials.signs.SignEntityListener.onSignEntityExplode(SignEntityListener.java:31) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor293.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.2.jar:git-Paper-68]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.2.jar:git-Paper-68]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.2.jar:git-Paper-68]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[patched_1.14.2.jar:git-Paper-68]
at net.minecraft.server.v1_14_R1.Explosion.a(Explosion.java:243) ~[patched_1.14.2.jar:git-Paper-68]
at net.minecraft.server.v1_14_R1.World.createExplosion(World.java:1044) ~[patched_1.14.2.jar:git-Paper-68]
at net.minecraft.server.v1_14_R1.WorldServer.createExplosion(WorldServer.java:1288) ~[patched_1.14.2.jar:git-Paper-68]
at net.minecraft.server.v1_14_R1.World.createExplosion(World.java:1033) ~[patched_1.14.2.jar:git-Paper-68]
at net.minecraft.server.v1_14_R1.EntityCreeper.eb(EntityCreeper.java:215) ~[patched_1.14.2.jar:git-Paper-68]
at net.minecraft.server.v1_14_R1.EntityCreeper.tick(EntityCreeper.java:119) ~[patched_1.14.2.jar:git-Paper-68]
at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:579) ~[patched_1.14.2.jar:git-Paper-68]
at net.minecraft.server.v1_14_R1.World.a(World.java:895) ~[patched_1.14.2.jar:git-Paper-68]
at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:354) ~[patched_1.14.2.jar:git-Paper-68]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1177) ~[patched_1.14.2.jar:git-Paper-68]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-68]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.2.jar:git-Paper-68]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.2.jar:git-Paper-68]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by mdcfe** [comment] 2019-06-09 20:50
Duplicate of #2529.

**Closed as completed by mdcfe** 2019-06-09 20:50 UTC
