### ISSUE TITLE
Players fishing but not taking the catch won't get kicked for AFK

### ISSUE THREAD

**Issue by Qinak** [EssentialsX/Essentials#1904] opened 2018-03-17 20:19 UTC
### Information

Full output of `/ess version`:

17.03 15:12:57 [Server] INFO [Essentials] Using Spigot 1.7.10+ ServerListPingEvent iterator
17.03 15:12:57 [Server] INFO (!) Essentials Omladdat 2.0.1-b601

Screenshot: https://i.imgur.com/btkmf0s.png

### Details

Players can just stand AFK like on the screenshot and not get kicked because when a fish is caught but not taken it seems to make the player look like his not AFK.

**Comment by mdcfe** [comment] 2018-03-18 09:19
Duplicate of #1050; will be fixed by #1804.

**Closed as completed by mdcfe** 2018-03-18 09:19 UTC
