### ISSUE TITLE
Cannot find ITEMS SIGNS

### ISSUE THREAD

**Issue by andfont** [EssentialsX/Essentials#2838] opened 2019-10-29 15:46 UTC
My server is 1.14.4 paper
Essentials version 2.17.1.19
Cannot find items such as posters, if you make a / itemdb of a poster, NULL
or if you want to create an example / createkit that has a sign, it doesn't take it either, other items fail but specifically this one, please fix this BUG it is very important to make my kit thanks

**Comment by pop4959** [comment] 2019-10-29 17:35
There is no such item in Minecraft. Do you perhaps mean "composter"? Or "itemframe"?

If not, then please properly fill out the issue template. It is required to look into the problem further.

**Comment by andfont** [comment] 2019-10-29 18:03
?? I'm not saying you can't create a KIT with a sign! or just take a con / give a sign etc ... that does not work the sign!

**Comment by andfont** [comment] 2019-10-29 18:05
I have already researched my friend and there is nothing about the signs you can not create a kit for example thank you I hope you solve the bug!

**Comment by pop4959** [comment] 2019-10-29 19:03
Try deleting the items.json file in your Essentials folder and then restart the server fully.

Also, as one last warning, if you do not fill out the issue template I will need to close this issue. I am not trying to be rude, but if you think you have a bug, you need to report it properly. Deleting the issue template is not acceptable, as it wastes developers' time.

If you are not sure where to find this, go back to New Issue -> Report a bug -> copy the template here into your original post.

**Comment by andfont** [comment] 2019-11-01 20:51
It already works by taking those two files from .JAR! but of course this is a mistake! you have to make it unnecessary to have to take out those files! detect that if they are old copy the new ones for example etc., now it works for me but surely many people will have the same thing. Regards.

**Comment by pop4959** [comment] 2019-11-02 00:22
~~As far as I know, this is not a bug or issue with Essentials, as items.json is a configuration file, and configurations (like config.yml) do not get automatically deleted since that would likely anger server owners. Even so, we'll see if and how we can improve this in the future.~~

Just read md's comment below. Seems like there is an intended auto upgrade after all. Sorry for the slight misinformation.

**Closed as completed by pop4959** 2019-11-02 00:22 UTC
Labels: status: invalid, status: not enough info

**Comment by mdcfe** [comment] 2019-11-02 16:49
`items.json` should update automatically as long as you don't modify it, but in `items.json` files shipped with 2.16.x, this mechanism was broken and you need to delete old files from these versions for the auto-update to start working.
