### ISSUE TITLE
1.19.3 crash players via chat in vanish

### ISSUE THREAD

**Issue by NikitaRTN** [EssentialsX/Essentials#5210] opened 2023-01-03 19:34 UTC
### Type of bug

Compatibility issue, Other unexpected behaviour

### `/ess dump all` output

it does not give errors

### Error log (if applicable)

it does not give errors

### Bug description

When writing to the chat (in disappearing mode) (tested not on a licensed server), all players, except administrators (who see me), crash with the error "Error confirming a message in the chat" (this was normal on 1.19.2), **detected in version 1.19.3**
**This only happens if I write while in vanish!**

### Steps to reproduce

/v
write in chat (in version 1.19.3)

### Expected behaviour

crash players who shouldn't see me in vanish

### Actual behaviour

Mojang's **chat reporting system** cannot identify who wrote the message.

**Comment by pop4959** [comment] 2023-01-03 20:58
Closing as a duplicate of #5201

**Closed as completed by pop4959** 2023-01-03 20:58 UTC
Labels: status: duplicate
