### ISSUE TITLE
PlayerInteractEvent

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#1433] opened 2017-08-03 14:00 UTC
Bug http://paste.yu8.me/?529458af19f19be0#R5HrxQ8hNE6EdOLtsz3Y3bCwj11td7ycYHaGDEbpnrA=

Essentials v2.0.1-b501
spigot-1.12.1

**Comment by FrankHeijden** [comment] 2017-08-03 14:32
Can confirm

**Comment by mdcfe** [comment] 2017-08-03 15:14
@FrankHeijden What version of Essentials (`/ess`) and Spigot (`/version`) are you running?

@TheChampTF 
* What version of PerWorldPlugins are you running, and from where did you get it? (There seems to be a few different maintained versions.)
* What caused this specific error?

**Comment by FrankHeijden** [comment] 2017-08-03 15:18
Essentials v2.0.1-b501
CraftBukkit version git-Spigot-edd0396-2a927e8 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

**Comment by FrankHeijden** [comment] 2017-08-03 15:20
This error just randomly occured at my console. and it spams like a lot. https://pastebin.com/BAX5xPgX

I see its a different error, but the same nullpointer

**Comment by Sikatsu** [comment] 2017-08-03 15:42
Same issue on just spigot 1.12.1 with essentials, latest version since I just pulled it from the devbuilds.

**Comment by filnari** [comment] 2017-08-03 17:34
I'm seeing this same error a couple times a minute.

Essentials reloaded 2.0.1-b501.
CraftBukkit version git-Spigot-edd0396-2a927e8 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

**Comment by mdcfe** [comment] 2017-08-03 18:40
This was caused by a removal of a deprecated method in Spigot 1.12.1:
* [Spigot/Bukkit commit](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/0aeac440c05a3ae3b69095e109372b7400f0feae#src/main/java/org/bukkit/entity/LivingEntity.java)

**Comment by mibby** [comment] 2017-08-03 20:48
Can confirm as well, happening on spigot 1.12.1.

Essentials dev 501
Paper dev 1170 (Spigot 1.12.1)

Pasting error on github so there is a copy here.
```
[13:43:27] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Essentials v2.0.1-b501
java.lang.NoSuchMethodError: org.bukkit.entity.Player.getTargetBlock(Ljava/util/HashSet;I)Lorg/bukkit/block/Block;
	at com.earth2me.essentials.signs.SignPlayerListener.onSignPlayerInteract(SignPlayerListener.java:41) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor252.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.12.1.jar:git-Paper-1170]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.1.jar:git-Paper-1170]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.1.jar:git-Paper-1170]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) ~[patched_1.12.1.jar:git-Paper-1170]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) ~[patched_1.12.1.jar:git-Paper-1170]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235) ~[patched_1.12.1.jar:git-Paper-1170]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:202) ~[patched_1.12.1.jar:git-Paper-1170]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198) ~[patched_1.12.1.jar:git-Paper-1170]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:987) ~[patched_1.12.1.jar:git-Paper-1170]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) ~[patched_1.12.1.jar:git-Paper-1170]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.12.1.jar:git-Paper-1170]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.1.jar:git-Paper-1170]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.1.jar:git-Paper-1170]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.1.jar:git-Paper-1170]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424) [patched_1.12.1.jar:git-Paper-1170]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.1.jar:git-Paper-1170]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.1.jar:git-Paper-1170]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

**Comment by andris155** [comment] 2017-08-03 20:51
Same problem
This server is running Paper version git-Paper-1170 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

**Comment by mdcfe** [comment] 2017-08-03 21:05
I've submitted a PR (#1435) that *should* fix this. Could someone test the [test build](https://github.com/drtshock/Essentials/pull/1435#issuecomment-320089716) and confirm whether the issue is still there or is gone?

**Comment by FrankHeijden** [comment] 2017-08-03 21:27
Worked for me!

**Comment by Sikatsu** [comment] 2017-08-03 22:07
Wouldn't it say EssentialsSpawn and EssentialsGEOIP are outdated if I only update the main plugin? @md678685

**Comment by FrankHeijden** [comment] 2017-08-03 22:08
It did just startup normal for me

**Comment by mdcfe** [comment] 2017-08-03 22:08
@Sikatsu Potentially, but since the test build doesn't change anything related to any of the other EssX modules, you can safely ignore it. You can also revert to the release build once the PR is merged.

**Closed as completed** 2017-08-03 22:33 UTC
Labels: bug: confirmed
