### ISSUE TITLE
/spawn & /setspawn gets error NULL in 1.13

### ISSUE THREAD

**Issue by BenjaminHoegh** [EssentialsX/Essentials#2090] opened 2018-07-29 14:27 UTC
In Minecraft 1.13 the command `/spawn` and `/setspawn` gets error NULL

### Technical information 

- EssentialsX: v2.0.1
- Spigot 1.13
- Minecraft 1.13

**Comment by RikoDEV** [comment] 2018-07-29 17:41
https://github.com/EssentialsX/Essentials/issues/2080

**Comment by mdcfe** [comment] 2018-08-01 14:46
Duplicate of #2080. Do not update to 1.13 yet.

**Closed as completed by mdcfe** 2018-08-01 14:46 UTC
