### ISSUE TITLE
[request] Warmup commands.

### ISSUE THREAD

**Issue by TomLewis** [EssentialsX/Essentials#1872] opened 2018-03-03 16:19 UTC
Requesting to be able to set external commands to have a warmup the same setup as the command-cooldowns" and "command-cooldown-persistence".

Same system just allow us to create warm-ups to use commands.

**Comment by mdcfe** [comment] 2018-03-07 22:59
Duplicate of #1320.

**Closed as completed by mdcfe** 2018-03-07 22:59 UTC
Labels: type: enhancement, help wanted
