### ISSUE TITLE
Uchat + EssentialsX Disables Tab completion on commands

### ISSUE THREAD

**Issue by TKwSni** [EssentialsX/Essentials#2046] opened 2018-06-17 19:07 UTC
Full output of `/ess version`:
 CONSOLE issued server command: /ess version
Server version: 1.12.2-R0.1-SNAPSHOT git-Spigot-2086bb0-2f3ed3b (MC: 1.12.2)
EssentialsX version: 2.15.0.16
LuckPerms version: 4.1.63
Vault version: 1.6.6-b${env.TRAVIS_BUILD_NUMBER}

Server log: https://gist.github.com/Blackyvk/8a772a04481eaba991f5eb31c75aaaa9

EssentialsX config:  Default

### Details

Describe your issue here.

When both plugins are used, if you try to autocomplete with TAB the names of the players, nothing happens, doesnt matter if you got all the nodes or are OP, if i remove essentialsx plugin, it starts working again.

**Comment by mdcfe** [comment] 2018-06-18 11:01
1. Does tab completion when UltimateChat is removed?
2. Do you have any other plugins installed?
3. Are there any logs in the console when a player tries to tab complete?

**Comment by TKwSni** [comment] 2018-06-18 13:14
I'll correct what I said, it does work when you are OP but, I think you are supposed to be able to use this as a normal user by default, right ?

 1. No it doesnt (tested), I think this only affects essentials commands, so for example I can use tab with /tell from Uchat.
 2. LuckPerms, Vault, ProtocolLib, Essentials
 3. No errors

**Comment by mdcfe** [comment] 2018-06-18 16:28
Could you give an example of a command that fails to tabcomplete, even when prefixed with `e`?

**Comment by TKwSni** [comment] 2018-06-18 17:03
Ok after thinking a little bit more , Ii found the problem is a permission issue.

if I give the user essentials.msg they can autocomplete names but, i dont want to give them those permission because I want uchat to handle all these.

So I tried to disable the commands in essentials using the disable feature but that makes the problem worse because not even as OP i can use autocomplete.

**Comment by mdcfe** [comment] 2018-06-19 06:55
I believe `/ultimatechat:msg` is an alias of `/ultimatechat:tell`, so when you tabcomplete, the Essentials command takes precedence. 

Could you alias `msg` to `ultimatechat:msg` in your server's [`commands.yml`](https://bukkit.gamepedia.com/Commands.yml#aliases) file?

**Comment by TKwSni** [comment] 2018-07-14 22:25
I overrided msg with umsg and now works perfectly

**Comment by mdcfe** [comment] 2018-07-17 07:01
If the issue is solved, feel free to close the issue.

**Closed as completed** 2018-07-17 11:23 UTC
Labels: type: problem
