### ISSUE TITLE
/seen command cant find ANY data

### ISSUE THREAD

**Issue by JHarris12345** [EssentialsX/Essentials#3128] opened 2020-04-03 11:27 UTC
### Information

**Full output of `/ess version`**:

```
Server version: 1.15.2R0.1-SNAPSHOT git-Tuinity-"dd7a194" (MC: 1.15.2)
EssentailsX version: 2.17.2.0
Luck perms version: 5.0.72
PlaceHolderAPI version: 2.10.5
Vault version: 1.7.2-b107


```

**Server log**:
https://pastebin.com/index.php?e=1

**EssentialsX config**: 
https://pastebin.com/NqUZuTeZ

### Details

**Description**  
I have had this server up for a year and NEVER had this issue, but everyone who hasnt been on in 2 days cannot not be found in /seen. The command shows they have never joined even though they have and are in the playerdata files. I am even able to pay people who arent appearing in /seen using /eco. ALSO /seen <uuid> works fine, but /seen <name> doesnt. It gives "The user {0} has not joined this server" which is different to "player not found" if I use it on a player that actually hasnt joined

**Steps to reproduce**  
No clue

**Expected behavior**  
People from before 2 days ago should appear in /seen

**Comment by triagonal** [comment] 2020-04-03 16:16
After investigating, it seems this issue was caused by Essentials' usermap somehow being populated entirely with v3 `NPC:name` UUIDs. Replacing the usermap with a clean version containing the correct v4 UUIDs resolved the problem (for now), but the cause is still unknown.

Closing for now.

**Closed as completed by triagonal** 2020-04-03 16:16 UTC
Labels: type: problem, bug: unconfirmed

**Comment by JHarris12345** [comment] 2020-04-11 15:30
Here is the error when it loses everyones data and I have to copy the usermap.csv from hub. 
![image](https://user-images.githubusercontent.com/46936647/79047951-aef80700-7c11-11ea-9ea0-0827ea5215af.png)

**Comment by pop4959** [comment] 2020-04-11 18:41
Here's 2 things you should be trying:
1) Use Paper instead of Truinity. Paper is more stable than Truinity and is officially supported by the plugin.
2) Remove the Holographic Placeholders plugin. This appears in your stack trace for when the user data files broke.

**Comment by JHarris12345** [comment] 2020-04-11 19:58
Paper is diabolical so wont be using that lag machine. Ill try removing holographic placeholders but then I cant have a baltop board. So can essentials make top 10 baltop placeholders please? Not sure why its not already done its very helpful

**Comment by RogerAntonio** [comment] 2020-04-24 16:21
Having the same issue on Paper 1.15.2R0.1-SNAPSHOT

EssentailsX version: 2.17.2.59
Luck perms version: 5.0.72
PlaceHolderAPI version: 2.10.5
Vault version: 1.7.2-b107


Edit:
I went through my userdata folder several times, but we don't have a "broken" file.
Could you upload the file for us to see JHarris12345?
It says "no special characters allowed" and I would like to see what special character they're talking about.

**Comment by mdcfe** [comment] 2020-05-11 16:20
@RogerAntonio The OP's issue stemmed from the fact they were using a third-party plugin which breaks EssentialsX's internal user map. If you're experiencing an issue with `/seen`, please [open a new issue](https://github.com/EssentialsX/Essentials/issues/new/choose).
