### ISSUE TITLE
EssentialsX suggestion.

### ISSUE THREAD

**Issue by DoubleThePsycho** [EssentialsX/Essentials#1846] opened 2018-02-13 14:37 UTC
A great idea (in my opinion) is to allow sharing certain elements over a database, if you run a Bungeecord network. Allowing nicknames or other player information to be shared across servers would seem pretty cool! (Plez add this, my dev dont wanna ;-;)

**Comment by mdcfe** [comment] 2018-02-13 14:44
Regarding the database element, this is a duplicate of #241. A good summary of why using a database is not feasible can be found [here](https://github.com/EssentialsX/Essentials/issues/241#issuecomment-166185349) and [here](https://github.com/EssentialsX/Essentials/issues/241#issuecomment-241254683). In short, it would introduce either major lag on the server or heavy delays in EssentialsX commands, and would generally lead to a poor user experience, and for this reason, drtshock [decided against it](https://github.com/EssentialsX/Essentials/issues/440#issuecomment-189747237).

Regarding BungeeCord, this is a duplicate of #912. It *may* be done in the future, but I doubt that it will happen any time soon (unless someone is willing to contribute a BungeeCord sync module to the plugin).

**Closed as completed by mdcfe** 2018-02-13 14:44 UTC

**Comment by DoubleThePsycho** [comment] 2018-02-13 14:45
Why would it cause such lag to only sync nicknames tho?

**Comment by mdcfe** [comment] 2018-02-13 14:52
Because *every single time* that EssentialsX does **anything at all** to users, it would require a call to the database to get the current player data, which would require waiting for it to respond before doing anything and could in theory take anywhere from milliseconds to minutes, since we don't control the database or how long it takes to respond.

**Anything at all** includes:
* Running *any* command
* Formatting *every single chat message*
* Sending AFK messages
* Informing users when they receive mail
* Getting users' balances for EssentialsX
* Returning users' balances to another plugin (which could happen hundreds of times a second for poorly-written plugins)
