### ISSUE TITLE
Suggestion: Per-player language?

### ISSUE THREAD

**Issue by Andre601** [EssentialsX/Essentials#3079] opened 2020-03-18 16:43 UTC
### Feature request

**Feature description**
Implement an option (disabled by default) where EssentialsX would try to see, what language a player has set in their own settings, to then display the various messages in the language of the user, when supported.

**How the feature is useful**
Servers sometimes want to be more international (Catering to an audience that may not speak language x natively), so having the plugin support displaying text in the language of the user would imo be a step to get rid of other plugins, which have a "hacky" approach to this (i.e. Triton).

**Comment by triagonal** [comment] 2020-03-18 16:47
Duplicate of #2029, which is set to be closed/implemented by PR #2502 in the 2.18 update.

**Closed as completed by triagonal** 2020-03-18 16:47 UTC
Labels: status: duplicate
