### ISSUE TITLE
Exclude some messages from socialspy

### ISSUE THREAD

**Issue by kaanakduman** [EssentialsX/Essentials#3031] opened 2020-02-24 00:28 UTC
### Feature request

**Feature description**
As it is now, if 

`socialspy-commands:
  - '*'
`

then socialspy will spy on all commands. Could you allow us to spy on all commands except a few specified commands?

**How the feature is useful**
When using /helpop, admins see the messages twice which is a little excessive. The requested feature will allow us to make that command less spammy.

On my server specifically, we also have an alias for /helpop defined in the commands.yml. So I was thinking of also including the alias in the "socialspy-ignore-commands".

**Comment by pop4959** [comment] 2020-02-24 01:14
Closing as a duplicate of #2075. Please search issues before creating a new one; thanks!

**Closed as completed by pop4959** 2020-02-24 01:14 UTC
Labels: status: duplicate
