### ISSUE TITLE
The /msgtoggle enable/disable command condition is invalid.

### ISSUE THREAD

**Issue by TheFaik** [EssentialsX/Essentials#5780] opened 2024-04-29 17:19 UTC
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=96780d217c2743728757436cd732fd9d

### Bug description

I enter the command /msgtoggle enable and instead of enabling personal messages, it turns off ._. Same with /msgtoggle disable

### Steps to reproduce

1. Прописывает команду /msgtoggle enable или disable и наслаждаемся нелогичностью

### Expected behaviour

.

### Actual behaviour

.

**Comment by Evidentsinger14** [comment] 2024-04-30 23:17
The arguments `enable` and `disable` are referring to the toggle, rather than receiving of the messages. This technically works as intended, but it definitely is poor wording. 
`msgtoggle enable` will enabled messages being blocked. gonna mark as won't fix, duplicate of #3346

**Closed as not planned by Evidentsinger14** 2024-04-30 23:17 UTC
Labels: status: duplicate, status: wontfix
