### ISSUE TITLE
Sudo gives "Chat message validation failure" kick message

### ISSUE THREAD

**Issue by ghost** [EssentialsX/Essentials#5038] opened 2022-08-07 20:00 UTC
### Type of bug

Other unexpected behaviour

### `/ess dump all` output

https://essentialsx.net/dump.html?id=7a3ad3b2c4e344dbada34250ae1a3d81

### Bug description

When running "/sudo (target player) c:(insert message here)" both the command sender and the target player get kicked for "Chat message validation failure"

### Steps to reproduce

Install latest build of Essentials.
Put two accounts on your server
Run the command /sudo (other player) c:(insert message here)

### Expected behaviour

Other player should say whatever message you put after c: without error.

### Actual behaviour

Both your account and the other player's account get kicked for "Chat message validation failure"

**Comment by osfanbuff63** [comment] 2022-08-07 20:42
~~Try with the latest dev build. This is probably a duplicate of #5031 which is fixed in the latest dev builds (#5030).~~ Read mdcfe's comment below

**Comment by ghost** [comment] 2022-08-07 20:48
I tried with the latest dev build (2.19.5-dev+40-422f25a), issue still occurs.

**Comment by mdcfe** [comment] 2022-08-07 23:52
This is not a duplicate of #5031. It is most likely due to an implementation choice by Spigot regarding the chat method we call that will need either changing upstream or working around in EssentialsX.

**Comment by JRoy** [comment] 2022-08-08 15:58
Fixed as of Paper #116

**Closed as completed by JRoy** 2022-08-08 15:58 UTC
Labels: bug: confirmed, bug: upstream
